// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Unique accessibility node identifier.
type AccessibilityAXNodeId string

// Enum of possible property types.
type AccessibilityAXValueType string

const (
	AccessibilityAXValueTypeBoolean            AccessibilityAXValueType = "boolean"
	AccessibilityAXValueTypeTristate           AccessibilityAXValueType = "tristate"
	AccessibilityAXValueTypeBooleanOrUndefined AccessibilityAXValueType = "booleanOrUndefined"
	AccessibilityAXValueTypeIdref              AccessibilityAXValueType = "idref"
	AccessibilityAXValueTypeIdrefList          AccessibilityAXValueType = "idrefList"
	AccessibilityAXValueTypeInteger            AccessibilityAXValueType = "integer"
	AccessibilityAXValueTypeNode               AccessibilityAXValueType = "node"
	AccessibilityAXValueTypeNodeList           AccessibilityAXValueType = "nodeList"
	AccessibilityAXValueTypeNumber             AccessibilityAXValueType = "number"
	AccessibilityAXValueTypeString             AccessibilityAXValueType = "string"
	AccessibilityAXValueTypeComputedString     AccessibilityAXValueType = "computedString"
	AccessibilityAXValueTypeToken              AccessibilityAXValueType = "token"
	AccessibilityAXValueTypeTokenList          AccessibilityAXValueType = "tokenList"
	AccessibilityAXValueTypeDomRelation        AccessibilityAXValueType = "domRelation"
	AccessibilityAXValueTypeRole               AccessibilityAXValueType = "role"
	AccessibilityAXValueTypeInternalRole       AccessibilityAXValueType = "internalRole"
	AccessibilityAXValueTypeValueUndefined     AccessibilityAXValueType = "valueUndefined"
)

// Enum of possible property sources.
type AccessibilityAXValueSourceType string

const (
	AccessibilityAXValueSourceTypeAttribute      AccessibilityAXValueSourceType = "attribute"
	AccessibilityAXValueSourceTypeImplicit       AccessibilityAXValueSourceType = "implicit"
	AccessibilityAXValueSourceTypeStyle          AccessibilityAXValueSourceType = "style"
	AccessibilityAXValueSourceTypeContents       AccessibilityAXValueSourceType = "contents"
	AccessibilityAXValueSourceTypePlaceholder    AccessibilityAXValueSourceType = "placeholder"
	AccessibilityAXValueSourceTypeRelatedElement AccessibilityAXValueSourceType = "relatedElement"
)

// Enum of possible native property sources (as a subtype of a particular AXValueSourceType).
type AccessibilityAXValueNativeSourceType string

const (
	AccessibilityAXValueNativeSourceTypeDescription    AccessibilityAXValueNativeSourceType = "description"
	AccessibilityAXValueNativeSourceTypeFigcaption     AccessibilityAXValueNativeSourceType = "figcaption"
	AccessibilityAXValueNativeSourceTypeLabel          AccessibilityAXValueNativeSourceType = "label"
	AccessibilityAXValueNativeSourceTypeLabelfor       AccessibilityAXValueNativeSourceType = "labelfor"
	AccessibilityAXValueNativeSourceTypeLabelwrapped   AccessibilityAXValueNativeSourceType = "labelwrapped"
	AccessibilityAXValueNativeSourceTypeLegend         AccessibilityAXValueNativeSourceType = "legend"
	AccessibilityAXValueNativeSourceTypeRubyannotation AccessibilityAXValueNativeSourceType = "rubyannotation"
	AccessibilityAXValueNativeSourceTypeTablecaption   AccessibilityAXValueNativeSourceType = "tablecaption"
	AccessibilityAXValueNativeSourceTypeTitle          AccessibilityAXValueNativeSourceType = "title"
	AccessibilityAXValueNativeSourceTypeOther          AccessibilityAXValueNativeSourceType = "other"
)

// A single source for a computed AX property.
type AccessibilityAXValueSource struct {
	// What type of source this is.
	Type AccessibilityAXValueSourceType `json:"type"`
	// The value of this property source.
	Value *AccessibilityAXValue `json:"value,omitempty"`
	// The name of the relevant attribute, if any.
	Attribute *string `json:"attribute,omitempty"`
	// The value of the relevant attribute, if any.
	AttributeValue *AccessibilityAXValue `json:"attributeValue,omitempty"`
	// Whether this source is superseded by a higher priority source.
	Superseded *bool `json:"superseded,omitempty"`
	// The native markup source for this value, e.g. a `<label>` element.
	NativeSource *AccessibilityAXValueNativeSourceType `json:"nativeSource,omitempty"`
	// The value, such as a node or node list, of the native source.
	NativeSourceValue *AccessibilityAXValue `json:"nativeSourceValue,omitempty"`
	// Whether the value for this property is invalid.
	Invalid *bool `json:"invalid,omitempty"`
	// Reason for the value being invalid, if it is.
	InvalidReason *string `json:"invalidReason,omitempty"`
}

type AccessibilityAXRelatedNode struct {
	// The BackendNodeId of the related DOM node.
	BackendDOMNodeId DOMBackendNodeId `json:"backendDOMNodeId"`
	// The IDRef value provided, if any.
	Idref *string `json:"idref,omitempty"`
	// The text alternative of this node in the current context.
	Text *string `json:"text,omitempty"`
}

type AccessibilityAXProperty struct {
	// The name of this property.
	Name AccessibilityAXPropertyName `json:"name"`
	// The value of this property.
	Value AccessibilityAXValue `json:"value"`
}

// A single computed AX property.
type AccessibilityAXValue struct {
	// The type of this value.
	Type AccessibilityAXValueType `json:"type"`
	// The computed value of this property.
	Value any `json:"value,omitempty"`
	// One or more related nodes, if applicable.
	RelatedNodes []AccessibilityAXRelatedNode `json:"relatedNodes,omitempty"`
	// The sources which contributed to the computation of this property.
	Sources []AccessibilityAXValueSource `json:"sources,omitempty"`
}

// Values of AXProperty name:
// - from 'busy' to 'roledescription': states which apply to every AX node
// - from 'live' to 'root': attributes which apply to nodes in live regions
// - from 'autocomplete' to 'valuetext': attributes which apply to widgets
// - from 'checked' to 'selected': states which apply to widgets
// - from 'activedescendant' to 'owns': relationships between elements other than parent/child/sibling
// - from 'activeFullscreenElement' to 'uninteresting': reasons why this noode is hidden
type AccessibilityAXPropertyName string

const (
	AccessibilityAXPropertyNameActions                    AccessibilityAXPropertyName = "actions"
	AccessibilityAXPropertyNameBusy                       AccessibilityAXPropertyName = "busy"
	AccessibilityAXPropertyNameDisabled                   AccessibilityAXPropertyName = "disabled"
	AccessibilityAXPropertyNameEditable                   AccessibilityAXPropertyName = "editable"
	AccessibilityAXPropertyNameFocusable                  AccessibilityAXPropertyName = "focusable"
	AccessibilityAXPropertyNameFocused                    AccessibilityAXPropertyName = "focused"
	AccessibilityAXPropertyNameHidden                     AccessibilityAXPropertyName = "hidden"
	AccessibilityAXPropertyNameHiddenRoot                 AccessibilityAXPropertyName = "hiddenRoot"
	AccessibilityAXPropertyNameInvalid                    AccessibilityAXPropertyName = "invalid"
	AccessibilityAXPropertyNameKeyshortcuts               AccessibilityAXPropertyName = "keyshortcuts"
	AccessibilityAXPropertyNameSettable                   AccessibilityAXPropertyName = "settable"
	AccessibilityAXPropertyNameRoledescription            AccessibilityAXPropertyName = "roledescription"
	AccessibilityAXPropertyNameLive                       AccessibilityAXPropertyName = "live"
	AccessibilityAXPropertyNameAtomic                     AccessibilityAXPropertyName = "atomic"
	AccessibilityAXPropertyNameRelevant                   AccessibilityAXPropertyName = "relevant"
	AccessibilityAXPropertyNameRoot                       AccessibilityAXPropertyName = "root"
	AccessibilityAXPropertyNameAutocomplete               AccessibilityAXPropertyName = "autocomplete"
	AccessibilityAXPropertyNameHasPopup                   AccessibilityAXPropertyName = "hasPopup"
	AccessibilityAXPropertyNameLevel                      AccessibilityAXPropertyName = "level"
	AccessibilityAXPropertyNameMultiselectable            AccessibilityAXPropertyName = "multiselectable"
	AccessibilityAXPropertyNameOrientation                AccessibilityAXPropertyName = "orientation"
	AccessibilityAXPropertyNameMultiline                  AccessibilityAXPropertyName = "multiline"
	AccessibilityAXPropertyNameReadonly                   AccessibilityAXPropertyName = "readonly"
	AccessibilityAXPropertyNameRequired                   AccessibilityAXPropertyName = "required"
	AccessibilityAXPropertyNameValuemin                   AccessibilityAXPropertyName = "valuemin"
	AccessibilityAXPropertyNameValuemax                   AccessibilityAXPropertyName = "valuemax"
	AccessibilityAXPropertyNameValuetext                  AccessibilityAXPropertyName = "valuetext"
	AccessibilityAXPropertyNameChecked                    AccessibilityAXPropertyName = "checked"
	AccessibilityAXPropertyNameExpanded                   AccessibilityAXPropertyName = "expanded"
	AccessibilityAXPropertyNameModal                      AccessibilityAXPropertyName = "modal"
	AccessibilityAXPropertyNamePressed                    AccessibilityAXPropertyName = "pressed"
	AccessibilityAXPropertyNameSelected                   AccessibilityAXPropertyName = "selected"
	AccessibilityAXPropertyNameActivedescendant           AccessibilityAXPropertyName = "activedescendant"
	AccessibilityAXPropertyNameControls                   AccessibilityAXPropertyName = "controls"
	AccessibilityAXPropertyNameDescribedby                AccessibilityAXPropertyName = "describedby"
	AccessibilityAXPropertyNameDetails                    AccessibilityAXPropertyName = "details"
	AccessibilityAXPropertyNameErrormessage               AccessibilityAXPropertyName = "errormessage"
	AccessibilityAXPropertyNameFlowto                     AccessibilityAXPropertyName = "flowto"
	AccessibilityAXPropertyNameLabelledby                 AccessibilityAXPropertyName = "labelledby"
	AccessibilityAXPropertyNameOwns                       AccessibilityAXPropertyName = "owns"
	AccessibilityAXPropertyNameUrl                        AccessibilityAXPropertyName = "url"
	AccessibilityAXPropertyNameActiveFullscreenElement    AccessibilityAXPropertyName = "activeFullscreenElement"
	AccessibilityAXPropertyNameActiveModalDialog          AccessibilityAXPropertyName = "activeModalDialog"
	AccessibilityAXPropertyNameActiveAriaModalDialog      AccessibilityAXPropertyName = "activeAriaModalDialog"
	AccessibilityAXPropertyNameAriaHiddenElement          AccessibilityAXPropertyName = "ariaHiddenElement"
	AccessibilityAXPropertyNameAriaHiddenSubtree          AccessibilityAXPropertyName = "ariaHiddenSubtree"
	AccessibilityAXPropertyNameEmptyAlt                   AccessibilityAXPropertyName = "emptyAlt"
	AccessibilityAXPropertyNameEmptyText                  AccessibilityAXPropertyName = "emptyText"
	AccessibilityAXPropertyNameInertElement               AccessibilityAXPropertyName = "inertElement"
	AccessibilityAXPropertyNameInertSubtree               AccessibilityAXPropertyName = "inertSubtree"
	AccessibilityAXPropertyNameLabelContainer             AccessibilityAXPropertyName = "labelContainer"
	AccessibilityAXPropertyNameLabelFor                   AccessibilityAXPropertyName = "labelFor"
	AccessibilityAXPropertyNameNotRendered                AccessibilityAXPropertyName = "notRendered"
	AccessibilityAXPropertyNameNotVisible                 AccessibilityAXPropertyName = "notVisible"
	AccessibilityAXPropertyNamePresentationalRole         AccessibilityAXPropertyName = "presentationalRole"
	AccessibilityAXPropertyNameProbablyPresentational     AccessibilityAXPropertyName = "probablyPresentational"
	AccessibilityAXPropertyNameInactiveCarouselTabContent AccessibilityAXPropertyName = "inactiveCarouselTabContent"
	AccessibilityAXPropertyNameUninteresting              AccessibilityAXPropertyName = "uninteresting"
)

// A node in the accessibility tree.
type AccessibilityAXNode struct {
	// Unique identifier for this node.
	NodeId AccessibilityAXNodeId `json:"nodeId"`
	// Whether this node is ignored for accessibility
	Ignored bool `json:"ignored"`
	// Collection of reasons why this node is hidden.
	IgnoredReasons []AccessibilityAXProperty `json:"ignoredReasons,omitempty"`
	// This `Node`'s role, whether explicit or implicit.
	Role *AccessibilityAXValue `json:"role,omitempty"`
	// This `Node`'s Chrome raw role.
	ChromeRole *AccessibilityAXValue `json:"chromeRole,omitempty"`
	// The accessible name for this `Node`.
	Name *AccessibilityAXValue `json:"name,omitempty"`
	// The accessible description for this `Node`.
	Description *AccessibilityAXValue `json:"description,omitempty"`
	// The value for this `Node`.
	Value *AccessibilityAXValue `json:"value,omitempty"`
	// All other properties
	Properties []AccessibilityAXProperty `json:"properties,omitempty"`
	// ID for this node's parent.
	ParentId *AccessibilityAXNodeId `json:"parentId,omitempty"`
	// IDs for each of this node's child nodes.
	ChildIds []AccessibilityAXNodeId `json:"childIds,omitempty"`
	// The backend ID for the associated DOM node, if any.
	BackendDOMNodeId *DOMBackendNodeId `json:"backendDOMNodeId,omitempty"`
	// The frame ID for the frame associated with this nodes document.
	FrameId *PageFrameId `json:"frameId,omitempty"`
}

// Disables the accessibility domain.
type AccessibilityDisableParams struct {
}

func AccessibilityDisable() *AccessibilityDisableParams {
	return &AccessibilityDisableParams{}
}

func (p *AccessibilityDisableParams) CDPMethodName() string {
	return "Accessibility.disable"
}

// Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.
// This turns on accessibility for the page, which can impact performance until accessibility is disabled.
type AccessibilityEnableParams struct {
}

func AccessibilityEnable() *AccessibilityEnableParams {
	return &AccessibilityEnableParams{}
}

func (p *AccessibilityEnableParams) CDPMethodName() string {
	return "Accessibility.enable"
}

// Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
type AccessibilityGetPartialAXTreeParams struct {
	// Identifier of the node to get the partial accessibility tree for.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node to get the partial accessibility tree for.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper to get the partial accessibility tree for.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// Whether to fetch this node's ancestors, siblings and children. Defaults to true.
	FetchRelatives *bool `json:"fetchRelatives,omitempty"`
}

type AccessibilityGetPartialAXTreeReturns struct {
	// The `Accessibility.AXNode` for this DOM node, if it exists, plus its ancestors, siblings and
	// children, if requested.
	Nodes []AccessibilityAXNode `json:"nodes"`
}

func AccessibilityGetPartialAXTree() *AccessibilityGetPartialAXTreeParams {
	return &AccessibilityGetPartialAXTreeParams{}
}

func (p *AccessibilityGetPartialAXTreeParams) WithNodeId(v DOMNodeId) *AccessibilityGetPartialAXTreeParams {
	p.NodeId = &v
	return p
}

func (p *AccessibilityGetPartialAXTreeParams) WithBackendNodeId(v DOMBackendNodeId) *AccessibilityGetPartialAXTreeParams {
	p.BackendNodeId = &v
	return p
}

func (p *AccessibilityGetPartialAXTreeParams) WithObjectId(v RuntimeRemoteObjectId) *AccessibilityGetPartialAXTreeParams {
	p.ObjectId = &v
	return p
}

func (p *AccessibilityGetPartialAXTreeParams) WithFetchRelatives(v bool) *AccessibilityGetPartialAXTreeParams {
	p.FetchRelatives = &v
	return p
}

func (p *AccessibilityGetPartialAXTreeParams) CDPMethodName() string {
	return "Accessibility.getPartialAXTree"
}

// Fetches the entire accessibility tree for the root Document
type AccessibilityGetFullAXTreeParams struct {
	// The maximum depth at which descendants of the root node should be retrieved.
	// If omitted, the full tree is returned.
	Depth *int64 `json:"depth,omitempty"`
	// The frame for whose document the AX tree should be retrieved.
	// If omitted, the root frame is used.
	FrameId *PageFrameId `json:"frameId,omitempty"`
}

type AccessibilityGetFullAXTreeReturns struct {
	Nodes []AccessibilityAXNode `json:"nodes"`
}

func AccessibilityGetFullAXTree() *AccessibilityGetFullAXTreeParams {
	return &AccessibilityGetFullAXTreeParams{}
}

func (p *AccessibilityGetFullAXTreeParams) WithDepth(v int64) *AccessibilityGetFullAXTreeParams {
	p.Depth = &v
	return p
}

func (p *AccessibilityGetFullAXTreeParams) WithFrameId(v PageFrameId) *AccessibilityGetFullAXTreeParams {
	p.FrameId = &v
	return p
}

func (p *AccessibilityGetFullAXTreeParams) CDPMethodName() string {
	return "Accessibility.getFullAXTree"
}

// Fetches the root node.
// Requires `enable()` to have been called previously.
type AccessibilityGetRootAXNodeParams struct {
	// The frame in whose document the node resides.
	// If omitted, the root frame is used.
	FrameId *PageFrameId `json:"frameId,omitempty"`
}

type AccessibilityGetRootAXNodeReturns struct {
	Node AccessibilityAXNode `json:"node"`
}

func AccessibilityGetRootAXNode() *AccessibilityGetRootAXNodeParams {
	return &AccessibilityGetRootAXNodeParams{}
}

func (p *AccessibilityGetRootAXNodeParams) WithFrameId(v PageFrameId) *AccessibilityGetRootAXNodeParams {
	p.FrameId = &v
	return p
}

func (p *AccessibilityGetRootAXNodeParams) CDPMethodName() string {
	return "Accessibility.getRootAXNode"
}

// Fetches a node and all ancestors up to and including the root.
// Requires `enable()` to have been called previously.
type AccessibilityGetAXNodeAndAncestorsParams struct {
	// Identifier of the node to get.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node to get.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper to get.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

type AccessibilityGetAXNodeAndAncestorsReturns struct {
	Nodes []AccessibilityAXNode `json:"nodes"`
}

func AccessibilityGetAXNodeAndAncestors() *AccessibilityGetAXNodeAndAncestorsParams {
	return &AccessibilityGetAXNodeAndAncestorsParams{}
}

func (p *AccessibilityGetAXNodeAndAncestorsParams) WithNodeId(v DOMNodeId) *AccessibilityGetAXNodeAndAncestorsParams {
	p.NodeId = &v
	return p
}

func (p *AccessibilityGetAXNodeAndAncestorsParams) WithBackendNodeId(v DOMBackendNodeId) *AccessibilityGetAXNodeAndAncestorsParams {
	p.BackendNodeId = &v
	return p
}

func (p *AccessibilityGetAXNodeAndAncestorsParams) WithObjectId(v RuntimeRemoteObjectId) *AccessibilityGetAXNodeAndAncestorsParams {
	p.ObjectId = &v
	return p
}

func (p *AccessibilityGetAXNodeAndAncestorsParams) CDPMethodName() string {
	return "Accessibility.getAXNodeAndAncestors"
}

// Fetches a particular accessibility node by AXNodeId.
// Requires `enable()` to have been called previously.
type AccessibilityGetChildAXNodesParams struct {
	Id AccessibilityAXNodeId `json:"id"`
	// The frame in whose document the node resides.
	// If omitted, the root frame is used.
	FrameId *PageFrameId `json:"frameId,omitempty"`
}

type AccessibilityGetChildAXNodesReturns struct {
	Nodes []AccessibilityAXNode `json:"nodes"`
}

func AccessibilityGetChildAXNodes(id AccessibilityAXNodeId) *AccessibilityGetChildAXNodesParams {
	return &AccessibilityGetChildAXNodesParams{
		Id: id,
	}
}

func (p *AccessibilityGetChildAXNodesParams) WithFrameId(v PageFrameId) *AccessibilityGetChildAXNodesParams {
	p.FrameId = &v
	return p
}

func (p *AccessibilityGetChildAXNodesParams) CDPMethodName() string {
	return "Accessibility.getChildAXNodes"
}

// Query a DOM node's accessibility subtree for accessible name and role.
// This command computes the name and role for all nodes in the subtree, including those that are
// ignored for accessibility, and returns those that match the specified name and role. If no DOM
// node is specified, or the DOM node does not exist, the command returns an error. If neither
// `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
type AccessibilityQueryAXTreeParams struct {
	// Identifier of the node for the root to query.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node for the root to query.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper for the root to query.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// Find nodes with this computed name.
	AccessibleName *string `json:"accessibleName,omitempty"`
	// Find nodes with this computed role.
	Role *string `json:"role,omitempty"`
}

type AccessibilityQueryAXTreeReturns struct {
	// A list of `Accessibility.AXNode` matching the specified attributes,
	// including nodes that are ignored for accessibility.
	Nodes []AccessibilityAXNode `json:"nodes"`
}

func AccessibilityQueryAXTree() *AccessibilityQueryAXTreeParams {
	return &AccessibilityQueryAXTreeParams{}
}

func (p *AccessibilityQueryAXTreeParams) WithNodeId(v DOMNodeId) *AccessibilityQueryAXTreeParams {
	p.NodeId = &v
	return p
}

func (p *AccessibilityQueryAXTreeParams) WithBackendNodeId(v DOMBackendNodeId) *AccessibilityQueryAXTreeParams {
	p.BackendNodeId = &v
	return p
}

func (p *AccessibilityQueryAXTreeParams) WithObjectId(v RuntimeRemoteObjectId) *AccessibilityQueryAXTreeParams {
	p.ObjectId = &v
	return p
}

func (p *AccessibilityQueryAXTreeParams) WithAccessibleName(v string) *AccessibilityQueryAXTreeParams {
	p.AccessibleName = &v
	return p
}

func (p *AccessibilityQueryAXTreeParams) WithRole(v string) *AccessibilityQueryAXTreeParams {
	p.Role = &v
	return p
}

func (p *AccessibilityQueryAXTreeParams) CDPMethodName() string {
	return "Accessibility.queryAXTree"
}

// The loadComplete event mirrors the load complete event sent by the browser to assistive
// technology when the web page has finished loading.
const EventAccessibilityLoadComplete = "Accessibility.loadComplete"

type AccessibilityLoadCompleteEvent struct {
	// New document root node.
	Root AccessibilityAXNode `json:"root"`
}

func (e *AccessibilityLoadCompleteEvent) CDPEventName() string {
	return EventAccessibilityLoadComplete
}

// The nodesUpdated event is sent every time a previously requested node has changed the in tree.
const EventAccessibilityNodesUpdated = "Accessibility.nodesUpdated"

type AccessibilityNodesUpdatedEvent struct {
	// Updated node data.
	Nodes []AccessibilityAXNode `json:"nodes"`
}

func (e *AccessibilityNodesUpdatedEvent) CDPEventName() string {
	return EventAccessibilityNodesUpdated
}
