// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Information about a cookie that is affected by an inspector issue.
type AuditsAffectedCookie struct {
	// The following three properties uniquely identify a cookie
	Name   string `json:"name"`
	Path   string `json:"path"`
	Domain string `json:"domain"`
}

// Information about a request that is affected by an inspector issue.
type AuditsAffectedRequest struct {
	// The unique request id.
	RequestId *NetworkRequestId `json:"requestId,omitempty"`
	Url       string            `json:"url"`
}

// Information about the frame affected by an inspector issue.
type AuditsAffectedFrame struct {
	FrameId PageFrameId `json:"frameId"`
}

type AuditsCookieExclusionReason string

const (
	AuditsCookieExclusionReasonExcludeSameSiteUnspecifiedTreatedAsLax        AuditsCookieExclusionReason = "ExcludeSameSiteUnspecifiedTreatedAsLax"
	AuditsCookieExclusionReasonExcludeSameSiteNoneInsecure                   AuditsCookieExclusionReason = "ExcludeSameSiteNoneInsecure"
	AuditsCookieExclusionReasonExcludeSameSiteLax                            AuditsCookieExclusionReason = "ExcludeSameSiteLax"
	AuditsCookieExclusionReasonExcludeSameSiteStrict                         AuditsCookieExclusionReason = "ExcludeSameSiteStrict"
	AuditsCookieExclusionReasonExcludeDomainNonASCII                         AuditsCookieExclusionReason = "ExcludeDomainNonASCII"
	AuditsCookieExclusionReasonExcludeThirdPartyCookieBlockedInFirstPartySet AuditsCookieExclusionReason = "ExcludeThirdPartyCookieBlockedInFirstPartySet"
	AuditsCookieExclusionReasonExcludeThirdPartyPhaseout                     AuditsCookieExclusionReason = "ExcludeThirdPartyPhaseout"
	AuditsCookieExclusionReasonExcludePortMismatch                           AuditsCookieExclusionReason = "ExcludePortMismatch"
	AuditsCookieExclusionReasonExcludeSchemeMismatch                         AuditsCookieExclusionReason = "ExcludeSchemeMismatch"
)

type AuditsCookieWarningReason string

const (
	AuditsCookieWarningReasonWarnSameSiteUnspecifiedCrossSiteContext        AuditsCookieWarningReason = "WarnSameSiteUnspecifiedCrossSiteContext"
	AuditsCookieWarningReasonWarnSameSiteNoneInsecure                       AuditsCookieWarningReason = "WarnSameSiteNoneInsecure"
	AuditsCookieWarningReasonWarnSameSiteUnspecifiedLaxAllowUnsafe          AuditsCookieWarningReason = "WarnSameSiteUnspecifiedLaxAllowUnsafe"
	AuditsCookieWarningReasonWarnSameSiteStrictLaxDowngradeStrict           AuditsCookieWarningReason = "WarnSameSiteStrictLaxDowngradeStrict"
	AuditsCookieWarningReasonWarnSameSiteStrictCrossDowngradeStrict         AuditsCookieWarningReason = "WarnSameSiteStrictCrossDowngradeStrict"
	AuditsCookieWarningReasonWarnSameSiteStrictCrossDowngradeLax            AuditsCookieWarningReason = "WarnSameSiteStrictCrossDowngradeLax"
	AuditsCookieWarningReasonWarnSameSiteLaxCrossDowngradeStrict            AuditsCookieWarningReason = "WarnSameSiteLaxCrossDowngradeStrict"
	AuditsCookieWarningReasonWarnSameSiteLaxCrossDowngradeLax               AuditsCookieWarningReason = "WarnSameSiteLaxCrossDowngradeLax"
	AuditsCookieWarningReasonWarnAttributeValueExceedsMaxSize               AuditsCookieWarningReason = "WarnAttributeValueExceedsMaxSize"
	AuditsCookieWarningReasonWarnDomainNonASCII                             AuditsCookieWarningReason = "WarnDomainNonASCII"
	AuditsCookieWarningReasonWarnThirdPartyPhaseout                         AuditsCookieWarningReason = "WarnThirdPartyPhaseout"
	AuditsCookieWarningReasonWarnCrossSiteRedirectDowngradeChangesInclusion AuditsCookieWarningReason = "WarnCrossSiteRedirectDowngradeChangesInclusion"
	AuditsCookieWarningReasonWarnDeprecationTrialMetadata                   AuditsCookieWarningReason = "WarnDeprecationTrialMetadata"
	AuditsCookieWarningReasonWarnThirdPartyCookieHeuristic                  AuditsCookieWarningReason = "WarnThirdPartyCookieHeuristic"
)

type AuditsCookieOperation string

const (
	AuditsCookieOperationSetCookie  AuditsCookieOperation = "SetCookie"
	AuditsCookieOperationReadCookie AuditsCookieOperation = "ReadCookie"
)

// Represents the category of insight that a cookie issue falls under.
type AuditsInsightType string

const (
	AuditsInsightTypeGitHubResource AuditsInsightType = "GitHubResource"
	AuditsInsightTypeGracePeriod    AuditsInsightType = "GracePeriod"
	AuditsInsightTypeHeuristics     AuditsInsightType = "Heuristics"
)

// Information about the suggested solution to a cookie issue.
type AuditsCookieIssueInsight struct {
	Type AuditsInsightType `json:"type"`
	// Link to table entry in third-party cookie migration readiness list.
	TableEntryUrl *string `json:"tableEntryUrl,omitempty"`
}

// This information is currently necessary, as the front-end has a difficult
// time finding a specific cookie. With this, we can convey specific error
// information without the cookie.
type AuditsCookieIssueDetails struct {
	// If AffectedCookie is not set then rawCookieLine contains the raw
	// Set-Cookie header string. This hints at a problem where the
	// cookie line is syntactically or semantically malformed in a way
	// that no valid cookie could be created.
	Cookie                 *AuditsAffectedCookie         `json:"cookie,omitempty"`
	RawCookieLine          *string                       `json:"rawCookieLine,omitempty"`
	CookieWarningReasons   []AuditsCookieWarningReason   `json:"cookieWarningReasons"`
	CookieExclusionReasons []AuditsCookieExclusionReason `json:"cookieExclusionReasons"`
	// Optionally identifies the site-for-cookies and the cookie url, which
	// may be used by the front-end as additional context.
	Operation      AuditsCookieOperation  `json:"operation"`
	SiteForCookies *string                `json:"siteForCookies,omitempty"`
	CookieUrl      *string                `json:"cookieUrl,omitempty"`
	Request        *AuditsAffectedRequest `json:"request,omitempty"`
	// The recommended solution to the issue.
	Insight *AuditsCookieIssueInsight `json:"insight,omitempty"`
}

type AuditsPerformanceIssueType string

const (
	AuditsPerformanceIssueTypeDocumentCookie AuditsPerformanceIssueType = "DocumentCookie"
)

// Details for a performance issue.
type AuditsPerformanceIssueDetails struct {
	PerformanceIssueType AuditsPerformanceIssueType `json:"performanceIssueType"`
	SourceCodeLocation   *AuditsSourceCodeLocation  `json:"sourceCodeLocation,omitempty"`
}

type AuditsMixedContentResolutionStatus string

const (
	AuditsMixedContentResolutionStatusMixedContentBlocked               AuditsMixedContentResolutionStatus = "MixedContentBlocked"
	AuditsMixedContentResolutionStatusMixedContentAutomaticallyUpgraded AuditsMixedContentResolutionStatus = "MixedContentAutomaticallyUpgraded"
	AuditsMixedContentResolutionStatusMixedContentWarning               AuditsMixedContentResolutionStatus = "MixedContentWarning"
)

type AuditsMixedContentResourceType string

const (
	AuditsMixedContentResourceTypeAttributionSrc   AuditsMixedContentResourceType = "AttributionSrc"
	AuditsMixedContentResourceTypeAudio            AuditsMixedContentResourceType = "Audio"
	AuditsMixedContentResourceTypeBeacon           AuditsMixedContentResourceType = "Beacon"
	AuditsMixedContentResourceTypeCSPReport        AuditsMixedContentResourceType = "CSPReport"
	AuditsMixedContentResourceTypeDownload         AuditsMixedContentResourceType = "Download"
	AuditsMixedContentResourceTypeEventSource      AuditsMixedContentResourceType = "EventSource"
	AuditsMixedContentResourceTypeFavicon          AuditsMixedContentResourceType = "Favicon"
	AuditsMixedContentResourceTypeFont             AuditsMixedContentResourceType = "Font"
	AuditsMixedContentResourceTypeForm             AuditsMixedContentResourceType = "Form"
	AuditsMixedContentResourceTypeFrame            AuditsMixedContentResourceType = "Frame"
	AuditsMixedContentResourceTypeImage            AuditsMixedContentResourceType = "Image"
	AuditsMixedContentResourceTypeImport           AuditsMixedContentResourceType = "Import"
	AuditsMixedContentResourceTypeJSON             AuditsMixedContentResourceType = "JSON"
	AuditsMixedContentResourceTypeManifest         AuditsMixedContentResourceType = "Manifest"
	AuditsMixedContentResourceTypePing             AuditsMixedContentResourceType = "Ping"
	AuditsMixedContentResourceTypePluginData       AuditsMixedContentResourceType = "PluginData"
	AuditsMixedContentResourceTypePluginResource   AuditsMixedContentResourceType = "PluginResource"
	AuditsMixedContentResourceTypePrefetch         AuditsMixedContentResourceType = "Prefetch"
	AuditsMixedContentResourceTypeResource         AuditsMixedContentResourceType = "Resource"
	AuditsMixedContentResourceTypeScript           AuditsMixedContentResourceType = "Script"
	AuditsMixedContentResourceTypeServiceWorker    AuditsMixedContentResourceType = "ServiceWorker"
	AuditsMixedContentResourceTypeSharedWorker     AuditsMixedContentResourceType = "SharedWorker"
	AuditsMixedContentResourceTypeSpeculationRules AuditsMixedContentResourceType = "SpeculationRules"
	AuditsMixedContentResourceTypeStylesheet       AuditsMixedContentResourceType = "Stylesheet"
	AuditsMixedContentResourceTypeTrack            AuditsMixedContentResourceType = "Track"
	AuditsMixedContentResourceTypeVideo            AuditsMixedContentResourceType = "Video"
	AuditsMixedContentResourceTypeWorker           AuditsMixedContentResourceType = "Worker"
	AuditsMixedContentResourceTypeXMLHttpRequest   AuditsMixedContentResourceType = "XMLHttpRequest"
	AuditsMixedContentResourceTypeXSLT             AuditsMixedContentResourceType = "XSLT"
)

type AuditsMixedContentIssueDetails struct {
	// The type of resource causing the mixed content issue (css, js, iframe,
	// form,...). Marked as optional because it is mapped to from
	// blink::mojom::RequestContextType, which will be replaced
	// by network::mojom::RequestDestination
	ResourceType *AuditsMixedContentResourceType `json:"resourceType,omitempty"`
	// The way the mixed content issue is being resolved.
	ResolutionStatus AuditsMixedContentResolutionStatus `json:"resolutionStatus"`
	// The unsafe http url causing the mixed content issue.
	InsecureURL string `json:"insecureURL"`
	// The url responsible for the call to an unsafe url.
	MainResourceURL string `json:"mainResourceURL"`
	// The mixed content request.
	// Does not always exist (e.g. for unsafe form submission urls).
	Request *AuditsAffectedRequest `json:"request,omitempty"`
	// Optional because not every mixed content issue is necessarily linked to a frame.
	Frame *AuditsAffectedFrame `json:"frame,omitempty"`
}

// Enum indicating the reason a response has been blocked. These reasons are
// refinements of the net error BLOCKED_BY_RESPONSE.
type AuditsBlockedByResponseReason string

const (
	AuditsBlockedByResponseReasonCoepFrameResourceNeedsCoepHeader                        AuditsBlockedByResponseReason = "CoepFrameResourceNeedsCoepHeader"
	AuditsBlockedByResponseReasonCoopSandboxedIFrameCannotNavigateToCoopPage             AuditsBlockedByResponseReason = "CoopSandboxedIFrameCannotNavigateToCoopPage"
	AuditsBlockedByResponseReasonCorpNotSameOrigin                                       AuditsBlockedByResponseReason = "CorpNotSameOrigin"
	AuditsBlockedByResponseReasonCorpNotSameOriginAfterDefaultedToSameOriginByCoep       AuditsBlockedByResponseReason = "CorpNotSameOriginAfterDefaultedToSameOriginByCoep"
	AuditsBlockedByResponseReasonCorpNotSameOriginAfterDefaultedToSameOriginByDip        AuditsBlockedByResponseReason = "CorpNotSameOriginAfterDefaultedToSameOriginByDip"
	AuditsBlockedByResponseReasonCorpNotSameOriginAfterDefaultedToSameOriginByCoepAndDip AuditsBlockedByResponseReason = "CorpNotSameOriginAfterDefaultedToSameOriginByCoepAndDip"
	AuditsBlockedByResponseReasonCorpNotSameSite                                         AuditsBlockedByResponseReason = "CorpNotSameSite"
	AuditsBlockedByResponseReasonSRIMessageSignatureMismatch                             AuditsBlockedByResponseReason = "SRIMessageSignatureMismatch"
)

// Details for a request that has been blocked with the BLOCKED_BY_RESPONSE
// code. Currently only used for COEP/COOP, but may be extended to include
// some CSP errors in the future.
type AuditsBlockedByResponseIssueDetails struct {
	Request      AuditsAffectedRequest         `json:"request"`
	ParentFrame  *AuditsAffectedFrame          `json:"parentFrame,omitempty"`
	BlockedFrame *AuditsAffectedFrame          `json:"blockedFrame,omitempty"`
	Reason       AuditsBlockedByResponseReason `json:"reason"`
}

type AuditsHeavyAdResolutionStatus string

const (
	AuditsHeavyAdResolutionStatusHeavyAdBlocked AuditsHeavyAdResolutionStatus = "HeavyAdBlocked"
	AuditsHeavyAdResolutionStatusHeavyAdWarning AuditsHeavyAdResolutionStatus = "HeavyAdWarning"
)

type AuditsHeavyAdReason string

const (
	AuditsHeavyAdReasonNetworkTotalLimit AuditsHeavyAdReason = "NetworkTotalLimit"
	AuditsHeavyAdReasonCpuTotalLimit     AuditsHeavyAdReason = "CpuTotalLimit"
	AuditsHeavyAdReasonCpuPeakLimit      AuditsHeavyAdReason = "CpuPeakLimit"
)

type AuditsHeavyAdIssueDetails struct {
	// The resolution status, either blocking the content or warning.
	Resolution AuditsHeavyAdResolutionStatus `json:"resolution"`
	// The reason the ad was blocked, total network or cpu or peak cpu.
	Reason AuditsHeavyAdReason `json:"reason"`
	// The frame that was blocked.
	Frame AuditsAffectedFrame `json:"frame"`
}

type AuditsContentSecurityPolicyViolationType string

const (
	AuditsContentSecurityPolicyViolationTypeKInlineViolation             AuditsContentSecurityPolicyViolationType = "kInlineViolation"
	AuditsContentSecurityPolicyViolationTypeKEvalViolation               AuditsContentSecurityPolicyViolationType = "kEvalViolation"
	AuditsContentSecurityPolicyViolationTypeKURLViolation                AuditsContentSecurityPolicyViolationType = "kURLViolation"
	AuditsContentSecurityPolicyViolationTypeKSRIViolation                AuditsContentSecurityPolicyViolationType = "kSRIViolation"
	AuditsContentSecurityPolicyViolationTypeKTrustedTypesSinkViolation   AuditsContentSecurityPolicyViolationType = "kTrustedTypesSinkViolation"
	AuditsContentSecurityPolicyViolationTypeKTrustedTypesPolicyViolation AuditsContentSecurityPolicyViolationType = "kTrustedTypesPolicyViolation"
	AuditsContentSecurityPolicyViolationTypeKWasmEvalViolation           AuditsContentSecurityPolicyViolationType = "kWasmEvalViolation"
)

type AuditsSourceCodeLocation struct {
	ScriptId     *RuntimeScriptId `json:"scriptId,omitempty"`
	Url          string           `json:"url"`
	LineNumber   int64            `json:"lineNumber"`
	ColumnNumber int64            `json:"columnNumber"`
}

type AuditsContentSecurityPolicyIssueDetails struct {
	// The url not included in allowed sources.
	BlockedURL *string `json:"blockedURL,omitempty"`
	// Specific directive that is violated, causing the CSP issue.
	ViolatedDirective                  string                                   `json:"violatedDirective"`
	IsReportOnly                       bool                                     `json:"isReportOnly"`
	ContentSecurityPolicyViolationType AuditsContentSecurityPolicyViolationType `json:"contentSecurityPolicyViolationType"`
	FrameAncestor                      *AuditsAffectedFrame                     `json:"frameAncestor,omitempty"`
	SourceCodeLocation                 *AuditsSourceCodeLocation                `json:"sourceCodeLocation,omitempty"`
	ViolatingNodeId                    *DOMBackendNodeId                        `json:"violatingNodeId,omitempty"`
}

type AuditsSharedArrayBufferIssueType string

const (
	AuditsSharedArrayBufferIssueTypeTransferIssue AuditsSharedArrayBufferIssueType = "TransferIssue"
	AuditsSharedArrayBufferIssueTypeCreationIssue AuditsSharedArrayBufferIssueType = "CreationIssue"
)

// Details for a issue arising from an SAB being instantiated in, or
// transferred to a context that is not cross-origin isolated.
type AuditsSharedArrayBufferIssueDetails struct {
	SourceCodeLocation AuditsSourceCodeLocation         `json:"sourceCodeLocation"`
	IsWarning          bool                             `json:"isWarning"`
	Type               AuditsSharedArrayBufferIssueType `json:"type"`
}

// Details for a CORS related issue, e.g. a warning or error related to
// CORS RFC1918 enforcement.
type AuditsCorsIssueDetails struct {
	CorsErrorStatus        NetworkCorsErrorStatus      `json:"corsErrorStatus"`
	IsWarning              bool                        `json:"isWarning"`
	Request                AuditsAffectedRequest       `json:"request"`
	Location               *AuditsSourceCodeLocation   `json:"location,omitempty"`
	InitiatorOrigin        *string                     `json:"initiatorOrigin,omitempty"`
	ResourceIPAddressSpace *NetworkIPAddressSpace      `json:"resourceIPAddressSpace,omitempty"`
	ClientSecurityState    *NetworkClientSecurityState `json:"clientSecurityState,omitempty"`
}

type AuditsAttributionReportingIssueType string

const (
	AuditsAttributionReportingIssueTypePermissionPolicyDisabled                             AuditsAttributionReportingIssueType = "PermissionPolicyDisabled"
	AuditsAttributionReportingIssueTypeUntrustworthyReportingOrigin                         AuditsAttributionReportingIssueType = "UntrustworthyReportingOrigin"
	AuditsAttributionReportingIssueTypeInsecureContext                                      AuditsAttributionReportingIssueType = "InsecureContext"
	AuditsAttributionReportingIssueTypeInvalidHeader                                        AuditsAttributionReportingIssueType = "InvalidHeader"
	AuditsAttributionReportingIssueTypeInvalidRegisterTriggerHeader                         AuditsAttributionReportingIssueType = "InvalidRegisterTriggerHeader"
	AuditsAttributionReportingIssueTypeSourceAndTriggerHeaders                              AuditsAttributionReportingIssueType = "SourceAndTriggerHeaders"
	AuditsAttributionReportingIssueTypeSourceIgnored                                        AuditsAttributionReportingIssueType = "SourceIgnored"
	AuditsAttributionReportingIssueTypeTriggerIgnored                                       AuditsAttributionReportingIssueType = "TriggerIgnored"
	AuditsAttributionReportingIssueTypeOsSourceIgnored                                      AuditsAttributionReportingIssueType = "OsSourceIgnored"
	AuditsAttributionReportingIssueTypeOsTriggerIgnored                                     AuditsAttributionReportingIssueType = "OsTriggerIgnored"
	AuditsAttributionReportingIssueTypeInvalidRegisterOsSourceHeader                        AuditsAttributionReportingIssueType = "InvalidRegisterOsSourceHeader"
	AuditsAttributionReportingIssueTypeInvalidRegisterOsTriggerHeader                       AuditsAttributionReportingIssueType = "InvalidRegisterOsTriggerHeader"
	AuditsAttributionReportingIssueTypeWebAndOsHeaders                                      AuditsAttributionReportingIssueType = "WebAndOsHeaders"
	AuditsAttributionReportingIssueTypeNoWebOrOsSupport                                     AuditsAttributionReportingIssueType = "NoWebOrOsSupport"
	AuditsAttributionReportingIssueTypeNavigationRegistrationWithoutTransientUserActivation AuditsAttributionReportingIssueType = "NavigationRegistrationWithoutTransientUserActivation"
	AuditsAttributionReportingIssueTypeInvalidInfoHeader                                    AuditsAttributionReportingIssueType = "InvalidInfoHeader"
	AuditsAttributionReportingIssueTypeNoRegisterSourceHeader                               AuditsAttributionReportingIssueType = "NoRegisterSourceHeader"
	AuditsAttributionReportingIssueTypeNoRegisterTriggerHeader                              AuditsAttributionReportingIssueType = "NoRegisterTriggerHeader"
	AuditsAttributionReportingIssueTypeNoRegisterOsSourceHeader                             AuditsAttributionReportingIssueType = "NoRegisterOsSourceHeader"
	AuditsAttributionReportingIssueTypeNoRegisterOsTriggerHeader                            AuditsAttributionReportingIssueType = "NoRegisterOsTriggerHeader"
	AuditsAttributionReportingIssueTypeNavigationRegistrationUniqueScopeAlreadySet          AuditsAttributionReportingIssueType = "NavigationRegistrationUniqueScopeAlreadySet"
)

type AuditsSharedDictionaryError string

const (
	AuditsSharedDictionaryErrorUseErrorCrossOriginNoCorsRequest          AuditsSharedDictionaryError = "UseErrorCrossOriginNoCorsRequest"
	AuditsSharedDictionaryErrorUseErrorDictionaryLoadFailure             AuditsSharedDictionaryError = "UseErrorDictionaryLoadFailure"
	AuditsSharedDictionaryErrorUseErrorMatchingDictionaryNotUsed         AuditsSharedDictionaryError = "UseErrorMatchingDictionaryNotUsed"
	AuditsSharedDictionaryErrorUseErrorUnexpectedContentDictionaryHeader AuditsSharedDictionaryError = "UseErrorUnexpectedContentDictionaryHeader"
	AuditsSharedDictionaryErrorWriteErrorCossOriginNoCorsRequest         AuditsSharedDictionaryError = "WriteErrorCossOriginNoCorsRequest"
	AuditsSharedDictionaryErrorWriteErrorDisallowedBySettings            AuditsSharedDictionaryError = "WriteErrorDisallowedBySettings"
	AuditsSharedDictionaryErrorWriteErrorExpiredResponse                 AuditsSharedDictionaryError = "WriteErrorExpiredResponse"
	AuditsSharedDictionaryErrorWriteErrorFeatureDisabled                 AuditsSharedDictionaryError = "WriteErrorFeatureDisabled"
	AuditsSharedDictionaryErrorWriteErrorInsufficientResources           AuditsSharedDictionaryError = "WriteErrorInsufficientResources"
	AuditsSharedDictionaryErrorWriteErrorInvalidMatchField               AuditsSharedDictionaryError = "WriteErrorInvalidMatchField"
	AuditsSharedDictionaryErrorWriteErrorInvalidStructuredHeader         AuditsSharedDictionaryError = "WriteErrorInvalidStructuredHeader"
	AuditsSharedDictionaryErrorWriteErrorInvalidTTLField                 AuditsSharedDictionaryError = "WriteErrorInvalidTTLField"
	AuditsSharedDictionaryErrorWriteErrorNavigationRequest               AuditsSharedDictionaryError = "WriteErrorNavigationRequest"
	AuditsSharedDictionaryErrorWriteErrorNoMatchField                    AuditsSharedDictionaryError = "WriteErrorNoMatchField"
	AuditsSharedDictionaryErrorWriteErrorNonIntegerTTLField              AuditsSharedDictionaryError = "WriteErrorNonIntegerTTLField"
	AuditsSharedDictionaryErrorWriteErrorNonListMatchDestField           AuditsSharedDictionaryError = "WriteErrorNonListMatchDestField"
	AuditsSharedDictionaryErrorWriteErrorNonSecureContext                AuditsSharedDictionaryError = "WriteErrorNonSecureContext"
	AuditsSharedDictionaryErrorWriteErrorNonStringIdField                AuditsSharedDictionaryError = "WriteErrorNonStringIdField"
	AuditsSharedDictionaryErrorWriteErrorNonStringInMatchDestList        AuditsSharedDictionaryError = "WriteErrorNonStringInMatchDestList"
	AuditsSharedDictionaryErrorWriteErrorNonStringMatchField             AuditsSharedDictionaryError = "WriteErrorNonStringMatchField"
	AuditsSharedDictionaryErrorWriteErrorNonTokenTypeField               AuditsSharedDictionaryError = "WriteErrorNonTokenTypeField"
	AuditsSharedDictionaryErrorWriteErrorRequestAborted                  AuditsSharedDictionaryError = "WriteErrorRequestAborted"
	AuditsSharedDictionaryErrorWriteErrorShuttingDown                    AuditsSharedDictionaryError = "WriteErrorShuttingDown"
	AuditsSharedDictionaryErrorWriteErrorTooLongIdField                  AuditsSharedDictionaryError = "WriteErrorTooLongIdField"
	AuditsSharedDictionaryErrorWriteErrorUnsupportedType                 AuditsSharedDictionaryError = "WriteErrorUnsupportedType"
)

type AuditsSRIMessageSignatureError string

const (
	AuditsSRIMessageSignatureErrorMissingSignatureHeader                               AuditsSRIMessageSignatureError = "MissingSignatureHeader"
	AuditsSRIMessageSignatureErrorMissingSignatureInputHeader                          AuditsSRIMessageSignatureError = "MissingSignatureInputHeader"
	AuditsSRIMessageSignatureErrorInvalidSignatureHeader                               AuditsSRIMessageSignatureError = "InvalidSignatureHeader"
	AuditsSRIMessageSignatureErrorInvalidSignatureInputHeader                          AuditsSRIMessageSignatureError = "InvalidSignatureInputHeader"
	AuditsSRIMessageSignatureErrorSignatureHeaderValueIsNotByteSequence                AuditsSRIMessageSignatureError = "SignatureHeaderValueIsNotByteSequence"
	AuditsSRIMessageSignatureErrorSignatureHeaderValueIsParameterized                  AuditsSRIMessageSignatureError = "SignatureHeaderValueIsParameterized"
	AuditsSRIMessageSignatureErrorSignatureHeaderValueIsIncorrectLength                AuditsSRIMessageSignatureError = "SignatureHeaderValueIsIncorrectLength"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderMissingLabel                     AuditsSRIMessageSignatureError = "SignatureInputHeaderMissingLabel"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderValueNotInnerList                AuditsSRIMessageSignatureError = "SignatureInputHeaderValueNotInnerList"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderValueMissingComponents           AuditsSRIMessageSignatureError = "SignatureInputHeaderValueMissingComponents"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderInvalidComponentType             AuditsSRIMessageSignatureError = "SignatureInputHeaderInvalidComponentType"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderInvalidComponentName             AuditsSRIMessageSignatureError = "SignatureInputHeaderInvalidComponentName"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderInvalidHeaderComponentParameter  AuditsSRIMessageSignatureError = "SignatureInputHeaderInvalidHeaderComponentParameter"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderInvalidDerivedComponentParameter AuditsSRIMessageSignatureError = "SignatureInputHeaderInvalidDerivedComponentParameter"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderKeyIdLength                      AuditsSRIMessageSignatureError = "SignatureInputHeaderKeyIdLength"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderInvalidParameter                 AuditsSRIMessageSignatureError = "SignatureInputHeaderInvalidParameter"
	AuditsSRIMessageSignatureErrorSignatureInputHeaderMissingRequiredParameters        AuditsSRIMessageSignatureError = "SignatureInputHeaderMissingRequiredParameters"
	AuditsSRIMessageSignatureErrorValidationFailedSignatureExpired                     AuditsSRIMessageSignatureError = "ValidationFailedSignatureExpired"
	AuditsSRIMessageSignatureErrorValidationFailedInvalidLength                        AuditsSRIMessageSignatureError = "ValidationFailedInvalidLength"
	AuditsSRIMessageSignatureErrorValidationFailedSignatureMismatch                    AuditsSRIMessageSignatureError = "ValidationFailedSignatureMismatch"
	AuditsSRIMessageSignatureErrorValidationFailedIntegrityMismatch                    AuditsSRIMessageSignatureError = "ValidationFailedIntegrityMismatch"
)

type AuditsUnencodedDigestError string

const (
	AuditsUnencodedDigestErrorMalformedDictionary   AuditsUnencodedDigestError = "MalformedDictionary"
	AuditsUnencodedDigestErrorUnknownAlgorithm      AuditsUnencodedDigestError = "UnknownAlgorithm"
	AuditsUnencodedDigestErrorIncorrectDigestType   AuditsUnencodedDigestError = "IncorrectDigestType"
	AuditsUnencodedDigestErrorIncorrectDigestLength AuditsUnencodedDigestError = "IncorrectDigestLength"
)

type AuditsConnectionAllowlistError string

const (
	AuditsConnectionAllowlistErrorInvalidHeader             AuditsConnectionAllowlistError = "InvalidHeader"
	AuditsConnectionAllowlistErrorMoreThanOneList           AuditsConnectionAllowlistError = "MoreThanOneList"
	AuditsConnectionAllowlistErrorItemNotInnerList          AuditsConnectionAllowlistError = "ItemNotInnerList"
	AuditsConnectionAllowlistErrorInvalidAllowlistItemType  AuditsConnectionAllowlistError = "InvalidAllowlistItemType"
	AuditsConnectionAllowlistErrorReportingEndpointNotToken AuditsConnectionAllowlistError = "ReportingEndpointNotToken"
	AuditsConnectionAllowlistErrorInvalidUrlPattern         AuditsConnectionAllowlistError = "InvalidUrlPattern"
)

// Details for issues around "Attribution Reporting API" usage.
// Explainer: https://github.com/WICG/attribution-reporting-api
type AuditsAttributionReportingIssueDetails struct {
	ViolationType    AuditsAttributionReportingIssueType `json:"violationType"`
	Request          *AuditsAffectedRequest              `json:"request,omitempty"`
	ViolatingNodeId  *DOMBackendNodeId                   `json:"violatingNodeId,omitempty"`
	InvalidParameter *string                             `json:"invalidParameter,omitempty"`
}

// Details for issues about documents in Quirks Mode
// or Limited Quirks Mode that affects page layouting.
type AuditsQuirksModeIssueDetails struct {
	// If false, it means the document's mode is "quirks"
	// instead of "limited-quirks".
	IsLimitedQuirksMode bool             `json:"isLimitedQuirksMode"`
	DocumentNodeId      DOMBackendNodeId `json:"documentNodeId"`
	Url                 string           `json:"url"`
	FrameId             PageFrameId      `json:"frameId"`
	LoaderId            NetworkLoaderId  `json:"loaderId"`
}

type AuditsNavigatorUserAgentIssueDetails struct {
	Url      string                    `json:"url"`
	Location *AuditsSourceCodeLocation `json:"location,omitempty"`
}

type AuditsSharedDictionaryIssueDetails struct {
	SharedDictionaryError AuditsSharedDictionaryError `json:"sharedDictionaryError"`
	Request               AuditsAffectedRequest       `json:"request"`
}

type AuditsSRIMessageSignatureIssueDetails struct {
	Error               AuditsSRIMessageSignatureError `json:"error"`
	SignatureBase       string                         `json:"signatureBase"`
	IntegrityAssertions []string                       `json:"integrityAssertions"`
	Request             AuditsAffectedRequest          `json:"request"`
}

type AuditsUnencodedDigestIssueDetails struct {
	Error   AuditsUnencodedDigestError `json:"error"`
	Request AuditsAffectedRequest      `json:"request"`
}

type AuditsConnectionAllowlistIssueDetails struct {
	Error   AuditsConnectionAllowlistError `json:"error"`
	Request AuditsAffectedRequest          `json:"request"`
}

type AuditsGenericIssueErrorType string

const (
	AuditsGenericIssueErrorTypeFormLabelForNameError                                      AuditsGenericIssueErrorType = "FormLabelForNameError"
	AuditsGenericIssueErrorTypeFormDuplicateIdForInputError                               AuditsGenericIssueErrorType = "FormDuplicateIdForInputError"
	AuditsGenericIssueErrorTypeFormInputWithNoLabelError                                  AuditsGenericIssueErrorType = "FormInputWithNoLabelError"
	AuditsGenericIssueErrorTypeFormAutocompleteAttributeEmptyError                        AuditsGenericIssueErrorType = "FormAutocompleteAttributeEmptyError"
	AuditsGenericIssueErrorTypeFormEmptyIdAndNameAttributesForInputError                  AuditsGenericIssueErrorType = "FormEmptyIdAndNameAttributesForInputError"
	AuditsGenericIssueErrorTypeFormAriaLabelledByToNonExistingIdError                     AuditsGenericIssueErrorType = "FormAriaLabelledByToNonExistingIdError"
	AuditsGenericIssueErrorTypeFormInputAssignedAutocompleteValueToIdOrNameAttributeError AuditsGenericIssueErrorType = "FormInputAssignedAutocompleteValueToIdOrNameAttributeError"
	AuditsGenericIssueErrorTypeFormLabelHasNeitherForNorNestedInputError                  AuditsGenericIssueErrorType = "FormLabelHasNeitherForNorNestedInputError"
	AuditsGenericIssueErrorTypeFormLabelForMatchesNonExistingIdError                      AuditsGenericIssueErrorType = "FormLabelForMatchesNonExistingIdError"
	AuditsGenericIssueErrorTypeFormInputHasWrongButWellIntendedAutocompleteValueError     AuditsGenericIssueErrorType = "FormInputHasWrongButWellIntendedAutocompleteValueError"
	AuditsGenericIssueErrorTypeResponseWasBlockedByORB                                    AuditsGenericIssueErrorType = "ResponseWasBlockedByORB"
	AuditsGenericIssueErrorTypeNavigationEntryMarkedSkippable                             AuditsGenericIssueErrorType = "NavigationEntryMarkedSkippable"
	AuditsGenericIssueErrorTypeAutofillAndManualTextPolicyControlledFeaturesInfo          AuditsGenericIssueErrorType = "AutofillAndManualTextPolicyControlledFeaturesInfo"
	AuditsGenericIssueErrorTypeAutofillPolicyControlledFeatureInfo                        AuditsGenericIssueErrorType = "AutofillPolicyControlledFeatureInfo"
	AuditsGenericIssueErrorTypeManualTextPolicyControlledFeatureInfo                      AuditsGenericIssueErrorType = "ManualTextPolicyControlledFeatureInfo"
	AuditsGenericIssueErrorTypeFormModelContextParameterMissingTitleAndDescription        AuditsGenericIssueErrorType = "FormModelContextParameterMissingTitleAndDescription"
)

// Depending on the concrete errorType, different properties are set.
type AuditsGenericIssueDetails struct {
	// Issues with the same errorType are aggregated in the frontend.
	ErrorType              AuditsGenericIssueErrorType `json:"errorType"`
	FrameId                *PageFrameId                `json:"frameId,omitempty"`
	ViolatingNodeId        *DOMBackendNodeId           `json:"violatingNodeId,omitempty"`
	ViolatingNodeAttribute *string                     `json:"violatingNodeAttribute,omitempty"`
	Request                *AuditsAffectedRequest      `json:"request,omitempty"`
}

// This issue tracks information needed to print a deprecation message.
// https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/frame/third_party/blink/renderer/core/frame/deprecation/README.md
type AuditsDeprecationIssueDetails struct {
	AffectedFrame      *AuditsAffectedFrame     `json:"affectedFrame,omitempty"`
	SourceCodeLocation AuditsSourceCodeLocation `json:"sourceCodeLocation"`
	// One of the deprecation names from third_party/blink/renderer/core/frame/deprecation/deprecation.json5
	Type string `json:"type"`
}

// This issue warns about sites in the redirect chain of a finished navigation
// that may be flagged as trackers and have their state cleared if they don't
// receive a user interaction. Note that in this context 'site' means eTLD+1.
// For example, if the URL `https://example.test:80/bounce` was in the
// redirect chain, the site reported would be `example.test`.
type AuditsBounceTrackingIssueDetails struct {
	TrackingSites []string `json:"trackingSites"`
}

// This issue warns about third-party sites that are accessing cookies on the
// current page, and have been permitted due to having a global metadata grant.
// Note that in this context 'site' means eTLD+1. For example, if the URL
// `https://example.test:80/web_page` was accessing cookies, the site reported
// would be `example.test`.
type AuditsCookieDeprecationMetadataIssueDetails struct {
	AllowedSites     []string              `json:"allowedSites"`
	OptOutPercentage float64               `json:"optOutPercentage"`
	IsOptOutTopLevel bool                  `json:"isOptOutTopLevel"`
	Operation        AuditsCookieOperation `json:"operation"`
}

type AuditsClientHintIssueReason string

const (
	AuditsClientHintIssueReasonMetaTagAllowListInvalidOrigin AuditsClientHintIssueReason = "MetaTagAllowListInvalidOrigin"
	AuditsClientHintIssueReasonMetaTagModifiedHTML           AuditsClientHintIssueReason = "MetaTagModifiedHTML"
)

type AuditsFederatedAuthRequestIssueDetails struct {
	FederatedAuthRequestIssueReason AuditsFederatedAuthRequestIssueReason `json:"federatedAuthRequestIssueReason"`
}

// Represents the failure reason when a federated authentication reason fails.
// Should be updated alongside RequestIdTokenStatus in
// third_party/blink/public/mojom/devtools/inspector_issue.mojom to include
// all cases except for success.
type AuditsFederatedAuthRequestIssueReason string

const (
	AuditsFederatedAuthRequestIssueReasonShouldEmbargo                    AuditsFederatedAuthRequestIssueReason = "ShouldEmbargo"
	AuditsFederatedAuthRequestIssueReasonTooManyRequests                  AuditsFederatedAuthRequestIssueReason = "TooManyRequests"
	AuditsFederatedAuthRequestIssueReasonWellKnownHttpNotFound            AuditsFederatedAuthRequestIssueReason = "WellKnownHttpNotFound"
	AuditsFederatedAuthRequestIssueReasonWellKnownNoResponse              AuditsFederatedAuthRequestIssueReason = "WellKnownNoResponse"
	AuditsFederatedAuthRequestIssueReasonWellKnownInvalidResponse         AuditsFederatedAuthRequestIssueReason = "WellKnownInvalidResponse"
	AuditsFederatedAuthRequestIssueReasonWellKnownListEmpty               AuditsFederatedAuthRequestIssueReason = "WellKnownListEmpty"
	AuditsFederatedAuthRequestIssueReasonWellKnownInvalidContentType      AuditsFederatedAuthRequestIssueReason = "WellKnownInvalidContentType"
	AuditsFederatedAuthRequestIssueReasonConfigNotInWellKnown             AuditsFederatedAuthRequestIssueReason = "ConfigNotInWellKnown"
	AuditsFederatedAuthRequestIssueReasonWellKnownTooBig                  AuditsFederatedAuthRequestIssueReason = "WellKnownTooBig"
	AuditsFederatedAuthRequestIssueReasonConfigHttpNotFound               AuditsFederatedAuthRequestIssueReason = "ConfigHttpNotFound"
	AuditsFederatedAuthRequestIssueReasonConfigNoResponse                 AuditsFederatedAuthRequestIssueReason = "ConfigNoResponse"
	AuditsFederatedAuthRequestIssueReasonConfigInvalidResponse            AuditsFederatedAuthRequestIssueReason = "ConfigInvalidResponse"
	AuditsFederatedAuthRequestIssueReasonConfigInvalidContentType         AuditsFederatedAuthRequestIssueReason = "ConfigInvalidContentType"
	AuditsFederatedAuthRequestIssueReasonIdpNotPotentiallyTrustworthy     AuditsFederatedAuthRequestIssueReason = "IdpNotPotentiallyTrustworthy"
	AuditsFederatedAuthRequestIssueReasonDisabledInSettings               AuditsFederatedAuthRequestIssueReason = "DisabledInSettings"
	AuditsFederatedAuthRequestIssueReasonDisabledInFlags                  AuditsFederatedAuthRequestIssueReason = "DisabledInFlags"
	AuditsFederatedAuthRequestIssueReasonErrorFetchingSignin              AuditsFederatedAuthRequestIssueReason = "ErrorFetchingSignin"
	AuditsFederatedAuthRequestIssueReasonInvalidSigninResponse            AuditsFederatedAuthRequestIssueReason = "InvalidSigninResponse"
	AuditsFederatedAuthRequestIssueReasonAccountsHttpNotFound             AuditsFederatedAuthRequestIssueReason = "AccountsHttpNotFound"
	AuditsFederatedAuthRequestIssueReasonAccountsNoResponse               AuditsFederatedAuthRequestIssueReason = "AccountsNoResponse"
	AuditsFederatedAuthRequestIssueReasonAccountsInvalidResponse          AuditsFederatedAuthRequestIssueReason = "AccountsInvalidResponse"
	AuditsFederatedAuthRequestIssueReasonAccountsListEmpty                AuditsFederatedAuthRequestIssueReason = "AccountsListEmpty"
	AuditsFederatedAuthRequestIssueReasonAccountsInvalidContentType       AuditsFederatedAuthRequestIssueReason = "AccountsInvalidContentType"
	AuditsFederatedAuthRequestIssueReasonIdTokenHttpNotFound              AuditsFederatedAuthRequestIssueReason = "IdTokenHttpNotFound"
	AuditsFederatedAuthRequestIssueReasonIdTokenNoResponse                AuditsFederatedAuthRequestIssueReason = "IdTokenNoResponse"
	AuditsFederatedAuthRequestIssueReasonIdTokenInvalidResponse           AuditsFederatedAuthRequestIssueReason = "IdTokenInvalidResponse"
	AuditsFederatedAuthRequestIssueReasonIdTokenIdpErrorResponse          AuditsFederatedAuthRequestIssueReason = "IdTokenIdpErrorResponse"
	AuditsFederatedAuthRequestIssueReasonIdTokenCrossSiteIdpErrorResponse AuditsFederatedAuthRequestIssueReason = "IdTokenCrossSiteIdpErrorResponse"
	AuditsFederatedAuthRequestIssueReasonIdTokenInvalidRequest            AuditsFederatedAuthRequestIssueReason = "IdTokenInvalidRequest"
	AuditsFederatedAuthRequestIssueReasonIdTokenInvalidContentType        AuditsFederatedAuthRequestIssueReason = "IdTokenInvalidContentType"
	AuditsFederatedAuthRequestIssueReasonErrorIdToken                     AuditsFederatedAuthRequestIssueReason = "ErrorIdToken"
	AuditsFederatedAuthRequestIssueReasonCanceled                         AuditsFederatedAuthRequestIssueReason = "Canceled"
	AuditsFederatedAuthRequestIssueReasonRpPageNotVisible                 AuditsFederatedAuthRequestIssueReason = "RpPageNotVisible"
	AuditsFederatedAuthRequestIssueReasonSilentMediationFailure           AuditsFederatedAuthRequestIssueReason = "SilentMediationFailure"
	AuditsFederatedAuthRequestIssueReasonNotSignedInWithIdp               AuditsFederatedAuthRequestIssueReason = "NotSignedInWithIdp"
	AuditsFederatedAuthRequestIssueReasonMissingTransientUserActivation   AuditsFederatedAuthRequestIssueReason = "MissingTransientUserActivation"
	AuditsFederatedAuthRequestIssueReasonReplacedByActiveMode             AuditsFederatedAuthRequestIssueReason = "ReplacedByActiveMode"
	AuditsFederatedAuthRequestIssueReasonRelyingPartyOriginIsOpaque       AuditsFederatedAuthRequestIssueReason = "RelyingPartyOriginIsOpaque"
	AuditsFederatedAuthRequestIssueReasonTypeNotMatching                  AuditsFederatedAuthRequestIssueReason = "TypeNotMatching"
	AuditsFederatedAuthRequestIssueReasonUiDismissedNoEmbargo             AuditsFederatedAuthRequestIssueReason = "UiDismissedNoEmbargo"
	AuditsFederatedAuthRequestIssueReasonCorsError                        AuditsFederatedAuthRequestIssueReason = "CorsError"
	AuditsFederatedAuthRequestIssueReasonSuppressedBySegmentationPlatform AuditsFederatedAuthRequestIssueReason = "SuppressedBySegmentationPlatform"
)

type AuditsFederatedAuthUserInfoRequestIssueDetails struct {
	FederatedAuthUserInfoRequestIssueReason AuditsFederatedAuthUserInfoRequestIssueReason `json:"federatedAuthUserInfoRequestIssueReason"`
}

// Represents the failure reason when a getUserInfo() call fails.
// Should be updated alongside FederatedAuthUserInfoRequestResult in
// third_party/blink/public/mojom/devtools/inspector_issue.mojom.
type AuditsFederatedAuthUserInfoRequestIssueReason string

const (
	AuditsFederatedAuthUserInfoRequestIssueReasonNotSameOrigin                      AuditsFederatedAuthUserInfoRequestIssueReason = "NotSameOrigin"
	AuditsFederatedAuthUserInfoRequestIssueReasonNotIframe                          AuditsFederatedAuthUserInfoRequestIssueReason = "NotIframe"
	AuditsFederatedAuthUserInfoRequestIssueReasonNotPotentiallyTrustworthy          AuditsFederatedAuthUserInfoRequestIssueReason = "NotPotentiallyTrustworthy"
	AuditsFederatedAuthUserInfoRequestIssueReasonNoApiPermission                    AuditsFederatedAuthUserInfoRequestIssueReason = "NoApiPermission"
	AuditsFederatedAuthUserInfoRequestIssueReasonNotSignedInWithIdp                 AuditsFederatedAuthUserInfoRequestIssueReason = "NotSignedInWithIdp"
	AuditsFederatedAuthUserInfoRequestIssueReasonNoAccountSharingPermission         AuditsFederatedAuthUserInfoRequestIssueReason = "NoAccountSharingPermission"
	AuditsFederatedAuthUserInfoRequestIssueReasonInvalidConfigOrWellKnown           AuditsFederatedAuthUserInfoRequestIssueReason = "InvalidConfigOrWellKnown"
	AuditsFederatedAuthUserInfoRequestIssueReasonInvalidAccountsResponse            AuditsFederatedAuthUserInfoRequestIssueReason = "InvalidAccountsResponse"
	AuditsFederatedAuthUserInfoRequestIssueReasonNoReturningUserFromFetchedAccounts AuditsFederatedAuthUserInfoRequestIssueReason = "NoReturningUserFromFetchedAccounts"
)

// This issue tracks client hints related issues. It's used to deprecate old
// features, encourage the use of new ones, and provide general guidance.
type AuditsClientHintIssueDetails struct {
	SourceCodeLocation    AuditsSourceCodeLocation    `json:"sourceCodeLocation"`
	ClientHintIssueReason AuditsClientHintIssueReason `json:"clientHintIssueReason"`
}

type AuditsFailedRequestInfo struct {
	// The URL that failed to load.
	Url string `json:"url"`
	// The failure message for the failed request.
	FailureMessage string            `json:"failureMessage"`
	RequestId      *NetworkRequestId `json:"requestId,omitempty"`
}

type AuditsPartitioningBlobURLInfo string

const (
	AuditsPartitioningBlobURLInfoBlockedCrossPartitionFetching AuditsPartitioningBlobURLInfo = "BlockedCrossPartitionFetching"
	AuditsPartitioningBlobURLInfoEnforceNoopenerForNavigation  AuditsPartitioningBlobURLInfo = "EnforceNoopenerForNavigation"
)

type AuditsPartitioningBlobURLIssueDetails struct {
	// The BlobURL that failed to load.
	Url string `json:"url"`
	// Additional information about the Partitioning Blob URL issue.
	PartitioningBlobURLInfo AuditsPartitioningBlobURLInfo `json:"partitioningBlobURLInfo"`
}

type AuditsElementAccessibilityIssueReason string

const (
	AuditsElementAccessibilityIssueReasonDisallowedSelectChild               AuditsElementAccessibilityIssueReason = "DisallowedSelectChild"
	AuditsElementAccessibilityIssueReasonDisallowedOptGroupChild             AuditsElementAccessibilityIssueReason = "DisallowedOptGroupChild"
	AuditsElementAccessibilityIssueReasonNonPhrasingContentOptionChild       AuditsElementAccessibilityIssueReason = "NonPhrasingContentOptionChild"
	AuditsElementAccessibilityIssueReasonInteractiveContentOptionChild       AuditsElementAccessibilityIssueReason = "InteractiveContentOptionChild"
	AuditsElementAccessibilityIssueReasonInteractiveContentLegendChild       AuditsElementAccessibilityIssueReason = "InteractiveContentLegendChild"
	AuditsElementAccessibilityIssueReasonInteractiveContentSummaryDescendant AuditsElementAccessibilityIssueReason = "InteractiveContentSummaryDescendant"
)

// This issue warns about errors in the select or summary element content model.
type AuditsElementAccessibilityIssueDetails struct {
	NodeId                          DOMBackendNodeId                      `json:"nodeId"`
	ElementAccessibilityIssueReason AuditsElementAccessibilityIssueReason `json:"elementAccessibilityIssueReason"`
	HasDisallowedAttributes         bool                                  `json:"hasDisallowedAttributes"`
}

type AuditsStyleSheetLoadingIssueReason string

const (
	AuditsStyleSheetLoadingIssueReasonLateImportRule AuditsStyleSheetLoadingIssueReason = "LateImportRule"
	AuditsStyleSheetLoadingIssueReasonRequestFailed  AuditsStyleSheetLoadingIssueReason = "RequestFailed"
)

// This issue warns when a referenced stylesheet couldn't be loaded.
type AuditsStylesheetLoadingIssueDetails struct {
	// Source code position that referenced the failing stylesheet.
	SourceCodeLocation AuditsSourceCodeLocation `json:"sourceCodeLocation"`
	// Reason why the stylesheet couldn't be loaded.
	StyleSheetLoadingIssueReason AuditsStyleSheetLoadingIssueReason `json:"styleSheetLoadingIssueReason"`
	// Contains additional info when the failure was due to a request.
	FailedRequestInfo *AuditsFailedRequestInfo `json:"failedRequestInfo,omitempty"`
}

type AuditsPropertyRuleIssueReason string

const (
	AuditsPropertyRuleIssueReasonInvalidSyntax       AuditsPropertyRuleIssueReason = "InvalidSyntax"
	AuditsPropertyRuleIssueReasonInvalidInitialValue AuditsPropertyRuleIssueReason = "InvalidInitialValue"
	AuditsPropertyRuleIssueReasonInvalidInherits     AuditsPropertyRuleIssueReason = "InvalidInherits"
	AuditsPropertyRuleIssueReasonInvalidName         AuditsPropertyRuleIssueReason = "InvalidName"
)

// This issue warns about errors in property rules that lead to property
// registrations being ignored.
type AuditsPropertyRuleIssueDetails struct {
	// Source code position of the property rule.
	SourceCodeLocation AuditsSourceCodeLocation `json:"sourceCodeLocation"`
	// Reason why the property rule was discarded.
	PropertyRuleIssueReason AuditsPropertyRuleIssueReason `json:"propertyRuleIssueReason"`
	// The value of the property rule property that failed to parse
	PropertyValue *string `json:"propertyValue,omitempty"`
}

type AuditsUserReidentificationIssueType string

const (
	AuditsUserReidentificationIssueTypeBlockedFrameNavigation AuditsUserReidentificationIssueType = "BlockedFrameNavigation"
	AuditsUserReidentificationIssueTypeBlockedSubresource     AuditsUserReidentificationIssueType = "BlockedSubresource"
	AuditsUserReidentificationIssueTypeNoisedCanvasReadback   AuditsUserReidentificationIssueType = "NoisedCanvasReadback"
)

// This issue warns about uses of APIs that may be considered misuse to
// re-identify users.
type AuditsUserReidentificationIssueDetails struct {
	Type AuditsUserReidentificationIssueType `json:"type"`
	// Applies to BlockedFrameNavigation and BlockedSubresource issue types.
	Request *AuditsAffectedRequest `json:"request,omitempty"`
	// Applies to NoisedCanvasReadback issue type.
	SourceCodeLocation *AuditsSourceCodeLocation `json:"sourceCodeLocation,omitempty"`
}

type AuditsPermissionElementIssueType string

const (
	AuditsPermissionElementIssueTypeInvalidType               AuditsPermissionElementIssueType = "InvalidType"
	AuditsPermissionElementIssueTypeFencedFrameDisallowed     AuditsPermissionElementIssueType = "FencedFrameDisallowed"
	AuditsPermissionElementIssueTypeCspFrameAncestorsMissing  AuditsPermissionElementIssueType = "CspFrameAncestorsMissing"
	AuditsPermissionElementIssueTypePermissionsPolicyBlocked  AuditsPermissionElementIssueType = "PermissionsPolicyBlocked"
	AuditsPermissionElementIssueTypePaddingRightUnsupported   AuditsPermissionElementIssueType = "PaddingRightUnsupported"
	AuditsPermissionElementIssueTypePaddingBottomUnsupported  AuditsPermissionElementIssueType = "PaddingBottomUnsupported"
	AuditsPermissionElementIssueTypeInsetBoxShadowUnsupported AuditsPermissionElementIssueType = "InsetBoxShadowUnsupported"
	AuditsPermissionElementIssueTypeRequestInProgress         AuditsPermissionElementIssueType = "RequestInProgress"
	AuditsPermissionElementIssueTypeUntrustedEvent            AuditsPermissionElementIssueType = "UntrustedEvent"
	AuditsPermissionElementIssueTypeRegistrationFailed        AuditsPermissionElementIssueType = "RegistrationFailed"
	AuditsPermissionElementIssueTypeTypeNotSupported          AuditsPermissionElementIssueType = "TypeNotSupported"
	AuditsPermissionElementIssueTypeInvalidTypeActivation     AuditsPermissionElementIssueType = "InvalidTypeActivation"
	AuditsPermissionElementIssueTypeSecurityChecksFailed      AuditsPermissionElementIssueType = "SecurityChecksFailed"
	AuditsPermissionElementIssueTypeActivationDisabled        AuditsPermissionElementIssueType = "ActivationDisabled"
	AuditsPermissionElementIssueTypeGeolocationDeprecated     AuditsPermissionElementIssueType = "GeolocationDeprecated"
	AuditsPermissionElementIssueTypeInvalidDisplayStyle       AuditsPermissionElementIssueType = "InvalidDisplayStyle"
	AuditsPermissionElementIssueTypeNonOpaqueColor            AuditsPermissionElementIssueType = "NonOpaqueColor"
	AuditsPermissionElementIssueTypeLowContrast               AuditsPermissionElementIssueType = "LowContrast"
	AuditsPermissionElementIssueTypeFontSizeTooSmall          AuditsPermissionElementIssueType = "FontSizeTooSmall"
	AuditsPermissionElementIssueTypeFontSizeTooLarge          AuditsPermissionElementIssueType = "FontSizeTooLarge"
	AuditsPermissionElementIssueTypeInvalidSizeValue          AuditsPermissionElementIssueType = "InvalidSizeValue"
)

// This issue warns about improper usage of the <permission> element.
type AuditsPermissionElementIssueDetails struct {
	IssueType AuditsPermissionElementIssueType `json:"issueType"`
	// The value of the type attribute.
	Type *string `json:"type,omitempty"`
	// The node ID of the <permission> element.
	NodeId *DOMBackendNodeId `json:"nodeId,omitempty"`
	// True if the issue is a warning, false if it is an error.
	IsWarning *bool `json:"isWarning,omitempty"`
	// Fields for message construction:
	// Used for messages that reference a specific permission name
	PermissionName *string `json:"permissionName,omitempty"`
	// Used for messages about occlusion
	OccluderNodeInfo *string `json:"occluderNodeInfo,omitempty"`
	// Used for messages about occluder's parent
	OccluderParentNodeInfo *string `json:"occluderParentNodeInfo,omitempty"`
	// Used for messages about activation disabled reason
	DisableReason *string `json:"disableReason,omitempty"`
}

// The issue warns about blocked calls to privacy sensitive APIs via the
// Selective Permissions Intervention.
type AuditsSelectivePermissionsInterventionIssueDetails struct {
	// Which API was intervened on.
	ApiName string `json:"apiName"`
	// Why the ad script using the API is considered an ad.
	AdAncestry NetworkAdAncestry `json:"adAncestry"`
	// The stack trace at the time of the intervention.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
}

// A unique identifier for the type of issue. Each type may use one of the
// optional fields in InspectorIssueDetails to convey more specific
// information about the kind of issue.
type AuditsInspectorIssueCode string

const (
	AuditsInspectorIssueCodeCookieIssue                           AuditsInspectorIssueCode = "CookieIssue"
	AuditsInspectorIssueCodeMixedContentIssue                     AuditsInspectorIssueCode = "MixedContentIssue"
	AuditsInspectorIssueCodeBlockedByResponseIssue                AuditsInspectorIssueCode = "BlockedByResponseIssue"
	AuditsInspectorIssueCodeHeavyAdIssue                          AuditsInspectorIssueCode = "HeavyAdIssue"
	AuditsInspectorIssueCodeContentSecurityPolicyIssue            AuditsInspectorIssueCode = "ContentSecurityPolicyIssue"
	AuditsInspectorIssueCodeSharedArrayBufferIssue                AuditsInspectorIssueCode = "SharedArrayBufferIssue"
	AuditsInspectorIssueCodeCorsIssue                             AuditsInspectorIssueCode = "CorsIssue"
	AuditsInspectorIssueCodeAttributionReportingIssue             AuditsInspectorIssueCode = "AttributionReportingIssue"
	AuditsInspectorIssueCodeQuirksModeIssue                       AuditsInspectorIssueCode = "QuirksModeIssue"
	AuditsInspectorIssueCodePartitioningBlobURLIssue              AuditsInspectorIssueCode = "PartitioningBlobURLIssue"
	AuditsInspectorIssueCodeNavigatorUserAgentIssue               AuditsInspectorIssueCode = "NavigatorUserAgentIssue"
	AuditsInspectorIssueCodeGenericIssue                          AuditsInspectorIssueCode = "GenericIssue"
	AuditsInspectorIssueCodeDeprecationIssue                      AuditsInspectorIssueCode = "DeprecationIssue"
	AuditsInspectorIssueCodeClientHintIssue                       AuditsInspectorIssueCode = "ClientHintIssue"
	AuditsInspectorIssueCodeFederatedAuthRequestIssue             AuditsInspectorIssueCode = "FederatedAuthRequestIssue"
	AuditsInspectorIssueCodeBounceTrackingIssue                   AuditsInspectorIssueCode = "BounceTrackingIssue"
	AuditsInspectorIssueCodeCookieDeprecationMetadataIssue        AuditsInspectorIssueCode = "CookieDeprecationMetadataIssue"
	AuditsInspectorIssueCodeStylesheetLoadingIssue                AuditsInspectorIssueCode = "StylesheetLoadingIssue"
	AuditsInspectorIssueCodeFederatedAuthUserInfoRequestIssue     AuditsInspectorIssueCode = "FederatedAuthUserInfoRequestIssue"
	AuditsInspectorIssueCodePropertyRuleIssue                     AuditsInspectorIssueCode = "PropertyRuleIssue"
	AuditsInspectorIssueCodeSharedDictionaryIssue                 AuditsInspectorIssueCode = "SharedDictionaryIssue"
	AuditsInspectorIssueCodeElementAccessibilityIssue             AuditsInspectorIssueCode = "ElementAccessibilityIssue"
	AuditsInspectorIssueCodeSRIMessageSignatureIssue              AuditsInspectorIssueCode = "SRIMessageSignatureIssue"
	AuditsInspectorIssueCodeUnencodedDigestIssue                  AuditsInspectorIssueCode = "UnencodedDigestIssue"
	AuditsInspectorIssueCodeConnectionAllowlistIssue              AuditsInspectorIssueCode = "ConnectionAllowlistIssue"
	AuditsInspectorIssueCodeUserReidentificationIssue             AuditsInspectorIssueCode = "UserReidentificationIssue"
	AuditsInspectorIssueCodePermissionElementIssue                AuditsInspectorIssueCode = "PermissionElementIssue"
	AuditsInspectorIssueCodePerformanceIssue                      AuditsInspectorIssueCode = "PerformanceIssue"
	AuditsInspectorIssueCodeSelectivePermissionsInterventionIssue AuditsInspectorIssueCode = "SelectivePermissionsInterventionIssue"
)

// This struct holds a list of optional fields with additional information
// specific to the kind of issue. When adding a new issue code, please also
// add a new optional field to this type.
type AuditsInspectorIssueDetails struct {
	CookieIssueDetails                           *AuditsCookieIssueDetails                           `json:"cookieIssueDetails,omitempty"`
	MixedContentIssueDetails                     *AuditsMixedContentIssueDetails                     `json:"mixedContentIssueDetails,omitempty"`
	BlockedByResponseIssueDetails                *AuditsBlockedByResponseIssueDetails                `json:"blockedByResponseIssueDetails,omitempty"`
	HeavyAdIssueDetails                          *AuditsHeavyAdIssueDetails                          `json:"heavyAdIssueDetails,omitempty"`
	ContentSecurityPolicyIssueDetails            *AuditsContentSecurityPolicyIssueDetails            `json:"contentSecurityPolicyIssueDetails,omitempty"`
	SharedArrayBufferIssueDetails                *AuditsSharedArrayBufferIssueDetails                `json:"sharedArrayBufferIssueDetails,omitempty"`
	CorsIssueDetails                             *AuditsCorsIssueDetails                             `json:"corsIssueDetails,omitempty"`
	AttributionReportingIssueDetails             *AuditsAttributionReportingIssueDetails             `json:"attributionReportingIssueDetails,omitempty"`
	QuirksModeIssueDetails                       *AuditsQuirksModeIssueDetails                       `json:"quirksModeIssueDetails,omitempty"`
	PartitioningBlobURLIssueDetails              *AuditsPartitioningBlobURLIssueDetails              `json:"partitioningBlobURLIssueDetails,omitempty"`
	NavigatorUserAgentIssueDetails               *AuditsNavigatorUserAgentIssueDetails               `json:"navigatorUserAgentIssueDetails,omitempty"`
	GenericIssueDetails                          *AuditsGenericIssueDetails                          `json:"genericIssueDetails,omitempty"`
	DeprecationIssueDetails                      *AuditsDeprecationIssueDetails                      `json:"deprecationIssueDetails,omitempty"`
	ClientHintIssueDetails                       *AuditsClientHintIssueDetails                       `json:"clientHintIssueDetails,omitempty"`
	FederatedAuthRequestIssueDetails             *AuditsFederatedAuthRequestIssueDetails             `json:"federatedAuthRequestIssueDetails,omitempty"`
	BounceTrackingIssueDetails                   *AuditsBounceTrackingIssueDetails                   `json:"bounceTrackingIssueDetails,omitempty"`
	CookieDeprecationMetadataIssueDetails        *AuditsCookieDeprecationMetadataIssueDetails        `json:"cookieDeprecationMetadataIssueDetails,omitempty"`
	StylesheetLoadingIssueDetails                *AuditsStylesheetLoadingIssueDetails                `json:"stylesheetLoadingIssueDetails,omitempty"`
	PropertyRuleIssueDetails                     *AuditsPropertyRuleIssueDetails                     `json:"propertyRuleIssueDetails,omitempty"`
	FederatedAuthUserInfoRequestIssueDetails     *AuditsFederatedAuthUserInfoRequestIssueDetails     `json:"federatedAuthUserInfoRequestIssueDetails,omitempty"`
	SharedDictionaryIssueDetails                 *AuditsSharedDictionaryIssueDetails                 `json:"sharedDictionaryIssueDetails,omitempty"`
	ElementAccessibilityIssueDetails             *AuditsElementAccessibilityIssueDetails             `json:"elementAccessibilityIssueDetails,omitempty"`
	SriMessageSignatureIssueDetails              *AuditsSRIMessageSignatureIssueDetails              `json:"sriMessageSignatureIssueDetails,omitempty"`
	UnencodedDigestIssueDetails                  *AuditsUnencodedDigestIssueDetails                  `json:"unencodedDigestIssueDetails,omitempty"`
	ConnectionAllowlistIssueDetails              *AuditsConnectionAllowlistIssueDetails              `json:"connectionAllowlistIssueDetails,omitempty"`
	UserReidentificationIssueDetails             *AuditsUserReidentificationIssueDetails             `json:"userReidentificationIssueDetails,omitempty"`
	PermissionElementIssueDetails                *AuditsPermissionElementIssueDetails                `json:"permissionElementIssueDetails,omitempty"`
	PerformanceIssueDetails                      *AuditsPerformanceIssueDetails                      `json:"performanceIssueDetails,omitempty"`
	SelectivePermissionsInterventionIssueDetails *AuditsSelectivePermissionsInterventionIssueDetails `json:"selectivePermissionsInterventionIssueDetails,omitempty"`
}

// A unique id for a DevTools inspector issue. Allows other entities (e.g.
// exceptions, CDP message, console messages, etc.) to reference an issue.
type AuditsIssueId string

// An inspector issue reported from the back-end.
type AuditsInspectorIssue struct {
	Code    AuditsInspectorIssueCode    `json:"code"`
	Details AuditsInspectorIssueDetails `json:"details"`
	// A unique id for this issue. May be omitted if no other entity (e.g.
	// exception, CDP message, etc.) is referencing this issue.
	IssueId *AuditsIssueId `json:"issueId,omitempty"`
}

// Returns the response body and size if it were re-encoded with the specified settings. Only
// applies to images.
type AuditsGetEncodedResponseParams struct {
	// Identifier of the network request to get content for.
	RequestId NetworkRequestId `json:"requestId"`
	// The encoding to use.
	Encoding string `json:"encoding"`
	// The quality of the encoding (0-1). (defaults to 1)
	Quality *float64 `json:"quality,omitempty"`
	// Whether to only return the size information (defaults to false).
	SizeOnly *bool `json:"sizeOnly,omitempty"`
}

type AuditsGetEncodedResponseReturns struct {
	// The encoded body as a base64 string. Omitted if sizeOnly is true. (Encoded as a base64 string when passed over JSON)
	Body *string `json:"body,omitempty"`
	// Size before re-encoding.
	OriginalSize int64 `json:"originalSize"`
	// Size after re-encoding.
	EncodedSize int64 `json:"encodedSize"`
}

func AuditsGetEncodedResponse(requestId NetworkRequestId, encoding string) *AuditsGetEncodedResponseParams {
	return &AuditsGetEncodedResponseParams{
		RequestId: requestId,
		Encoding:  encoding,
	}
}

func (p *AuditsGetEncodedResponseParams) WithQuality(v float64) *AuditsGetEncodedResponseParams {
	p.Quality = &v
	return p
}

func (p *AuditsGetEncodedResponseParams) WithSizeOnly(v bool) *AuditsGetEncodedResponseParams {
	p.SizeOnly = &v
	return p
}

func (p *AuditsGetEncodedResponseParams) CDPMethodName() string {
	return "Audits.getEncodedResponse"
}

// Disables issues domain, prevents further issues from being reported to the client.
type AuditsDisableParams struct {
}

func AuditsDisable() *AuditsDisableParams {
	return &AuditsDisableParams{}
}

func (p *AuditsDisableParams) CDPMethodName() string {
	return "Audits.disable"
}

// Enables issues domain, sends the issues collected so far to the client by means of the
// `issueAdded` event.
type AuditsEnableParams struct {
}

func AuditsEnable() *AuditsEnableParams {
	return &AuditsEnableParams{}
}

func (p *AuditsEnableParams) CDPMethodName() string {
	return "Audits.enable"
}

// Runs the form issues check for the target page. Found issues are reported
// using Audits.issueAdded event.
type AuditsCheckFormsIssuesParams struct {
}

type AuditsCheckFormsIssuesReturns struct {
	FormIssues []AuditsGenericIssueDetails `json:"formIssues"`
}

func AuditsCheckFormsIssues() *AuditsCheckFormsIssuesParams {
	return &AuditsCheckFormsIssuesParams{}
}

func (p *AuditsCheckFormsIssuesParams) CDPMethodName() string {
	return "Audits.checkFormsIssues"
}

const EventAuditsIssueAdded = "Audits.issueAdded"

type AuditsIssueAddedEvent struct {
	Issue AuditsInspectorIssue `json:"issue"`
}

func (e *AuditsIssueAddedEvent) CDPEventName() string {
	return EventAuditsIssueAdded
}
