// Code generated by cdpgen; DO NOT EDIT.

package cdp

type AutofillCreditCard struct {
	// 16-digit credit card number.
	Number string `json:"number"`
	// Name of the credit card owner.
	Name string `json:"name"`
	// 2-digit expiry month.
	ExpiryMonth string `json:"expiryMonth"`
	// 4-digit expiry year.
	ExpiryYear string `json:"expiryYear"`
	// 3-digit card verification code.
	Cvc string `json:"cvc"`
}

type AutofillAddressField struct {
	// address field name, for example GIVEN_NAME.
	// The full list of supported field names:
	// https://source.chromium.org/chromium/chromium/src/+/main:components/autofill/core/browser/field_types.cc;l=38
	Name string `json:"name"`
	// address field value, for example Jon Doe.
	Value string `json:"value"`
}

// A list of address fields.
type AutofillAddressFields struct {
	Fields []AutofillAddressField `json:"fields"`
}

type AutofillAddress struct {
	// fields and values defining an address.
	Fields []AutofillAddressField `json:"fields"`
}

// Defines how an address can be displayed like in chrome://settings/addresses.
// Address UI is a two dimensional array, each inner array is an "address information line", and when rendered in a UI surface should be displayed as such.
// The following address UI for instance:
// [[{name: "GIVE_NAME", value: "Jon"}, {name: "FAMILY_NAME", value: "Doe"}], [{name: "CITY", value: "Munich"}, {name: "ZIP", value: "81456"}]]
// should allow the receiver to render:
// Jon Doe
// Munich 81456
type AutofillAddressUI struct {
	// A two dimension array containing the representation of values from an address profile.
	AddressFields []AutofillAddressFields `json:"addressFields"`
}

// Specified whether a filled field was done so by using the html autocomplete attribute or autofill heuristics.
type AutofillFillingStrategy string

const (
	AutofillFillingStrategyAutocompleteAttribute AutofillFillingStrategy = "autocompleteAttribute"
	AutofillFillingStrategyAutofillInferred      AutofillFillingStrategy = "autofillInferred"
)

type AutofillFilledField struct {
	// The type of the field, e.g text, password etc.
	HtmlType string `json:"htmlType"`
	// the html id
	Id string `json:"id"`
	// the html name
	Name string `json:"name"`
	// the field value
	Value string `json:"value"`
	// The actual field type, e.g FAMILY_NAME
	AutofillType string `json:"autofillType"`
	// The filling strategy
	FillingStrategy AutofillFillingStrategy `json:"fillingStrategy"`
	// The frame the field belongs to
	FrameId PageFrameId `json:"frameId"`
	// The form field's DOM node
	FieldId DOMBackendNodeId `json:"fieldId"`
}

// Trigger autofill on a form identified by the fieldId.
// If the field and related form cannot be autofilled, returns an error.
type AutofillTriggerParams struct {
	// Identifies a field that serves as an anchor for autofill.
	FieldId DOMBackendNodeId `json:"fieldId"`
	// Identifies the frame that field belongs to.
	FrameId *PageFrameId `json:"frameId,omitempty"`
	// Credit card information to fill out the form. Credit card data is not saved.  Mutually exclusive with `address`.
	Card *AutofillCreditCard `json:"card,omitempty"`
	// Address to fill out the form. Address data is not saved. Mutually exclusive with `card`.
	Address *AutofillAddress `json:"address,omitempty"`
}

func AutofillTrigger(fieldId DOMBackendNodeId) *AutofillTriggerParams {
	return &AutofillTriggerParams{
		FieldId: fieldId,
	}
}

func (p *AutofillTriggerParams) WithFrameId(v PageFrameId) *AutofillTriggerParams {
	p.FrameId = &v
	return p
}

func (p *AutofillTriggerParams) WithCard(v AutofillCreditCard) *AutofillTriggerParams {
	p.Card = &v
	return p
}

func (p *AutofillTriggerParams) WithAddress(v AutofillAddress) *AutofillTriggerParams {
	p.Address = &v
	return p
}

func (p *AutofillTriggerParams) CDPMethodName() string {
	return "Autofill.trigger"
}

// Set addresses so that developers can verify their forms implementation.
type AutofillSetAddressesParams struct {
	Addresses []AutofillAddress `json:"addresses"`
}

func AutofillSetAddresses(addresses []AutofillAddress) *AutofillSetAddressesParams {
	return &AutofillSetAddressesParams{
		Addresses: addresses,
	}
}

func (p *AutofillSetAddressesParams) CDPMethodName() string {
	return "Autofill.setAddresses"
}

// Disables autofill domain notifications.
type AutofillDisableParams struct {
}

func AutofillDisable() *AutofillDisableParams {
	return &AutofillDisableParams{}
}

func (p *AutofillDisableParams) CDPMethodName() string {
	return "Autofill.disable"
}

// Enables autofill domain notifications.
type AutofillEnableParams struct {
}

func AutofillEnable() *AutofillEnableParams {
	return &AutofillEnableParams{}
}

func (p *AutofillEnableParams) CDPMethodName() string {
	return "Autofill.enable"
}

// Emitted when an address form is filled.
const EventAutofillAddressFormFilled = "Autofill.addressFormFilled"

type AutofillAddressFormFilledEvent struct {
	// Information about the fields that were filled
	FilledFields []AutofillFilledField `json:"filledFields"`
	// An UI representation of the address used to fill the form.
	// Consists of a 2D array where each child represents an address/profile line.
	AddressUi AutofillAddressUI `json:"addressUi"`
}

func (e *AutofillAddressFormFilledEvent) CDPEventName() string {
	return EventAutofillAddressFormFilled
}
