// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Indicates the various states of Central.
type BluetoothEmulationCentralState string

const (
	BluetoothEmulationCentralStateAbsent     BluetoothEmulationCentralState = "absent"
	BluetoothEmulationCentralStatePoweredOff BluetoothEmulationCentralState = "powered-off"
	BluetoothEmulationCentralStatePoweredOn  BluetoothEmulationCentralState = "powered-on"
)

// Indicates the various types of GATT event.
type BluetoothEmulationGATTOperationType string

const (
	BluetoothEmulationGATTOperationTypeConnection BluetoothEmulationGATTOperationType = "connection"
	BluetoothEmulationGATTOperationTypeDiscovery  BluetoothEmulationGATTOperationType = "discovery"
)

// Indicates the various types of characteristic write.
type BluetoothEmulationCharacteristicWriteType string

const (
	BluetoothEmulationCharacteristicWriteTypeWriteDefaultDeprecated BluetoothEmulationCharacteristicWriteType = "write-default-deprecated"
	BluetoothEmulationCharacteristicWriteTypeWriteWithResponse      BluetoothEmulationCharacteristicWriteType = "write-with-response"
	BluetoothEmulationCharacteristicWriteTypeWriteWithoutResponse   BluetoothEmulationCharacteristicWriteType = "write-without-response"
)

// Indicates the various types of characteristic operation.
type BluetoothEmulationCharacteristicOperationType string

const (
	BluetoothEmulationCharacteristicOperationTypeRead                         BluetoothEmulationCharacteristicOperationType = "read"
	BluetoothEmulationCharacteristicOperationTypeWrite                        BluetoothEmulationCharacteristicOperationType = "write"
	BluetoothEmulationCharacteristicOperationTypeSubscribeToNotifications     BluetoothEmulationCharacteristicOperationType = "subscribe-to-notifications"
	BluetoothEmulationCharacteristicOperationTypeUnsubscribeFromNotifications BluetoothEmulationCharacteristicOperationType = "unsubscribe-from-notifications"
)

// Indicates the various types of descriptor operation.
type BluetoothEmulationDescriptorOperationType string

const (
	BluetoothEmulationDescriptorOperationTypeRead  BluetoothEmulationDescriptorOperationType = "read"
	BluetoothEmulationDescriptorOperationTypeWrite BluetoothEmulationDescriptorOperationType = "write"
)

// Stores the manufacturer data
type BluetoothEmulationManufacturerData struct {
	// Company identifier
	// https://bitbucket.org/bluetooth-SIG/public/src/main/assigned_numbers/company_identifiers/company_identifiers.yaml
	// https://usb.org/developers
	Key int64 `json:"key"`
	// Manufacturer-specific data (Encoded as a base64 string when passed over JSON)
	Data string `json:"data"`
}

// Stores the byte data of the advertisement packet sent by a Bluetooth device.
type BluetoothEmulationScanRecord struct {
	Name  *string  `json:"name,omitempty"`
	Uuids []string `json:"uuids,omitempty"`
	// Stores the external appearance description of the device.
	Appearance *int64 `json:"appearance,omitempty"`
	// Stores the transmission power of a broadcasting device.
	TxPower *int64 `json:"txPower,omitempty"`
	// Key is the company identifier and the value is an array of bytes of
	// manufacturer specific data.
	ManufacturerData []BluetoothEmulationManufacturerData `json:"manufacturerData,omitempty"`
}

// Stores the advertisement packet information that is sent by a Bluetooth device.
type BluetoothEmulationScanEntry struct {
	DeviceAddress string                       `json:"deviceAddress"`
	Rssi          int64                        `json:"rssi"`
	ScanRecord    BluetoothEmulationScanRecord `json:"scanRecord"`
}

// Describes the properties of a characteristic. This follows Bluetooth Core
// Specification BT 4.2 Vol 3 Part G 3.3.1. Characteristic Properties.
type BluetoothEmulationCharacteristicProperties struct {
	Broadcast                 *bool `json:"broadcast,omitempty"`
	Read                      *bool `json:"read,omitempty"`
	WriteWithoutResponse      *bool `json:"writeWithoutResponse,omitempty"`
	Write                     *bool `json:"write,omitempty"`
	Notify                    *bool `json:"notify,omitempty"`
	Indicate                  *bool `json:"indicate,omitempty"`
	AuthenticatedSignedWrites *bool `json:"authenticatedSignedWrites,omitempty"`
	ExtendedProperties        *bool `json:"extendedProperties,omitempty"`
}

// Enable the BluetoothEmulation domain.
type BluetoothEmulationEnableParams struct {
	// State of the simulated central.
	State BluetoothEmulationCentralState `json:"state"`
	// If the simulated central supports low-energy.
	LeSupported bool `json:"leSupported"`
}

func BluetoothEmulationEnable(state BluetoothEmulationCentralState, leSupported bool) *BluetoothEmulationEnableParams {
	return &BluetoothEmulationEnableParams{
		State:       state,
		LeSupported: leSupported,
	}
}

func (p *BluetoothEmulationEnableParams) CDPMethodName() string {
	return "BluetoothEmulation.enable"
}

// Set the state of the simulated central.
type BluetoothEmulationSetSimulatedCentralStateParams struct {
	// State of the simulated central.
	State BluetoothEmulationCentralState `json:"state"`
}

func BluetoothEmulationSetSimulatedCentralState(state BluetoothEmulationCentralState) *BluetoothEmulationSetSimulatedCentralStateParams {
	return &BluetoothEmulationSetSimulatedCentralStateParams{
		State: state,
	}
}

func (p *BluetoothEmulationSetSimulatedCentralStateParams) CDPMethodName() string {
	return "BluetoothEmulation.setSimulatedCentralState"
}

// Disable the BluetoothEmulation domain.
type BluetoothEmulationDisableParams struct {
}

func BluetoothEmulationDisable() *BluetoothEmulationDisableParams {
	return &BluetoothEmulationDisableParams{}
}

func (p *BluetoothEmulationDisableParams) CDPMethodName() string {
	return "BluetoothEmulation.disable"
}

// Simulates a peripheral with |address|, |name| and |knownServiceUuids|
// that has already been connected to the system.
type BluetoothEmulationSimulatePreconnectedPeripheralParams struct {
	Address           string                               `json:"address"`
	Name              string                               `json:"name"`
	ManufacturerData  []BluetoothEmulationManufacturerData `json:"manufacturerData"`
	KnownServiceUuids []string                             `json:"knownServiceUuids"`
}

func BluetoothEmulationSimulatePreconnectedPeripheral(address string, name string, manufacturerData []BluetoothEmulationManufacturerData, knownServiceUuids []string) *BluetoothEmulationSimulatePreconnectedPeripheralParams {
	return &BluetoothEmulationSimulatePreconnectedPeripheralParams{
		Address:           address,
		Name:              name,
		ManufacturerData:  manufacturerData,
		KnownServiceUuids: knownServiceUuids,
	}
}

func (p *BluetoothEmulationSimulatePreconnectedPeripheralParams) CDPMethodName() string {
	return "BluetoothEmulation.simulatePreconnectedPeripheral"
}

// Simulates an advertisement packet described in |entry| being received by
// the central.
type BluetoothEmulationSimulateAdvertisementParams struct {
	Entry BluetoothEmulationScanEntry `json:"entry"`
}

func BluetoothEmulationSimulateAdvertisement(entry BluetoothEmulationScanEntry) *BluetoothEmulationSimulateAdvertisementParams {
	return &BluetoothEmulationSimulateAdvertisementParams{
		Entry: entry,
	}
}

func (p *BluetoothEmulationSimulateAdvertisementParams) CDPMethodName() string {
	return "BluetoothEmulation.simulateAdvertisement"
}

// Simulates the response code from the peripheral with |address| for a
// GATT operation of |type|. The |code| value follows the HCI Error Codes from
// Bluetooth Core Specification Vol 2 Part D 1.3 List Of Error Codes.
type BluetoothEmulationSimulateGATTOperationResponseParams struct {
	Address string                              `json:"address"`
	Type    BluetoothEmulationGATTOperationType `json:"type"`
	Code    int64                               `json:"code"`
}

func BluetoothEmulationSimulateGATTOperationResponse(address string, type_ BluetoothEmulationGATTOperationType, code int64) *BluetoothEmulationSimulateGATTOperationResponseParams {
	return &BluetoothEmulationSimulateGATTOperationResponseParams{
		Address: address,
		Type:    type_,
		Code:    code,
	}
}

func (p *BluetoothEmulationSimulateGATTOperationResponseParams) CDPMethodName() string {
	return "BluetoothEmulation.simulateGATTOperationResponse"
}

// Simulates the response from the characteristic with |characteristicId| for a
// characteristic operation of |type|. The |code| value follows the Error
// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
// The |data| is expected to exist when simulating a successful read operation
// response.
type BluetoothEmulationSimulateCharacteristicOperationResponseParams struct {
	CharacteristicId string                                        `json:"characteristicId"`
	Type             BluetoothEmulationCharacteristicOperationType `json:"type"`
	Code             int64                                         `json:"code"`
	Data             *string                                       `json:"data,omitempty"`
}

func BluetoothEmulationSimulateCharacteristicOperationResponse(characteristicId string, type_ BluetoothEmulationCharacteristicOperationType, code int64) *BluetoothEmulationSimulateCharacteristicOperationResponseParams {
	return &BluetoothEmulationSimulateCharacteristicOperationResponseParams{
		CharacteristicId: characteristicId,
		Type:             type_,
		Code:             code,
	}
}

func (p *BluetoothEmulationSimulateCharacteristicOperationResponseParams) WithData(v string) *BluetoothEmulationSimulateCharacteristicOperationResponseParams {
	p.Data = &v
	return p
}

func (p *BluetoothEmulationSimulateCharacteristicOperationResponseParams) CDPMethodName() string {
	return "BluetoothEmulation.simulateCharacteristicOperationResponse"
}

// Simulates the response from the descriptor with |descriptorId| for a
// descriptor operation of |type|. The |code| value follows the Error
// Codes from Bluetooth Core Specification Vol 3 Part F 3.4.1.1 Error Response.
// The |data| is expected to exist when simulating a successful read operation
// response.
type BluetoothEmulationSimulateDescriptorOperationResponseParams struct {
	DescriptorId string                                    `json:"descriptorId"`
	Type         BluetoothEmulationDescriptorOperationType `json:"type"`
	Code         int64                                     `json:"code"`
	Data         *string                                   `json:"data,omitempty"`
}

func BluetoothEmulationSimulateDescriptorOperationResponse(descriptorId string, type_ BluetoothEmulationDescriptorOperationType, code int64) *BluetoothEmulationSimulateDescriptorOperationResponseParams {
	return &BluetoothEmulationSimulateDescriptorOperationResponseParams{
		DescriptorId: descriptorId,
		Type:         type_,
		Code:         code,
	}
}

func (p *BluetoothEmulationSimulateDescriptorOperationResponseParams) WithData(v string) *BluetoothEmulationSimulateDescriptorOperationResponseParams {
	p.Data = &v
	return p
}

func (p *BluetoothEmulationSimulateDescriptorOperationResponseParams) CDPMethodName() string {
	return "BluetoothEmulation.simulateDescriptorOperationResponse"
}

// Adds a service with |serviceUuid| to the peripheral with |address|.
type BluetoothEmulationAddServiceParams struct {
	Address     string `json:"address"`
	ServiceUuid string `json:"serviceUuid"`
}

type BluetoothEmulationAddServiceReturns struct {
	// An identifier that uniquely represents this service.
	ServiceId string `json:"serviceId"`
}

func BluetoothEmulationAddService(address string, serviceUuid string) *BluetoothEmulationAddServiceParams {
	return &BluetoothEmulationAddServiceParams{
		Address:     address,
		ServiceUuid: serviceUuid,
	}
}

func (p *BluetoothEmulationAddServiceParams) CDPMethodName() string {
	return "BluetoothEmulation.addService"
}

// Removes the service respresented by |serviceId| from the simulated central.
type BluetoothEmulationRemoveServiceParams struct {
	ServiceId string `json:"serviceId"`
}

func BluetoothEmulationRemoveService(serviceId string) *BluetoothEmulationRemoveServiceParams {
	return &BluetoothEmulationRemoveServiceParams{
		ServiceId: serviceId,
	}
}

func (p *BluetoothEmulationRemoveServiceParams) CDPMethodName() string {
	return "BluetoothEmulation.removeService"
}

// Adds a characteristic with |characteristicUuid| and |properties| to the
// service represented by |serviceId|.
type BluetoothEmulationAddCharacteristicParams struct {
	ServiceId          string                                     `json:"serviceId"`
	CharacteristicUuid string                                     `json:"characteristicUuid"`
	Properties         BluetoothEmulationCharacteristicProperties `json:"properties"`
}

type BluetoothEmulationAddCharacteristicReturns struct {
	// An identifier that uniquely represents this characteristic.
	CharacteristicId string `json:"characteristicId"`
}

func BluetoothEmulationAddCharacteristic(serviceId string, characteristicUuid string, properties BluetoothEmulationCharacteristicProperties) *BluetoothEmulationAddCharacteristicParams {
	return &BluetoothEmulationAddCharacteristicParams{
		ServiceId:          serviceId,
		CharacteristicUuid: characteristicUuid,
		Properties:         properties,
	}
}

func (p *BluetoothEmulationAddCharacteristicParams) CDPMethodName() string {
	return "BluetoothEmulation.addCharacteristic"
}

// Removes the characteristic respresented by |characteristicId| from the
// simulated central.
type BluetoothEmulationRemoveCharacteristicParams struct {
	CharacteristicId string `json:"characteristicId"`
}

func BluetoothEmulationRemoveCharacteristic(characteristicId string) *BluetoothEmulationRemoveCharacteristicParams {
	return &BluetoothEmulationRemoveCharacteristicParams{
		CharacteristicId: characteristicId,
	}
}

func (p *BluetoothEmulationRemoveCharacteristicParams) CDPMethodName() string {
	return "BluetoothEmulation.removeCharacteristic"
}

// Adds a descriptor with |descriptorUuid| to the characteristic respresented
// by |characteristicId|.
type BluetoothEmulationAddDescriptorParams struct {
	CharacteristicId string `json:"characteristicId"`
	DescriptorUuid   string `json:"descriptorUuid"`
}

type BluetoothEmulationAddDescriptorReturns struct {
	// An identifier that uniquely represents this descriptor.
	DescriptorId string `json:"descriptorId"`
}

func BluetoothEmulationAddDescriptor(characteristicId string, descriptorUuid string) *BluetoothEmulationAddDescriptorParams {
	return &BluetoothEmulationAddDescriptorParams{
		CharacteristicId: characteristicId,
		DescriptorUuid:   descriptorUuid,
	}
}

func (p *BluetoothEmulationAddDescriptorParams) CDPMethodName() string {
	return "BluetoothEmulation.addDescriptor"
}

// Removes the descriptor with |descriptorId| from the simulated central.
type BluetoothEmulationRemoveDescriptorParams struct {
	DescriptorId string `json:"descriptorId"`
}

func BluetoothEmulationRemoveDescriptor(descriptorId string) *BluetoothEmulationRemoveDescriptorParams {
	return &BluetoothEmulationRemoveDescriptorParams{
		DescriptorId: descriptorId,
	}
}

func (p *BluetoothEmulationRemoveDescriptorParams) CDPMethodName() string {
	return "BluetoothEmulation.removeDescriptor"
}

// Simulates a GATT disconnection from the peripheral with |address|.
type BluetoothEmulationSimulateGATTDisconnectionParams struct {
	Address string `json:"address"`
}

func BluetoothEmulationSimulateGATTDisconnection(address string) *BluetoothEmulationSimulateGATTDisconnectionParams {
	return &BluetoothEmulationSimulateGATTDisconnectionParams{
		Address: address,
	}
}

func (p *BluetoothEmulationSimulateGATTDisconnectionParams) CDPMethodName() string {
	return "BluetoothEmulation.simulateGATTDisconnection"
}

// Event for when a GATT operation of |type| to the peripheral with |address|
// happened.
const EventBluetoothEmulationGattOperationReceived = "BluetoothEmulation.gattOperationReceived"

type BluetoothEmulationGattOperationReceivedEvent struct {
	Address string                              `json:"address"`
	Type    BluetoothEmulationGATTOperationType `json:"type"`
}

func (e *BluetoothEmulationGattOperationReceivedEvent) CDPEventName() string {
	return EventBluetoothEmulationGattOperationReceived
}

// Event for when a characteristic operation of |type| to the characteristic
// respresented by |characteristicId| happened. |data| and |writeType| is
// expected to exist when |type| is write.
const EventBluetoothEmulationCharacteristicOperationReceived = "BluetoothEmulation.characteristicOperationReceived"

type BluetoothEmulationCharacteristicOperationReceivedEvent struct {
	CharacteristicId string                                        `json:"characteristicId"`
	Type             BluetoothEmulationCharacteristicOperationType `json:"type"`
	Data             *string                                       `json:"data,omitempty"`
	WriteType        *BluetoothEmulationCharacteristicWriteType    `json:"writeType,omitempty"`
}

func (e *BluetoothEmulationCharacteristicOperationReceivedEvent) CDPEventName() string {
	return EventBluetoothEmulationCharacteristicOperationReceived
}

// Event for when a descriptor operation of |type| to the descriptor
// respresented by |descriptorId| happened. |data| is expected to exist when
// |type| is write.
const EventBluetoothEmulationDescriptorOperationReceived = "BluetoothEmulation.descriptorOperationReceived"

type BluetoothEmulationDescriptorOperationReceivedEvent struct {
	DescriptorId string                                    `json:"descriptorId"`
	Type         BluetoothEmulationDescriptorOperationType `json:"type"`
	Data         *string                                   `json:"data,omitempty"`
}

func (e *BluetoothEmulationDescriptorOperationReceivedEvent) CDPEventName() string {
	return EventBluetoothEmulationDescriptorOperationReceived
}
