// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Unique identifier of the Cache object.
type CacheStorageCacheId string

// type of HTTP response cached
type CacheStorageCachedResponseType string

const (
	CacheStorageCachedResponseTypeBasic          CacheStorageCachedResponseType = "basic"
	CacheStorageCachedResponseTypeCors           CacheStorageCachedResponseType = "cors"
	CacheStorageCachedResponseTypeDefault        CacheStorageCachedResponseType = "default"
	CacheStorageCachedResponseTypeError          CacheStorageCachedResponseType = "error"
	CacheStorageCachedResponseTypeOpaqueResponse CacheStorageCachedResponseType = "opaqueResponse"
	CacheStorageCachedResponseTypeOpaqueRedirect CacheStorageCachedResponseType = "opaqueRedirect"
)

// Data entry.
type CacheStorageDataEntry struct {
	// Request URL.
	RequestURL string `json:"requestURL"`
	// Request method.
	RequestMethod string `json:"requestMethod"`
	// Request headers
	RequestHeaders []CacheStorageHeader `json:"requestHeaders"`
	// Number of seconds since epoch.
	ResponseTime float64 `json:"responseTime"`
	// HTTP response status code.
	ResponseStatus int64 `json:"responseStatus"`
	// HTTP response status text.
	ResponseStatusText string `json:"responseStatusText"`
	// HTTP response type
	ResponseType CacheStorageCachedResponseType `json:"responseType"`
	// Response headers
	ResponseHeaders []CacheStorageHeader `json:"responseHeaders"`
}

// Cache identifier.
type CacheStorageCache struct {
	// An opaque unique id of the cache.
	CacheId CacheStorageCacheId `json:"cacheId"`
	// Security origin of the cache.
	SecurityOrigin string `json:"securityOrigin"`
	// Storage key of the cache.
	StorageKey string `json:"storageKey"`
	// Storage bucket of the cache.
	StorageBucket *StorageStorageBucket `json:"storageBucket,omitempty"`
	// The name of the cache.
	CacheName string `json:"cacheName"`
}

type CacheStorageHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Cached response
type CacheStorageCachedResponse struct {
	// Entry content, base64-encoded. (Encoded as a base64 string when passed over JSON)
	Body string `json:"body"`
}

// Deletes a cache.
type CacheStorageDeleteCacheParams struct {
	// Id of cache for deletion.
	CacheId CacheStorageCacheId `json:"cacheId"`
}

func CacheStorageDeleteCache(cacheId CacheStorageCacheId) *CacheStorageDeleteCacheParams {
	return &CacheStorageDeleteCacheParams{
		CacheId: cacheId,
	}
}

func (p *CacheStorageDeleteCacheParams) CDPMethodName() string {
	return "CacheStorage.deleteCache"
}

// Deletes a cache entry.
type CacheStorageDeleteEntryParams struct {
	// Id of cache where the entry will be deleted.
	CacheId CacheStorageCacheId `json:"cacheId"`
	// URL spec of the request.
	Request string `json:"request"`
}

func CacheStorageDeleteEntry(cacheId CacheStorageCacheId, request string) *CacheStorageDeleteEntryParams {
	return &CacheStorageDeleteEntryParams{
		CacheId: cacheId,
		Request: request,
	}
}

func (p *CacheStorageDeleteEntryParams) CDPMethodName() string {
	return "CacheStorage.deleteEntry"
}

// Requests cache names.
type CacheStorageRequestCacheNamesParams struct {
	// At least and at most one of securityOrigin, storageKey, storageBucket must be specified.
	// Security origin.
	SecurityOrigin *string `json:"securityOrigin,omitempty"`
	// Storage key.
	StorageKey *string `json:"storageKey,omitempty"`
	// Storage bucket. If not specified, it uses the default bucket.
	StorageBucket *StorageStorageBucket `json:"storageBucket,omitempty"`
}

type CacheStorageRequestCacheNamesReturns struct {
	// Caches for the security origin.
	Caches []CacheStorageCache `json:"caches"`
}

func CacheStorageRequestCacheNames() *CacheStorageRequestCacheNamesParams {
	return &CacheStorageRequestCacheNamesParams{}
}

func (p *CacheStorageRequestCacheNamesParams) WithSecurityOrigin(v string) *CacheStorageRequestCacheNamesParams {
	p.SecurityOrigin = &v
	return p
}

func (p *CacheStorageRequestCacheNamesParams) WithStorageKey(v string) *CacheStorageRequestCacheNamesParams {
	p.StorageKey = &v
	return p
}

func (p *CacheStorageRequestCacheNamesParams) WithStorageBucket(v StorageStorageBucket) *CacheStorageRequestCacheNamesParams {
	p.StorageBucket = &v
	return p
}

func (p *CacheStorageRequestCacheNamesParams) CDPMethodName() string {
	return "CacheStorage.requestCacheNames"
}

// Fetches cache entry.
type CacheStorageRequestCachedResponseParams struct {
	// Id of cache that contains the entry.
	CacheId CacheStorageCacheId `json:"cacheId"`
	// URL spec of the request.
	RequestURL string `json:"requestURL"`
	// headers of the request.
	RequestHeaders []CacheStorageHeader `json:"requestHeaders"`
}

type CacheStorageRequestCachedResponseReturns struct {
	// Response read from the cache.
	Response CacheStorageCachedResponse `json:"response"`
}

func CacheStorageRequestCachedResponse(cacheId CacheStorageCacheId, requestURL string, requestHeaders []CacheStorageHeader) *CacheStorageRequestCachedResponseParams {
	return &CacheStorageRequestCachedResponseParams{
		CacheId:        cacheId,
		RequestURL:     requestURL,
		RequestHeaders: requestHeaders,
	}
}

func (p *CacheStorageRequestCachedResponseParams) CDPMethodName() string {
	return "CacheStorage.requestCachedResponse"
}

// Requests data from cache.
type CacheStorageRequestEntriesParams struct {
	// ID of cache to get entries from.
	CacheId CacheStorageCacheId `json:"cacheId"`
	// Number of records to skip.
	SkipCount *int64 `json:"skipCount,omitempty"`
	// Number of records to fetch.
	PageSize *int64 `json:"pageSize,omitempty"`
	// If present, only return the entries containing this substring in the path
	PathFilter *string `json:"pathFilter,omitempty"`
}

type CacheStorageRequestEntriesReturns struct {
	// Array of object store data entries.
	CacheDataEntries []CacheStorageDataEntry `json:"cacheDataEntries"`
	// Count of returned entries from this storage. If pathFilter is empty, it
	// is the count of all entries from this storage.
	ReturnCount float64 `json:"returnCount"`
}

func CacheStorageRequestEntries(cacheId CacheStorageCacheId) *CacheStorageRequestEntriesParams {
	return &CacheStorageRequestEntriesParams{
		CacheId: cacheId,
	}
}

func (p *CacheStorageRequestEntriesParams) WithSkipCount(v int64) *CacheStorageRequestEntriesParams {
	p.SkipCount = &v
	return p
}

func (p *CacheStorageRequestEntriesParams) WithPageSize(v int64) *CacheStorageRequestEntriesParams {
	p.PageSize = &v
	return p
}

func (p *CacheStorageRequestEntriesParams) WithPathFilter(v string) *CacheStorageRequestEntriesParams {
	p.PathFilter = &v
	return p
}

func (p *CacheStorageRequestEntriesParams) CDPMethodName() string {
	return "CacheStorage.requestEntries"
}
