// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Breakpoint identifier.
type DebuggerBreakpointId string

// Call frame identifier.
type DebuggerCallFrameId string

// Location in the source code.
type DebuggerLocation struct {
	// Script identifier as reported in the `Debugger.scriptParsed`.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// Line number in the script (0-based).
	LineNumber int64 `json:"lineNumber"`
	// Column number in the script (0-based).
	ColumnNumber *int64 `json:"columnNumber,omitempty"`
}

// Location in the source code.
type DebuggerScriptPosition struct {
	LineNumber   int64 `json:"lineNumber"`
	ColumnNumber int64 `json:"columnNumber"`
}

// Location range within one script.
type DebuggerLocationRange struct {
	ScriptId RuntimeScriptId        `json:"scriptId"`
	Start    DebuggerScriptPosition `json:"start"`
	End      DebuggerScriptPosition `json:"end"`
}

// JavaScript call frame. Array of call frames form the call stack.
type DebuggerCallFrame struct {
	// Call frame identifier. This identifier is only valid while the virtual machine is paused.
	CallFrameId DebuggerCallFrameId `json:"callFrameId"`
	// Name of the JavaScript function called on this call frame.
	FunctionName string `json:"functionName"`
	// Location in the source code.
	FunctionLocation *DebuggerLocation `json:"functionLocation,omitempty"`
	// Location in the source code.
	Location DebuggerLocation `json:"location"`
	// JavaScript script name or url.
	// Deprecated in favor of using the `location.scriptId` to resolve the URL via a previously
	// sent `Debugger.scriptParsed` event.
	Url string `json:"url"`
	// Scope chain for this call frame.
	ScopeChain []DebuggerScope `json:"scopeChain"`
	// `this` object for this call frame.
	This RuntimeRemoteObject `json:"this"`
	// The value being returned, if the function is at return point.
	ReturnValue *RuntimeRemoteObject `json:"returnValue,omitempty"`
	// Valid only while the VM is paused and indicates whether this frame
	// can be restarted or not. Note that a `true` value here does not
	// guarantee that Debugger#restartFrame with this CallFrameId will be
	// successful, but it is very likely.
	CanBeRestarted *bool `json:"canBeRestarted,omitempty"`
}

// Scope description.
type DebuggerScope struct {
	// Scope type.
	Type string `json:"type"`
	// Object representing the scope. For `global` and `with` scopes it represents the actual
	// object; for the rest of the scopes, it is artificial transient object enumerating scope
	// variables as its properties.
	Object RuntimeRemoteObject `json:"object"`
	Name   *string             `json:"name,omitempty"`
	// Location in the source code where scope starts
	StartLocation *DebuggerLocation `json:"startLocation,omitempty"`
	// Location in the source code where scope ends
	EndLocation *DebuggerLocation `json:"endLocation,omitempty"`
}

// Search match for resource.
type DebuggerSearchMatch struct {
	// Line number in resource content.
	LineNumber float64 `json:"lineNumber"`
	// Line with match content.
	LineContent string `json:"lineContent"`
}

type DebuggerBreakLocation struct {
	// Script identifier as reported in the `Debugger.scriptParsed`.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// Line number in the script (0-based).
	LineNumber int64 `json:"lineNumber"`
	// Column number in the script (0-based).
	ColumnNumber *int64  `json:"columnNumber,omitempty"`
	Type         *string `json:"type,omitempty"`
}

type DebuggerWasmDisassemblyChunk struct {
	// The next chunk of disassembled lines.
	Lines []string `json:"lines"`
	// The bytecode offsets describing the start of each line.
	BytecodeOffsets []int64 `json:"bytecodeOffsets"`
}

// Enum of possible script languages.
type DebuggerScriptLanguage string

const (
	DebuggerScriptLanguageJavaScript  DebuggerScriptLanguage = "JavaScript"
	DebuggerScriptLanguageWebAssembly DebuggerScriptLanguage = "WebAssembly"
)

// Debug symbols available for a wasm script.
type DebuggerDebugSymbols struct {
	// Type of the debug symbols.
	Type string `json:"type"`
	// URL of the external symbol source.
	ExternalURL *string `json:"externalURL,omitempty"`
}

type DebuggerResolvedBreakpoint struct {
	// Breakpoint unique identifier.
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
	// Actual breakpoint location.
	Location DebuggerLocation `json:"location"`
}

// Continues execution until specific location is reached.
type DebuggerContinueToLocationParams struct {
	// Location to continue to.
	Location         DebuggerLocation `json:"location"`
	TargetCallFrames *string          `json:"targetCallFrames,omitempty"`
}

func DebuggerContinueToLocation(location DebuggerLocation) *DebuggerContinueToLocationParams {
	return &DebuggerContinueToLocationParams{
		Location: location,
	}
}

func (p *DebuggerContinueToLocationParams) WithTargetCallFrames(v string) *DebuggerContinueToLocationParams {
	p.TargetCallFrames = &v
	return p
}

func (p *DebuggerContinueToLocationParams) CDPMethodName() string {
	return "Debugger.continueToLocation"
}

// Disables debugger for given page.
type DebuggerDisableParams struct {
}

func DebuggerDisable() *DebuggerDisableParams {
	return &DebuggerDisableParams{}
}

func (p *DebuggerDisableParams) CDPMethodName() string {
	return "Debugger.disable"
}

// Enables debugger for the given page. Clients should not assume that the debugging has been
// enabled until the result for this command is received.
type DebuggerEnableParams struct {
	// The maximum size in bytes of collected scripts (not referenced by other heap objects)
	// the debugger can hold. Puts no limit if parameter is omitted.
	MaxScriptsCacheSize *float64 `json:"maxScriptsCacheSize,omitempty"`
}

type DebuggerEnableReturns struct {
	// Unique identifier of the debugger.
	DebuggerId RuntimeUniqueDebuggerId `json:"debuggerId"`
}

func DebuggerEnable() *DebuggerEnableParams {
	return &DebuggerEnableParams{}
}

func (p *DebuggerEnableParams) WithMaxScriptsCacheSize(v float64) *DebuggerEnableParams {
	p.MaxScriptsCacheSize = &v
	return p
}

func (p *DebuggerEnableParams) CDPMethodName() string {
	return "Debugger.enable"
}

// Evaluates expression on a given call frame.
type DebuggerEvaluateOnCallFrameParams struct {
	// Call frame identifier to evaluate on.
	CallFrameId DebuggerCallFrameId `json:"callFrameId"`
	// Expression to evaluate.
	Expression string `json:"expression"`
	// String object group name to put result into (allows rapid releasing resulting object handles
	// using `releaseObjectGroup`).
	ObjectGroup *string `json:"objectGroup,omitempty"`
	// Specifies whether command line API should be available to the evaluated expression, defaults
	// to false.
	IncludeCommandLineAPI *bool `json:"includeCommandLineAPI,omitempty"`
	// In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent *bool `json:"silent,omitempty"`
	// Whether the result is expected to be a JSON object that should be sent by value.
	ReturnByValue *bool `json:"returnByValue,omitempty"`
	// Whether preview should be generated for the result.
	GeneratePreview *bool `json:"generatePreview,omitempty"`
	// Whether to throw an exception if side effect cannot be ruled out during evaluation.
	ThrowOnSideEffect *bool `json:"throwOnSideEffect,omitempty"`
	// Terminate execution after timing out (number of milliseconds).
	Timeout *RuntimeTimeDelta `json:"timeout,omitempty"`
}

type DebuggerEvaluateOnCallFrameReturns struct {
	// Object wrapper for the evaluation result.
	Result RuntimeRemoteObject `json:"result"`
	// Exception details.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func DebuggerEvaluateOnCallFrame(callFrameId DebuggerCallFrameId, expression string) *DebuggerEvaluateOnCallFrameParams {
	return &DebuggerEvaluateOnCallFrameParams{
		CallFrameId: callFrameId,
		Expression:  expression,
	}
}

func (p *DebuggerEvaluateOnCallFrameParams) WithObjectGroup(v string) *DebuggerEvaluateOnCallFrameParams {
	p.ObjectGroup = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) WithIncludeCommandLineAPI(v bool) *DebuggerEvaluateOnCallFrameParams {
	p.IncludeCommandLineAPI = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) WithSilent(v bool) *DebuggerEvaluateOnCallFrameParams {
	p.Silent = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) WithReturnByValue(v bool) *DebuggerEvaluateOnCallFrameParams {
	p.ReturnByValue = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) WithGeneratePreview(v bool) *DebuggerEvaluateOnCallFrameParams {
	p.GeneratePreview = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) WithThrowOnSideEffect(v bool) *DebuggerEvaluateOnCallFrameParams {
	p.ThrowOnSideEffect = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) WithTimeout(v RuntimeTimeDelta) *DebuggerEvaluateOnCallFrameParams {
	p.Timeout = &v
	return p
}

func (p *DebuggerEvaluateOnCallFrameParams) CDPMethodName() string {
	return "Debugger.evaluateOnCallFrame"
}

// Returns possible locations for breakpoint. scriptId in start and end range locations should be
// the same.
type DebuggerGetPossibleBreakpointsParams struct {
	// Start of range to search possible breakpoint locations in.
	Start DebuggerLocation `json:"start"`
	// End of range to search possible breakpoint locations in (excluding). When not specified, end
	// of scripts is used as end of range.
	End *DebuggerLocation `json:"end,omitempty"`
	// Only consider locations which are in the same (non-nested) function as start.
	RestrictToFunction *bool `json:"restrictToFunction,omitempty"`
}

type DebuggerGetPossibleBreakpointsReturns struct {
	// List of the possible breakpoint locations.
	Locations []DebuggerBreakLocation `json:"locations"`
}

func DebuggerGetPossibleBreakpoints(start DebuggerLocation) *DebuggerGetPossibleBreakpointsParams {
	return &DebuggerGetPossibleBreakpointsParams{
		Start: start,
	}
}

func (p *DebuggerGetPossibleBreakpointsParams) WithEnd(v DebuggerLocation) *DebuggerGetPossibleBreakpointsParams {
	p.End = &v
	return p
}

func (p *DebuggerGetPossibleBreakpointsParams) WithRestrictToFunction(v bool) *DebuggerGetPossibleBreakpointsParams {
	p.RestrictToFunction = &v
	return p
}

func (p *DebuggerGetPossibleBreakpointsParams) CDPMethodName() string {
	return "Debugger.getPossibleBreakpoints"
}

// Returns source for the script with given id.
type DebuggerGetScriptSourceParams struct {
	// Id of the script to get source for.
	ScriptId RuntimeScriptId `json:"scriptId"`
}

type DebuggerGetScriptSourceReturns struct {
	// Script source (empty in case of Wasm bytecode).
	ScriptSource string `json:"scriptSource"`
	// Wasm bytecode. (Encoded as a base64 string when passed over JSON)
	Bytecode *string `json:"bytecode,omitempty"`
}

func DebuggerGetScriptSource(scriptId RuntimeScriptId) *DebuggerGetScriptSourceParams {
	return &DebuggerGetScriptSourceParams{
		ScriptId: scriptId,
	}
}

func (p *DebuggerGetScriptSourceParams) CDPMethodName() string {
	return "Debugger.getScriptSource"
}

type DebuggerDisassembleWasmModuleParams struct {
	// Id of the script to disassemble
	ScriptId RuntimeScriptId `json:"scriptId"`
}

type DebuggerDisassembleWasmModuleReturns struct {
	// For large modules, return a stream from which additional chunks of
	// disassembly can be read successively.
	StreamId *string `json:"streamId,omitempty"`
	// The total number of lines in the disassembly text.
	TotalNumberOfLines int64 `json:"totalNumberOfLines"`
	// The offsets of all function bodies, in the format [start1, end1,
	// start2, end2, ...] where all ends are exclusive.
	FunctionBodyOffsets []int64 `json:"functionBodyOffsets"`
	// The first chunk of disassembly.
	Chunk DebuggerWasmDisassemblyChunk `json:"chunk"`
}

func DebuggerDisassembleWasmModule(scriptId RuntimeScriptId) *DebuggerDisassembleWasmModuleParams {
	return &DebuggerDisassembleWasmModuleParams{
		ScriptId: scriptId,
	}
}

func (p *DebuggerDisassembleWasmModuleParams) CDPMethodName() string {
	return "Debugger.disassembleWasmModule"
}

// Disassemble the next chunk of lines for the module corresponding to the
// stream. If disassembly is complete, this API will invalidate the streamId
// and return an empty chunk. Any subsequent calls for the now invalid stream
// will return errors.
type DebuggerNextWasmDisassemblyChunkParams struct {
	StreamId string `json:"streamId"`
}

type DebuggerNextWasmDisassemblyChunkReturns struct {
	// The next chunk of disassembly.
	Chunk DebuggerWasmDisassemblyChunk `json:"chunk"`
}

func DebuggerNextWasmDisassemblyChunk(streamId string) *DebuggerNextWasmDisassemblyChunkParams {
	return &DebuggerNextWasmDisassemblyChunkParams{
		StreamId: streamId,
	}
}

func (p *DebuggerNextWasmDisassemblyChunkParams) CDPMethodName() string {
	return "Debugger.nextWasmDisassemblyChunk"
}

// This command is deprecated. Use getScriptSource instead.
type DebuggerGetWasmBytecodeParams struct {
	// Id of the Wasm script to get source for.
	ScriptId RuntimeScriptId `json:"scriptId"`
}

type DebuggerGetWasmBytecodeReturns struct {
	// Script source. (Encoded as a base64 string when passed over JSON)
	Bytecode string `json:"bytecode"`
}

func DebuggerGetWasmBytecode(scriptId RuntimeScriptId) *DebuggerGetWasmBytecodeParams {
	return &DebuggerGetWasmBytecodeParams{
		ScriptId: scriptId,
	}
}

func (p *DebuggerGetWasmBytecodeParams) CDPMethodName() string {
	return "Debugger.getWasmBytecode"
}

// Returns stack trace with given `stackTraceId`.
type DebuggerGetStackTraceParams struct {
	StackTraceId RuntimeStackTraceId `json:"stackTraceId"`
}

type DebuggerGetStackTraceReturns struct {
	StackTrace RuntimeStackTrace `json:"stackTrace"`
}

func DebuggerGetStackTrace(stackTraceId RuntimeStackTraceId) *DebuggerGetStackTraceParams {
	return &DebuggerGetStackTraceParams{
		StackTraceId: stackTraceId,
	}
}

func (p *DebuggerGetStackTraceParams) CDPMethodName() string {
	return "Debugger.getStackTrace"
}

// Stops on the next JavaScript statement.
type DebuggerPauseParams struct {
}

func DebuggerPause() *DebuggerPauseParams {
	return &DebuggerPauseParams{}
}

func (p *DebuggerPauseParams) CDPMethodName() string {
	return "Debugger.pause"
}

type DebuggerPauseOnAsyncCallParams struct {
	// Debugger will pause when async call with given stack trace is started.
	ParentStackTraceId RuntimeStackTraceId `json:"parentStackTraceId"`
}

func DebuggerPauseOnAsyncCall(parentStackTraceId RuntimeStackTraceId) *DebuggerPauseOnAsyncCallParams {
	return &DebuggerPauseOnAsyncCallParams{
		ParentStackTraceId: parentStackTraceId,
	}
}

func (p *DebuggerPauseOnAsyncCallParams) CDPMethodName() string {
	return "Debugger.pauseOnAsyncCall"
}

// Removes JavaScript breakpoint.
type DebuggerRemoveBreakpointParams struct {
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
}

func DebuggerRemoveBreakpoint(breakpointId DebuggerBreakpointId) *DebuggerRemoveBreakpointParams {
	return &DebuggerRemoveBreakpointParams{
		BreakpointId: breakpointId,
	}
}

func (p *DebuggerRemoveBreakpointParams) CDPMethodName() string {
	return "Debugger.removeBreakpoint"
}

// Restarts particular call frame from the beginning. The old, deprecated
// behavior of `restartFrame` is to stay paused and allow further CDP commands
// after a restart was scheduled. This can cause problems with restarting, so
// we now continue execution immediatly after it has been scheduled until we
// reach the beginning of the restarted frame.
//
// To stay back-wards compatible, `restartFrame` now expects a `mode`
// parameter to be present. If the `mode` parameter is missing, `restartFrame`
// errors out.
//
// The various return values are deprecated and `callFrames` is always empty.
// Use the call frames from the `Debugger#paused` events instead, that fires
// once V8 pauses at the beginning of the restarted function.
type DebuggerRestartFrameParams struct {
	// Call frame identifier to evaluate on.
	CallFrameId DebuggerCallFrameId `json:"callFrameId"`
	// The `mode` parameter must be present and set to 'StepInto', otherwise
	// `restartFrame` will error out.
	Mode *string `json:"mode,omitempty"`
}

type DebuggerRestartFrameReturns struct {
	// New stack trace.
	CallFrames []DebuggerCallFrame `json:"callFrames"`
	// Async stack trace, if any.
	AsyncStackTrace *RuntimeStackTrace `json:"asyncStackTrace,omitempty"`
	// Async stack trace, if any.
	AsyncStackTraceId *RuntimeStackTraceId `json:"asyncStackTraceId,omitempty"`
}

func DebuggerRestartFrame(callFrameId DebuggerCallFrameId) *DebuggerRestartFrameParams {
	return &DebuggerRestartFrameParams{
		CallFrameId: callFrameId,
	}
}

func (p *DebuggerRestartFrameParams) WithMode(v string) *DebuggerRestartFrameParams {
	p.Mode = &v
	return p
}

func (p *DebuggerRestartFrameParams) CDPMethodName() string {
	return "Debugger.restartFrame"
}

// Resumes JavaScript execution.
type DebuggerResumeParams struct {
	// Set to true to terminate execution upon resuming execution. In contrast
	// to Runtime.terminateExecution, this will allows to execute further
	// JavaScript (i.e. via evaluation) until execution of the paused code
	// is actually resumed, at which point termination is triggered.
	// If execution is currently not paused, this parameter has no effect.
	TerminateOnResume *bool `json:"terminateOnResume,omitempty"`
}

func DebuggerResume() *DebuggerResumeParams {
	return &DebuggerResumeParams{}
}

func (p *DebuggerResumeParams) WithTerminateOnResume(v bool) *DebuggerResumeParams {
	p.TerminateOnResume = &v
	return p
}

func (p *DebuggerResumeParams) CDPMethodName() string {
	return "Debugger.resume"
}

// Searches for given string in script content.
type DebuggerSearchInContentParams struct {
	// Id of the script to search in.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// String to search for.
	Query string `json:"query"`
	// If true, search is case sensitive.
	CaseSensitive *bool `json:"caseSensitive,omitempty"`
	// If true, treats string parameter as regex.
	IsRegex *bool `json:"isRegex,omitempty"`
}

type DebuggerSearchInContentReturns struct {
	// List of search matches.
	Result []DebuggerSearchMatch `json:"result"`
}

func DebuggerSearchInContent(scriptId RuntimeScriptId, query string) *DebuggerSearchInContentParams {
	return &DebuggerSearchInContentParams{
		ScriptId: scriptId,
		Query:    query,
	}
}

func (p *DebuggerSearchInContentParams) WithCaseSensitive(v bool) *DebuggerSearchInContentParams {
	p.CaseSensitive = &v
	return p
}

func (p *DebuggerSearchInContentParams) WithIsRegex(v bool) *DebuggerSearchInContentParams {
	p.IsRegex = &v
	return p
}

func (p *DebuggerSearchInContentParams) CDPMethodName() string {
	return "Debugger.searchInContent"
}

// Enables or disables async call stacks tracking.
type DebuggerSetAsyncCallStackDepthParams struct {
	// Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async
	// call stacks (default).
	MaxDepth int64 `json:"maxDepth"`
}

func DebuggerSetAsyncCallStackDepth(maxDepth int64) *DebuggerSetAsyncCallStackDepthParams {
	return &DebuggerSetAsyncCallStackDepthParams{
		MaxDepth: maxDepth,
	}
}

func (p *DebuggerSetAsyncCallStackDepthParams) CDPMethodName() string {
	return "Debugger.setAsyncCallStackDepth"
}

// Replace previous blackbox execution contexts with passed ones. Forces backend to skip
// stepping/pausing in scripts in these execution contexts. VM will try to leave blackboxed script by
// performing 'step in' several times, finally resorting to 'step out' if unsuccessful.
type DebuggerSetBlackboxExecutionContextsParams struct {
	// Array of execution context unique ids for the debugger to ignore.
	UniqueIds []string `json:"uniqueIds"`
}

func DebuggerSetBlackboxExecutionContexts(uniqueIds []string) *DebuggerSetBlackboxExecutionContextsParams {
	return &DebuggerSetBlackboxExecutionContextsParams{
		UniqueIds: uniqueIds,
	}
}

func (p *DebuggerSetBlackboxExecutionContextsParams) CDPMethodName() string {
	return "Debugger.setBlackboxExecutionContexts"
}

// Replace previous blackbox patterns with passed ones. Forces backend to skip stepping/pausing in
// scripts with url matching one of the patterns. VM will try to leave blackboxed script by
// performing 'step in' several times, finally resorting to 'step out' if unsuccessful.
type DebuggerSetBlackboxPatternsParams struct {
	// Array of regexps that will be used to check script url for blackbox state.
	Patterns []string `json:"patterns"`
	// If true, also ignore scripts with no source url.
	SkipAnonymous *bool `json:"skipAnonymous,omitempty"`
}

func DebuggerSetBlackboxPatterns(patterns []string) *DebuggerSetBlackboxPatternsParams {
	return &DebuggerSetBlackboxPatternsParams{
		Patterns: patterns,
	}
}

func (p *DebuggerSetBlackboxPatternsParams) WithSkipAnonymous(v bool) *DebuggerSetBlackboxPatternsParams {
	p.SkipAnonymous = &v
	return p
}

func (p *DebuggerSetBlackboxPatternsParams) CDPMethodName() string {
	return "Debugger.setBlackboxPatterns"
}

// Makes backend skip steps in the script in blackboxed ranges. VM will try leave blacklisted
// scripts by performing 'step in' several times, finally resorting to 'step out' if unsuccessful.
// Positions array contains positions where blackbox state is changed. First interval isn't
// blackboxed. Array should be sorted.
type DebuggerSetBlackboxedRangesParams struct {
	// Id of the script.
	ScriptId  RuntimeScriptId          `json:"scriptId"`
	Positions []DebuggerScriptPosition `json:"positions"`
}

func DebuggerSetBlackboxedRanges(scriptId RuntimeScriptId, positions []DebuggerScriptPosition) *DebuggerSetBlackboxedRangesParams {
	return &DebuggerSetBlackboxedRangesParams{
		ScriptId:  scriptId,
		Positions: positions,
	}
}

func (p *DebuggerSetBlackboxedRangesParams) CDPMethodName() string {
	return "Debugger.setBlackboxedRanges"
}

// Sets JavaScript breakpoint at a given location.
type DebuggerSetBreakpointParams struct {
	// Location to set breakpoint in.
	Location DebuggerLocation `json:"location"`
	// Expression to use as a breakpoint condition. When specified, debugger will only stop on the
	// breakpoint if this expression evaluates to true.
	Condition *string `json:"condition,omitempty"`
}

type DebuggerSetBreakpointReturns struct {
	// Id of the created breakpoint for further reference.
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
	// Location this breakpoint resolved into.
	ActualLocation DebuggerLocation `json:"actualLocation"`
}

func DebuggerSetBreakpoint(location DebuggerLocation) *DebuggerSetBreakpointParams {
	return &DebuggerSetBreakpointParams{
		Location: location,
	}
}

func (p *DebuggerSetBreakpointParams) WithCondition(v string) *DebuggerSetBreakpointParams {
	p.Condition = &v
	return p
}

func (p *DebuggerSetBreakpointParams) CDPMethodName() string {
	return "Debugger.setBreakpoint"
}

// Sets instrumentation breakpoint.
type DebuggerSetInstrumentationBreakpointParams struct {
	// Instrumentation name.
	Instrumentation string `json:"instrumentation"`
}

type DebuggerSetInstrumentationBreakpointReturns struct {
	// Id of the created breakpoint for further reference.
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
}

func DebuggerSetInstrumentationBreakpoint(instrumentation string) *DebuggerSetInstrumentationBreakpointParams {
	return &DebuggerSetInstrumentationBreakpointParams{
		Instrumentation: instrumentation,
	}
}

func (p *DebuggerSetInstrumentationBreakpointParams) CDPMethodName() string {
	return "Debugger.setInstrumentationBreakpoint"
}

// Sets JavaScript breakpoint at given location specified either by URL or URL regex. Once this
// command is issued, all existing parsed scripts will have breakpoints resolved and returned in
// `locations` property. Further matching script parsing will result in subsequent
// `breakpointResolved` events issued. This logical breakpoint will survive page reloads.
type DebuggerSetBreakpointByUrlParams struct {
	// Line number to set breakpoint at.
	LineNumber int64 `json:"lineNumber"`
	// URL of the resources to set breakpoint on.
	Url *string `json:"url,omitempty"`
	// Regex pattern for the URLs of the resources to set breakpoints on. Either `url` or
	// `urlRegex` must be specified.
	UrlRegex *string `json:"urlRegex,omitempty"`
	// Script hash of the resources to set breakpoint on.
	ScriptHash *string `json:"scriptHash,omitempty"`
	// Offset in the line to set breakpoint at.
	ColumnNumber *int64 `json:"columnNumber,omitempty"`
	// Expression to use as a breakpoint condition. When specified, debugger will only stop on the
	// breakpoint if this expression evaluates to true.
	Condition *string `json:"condition,omitempty"`
}

type DebuggerSetBreakpointByUrlReturns struct {
	// Id of the created breakpoint for further reference.
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
	// List of the locations this breakpoint resolved into upon addition.
	Locations []DebuggerLocation `json:"locations"`
}

func DebuggerSetBreakpointByUrl(lineNumber int64) *DebuggerSetBreakpointByUrlParams {
	return &DebuggerSetBreakpointByUrlParams{
		LineNumber: lineNumber,
	}
}

func (p *DebuggerSetBreakpointByUrlParams) WithUrl(v string) *DebuggerSetBreakpointByUrlParams {
	p.Url = &v
	return p
}

func (p *DebuggerSetBreakpointByUrlParams) WithUrlRegex(v string) *DebuggerSetBreakpointByUrlParams {
	p.UrlRegex = &v
	return p
}

func (p *DebuggerSetBreakpointByUrlParams) WithScriptHash(v string) *DebuggerSetBreakpointByUrlParams {
	p.ScriptHash = &v
	return p
}

func (p *DebuggerSetBreakpointByUrlParams) WithColumnNumber(v int64) *DebuggerSetBreakpointByUrlParams {
	p.ColumnNumber = &v
	return p
}

func (p *DebuggerSetBreakpointByUrlParams) WithCondition(v string) *DebuggerSetBreakpointByUrlParams {
	p.Condition = &v
	return p
}

func (p *DebuggerSetBreakpointByUrlParams) CDPMethodName() string {
	return "Debugger.setBreakpointByUrl"
}

// Sets JavaScript breakpoint before each call to the given function.
// If another function was created from the same source as a given one,
// calling it will also trigger the breakpoint.
type DebuggerSetBreakpointOnFunctionCallParams struct {
	// Function object id.
	ObjectId RuntimeRemoteObjectId `json:"objectId"`
	// Expression to use as a breakpoint condition. When specified, debugger will
	// stop on the breakpoint if this expression evaluates to true.
	Condition *string `json:"condition,omitempty"`
}

type DebuggerSetBreakpointOnFunctionCallReturns struct {
	// Id of the created breakpoint for further reference.
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
}

func DebuggerSetBreakpointOnFunctionCall(objectId RuntimeRemoteObjectId) *DebuggerSetBreakpointOnFunctionCallParams {
	return &DebuggerSetBreakpointOnFunctionCallParams{
		ObjectId: objectId,
	}
}

func (p *DebuggerSetBreakpointOnFunctionCallParams) WithCondition(v string) *DebuggerSetBreakpointOnFunctionCallParams {
	p.Condition = &v
	return p
}

func (p *DebuggerSetBreakpointOnFunctionCallParams) CDPMethodName() string {
	return "Debugger.setBreakpointOnFunctionCall"
}

// Activates / deactivates all breakpoints on the page.
type DebuggerSetBreakpointsActiveParams struct {
	// New value for breakpoints active state.
	Active bool `json:"active"`
}

func DebuggerSetBreakpointsActive(active bool) *DebuggerSetBreakpointsActiveParams {
	return &DebuggerSetBreakpointsActiveParams{
		Active: active,
	}
}

func (p *DebuggerSetBreakpointsActiveParams) CDPMethodName() string {
	return "Debugger.setBreakpointsActive"
}

// Defines pause on exceptions state. Can be set to stop on all exceptions, uncaught exceptions,
// or caught exceptions, no exceptions. Initial pause on exceptions state is `none`.
type DebuggerSetPauseOnExceptionsParams struct {
	// Pause on exceptions mode.
	State string `json:"state"`
}

func DebuggerSetPauseOnExceptions(state string) *DebuggerSetPauseOnExceptionsParams {
	return &DebuggerSetPauseOnExceptionsParams{
		State: state,
	}
}

func (p *DebuggerSetPauseOnExceptionsParams) CDPMethodName() string {
	return "Debugger.setPauseOnExceptions"
}

// Changes return value in top frame. Available only at return break position.
type DebuggerSetReturnValueParams struct {
	// New return value.
	NewValue RuntimeCallArgument `json:"newValue"`
}

func DebuggerSetReturnValue(newValue RuntimeCallArgument) *DebuggerSetReturnValueParams {
	return &DebuggerSetReturnValueParams{
		NewValue: newValue,
	}
}

func (p *DebuggerSetReturnValueParams) CDPMethodName() string {
	return "Debugger.setReturnValue"
}

// Edits JavaScript source live.
//
// In general, functions that are currently on the stack can not be edited with
// a single exception: If the edited function is the top-most stack frame and
// that is the only activation of that function on the stack. In this case
// the live edit will be successful and a `Debugger.restartFrame` for the
// top-most function is automatically triggered.
type DebuggerSetScriptSourceParams struct {
	// Id of the script to edit.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// New content of the script.
	ScriptSource string `json:"scriptSource"`
	// If true the change will not actually be applied. Dry run may be used to get result
	// description without actually modifying the code.
	DryRun *bool `json:"dryRun,omitempty"`
	// If true, then `scriptSource` is allowed to change the function on top of the stack
	// as long as the top-most stack frame is the only activation of that function.
	AllowTopFrameEditing *bool `json:"allowTopFrameEditing,omitempty"`
}

type DebuggerSetScriptSourceReturns struct {
	// New stack trace in case editing has happened while VM was stopped.
	CallFrames []DebuggerCallFrame `json:"callFrames,omitempty"`
	// Whether current call stack  was modified after applying the changes.
	StackChanged *bool `json:"stackChanged,omitempty"`
	// Async stack trace, if any.
	AsyncStackTrace *RuntimeStackTrace `json:"asyncStackTrace,omitempty"`
	// Async stack trace, if any.
	AsyncStackTraceId *RuntimeStackTraceId `json:"asyncStackTraceId,omitempty"`
	// Whether the operation was successful or not. Only `Ok` denotes a
	// successful live edit while the other enum variants denote why
	// the live edit failed.
	Status string `json:"status"`
	// Exception details if any. Only present when `status` is `CompileError`.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func DebuggerSetScriptSource(scriptId RuntimeScriptId, scriptSource string) *DebuggerSetScriptSourceParams {
	return &DebuggerSetScriptSourceParams{
		ScriptId:     scriptId,
		ScriptSource: scriptSource,
	}
}

func (p *DebuggerSetScriptSourceParams) WithDryRun(v bool) *DebuggerSetScriptSourceParams {
	p.DryRun = &v
	return p
}

func (p *DebuggerSetScriptSourceParams) WithAllowTopFrameEditing(v bool) *DebuggerSetScriptSourceParams {
	p.AllowTopFrameEditing = &v
	return p
}

func (p *DebuggerSetScriptSourceParams) CDPMethodName() string {
	return "Debugger.setScriptSource"
}

// Makes page not interrupt on any pauses (breakpoint, exception, dom exception etc).
type DebuggerSetSkipAllPausesParams struct {
	// New value for skip pauses state.
	Skip bool `json:"skip"`
}

func DebuggerSetSkipAllPauses(skip bool) *DebuggerSetSkipAllPausesParams {
	return &DebuggerSetSkipAllPausesParams{
		Skip: skip,
	}
}

func (p *DebuggerSetSkipAllPausesParams) CDPMethodName() string {
	return "Debugger.setSkipAllPauses"
}

// Changes value of variable in a callframe. Object-based scopes are not supported and must be
// mutated manually.
type DebuggerSetVariableValueParams struct {
	// 0-based number of scope as was listed in scope chain. Only 'local', 'closure' and 'catch'
	// scope types are allowed. Other scopes could be manipulated manually.
	ScopeNumber int64 `json:"scopeNumber"`
	// Variable name.
	VariableName string `json:"variableName"`
	// New variable value.
	NewValue RuntimeCallArgument `json:"newValue"`
	// Id of callframe that holds variable.
	CallFrameId DebuggerCallFrameId `json:"callFrameId"`
}

func DebuggerSetVariableValue(scopeNumber int64, variableName string, newValue RuntimeCallArgument, callFrameId DebuggerCallFrameId) *DebuggerSetVariableValueParams {
	return &DebuggerSetVariableValueParams{
		ScopeNumber:  scopeNumber,
		VariableName: variableName,
		NewValue:     newValue,
		CallFrameId:  callFrameId,
	}
}

func (p *DebuggerSetVariableValueParams) CDPMethodName() string {
	return "Debugger.setVariableValue"
}

// Steps into the function call.
type DebuggerStepIntoParams struct {
	// Debugger will pause on the execution of the first async task which was scheduled
	// before next pause.
	BreakOnAsyncCall *bool `json:"breakOnAsyncCall,omitempty"`
	// The skipList specifies location ranges that should be skipped on step into.
	SkipList []DebuggerLocationRange `json:"skipList,omitempty"`
}

func DebuggerStepInto() *DebuggerStepIntoParams {
	return &DebuggerStepIntoParams{}
}

func (p *DebuggerStepIntoParams) WithBreakOnAsyncCall(v bool) *DebuggerStepIntoParams {
	p.BreakOnAsyncCall = &v
	return p
}

func (p *DebuggerStepIntoParams) WithSkipList(v []DebuggerLocationRange) *DebuggerStepIntoParams {
	p.SkipList = v
	return p
}

func (p *DebuggerStepIntoParams) CDPMethodName() string {
	return "Debugger.stepInto"
}

// Steps out of the function call.
type DebuggerStepOutParams struct {
}

func DebuggerStepOut() *DebuggerStepOutParams {
	return &DebuggerStepOutParams{}
}

func (p *DebuggerStepOutParams) CDPMethodName() string {
	return "Debugger.stepOut"
}

// Steps over the statement.
type DebuggerStepOverParams struct {
	// The skipList specifies location ranges that should be skipped on step over.
	SkipList []DebuggerLocationRange `json:"skipList,omitempty"`
}

func DebuggerStepOver() *DebuggerStepOverParams {
	return &DebuggerStepOverParams{}
}

func (p *DebuggerStepOverParams) WithSkipList(v []DebuggerLocationRange) *DebuggerStepOverParams {
	p.SkipList = v
	return p
}

func (p *DebuggerStepOverParams) CDPMethodName() string {
	return "Debugger.stepOver"
}

// Fired when breakpoint is resolved to an actual script and location.
// Deprecated in favor of `resolvedBreakpoints` in the `scriptParsed` event.
const EventDebuggerBreakpointResolved = "Debugger.breakpointResolved"

type DebuggerBreakpointResolvedEvent struct {
	// Breakpoint unique identifier.
	BreakpointId DebuggerBreakpointId `json:"breakpointId"`
	// Actual breakpoint location.
	Location DebuggerLocation `json:"location"`
}

func (e *DebuggerBreakpointResolvedEvent) CDPEventName() string {
	return EventDebuggerBreakpointResolved
}

// Fired when the virtual machine stopped on breakpoint or exception or any other stop criteria.
const EventDebuggerPaused = "Debugger.paused"

type DebuggerPausedEvent struct {
	// Call stack the virtual machine stopped on.
	CallFrames []DebuggerCallFrame `json:"callFrames"`
	// Pause reason.
	Reason string `json:"reason"`
	// Object containing break-specific auxiliary properties.
	Data map[string]any `json:"data,omitempty"`
	// Hit breakpoints IDs
	HitBreakpoints []string `json:"hitBreakpoints,omitempty"`
	// Async stack trace, if any.
	AsyncStackTrace *RuntimeStackTrace `json:"asyncStackTrace,omitempty"`
	// Async stack trace, if any.
	AsyncStackTraceId *RuntimeStackTraceId `json:"asyncStackTraceId,omitempty"`
	// Never present, will be removed.
	AsyncCallStackTraceId *RuntimeStackTraceId `json:"asyncCallStackTraceId,omitempty"`
}

func (e *DebuggerPausedEvent) CDPEventName() string {
	return EventDebuggerPaused
}

// Fired when the virtual machine resumed execution.
const EventDebuggerResumed = "Debugger.resumed"

type DebuggerResumedEvent struct {
}

func (e *DebuggerResumedEvent) CDPEventName() string {
	return EventDebuggerResumed
}

// Fired when virtual machine fails to parse the script.
const EventDebuggerScriptFailedToParse = "Debugger.scriptFailedToParse"

type DebuggerScriptFailedToParseEvent struct {
	// Identifier of the script parsed.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// URL or name of the script parsed (if any).
	Url string `json:"url"`
	// Line offset of the script within the resource with given URL (for script tags).
	StartLine int64 `json:"startLine"`
	// Column offset of the script within the resource with given URL.
	StartColumn int64 `json:"startColumn"`
	// Last line of the script.
	EndLine int64 `json:"endLine"`
	// Length of the last line of the script.
	EndColumn int64 `json:"endColumn"`
	// Specifies script creation context.
	ExecutionContextId RuntimeExecutionContextId `json:"executionContextId"`
	// Content hash of the script, SHA-256.
	Hash string `json:"hash"`
	// For Wasm modules, the content of the `build_id` custom section. For JavaScript the `debugId` magic comment.
	BuildId string `json:"buildId"`
	// Embedder-specific auxiliary data likely matching {isDefault: boolean, type: 'default'|'isolated'|'worker', frameId: string}
	ExecutionContextAuxData map[string]any `json:"executionContextAuxData,omitempty"`
	// URL of source map associated with script (if any).
	SourceMapURL *string `json:"sourceMapURL,omitempty"`
	// True, if this script has sourceURL.
	HasSourceURL *bool `json:"hasSourceURL,omitempty"`
	// True, if this script is ES6 module.
	IsModule *bool `json:"isModule,omitempty"`
	// This script length.
	Length *int64 `json:"length,omitempty"`
	// JavaScript top stack frame of where the script parsed event was triggered if available.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
	// If the scriptLanguage is WebAssembly, the code section offset in the module.
	CodeOffset *int64 `json:"codeOffset,omitempty"`
	// The language of the script.
	ScriptLanguage *DebuggerScriptLanguage `json:"scriptLanguage,omitempty"`
	// The name the embedder supplied for this script.
	EmbedderName *string `json:"embedderName,omitempty"`
}

func (e *DebuggerScriptFailedToParseEvent) CDPEventName() string {
	return EventDebuggerScriptFailedToParse
}

// Fired when virtual machine parses script. This event is also fired for all known and uncollected
// scripts upon enabling debugger.
const EventDebuggerScriptParsed = "Debugger.scriptParsed"

type DebuggerScriptParsedEvent struct {
	// Identifier of the script parsed.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// URL or name of the script parsed (if any).
	Url string `json:"url"`
	// Line offset of the script within the resource with given URL (for script tags).
	StartLine int64 `json:"startLine"`
	// Column offset of the script within the resource with given URL.
	StartColumn int64 `json:"startColumn"`
	// Last line of the script.
	EndLine int64 `json:"endLine"`
	// Length of the last line of the script.
	EndColumn int64 `json:"endColumn"`
	// Specifies script creation context.
	ExecutionContextId RuntimeExecutionContextId `json:"executionContextId"`
	// Content hash of the script, SHA-256.
	Hash string `json:"hash"`
	// For Wasm modules, the content of the `build_id` custom section. For JavaScript the `debugId` magic comment.
	BuildId string `json:"buildId"`
	// Embedder-specific auxiliary data likely matching {isDefault: boolean, type: 'default'|'isolated'|'worker', frameId: string}
	ExecutionContextAuxData map[string]any `json:"executionContextAuxData,omitempty"`
	// True, if this script is generated as a result of the live edit operation.
	IsLiveEdit *bool `json:"isLiveEdit,omitempty"`
	// URL of source map associated with script (if any).
	SourceMapURL *string `json:"sourceMapURL,omitempty"`
	// True, if this script has sourceURL.
	HasSourceURL *bool `json:"hasSourceURL,omitempty"`
	// True, if this script is ES6 module.
	IsModule *bool `json:"isModule,omitempty"`
	// This script length.
	Length *int64 `json:"length,omitempty"`
	// JavaScript top stack frame of where the script parsed event was triggered if available.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
	// If the scriptLanguage is WebAssembly, the code section offset in the module.
	CodeOffset *int64 `json:"codeOffset,omitempty"`
	// The language of the script.
	ScriptLanguage *DebuggerScriptLanguage `json:"scriptLanguage,omitempty"`
	// If the scriptLanguage is WebAssembly, the source of debug symbols for the module.
	DebugSymbols []DebuggerDebugSymbols `json:"debugSymbols,omitempty"`
	// The name the embedder supplied for this script.
	EmbedderName *string `json:"embedderName,omitempty"`
	// The list of set breakpoints in this script if calls to `setBreakpointByUrl`
	// matches this script's URL or hash. Clients that use this list can ignore the
	// `breakpointResolved` event. They are equivalent.
	ResolvedBreakpoints []DebuggerResolvedBreakpoint `json:"resolvedBreakpoints,omitempty"`
}

func (e *DebuggerScriptParsedEvent) CDPEventName() string {
	return EventDebuggerScriptParsed
}
