// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Unique DOM node identifier.
type DOMNodeId int64

// Unique DOM node identifier used to reference a node that may not have been pushed to the
// front-end.
type DOMBackendNodeId int64

// Unique identifier for a CSS stylesheet.
type DOMStyleSheetId string

// Backend node with a friendly name.
type DOMBackendNode struct {
	// `Node`'s nodeType.
	NodeType int64 `json:"nodeType"`
	// `Node`'s nodeName.
	NodeName      string           `json:"nodeName"`
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
}

// Pseudo element type.
type DOMPseudoType string

const (
	DOMPseudoTypeFirstLine                   DOMPseudoType = "first-line"
	DOMPseudoTypeFirstLetter                 DOMPseudoType = "first-letter"
	DOMPseudoTypeCheckmark                   DOMPseudoType = "checkmark"
	DOMPseudoTypeBefore                      DOMPseudoType = "before"
	DOMPseudoTypeAfter                       DOMPseudoType = "after"
	DOMPseudoTypeExpandIcon                  DOMPseudoType = "expand-icon"
	DOMPseudoTypePickerIcon                  DOMPseudoType = "picker-icon"
	DOMPseudoTypeInterestHint                DOMPseudoType = "interest-hint"
	DOMPseudoTypeMarker                      DOMPseudoType = "marker"
	DOMPseudoTypeBackdrop                    DOMPseudoType = "backdrop"
	DOMPseudoTypeColumn                      DOMPseudoType = "column"
	DOMPseudoTypeSelection                   DOMPseudoType = "selection"
	DOMPseudoTypeSearchText                  DOMPseudoType = "search-text"
	DOMPseudoTypeTargetText                  DOMPseudoType = "target-text"
	DOMPseudoTypeSpellingError               DOMPseudoType = "spelling-error"
	DOMPseudoTypeGrammarError                DOMPseudoType = "grammar-error"
	DOMPseudoTypeHighlight                   DOMPseudoType = "highlight"
	DOMPseudoTypeFirstLineInherited          DOMPseudoType = "first-line-inherited"
	DOMPseudoTypeScrollMarker                DOMPseudoType = "scroll-marker"
	DOMPseudoTypeScrollMarkerGroup           DOMPseudoType = "scroll-marker-group"
	DOMPseudoTypeScrollButton                DOMPseudoType = "scroll-button"
	DOMPseudoTypeScrollbar                   DOMPseudoType = "scrollbar"
	DOMPseudoTypeScrollbarThumb              DOMPseudoType = "scrollbar-thumb"
	DOMPseudoTypeScrollbarButton             DOMPseudoType = "scrollbar-button"
	DOMPseudoTypeScrollbarTrack              DOMPseudoType = "scrollbar-track"
	DOMPseudoTypeScrollbarTrackPiece         DOMPseudoType = "scrollbar-track-piece"
	DOMPseudoTypeScrollbarCorner             DOMPseudoType = "scrollbar-corner"
	DOMPseudoTypeResizer                     DOMPseudoType = "resizer"
	DOMPseudoTypeInputListButton             DOMPseudoType = "input-list-button"
	DOMPseudoTypeViewTransition              DOMPseudoType = "view-transition"
	DOMPseudoTypeViewTransitionGroup         DOMPseudoType = "view-transition-group"
	DOMPseudoTypeViewTransitionImagePair     DOMPseudoType = "view-transition-image-pair"
	DOMPseudoTypeViewTransitionGroupChildren DOMPseudoType = "view-transition-group-children"
	DOMPseudoTypeViewTransitionOld           DOMPseudoType = "view-transition-old"
	DOMPseudoTypeViewTransitionNew           DOMPseudoType = "view-transition-new"
	DOMPseudoTypePlaceholder                 DOMPseudoType = "placeholder"
	DOMPseudoTypeFileSelectorButton          DOMPseudoType = "file-selector-button"
	DOMPseudoTypeDetailsContent              DOMPseudoType = "details-content"
	DOMPseudoTypePicker                      DOMPseudoType = "picker"
	DOMPseudoTypePermissionIcon              DOMPseudoType = "permission-icon"
	DOMPseudoTypeOverscrollAreaParent        DOMPseudoType = "overscroll-area-parent"
)

// Shadow root type.
type DOMShadowRootType string

const (
	DOMShadowRootTypeUserAgent DOMShadowRootType = "user-agent"
	DOMShadowRootTypeOpen      DOMShadowRootType = "open"
	DOMShadowRootTypeClosed    DOMShadowRootType = "closed"
)

// Document compatibility mode.
type DOMCompatibilityMode string

const (
	DOMCompatibilityModeQuirksMode        DOMCompatibilityMode = "QuirksMode"
	DOMCompatibilityModeLimitedQuirksMode DOMCompatibilityMode = "LimitedQuirksMode"
	DOMCompatibilityModeNoQuirksMode      DOMCompatibilityMode = "NoQuirksMode"
)

// ContainerSelector physical axes
type DOMPhysicalAxes string

const (
	DOMPhysicalAxesHorizontal DOMPhysicalAxes = "Horizontal"
	DOMPhysicalAxesVertical   DOMPhysicalAxes = "Vertical"
	DOMPhysicalAxesBoth       DOMPhysicalAxes = "Both"
)

// ContainerSelector logical axes
type DOMLogicalAxes string

const (
	DOMLogicalAxesInline DOMLogicalAxes = "Inline"
	DOMLogicalAxesBlock  DOMLogicalAxes = "Block"
	DOMLogicalAxesBoth   DOMLogicalAxes = "Both"
)

// Physical scroll orientation
type DOMScrollOrientation string

const (
	DOMScrollOrientationHorizontal DOMScrollOrientation = "horizontal"
	DOMScrollOrientationVertical   DOMScrollOrientation = "vertical"
)

// DOM interaction is implemented in terms of mirror objects that represent the actual DOM nodes.
// DOMNode is a base node mirror type.
type DOMNode struct {
	// Node identifier that is passed into the rest of the DOM messages as the `nodeId`. Backend
	// will only push node with given `id` once. It is aware of all requested nodes and will only
	// fire DOM events for nodes known to the client.
	NodeId DOMNodeId `json:"nodeId"`
	// The id of the parent node if any.
	ParentId *DOMNodeId `json:"parentId,omitempty"`
	// The BackendNodeId for this node.
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
	// `Node`'s nodeType.
	NodeType int64 `json:"nodeType"`
	// `Node`'s nodeName.
	NodeName string `json:"nodeName"`
	// `Node`'s localName.
	LocalName string `json:"localName"`
	// `Node`'s nodeValue.
	NodeValue string `json:"nodeValue"`
	// Child count for `Container` nodes.
	ChildNodeCount *int64 `json:"childNodeCount,omitempty"`
	// Child nodes of this node when requested with children.
	Children []DOMNode `json:"children,omitempty"`
	// Attributes of the `Element` node in the form of flat array `[name1, value1, name2, value2]`.
	Attributes []string `json:"attributes,omitempty"`
	// Document URL that `Document` or `FrameOwner` node points to.
	DocumentURL *string `json:"documentURL,omitempty"`
	// Base URL that `Document` or `FrameOwner` node uses for URL completion.
	BaseURL *string `json:"baseURL,omitempty"`
	// `DocumentType`'s publicId.
	PublicId *string `json:"publicId,omitempty"`
	// `DocumentType`'s systemId.
	SystemId *string `json:"systemId,omitempty"`
	// `DocumentType`'s internalSubset.
	InternalSubset *string `json:"internalSubset,omitempty"`
	// `Document`'s XML version in case of XML documents.
	XmlVersion *string `json:"xmlVersion,omitempty"`
	// `Attr`'s name.
	Name *string `json:"name,omitempty"`
	// `Attr`'s value.
	Value *string `json:"value,omitempty"`
	// Pseudo element type for this node.
	PseudoType *DOMPseudoType `json:"pseudoType,omitempty"`
	// Pseudo element identifier for this node. Only present if there is a
	// valid pseudoType.
	PseudoIdentifier *string `json:"pseudoIdentifier,omitempty"`
	// Shadow root type.
	ShadowRootType *DOMShadowRootType `json:"shadowRootType,omitempty"`
	// Frame ID for frame owner elements.
	FrameId *PageFrameId `json:"frameId,omitempty"`
	// Content document for frame owner elements.
	ContentDocument *DOMNode `json:"contentDocument,omitempty"`
	// Shadow root list for given element host.
	ShadowRoots []DOMNode `json:"shadowRoots,omitempty"`
	// Content document fragment for template elements.
	TemplateContent *DOMNode `json:"templateContent,omitempty"`
	// Pseudo elements associated with this node.
	PseudoElements []DOMNode `json:"pseudoElements,omitempty"`
	// Deprecated, as the HTML Imports API has been removed (crbug.com/937746).
	// This property used to return the imported document for the HTMLImport links.
	// The property is always undefined now.
	ImportedDocument *DOMNode `json:"importedDocument,omitempty"`
	// Distributed nodes for given insertion point.
	DistributedNodes []DOMBackendNode `json:"distributedNodes,omitempty"`
	// Whether the node is SVG.
	IsSVG                    *bool                 `json:"isSVG,omitempty"`
	CompatibilityMode        *DOMCompatibilityMode `json:"compatibilityMode,omitempty"`
	AssignedSlot             *DOMBackendNode       `json:"assignedSlot,omitempty"`
	IsScrollable             *bool                 `json:"isScrollable,omitempty"`
	AffectedByStartingStyles *bool                 `json:"affectedByStartingStyles,omitempty"`
	AdoptedStyleSheets       []DOMStyleSheetId     `json:"adoptedStyleSheets,omitempty"`
	AdProvenance             *NetworkAdProvenance  `json:"adProvenance,omitempty"`
}

// A structure to hold the top-level node of a detached tree and an array of its retained descendants.
type DOMDetachedElementInfo struct {
	TreeNode        DOMNode     `json:"treeNode"`
	RetainedNodeIds []DOMNodeId `json:"retainedNodeIds"`
}

// A structure holding an RGBA color.
type DOMRGBA struct {
	// The red component, in the [0-255] range.
	R int64 `json:"r"`
	// The green component, in the [0-255] range.
	G int64 `json:"g"`
	// The blue component, in the [0-255] range.
	B int64 `json:"b"`
	// The alpha component, in the [0-1] range (default: 1).
	A *float64 `json:"a,omitempty"`
}

// An array of quad vertices, x immediately followed by y for each point, points clock-wise.
type DOMQuad []float64

// Box model.
type DOMBoxModel struct {
	// Content box
	Content DOMQuad `json:"content"`
	// Padding box
	Padding DOMQuad `json:"padding"`
	// Border box
	Border DOMQuad `json:"border"`
	// Margin box
	Margin DOMQuad `json:"margin"`
	// Node width
	Width int64 `json:"width"`
	// Node height
	Height int64 `json:"height"`
	// Shape outside coordinates
	ShapeOutside *DOMShapeOutsideInfo `json:"shapeOutside,omitempty"`
}

// CSS Shape Outside details.
type DOMShapeOutsideInfo struct {
	// Shape bounds
	Bounds DOMQuad `json:"bounds"`
	// Shape coordinate details
	Shape []any `json:"shape"`
	// Margin shape bounds
	MarginShape []any `json:"marginShape"`
}

// Rectangle.
type DOMRect struct {
	// X coordinate
	X float64 `json:"x"`
	// Y coordinate
	Y float64 `json:"y"`
	// Rectangle width
	Width float64 `json:"width"`
	// Rectangle height
	Height float64 `json:"height"`
}

type DOMCSSComputedStyleProperty struct {
	// Computed style property name.
	Name string `json:"name"`
	// Computed style property value.
	Value string `json:"value"`
}

// Collects class names for the node with given id and all of it's child nodes.
type DOMCollectClassNamesFromSubtreeParams struct {
	// Id of the node to collect class names.
	NodeId DOMNodeId `json:"nodeId"`
}

type DOMCollectClassNamesFromSubtreeReturns struct {
	// Class name list.
	ClassNames []string `json:"classNames"`
}

func DOMCollectClassNamesFromSubtree(nodeId DOMNodeId) *DOMCollectClassNamesFromSubtreeParams {
	return &DOMCollectClassNamesFromSubtreeParams{
		NodeId: nodeId,
	}
}

func (p *DOMCollectClassNamesFromSubtreeParams) CDPMethodName() string {
	return "DOM.collectClassNamesFromSubtree"
}

// Creates a deep copy of the specified node and places it into the target container before the
// given anchor.
type DOMCopyToParams struct {
	// Id of the node to copy.
	NodeId DOMNodeId `json:"nodeId"`
	// Id of the element to drop the copy into.
	TargetNodeId DOMNodeId `json:"targetNodeId"`
	// Drop the copy before this node (if absent, the copy becomes the last child of
	// `targetNodeId`).
	InsertBeforeNodeId *DOMNodeId `json:"insertBeforeNodeId,omitempty"`
}

type DOMCopyToReturns struct {
	// Id of the node clone.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMCopyTo(nodeId DOMNodeId, targetNodeId DOMNodeId) *DOMCopyToParams {
	return &DOMCopyToParams{
		NodeId:       nodeId,
		TargetNodeId: targetNodeId,
	}
}

func (p *DOMCopyToParams) WithInsertBeforeNodeId(v DOMNodeId) *DOMCopyToParams {
	p.InsertBeforeNodeId = &v
	return p
}

func (p *DOMCopyToParams) CDPMethodName() string {
	return "DOM.copyTo"
}

// Describes node given its id, does not require domain to be enabled. Does not start tracking any
// objects, can be used for automation.
type DOMDescribeNodeParams struct {
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth *int64 `json:"depth,omitempty"`
	// Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false).
	Pierce *bool `json:"pierce,omitempty"`
}

type DOMDescribeNodeReturns struct {
	// Node description.
	Node DOMNode `json:"node"`
}

func DOMDescribeNode() *DOMDescribeNodeParams {
	return &DOMDescribeNodeParams{}
}

func (p *DOMDescribeNodeParams) WithNodeId(v DOMNodeId) *DOMDescribeNodeParams {
	p.NodeId = &v
	return p
}

func (p *DOMDescribeNodeParams) WithBackendNodeId(v DOMBackendNodeId) *DOMDescribeNodeParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMDescribeNodeParams) WithObjectId(v RuntimeRemoteObjectId) *DOMDescribeNodeParams {
	p.ObjectId = &v
	return p
}

func (p *DOMDescribeNodeParams) WithDepth(v int64) *DOMDescribeNodeParams {
	p.Depth = &v
	return p
}

func (p *DOMDescribeNodeParams) WithPierce(v bool) *DOMDescribeNodeParams {
	p.Pierce = &v
	return p
}

func (p *DOMDescribeNodeParams) CDPMethodName() string {
	return "DOM.describeNode"
}

// Scrolls the specified rect of the given node into view if not already visible.
// Note: exactly one between nodeId, backendNodeId and objectId should be passed
// to identify the node.
type DOMScrollIntoViewIfNeededParams struct {
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// The rect to be scrolled into view, relative to the node's border box, in CSS pixels.
	// When omitted, center of the node will be used, similar to Element.scrollIntoView.
	Rect *DOMRect `json:"rect,omitempty"`
}

func DOMScrollIntoViewIfNeeded() *DOMScrollIntoViewIfNeededParams {
	return &DOMScrollIntoViewIfNeededParams{}
}

func (p *DOMScrollIntoViewIfNeededParams) WithNodeId(v DOMNodeId) *DOMScrollIntoViewIfNeededParams {
	p.NodeId = &v
	return p
}

func (p *DOMScrollIntoViewIfNeededParams) WithBackendNodeId(v DOMBackendNodeId) *DOMScrollIntoViewIfNeededParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMScrollIntoViewIfNeededParams) WithObjectId(v RuntimeRemoteObjectId) *DOMScrollIntoViewIfNeededParams {
	p.ObjectId = &v
	return p
}

func (p *DOMScrollIntoViewIfNeededParams) WithRect(v DOMRect) *DOMScrollIntoViewIfNeededParams {
	p.Rect = &v
	return p
}

func (p *DOMScrollIntoViewIfNeededParams) CDPMethodName() string {
	return "DOM.scrollIntoViewIfNeeded"
}

// Disables DOM agent for the given page.
type DOMDisableParams struct {
}

func DOMDisable() *DOMDisableParams {
	return &DOMDisableParams{}
}

func (p *DOMDisableParams) CDPMethodName() string {
	return "DOM.disable"
}

// Discards search results from the session with the given id. `getSearchResults` should no longer
// be called for that search.
type DOMDiscardSearchResultsParams struct {
	// Unique search session identifier.
	SearchId string `json:"searchId"`
}

func DOMDiscardSearchResults(searchId string) *DOMDiscardSearchResultsParams {
	return &DOMDiscardSearchResultsParams{
		SearchId: searchId,
	}
}

func (p *DOMDiscardSearchResultsParams) CDPMethodName() string {
	return "DOM.discardSearchResults"
}

// Enables DOM agent for the given page.
type DOMEnableParams struct {
	// Whether to include whitespaces in the children array of returned Nodes.
	IncludeWhitespace *string `json:"includeWhitespace,omitempty"`
}

func DOMEnable() *DOMEnableParams {
	return &DOMEnableParams{}
}

func (p *DOMEnableParams) WithIncludeWhitespace(v string) *DOMEnableParams {
	p.IncludeWhitespace = &v
	return p
}

func (p *DOMEnableParams) CDPMethodName() string {
	return "DOM.enable"
}

// Focuses the given element.
type DOMFocusParams struct {
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

func DOMFocus() *DOMFocusParams {
	return &DOMFocusParams{}
}

func (p *DOMFocusParams) WithNodeId(v DOMNodeId) *DOMFocusParams {
	p.NodeId = &v
	return p
}

func (p *DOMFocusParams) WithBackendNodeId(v DOMBackendNodeId) *DOMFocusParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMFocusParams) WithObjectId(v RuntimeRemoteObjectId) *DOMFocusParams {
	p.ObjectId = &v
	return p
}

func (p *DOMFocusParams) CDPMethodName() string {
	return "DOM.focus"
}

// Returns attributes for the specified node.
type DOMGetAttributesParams struct {
	// Id of the node to retrieve attributes for.
	NodeId DOMNodeId `json:"nodeId"`
}

type DOMGetAttributesReturns struct {
	// An interleaved array of node attribute names and values.
	Attributes []string `json:"attributes"`
}

func DOMGetAttributes(nodeId DOMNodeId) *DOMGetAttributesParams {
	return &DOMGetAttributesParams{
		NodeId: nodeId,
	}
}

func (p *DOMGetAttributesParams) CDPMethodName() string {
	return "DOM.getAttributes"
}

// Returns boxes for the given node.
type DOMGetBoxModelParams struct {
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

type DOMGetBoxModelReturns struct {
	// Box model for the node.
	Model DOMBoxModel `json:"model"`
}

func DOMGetBoxModel() *DOMGetBoxModelParams {
	return &DOMGetBoxModelParams{}
}

func (p *DOMGetBoxModelParams) WithNodeId(v DOMNodeId) *DOMGetBoxModelParams {
	p.NodeId = &v
	return p
}

func (p *DOMGetBoxModelParams) WithBackendNodeId(v DOMBackendNodeId) *DOMGetBoxModelParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMGetBoxModelParams) WithObjectId(v RuntimeRemoteObjectId) *DOMGetBoxModelParams {
	p.ObjectId = &v
	return p
}

func (p *DOMGetBoxModelParams) CDPMethodName() string {
	return "DOM.getBoxModel"
}

// Returns quads that describe node position on the page. This method
// might return multiple quads for inline nodes.
type DOMGetContentQuadsParams struct {
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

type DOMGetContentQuadsReturns struct {
	// Quads that describe node layout relative to viewport.
	Quads []DOMQuad `json:"quads"`
}

func DOMGetContentQuads() *DOMGetContentQuadsParams {
	return &DOMGetContentQuadsParams{}
}

func (p *DOMGetContentQuadsParams) WithNodeId(v DOMNodeId) *DOMGetContentQuadsParams {
	p.NodeId = &v
	return p
}

func (p *DOMGetContentQuadsParams) WithBackendNodeId(v DOMBackendNodeId) *DOMGetContentQuadsParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMGetContentQuadsParams) WithObjectId(v RuntimeRemoteObjectId) *DOMGetContentQuadsParams {
	p.ObjectId = &v
	return p
}

func (p *DOMGetContentQuadsParams) CDPMethodName() string {
	return "DOM.getContentQuads"
}

// Returns the root DOM node (and optionally the subtree) to the caller.
// Implicitly enables the DOM domain events for the current target.
type DOMGetDocumentParams struct {
	// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth *int64 `json:"depth,omitempty"`
	// Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false).
	Pierce *bool `json:"pierce,omitempty"`
}

type DOMGetDocumentReturns struct {
	// Resulting node.
	Root DOMNode `json:"root"`
}

func DOMGetDocument() *DOMGetDocumentParams {
	return &DOMGetDocumentParams{}
}

func (p *DOMGetDocumentParams) WithDepth(v int64) *DOMGetDocumentParams {
	p.Depth = &v
	return p
}

func (p *DOMGetDocumentParams) WithPierce(v bool) *DOMGetDocumentParams {
	p.Pierce = &v
	return p
}

func (p *DOMGetDocumentParams) CDPMethodName() string {
	return "DOM.getDocument"
}

// Returns the root DOM node (and optionally the subtree) to the caller.
// Deprecated, as it is not designed to work well with the rest of the DOM agent.
// Use DOMSnapshot.captureSnapshot instead.
type DOMGetFlattenedDocumentParams struct {
	// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth *int64 `json:"depth,omitempty"`
	// Whether or not iframes and shadow roots should be traversed when returning the subtree
	// (default is false).
	Pierce *bool `json:"pierce,omitempty"`
}

type DOMGetFlattenedDocumentReturns struct {
	// Resulting node.
	Nodes []DOMNode `json:"nodes"`
}

func DOMGetFlattenedDocument() *DOMGetFlattenedDocumentParams {
	return &DOMGetFlattenedDocumentParams{}
}

func (p *DOMGetFlattenedDocumentParams) WithDepth(v int64) *DOMGetFlattenedDocumentParams {
	p.Depth = &v
	return p
}

func (p *DOMGetFlattenedDocumentParams) WithPierce(v bool) *DOMGetFlattenedDocumentParams {
	p.Pierce = &v
	return p
}

func (p *DOMGetFlattenedDocumentParams) CDPMethodName() string {
	return "DOM.getFlattenedDocument"
}

// Finds nodes with a given computed style in a subtree.
type DOMGetNodesForSubtreeByStyleParams struct {
	// Node ID pointing to the root of a subtree.
	NodeId DOMNodeId `json:"nodeId"`
	// The style to filter nodes by (includes nodes if any of properties matches).
	ComputedStyles []DOMCSSComputedStyleProperty `json:"computedStyles"`
	// Whether or not iframes and shadow roots in the same target should be traversed when returning the
	// results (default is false).
	Pierce *bool `json:"pierce,omitempty"`
}

type DOMGetNodesForSubtreeByStyleReturns struct {
	// Resulting nodes.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMGetNodesForSubtreeByStyle(nodeId DOMNodeId, computedStyles []DOMCSSComputedStyleProperty) *DOMGetNodesForSubtreeByStyleParams {
	return &DOMGetNodesForSubtreeByStyleParams{
		NodeId:         nodeId,
		ComputedStyles: computedStyles,
	}
}

func (p *DOMGetNodesForSubtreeByStyleParams) WithPierce(v bool) *DOMGetNodesForSubtreeByStyleParams {
	p.Pierce = &v
	return p
}

func (p *DOMGetNodesForSubtreeByStyleParams) CDPMethodName() string {
	return "DOM.getNodesForSubtreeByStyle"
}

// Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is
// either returned or not.
type DOMGetNodeForLocationParams struct {
	// X coordinate.
	X int64 `json:"x"`
	// Y coordinate.
	Y int64 `json:"y"`
	// False to skip to the nearest non-UA shadow root ancestor (default: false).
	IncludeUserAgentShadowDOM *bool `json:"includeUserAgentShadowDOM,omitempty"`
	// Whether to ignore pointer-events: none on elements and hit test them.
	IgnorePointerEventsNone *bool `json:"ignorePointerEventsNone,omitempty"`
}

type DOMGetNodeForLocationReturns struct {
	// Resulting node.
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
	// Frame this node belongs to.
	FrameId PageFrameId `json:"frameId"`
	// Id of the node at given coordinates, only when enabled and requested document.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
}

func DOMGetNodeForLocation(x int64, y int64) *DOMGetNodeForLocationParams {
	return &DOMGetNodeForLocationParams{
		X: x,
		Y: y,
	}
}

func (p *DOMGetNodeForLocationParams) WithIncludeUserAgentShadowDOM(v bool) *DOMGetNodeForLocationParams {
	p.IncludeUserAgentShadowDOM = &v
	return p
}

func (p *DOMGetNodeForLocationParams) WithIgnorePointerEventsNone(v bool) *DOMGetNodeForLocationParams {
	p.IgnorePointerEventsNone = &v
	return p
}

func (p *DOMGetNodeForLocationParams) CDPMethodName() string {
	return "DOM.getNodeForLocation"
}

// Returns node's HTML markup.
type DOMGetOuterHTMLParams struct {
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// Include all shadow roots. Equals to false if not specified.
	IncludeShadowDOM *bool `json:"includeShadowDOM,omitempty"`
}

type DOMGetOuterHTMLReturns struct {
	// Outer HTML markup.
	OuterHTML string `json:"outerHTML"`
}

func DOMGetOuterHTML() *DOMGetOuterHTMLParams {
	return &DOMGetOuterHTMLParams{}
}

func (p *DOMGetOuterHTMLParams) WithNodeId(v DOMNodeId) *DOMGetOuterHTMLParams {
	p.NodeId = &v
	return p
}

func (p *DOMGetOuterHTMLParams) WithBackendNodeId(v DOMBackendNodeId) *DOMGetOuterHTMLParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMGetOuterHTMLParams) WithObjectId(v RuntimeRemoteObjectId) *DOMGetOuterHTMLParams {
	p.ObjectId = &v
	return p
}

func (p *DOMGetOuterHTMLParams) WithIncludeShadowDOM(v bool) *DOMGetOuterHTMLParams {
	p.IncludeShadowDOM = &v
	return p
}

func (p *DOMGetOuterHTMLParams) CDPMethodName() string {
	return "DOM.getOuterHTML"
}

// Returns the id of the nearest ancestor that is a relayout boundary.
type DOMGetRelayoutBoundaryParams struct {
	// Id of the node.
	NodeId DOMNodeId `json:"nodeId"`
}

type DOMGetRelayoutBoundaryReturns struct {
	// Relayout boundary node id for the given node.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMGetRelayoutBoundary(nodeId DOMNodeId) *DOMGetRelayoutBoundaryParams {
	return &DOMGetRelayoutBoundaryParams{
		NodeId: nodeId,
	}
}

func (p *DOMGetRelayoutBoundaryParams) CDPMethodName() string {
	return "DOM.getRelayoutBoundary"
}

// Returns search results from given `fromIndex` to given `toIndex` from the search with the given
// identifier.
type DOMGetSearchResultsParams struct {
	// Unique search session identifier.
	SearchId string `json:"searchId"`
	// Start index of the search result to be returned.
	FromIndex int64 `json:"fromIndex"`
	// End index of the search result to be returned.
	ToIndex int64 `json:"toIndex"`
}

type DOMGetSearchResultsReturns struct {
	// Ids of the search result nodes.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMGetSearchResults(searchId string, fromIndex int64, toIndex int64) *DOMGetSearchResultsParams {
	return &DOMGetSearchResultsParams{
		SearchId:  searchId,
		FromIndex: fromIndex,
		ToIndex:   toIndex,
	}
}

func (p *DOMGetSearchResultsParams) CDPMethodName() string {
	return "DOM.getSearchResults"
}

// Hides any highlight.
type DOMHideHighlightParams struct {
}

func DOMHideHighlight() *DOMHideHighlightParams {
	return &DOMHideHighlightParams{}
}

func (p *DOMHideHighlightParams) CDPMethodName() string {
	return "DOM.hideHighlight"
}

// Highlights DOM node.
type DOMHighlightNodeParams struct {
}

func DOMHighlightNode() *DOMHighlightNodeParams {
	return &DOMHighlightNodeParams{}
}

func (p *DOMHighlightNodeParams) CDPMethodName() string {
	return "DOM.highlightNode"
}

// Highlights given rectangle.
type DOMHighlightRectParams struct {
}

func DOMHighlightRect() *DOMHighlightRectParams {
	return &DOMHighlightRectParams{}
}

func (p *DOMHighlightRectParams) CDPMethodName() string {
	return "DOM.highlightRect"
}

// Marks last undoable state.
type DOMMarkUndoableStateParams struct {
}

func DOMMarkUndoableState() *DOMMarkUndoableStateParams {
	return &DOMMarkUndoableStateParams{}
}

func (p *DOMMarkUndoableStateParams) CDPMethodName() string {
	return "DOM.markUndoableState"
}

// Moves node into the new container, places it before the given anchor.
type DOMMoveToParams struct {
	// Id of the node to move.
	NodeId DOMNodeId `json:"nodeId"`
	// Id of the element to drop the moved node into.
	TargetNodeId DOMNodeId `json:"targetNodeId"`
	// Drop node before this one (if absent, the moved node becomes the last child of
	// `targetNodeId`).
	InsertBeforeNodeId *DOMNodeId `json:"insertBeforeNodeId,omitempty"`
}

type DOMMoveToReturns struct {
	// New id of the moved node.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMMoveTo(nodeId DOMNodeId, targetNodeId DOMNodeId) *DOMMoveToParams {
	return &DOMMoveToParams{
		NodeId:       nodeId,
		TargetNodeId: targetNodeId,
	}
}

func (p *DOMMoveToParams) WithInsertBeforeNodeId(v DOMNodeId) *DOMMoveToParams {
	p.InsertBeforeNodeId = &v
	return p
}

func (p *DOMMoveToParams) CDPMethodName() string {
	return "DOM.moveTo"
}

// Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or
// `cancelSearch` to end this search session.
type DOMPerformSearchParams struct {
	// Plain text or query selector or XPath search query.
	Query string `json:"query"`
	// True to search in user agent shadow DOM.
	IncludeUserAgentShadowDOM *bool `json:"includeUserAgentShadowDOM,omitempty"`
}

type DOMPerformSearchReturns struct {
	// Unique search session identifier.
	SearchId string `json:"searchId"`
	// Number of search results.
	ResultCount int64 `json:"resultCount"`
}

func DOMPerformSearch(query string) *DOMPerformSearchParams {
	return &DOMPerformSearchParams{
		Query: query,
	}
}

func (p *DOMPerformSearchParams) WithIncludeUserAgentShadowDOM(v bool) *DOMPerformSearchParams {
	p.IncludeUserAgentShadowDOM = &v
	return p
}

func (p *DOMPerformSearchParams) CDPMethodName() string {
	return "DOM.performSearch"
}

// Requests that the node is sent to the caller given its path. // FIXME, use XPath
type DOMPushNodeByPathToFrontendParams struct {
	// Path to node in the proprietary format.
	Path string `json:"path"`
}

type DOMPushNodeByPathToFrontendReturns struct {
	// Id of the node for given path.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMPushNodeByPathToFrontend(path string) *DOMPushNodeByPathToFrontendParams {
	return &DOMPushNodeByPathToFrontendParams{
		Path: path,
	}
}

func (p *DOMPushNodeByPathToFrontendParams) CDPMethodName() string {
	return "DOM.pushNodeByPathToFrontend"
}

// Requests that a batch of nodes is sent to the caller given their backend node ids.
type DOMPushNodesByBackendIdsToFrontendParams struct {
	// The array of backend node ids.
	BackendNodeIds []DOMBackendNodeId `json:"backendNodeIds"`
}

type DOMPushNodesByBackendIdsToFrontendReturns struct {
	// The array of ids of pushed nodes that correspond to the backend ids specified in
	// backendNodeIds.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMPushNodesByBackendIdsToFrontend(backendNodeIds []DOMBackendNodeId) *DOMPushNodesByBackendIdsToFrontendParams {
	return &DOMPushNodesByBackendIdsToFrontendParams{
		BackendNodeIds: backendNodeIds,
	}
}

func (p *DOMPushNodesByBackendIdsToFrontendParams) CDPMethodName() string {
	return "DOM.pushNodesByBackendIdsToFrontend"
}

// Executes `querySelector` on a given node.
type DOMQuerySelectorParams struct {
	// Id of the node to query upon.
	NodeId DOMNodeId `json:"nodeId"`
	// Selector string.
	Selector string `json:"selector"`
}

type DOMQuerySelectorReturns struct {
	// Query selector result.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMQuerySelector(nodeId DOMNodeId, selector string) *DOMQuerySelectorParams {
	return &DOMQuerySelectorParams{
		NodeId:   nodeId,
		Selector: selector,
	}
}

func (p *DOMQuerySelectorParams) CDPMethodName() string {
	return "DOM.querySelector"
}

// Executes `querySelectorAll` on a given node.
type DOMQuerySelectorAllParams struct {
	// Id of the node to query upon.
	NodeId DOMNodeId `json:"nodeId"`
	// Selector string.
	Selector string `json:"selector"`
}

type DOMQuerySelectorAllReturns struct {
	// Query selector result.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMQuerySelectorAll(nodeId DOMNodeId, selector string) *DOMQuerySelectorAllParams {
	return &DOMQuerySelectorAllParams{
		NodeId:   nodeId,
		Selector: selector,
	}
}

func (p *DOMQuerySelectorAllParams) CDPMethodName() string {
	return "DOM.querySelectorAll"
}

// Returns NodeIds of current top layer elements.
// Top layer is rendered closest to the user within a viewport, therefore its elements always
// appear on top of all other content.
type DOMGetTopLayerElementsParams struct {
}

type DOMGetTopLayerElementsReturns struct {
	// NodeIds of top layer elements
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMGetTopLayerElements() *DOMGetTopLayerElementsParams {
	return &DOMGetTopLayerElementsParams{}
}

func (p *DOMGetTopLayerElementsParams) CDPMethodName() string {
	return "DOM.getTopLayerElements"
}

// Returns the NodeId of the matched element according to certain relations.
type DOMGetElementByRelationParams struct {
	// Id of the node from which to query the relation.
	NodeId DOMNodeId `json:"nodeId"`
	// Type of relation to get.
	Relation string `json:"relation"`
}

type DOMGetElementByRelationReturns struct {
	// NodeId of the element matching the queried relation.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMGetElementByRelation(nodeId DOMNodeId, relation string) *DOMGetElementByRelationParams {
	return &DOMGetElementByRelationParams{
		NodeId:   nodeId,
		Relation: relation,
	}
}

func (p *DOMGetElementByRelationParams) CDPMethodName() string {
	return "DOM.getElementByRelation"
}

// Re-does the last undone action.
type DOMRedoParams struct {
}

func DOMRedo() *DOMRedoParams {
	return &DOMRedoParams{}
}

func (p *DOMRedoParams) CDPMethodName() string {
	return "DOM.redo"
}

// Removes attribute with given name from an element with given id.
type DOMRemoveAttributeParams struct {
	// Id of the element to remove attribute from.
	NodeId DOMNodeId `json:"nodeId"`
	// Name of the attribute to remove.
	Name string `json:"name"`
}

func DOMRemoveAttribute(nodeId DOMNodeId, name string) *DOMRemoveAttributeParams {
	return &DOMRemoveAttributeParams{
		NodeId: nodeId,
		Name:   name,
	}
}

func (p *DOMRemoveAttributeParams) CDPMethodName() string {
	return "DOM.removeAttribute"
}

// Removes node with given id.
type DOMRemoveNodeParams struct {
	// Id of the node to remove.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMRemoveNode(nodeId DOMNodeId) *DOMRemoveNodeParams {
	return &DOMRemoveNodeParams{
		NodeId: nodeId,
	}
}

func (p *DOMRemoveNodeParams) CDPMethodName() string {
	return "DOM.removeNode"
}

// Requests that children of the node with given id are returned to the caller in form of
// `setChildNodes` events where not only immediate children are retrieved, but all children down to
// the specified depth.
type DOMRequestChildNodesParams struct {
	// Id of the node to get children for.
	NodeId DOMNodeId `json:"nodeId"`
	// The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the
	// entire subtree or provide an integer larger than 0.
	Depth *int64 `json:"depth,omitempty"`
	// Whether or not iframes and shadow roots should be traversed when returning the sub-tree
	// (default is false).
	Pierce *bool `json:"pierce,omitempty"`
}

func DOMRequestChildNodes(nodeId DOMNodeId) *DOMRequestChildNodesParams {
	return &DOMRequestChildNodesParams{
		NodeId: nodeId,
	}
}

func (p *DOMRequestChildNodesParams) WithDepth(v int64) *DOMRequestChildNodesParams {
	p.Depth = &v
	return p
}

func (p *DOMRequestChildNodesParams) WithPierce(v bool) *DOMRequestChildNodesParams {
	p.Pierce = &v
	return p
}

func (p *DOMRequestChildNodesParams) CDPMethodName() string {
	return "DOM.requestChildNodes"
}

// Requests that the node is sent to the caller given the JavaScript node object reference. All
// nodes that form the path from the node to the root are also sent to the client as a series of
// `setChildNodes` notifications.
type DOMRequestNodeParams struct {
	// JavaScript object id to convert into node.
	ObjectId RuntimeRemoteObjectId `json:"objectId"`
}

type DOMRequestNodeReturns struct {
	// Node id for given object.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMRequestNode(objectId RuntimeRemoteObjectId) *DOMRequestNodeParams {
	return &DOMRequestNodeParams{
		ObjectId: objectId,
	}
}

func (p *DOMRequestNodeParams) CDPMethodName() string {
	return "DOM.requestNode"
}

// Resolves the JavaScript node object for a given NodeId or BackendNodeId.
type DOMResolveNodeParams struct {
	// Id of the node to resolve.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Backend identifier of the node to resolve.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// Symbolic group name that can be used to release multiple objects.
	ObjectGroup *string `json:"objectGroup,omitempty"`
	// Execution context in which to resolve the node.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
}

type DOMResolveNodeReturns struct {
	// JavaScript object wrapper for given node.
	Object RuntimeRemoteObject `json:"object"`
}

func DOMResolveNode() *DOMResolveNodeParams {
	return &DOMResolveNodeParams{}
}

func (p *DOMResolveNodeParams) WithNodeId(v DOMNodeId) *DOMResolveNodeParams {
	p.NodeId = &v
	return p
}

func (p *DOMResolveNodeParams) WithBackendNodeId(v DOMBackendNodeId) *DOMResolveNodeParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMResolveNodeParams) WithObjectGroup(v string) *DOMResolveNodeParams {
	p.ObjectGroup = &v
	return p
}

func (p *DOMResolveNodeParams) WithExecutionContextId(v RuntimeExecutionContextId) *DOMResolveNodeParams {
	p.ExecutionContextId = &v
	return p
}

func (p *DOMResolveNodeParams) CDPMethodName() string {
	return "DOM.resolveNode"
}

// Sets attribute for an element with given id.
type DOMSetAttributeValueParams struct {
	// Id of the element to set attribute for.
	NodeId DOMNodeId `json:"nodeId"`
	// Attribute name.
	Name string `json:"name"`
	// Attribute value.
	Value string `json:"value"`
}

func DOMSetAttributeValue(nodeId DOMNodeId, name string, value string) *DOMSetAttributeValueParams {
	return &DOMSetAttributeValueParams{
		NodeId: nodeId,
		Name:   name,
		Value:  value,
	}
}

func (p *DOMSetAttributeValueParams) CDPMethodName() string {
	return "DOM.setAttributeValue"
}

// Sets attributes on element with given id. This method is useful when user edits some existing
// attribute value and types in several attribute name/value pairs.
type DOMSetAttributesAsTextParams struct {
	// Id of the element to set attributes for.
	NodeId DOMNodeId `json:"nodeId"`
	// Text with a number of attributes. Will parse this text using HTML parser.
	Text string `json:"text"`
	// Attribute name to replace with new attributes derived from text in case text parsed
	// successfully.
	Name *string `json:"name,omitempty"`
}

func DOMSetAttributesAsText(nodeId DOMNodeId, text string) *DOMSetAttributesAsTextParams {
	return &DOMSetAttributesAsTextParams{
		NodeId: nodeId,
		Text:   text,
	}
}

func (p *DOMSetAttributesAsTextParams) WithName(v string) *DOMSetAttributesAsTextParams {
	p.Name = &v
	return p
}

func (p *DOMSetAttributesAsTextParams) CDPMethodName() string {
	return "DOM.setAttributesAsText"
}

// Sets files for the given file input element.
type DOMSetFileInputFilesParams struct {
	// Array of file paths to set.
	Files []string `json:"files"`
	// Identifier of the node.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node wrapper.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

func DOMSetFileInputFiles(files []string) *DOMSetFileInputFilesParams {
	return &DOMSetFileInputFilesParams{
		Files: files,
	}
}

func (p *DOMSetFileInputFilesParams) WithNodeId(v DOMNodeId) *DOMSetFileInputFilesParams {
	p.NodeId = &v
	return p
}

func (p *DOMSetFileInputFilesParams) WithBackendNodeId(v DOMBackendNodeId) *DOMSetFileInputFilesParams {
	p.BackendNodeId = &v
	return p
}

func (p *DOMSetFileInputFilesParams) WithObjectId(v RuntimeRemoteObjectId) *DOMSetFileInputFilesParams {
	p.ObjectId = &v
	return p
}

func (p *DOMSetFileInputFilesParams) CDPMethodName() string {
	return "DOM.setFileInputFiles"
}

// Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled.
type DOMSetNodeStackTracesEnabledParams struct {
	// Enable or disable.
	Enable bool `json:"enable"`
}

func DOMSetNodeStackTracesEnabled(enable bool) *DOMSetNodeStackTracesEnabledParams {
	return &DOMSetNodeStackTracesEnabledParams{
		Enable: enable,
	}
}

func (p *DOMSetNodeStackTracesEnabledParams) CDPMethodName() string {
	return "DOM.setNodeStackTracesEnabled"
}

// Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation.
type DOMGetNodeStackTracesParams struct {
	// Id of the node to get stack traces for.
	NodeId DOMNodeId `json:"nodeId"`
}

type DOMGetNodeStackTracesReturns struct {
	// Creation stack trace, if available.
	Creation *RuntimeStackTrace `json:"creation,omitempty"`
}

func DOMGetNodeStackTraces(nodeId DOMNodeId) *DOMGetNodeStackTracesParams {
	return &DOMGetNodeStackTracesParams{
		NodeId: nodeId,
	}
}

func (p *DOMGetNodeStackTracesParams) CDPMethodName() string {
	return "DOM.getNodeStackTraces"
}

// Returns file information for the given
// File wrapper.
type DOMGetFileInfoParams struct {
	// JavaScript object id of the node wrapper.
	ObjectId RuntimeRemoteObjectId `json:"objectId"`
}

type DOMGetFileInfoReturns struct {
	Path string `json:"path"`
}

func DOMGetFileInfo(objectId RuntimeRemoteObjectId) *DOMGetFileInfoParams {
	return &DOMGetFileInfoParams{
		ObjectId: objectId,
	}
}

func (p *DOMGetFileInfoParams) CDPMethodName() string {
	return "DOM.getFileInfo"
}

// Returns list of detached nodes
type DOMGetDetachedDomNodesParams struct {
}

type DOMGetDetachedDomNodesReturns struct {
	// The list of detached nodes
	DetachedNodes []DOMDetachedElementInfo `json:"detachedNodes"`
}

func DOMGetDetachedDomNodes() *DOMGetDetachedDomNodesParams {
	return &DOMGetDetachedDomNodesParams{}
}

func (p *DOMGetDetachedDomNodesParams) CDPMethodName() string {
	return "DOM.getDetachedDomNodes"
}

// Enables console to refer to the node with given id via $x (see Command Line API for more details
// $x functions).
type DOMSetInspectedNodeParams struct {
	// DOM node id to be accessible by means of $x command line API.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMSetInspectedNode(nodeId DOMNodeId) *DOMSetInspectedNodeParams {
	return &DOMSetInspectedNodeParams{
		NodeId: nodeId,
	}
}

func (p *DOMSetInspectedNodeParams) CDPMethodName() string {
	return "DOM.setInspectedNode"
}

// Sets node name for a node with given id.
type DOMSetNodeNameParams struct {
	// Id of the node to set name for.
	NodeId DOMNodeId `json:"nodeId"`
	// New node's name.
	Name string `json:"name"`
}

type DOMSetNodeNameReturns struct {
	// New node's id.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMSetNodeName(nodeId DOMNodeId, name string) *DOMSetNodeNameParams {
	return &DOMSetNodeNameParams{
		NodeId: nodeId,
		Name:   name,
	}
}

func (p *DOMSetNodeNameParams) CDPMethodName() string {
	return "DOM.setNodeName"
}

// Sets node value for a node with given id.
type DOMSetNodeValueParams struct {
	// Id of the node to set value for.
	NodeId DOMNodeId `json:"nodeId"`
	// New node's value.
	Value string `json:"value"`
}

func DOMSetNodeValue(nodeId DOMNodeId, value string) *DOMSetNodeValueParams {
	return &DOMSetNodeValueParams{
		NodeId: nodeId,
		Value:  value,
	}
}

func (p *DOMSetNodeValueParams) CDPMethodName() string {
	return "DOM.setNodeValue"
}

// Sets node HTML markup, returns new node id.
type DOMSetOuterHTMLParams struct {
	// Id of the node to set markup for.
	NodeId DOMNodeId `json:"nodeId"`
	// Outer HTML markup to set.
	OuterHTML string `json:"outerHTML"`
}

func DOMSetOuterHTML(nodeId DOMNodeId, outerHTML string) *DOMSetOuterHTMLParams {
	return &DOMSetOuterHTMLParams{
		NodeId:    nodeId,
		OuterHTML: outerHTML,
	}
}

func (p *DOMSetOuterHTMLParams) CDPMethodName() string {
	return "DOM.setOuterHTML"
}

// Undoes the last performed action.
type DOMUndoParams struct {
}

func DOMUndo() *DOMUndoParams {
	return &DOMUndoParams{}
}

func (p *DOMUndoParams) CDPMethodName() string {
	return "DOM.undo"
}

// Returns iframe node that owns iframe with the given domain.
type DOMGetFrameOwnerParams struct {
	FrameId PageFrameId `json:"frameId"`
}

type DOMGetFrameOwnerReturns struct {
	// Resulting node.
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
	// Id of the node at given coordinates, only when enabled and requested document.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
}

func DOMGetFrameOwner(frameId PageFrameId) *DOMGetFrameOwnerParams {
	return &DOMGetFrameOwnerParams{
		FrameId: frameId,
	}
}

func (p *DOMGetFrameOwnerParams) CDPMethodName() string {
	return "DOM.getFrameOwner"
}

// Returns the query container of the given node based on container query
// conditions: containerName, physical and logical axes, and whether it queries
// scroll-state or anchored elements. If no axes are provided and
// queriesScrollState is false, the style container is returned, which is the
// direct parent or the closest element with a matching container-name.
type DOMGetContainerForNodeParams struct {
	NodeId             DOMNodeId        `json:"nodeId"`
	ContainerName      *string          `json:"containerName,omitempty"`
	PhysicalAxes       *DOMPhysicalAxes `json:"physicalAxes,omitempty"`
	LogicalAxes        *DOMLogicalAxes  `json:"logicalAxes,omitempty"`
	QueriesScrollState *bool            `json:"queriesScrollState,omitempty"`
	QueriesAnchored    *bool            `json:"queriesAnchored,omitempty"`
}

type DOMGetContainerForNodeReturns struct {
	// The container node for the given node, or null if not found.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
}

func DOMGetContainerForNode(nodeId DOMNodeId) *DOMGetContainerForNodeParams {
	return &DOMGetContainerForNodeParams{
		NodeId: nodeId,
	}
}

func (p *DOMGetContainerForNodeParams) WithContainerName(v string) *DOMGetContainerForNodeParams {
	p.ContainerName = &v
	return p
}

func (p *DOMGetContainerForNodeParams) WithPhysicalAxes(v DOMPhysicalAxes) *DOMGetContainerForNodeParams {
	p.PhysicalAxes = &v
	return p
}

func (p *DOMGetContainerForNodeParams) WithLogicalAxes(v DOMLogicalAxes) *DOMGetContainerForNodeParams {
	p.LogicalAxes = &v
	return p
}

func (p *DOMGetContainerForNodeParams) WithQueriesScrollState(v bool) *DOMGetContainerForNodeParams {
	p.QueriesScrollState = &v
	return p
}

func (p *DOMGetContainerForNodeParams) WithQueriesAnchored(v bool) *DOMGetContainerForNodeParams {
	p.QueriesAnchored = &v
	return p
}

func (p *DOMGetContainerForNodeParams) CDPMethodName() string {
	return "DOM.getContainerForNode"
}

// Returns the descendants of a container query container that have
// container queries against this container.
type DOMGetQueryingDescendantsForContainerParams struct {
	// Id of the container node to find querying descendants from.
	NodeId DOMNodeId `json:"nodeId"`
}

type DOMGetQueryingDescendantsForContainerReturns struct {
	// Descendant nodes with container queries against the given container.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMGetQueryingDescendantsForContainer(nodeId DOMNodeId) *DOMGetQueryingDescendantsForContainerParams {
	return &DOMGetQueryingDescendantsForContainerParams{
		NodeId: nodeId,
	}
}

func (p *DOMGetQueryingDescendantsForContainerParams) CDPMethodName() string {
	return "DOM.getQueryingDescendantsForContainer"
}

// Returns the target anchor element of the given anchor query according to
// https://www.w3.org/TR/css-anchor-position-1/#target.
type DOMGetAnchorElementParams struct {
	// Id of the positioned element from which to find the anchor.
	NodeId DOMNodeId `json:"nodeId"`
	// An optional anchor specifier, as defined in
	// https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier.
	// If not provided, it will return the implicit anchor element for
	// the given positioned element.
	AnchorSpecifier *string `json:"anchorSpecifier,omitempty"`
}

type DOMGetAnchorElementReturns struct {
	// The anchor element of the given anchor query.
	NodeId DOMNodeId `json:"nodeId"`
}

func DOMGetAnchorElement(nodeId DOMNodeId) *DOMGetAnchorElementParams {
	return &DOMGetAnchorElementParams{
		NodeId: nodeId,
	}
}

func (p *DOMGetAnchorElementParams) WithAnchorSpecifier(v string) *DOMGetAnchorElementParams {
	p.AnchorSpecifier = &v
	return p
}

func (p *DOMGetAnchorElementParams) CDPMethodName() string {
	return "DOM.getAnchorElement"
}

// When enabling, this API force-opens the popover identified by nodeId
// and keeps it open until disabled.
type DOMForceShowPopoverParams struct {
	// Id of the popover HTMLElement
	NodeId DOMNodeId `json:"nodeId"`
	// If true, opens the popover and keeps it open. If false, closes the
	// popover if it was previously force-opened.
	Enable bool `json:"enable"`
}

type DOMForceShowPopoverReturns struct {
	// List of popovers that were closed in order to respect popover stacking order.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func DOMForceShowPopover(nodeId DOMNodeId, enable bool) *DOMForceShowPopoverParams {
	return &DOMForceShowPopoverParams{
		NodeId: nodeId,
		Enable: enable,
	}
}

func (p *DOMForceShowPopoverParams) CDPMethodName() string {
	return "DOM.forceShowPopover"
}

// Fired when `Element`'s attribute is modified.
const EventDOMAttributeModified = "DOM.attributeModified"

type DOMAttributeModifiedEvent struct {
	// Id of the node that has changed.
	NodeId DOMNodeId `json:"nodeId"`
	// Attribute name.
	Name string `json:"name"`
	// Attribute value.
	Value string `json:"value"`
}

func (e *DOMAttributeModifiedEvent) CDPEventName() string {
	return EventDOMAttributeModified
}

// Fired when `Element`'s adoptedStyleSheets are modified.
const EventDOMAdoptedStyleSheetsModified = "DOM.adoptedStyleSheetsModified"

type DOMAdoptedStyleSheetsModifiedEvent struct {
	// Id of the node that has changed.
	NodeId DOMNodeId `json:"nodeId"`
	// New adoptedStyleSheets array.
	AdoptedStyleSheets []DOMStyleSheetId `json:"adoptedStyleSheets"`
}

func (e *DOMAdoptedStyleSheetsModifiedEvent) CDPEventName() string {
	return EventDOMAdoptedStyleSheetsModified
}

// Fired when `Element`'s attribute is removed.
const EventDOMAttributeRemoved = "DOM.attributeRemoved"

type DOMAttributeRemovedEvent struct {
	// Id of the node that has changed.
	NodeId DOMNodeId `json:"nodeId"`
	// A ttribute name.
	Name string `json:"name"`
}

func (e *DOMAttributeRemovedEvent) CDPEventName() string {
	return EventDOMAttributeRemoved
}

// Mirrors `DOMCharacterDataModified` event.
const EventDOMCharacterDataModified = "DOM.characterDataModified"

type DOMCharacterDataModifiedEvent struct {
	// Id of the node that has changed.
	NodeId DOMNodeId `json:"nodeId"`
	// New text value.
	CharacterData string `json:"characterData"`
}

func (e *DOMCharacterDataModifiedEvent) CDPEventName() string {
	return EventDOMCharacterDataModified
}

// Fired when `Container`'s child node count has changed.
const EventDOMChildNodeCountUpdated = "DOM.childNodeCountUpdated"

type DOMChildNodeCountUpdatedEvent struct {
	// Id of the node that has changed.
	NodeId DOMNodeId `json:"nodeId"`
	// New node count.
	ChildNodeCount int64 `json:"childNodeCount"`
}

func (e *DOMChildNodeCountUpdatedEvent) CDPEventName() string {
	return EventDOMChildNodeCountUpdated
}

// Mirrors `DOMNodeInserted` event.
const EventDOMChildNodeInserted = "DOM.childNodeInserted"

type DOMChildNodeInsertedEvent struct {
	// Id of the node that has changed.
	ParentNodeId DOMNodeId `json:"parentNodeId"`
	// Id of the previous sibling.
	PreviousNodeId DOMNodeId `json:"previousNodeId"`
	// Inserted node data.
	Node DOMNode `json:"node"`
}

func (e *DOMChildNodeInsertedEvent) CDPEventName() string {
	return EventDOMChildNodeInserted
}

// Mirrors `DOMNodeRemoved` event.
const EventDOMChildNodeRemoved = "DOM.childNodeRemoved"

type DOMChildNodeRemovedEvent struct {
	// Parent id.
	ParentNodeId DOMNodeId `json:"parentNodeId"`
	// Id of the node that has been removed.
	NodeId DOMNodeId `json:"nodeId"`
}

func (e *DOMChildNodeRemovedEvent) CDPEventName() string {
	return EventDOMChildNodeRemoved
}

// Called when distribution is changed.
const EventDOMDistributedNodesUpdated = "DOM.distributedNodesUpdated"

type DOMDistributedNodesUpdatedEvent struct {
	// Insertion point where distributed nodes were updated.
	InsertionPointId DOMNodeId `json:"insertionPointId"`
	// Distributed nodes for given insertion point.
	DistributedNodes []DOMBackendNode `json:"distributedNodes"`
}

func (e *DOMDistributedNodesUpdatedEvent) CDPEventName() string {
	return EventDOMDistributedNodesUpdated
}

// Fired when `Document` has been totally updated. Node ids are no longer valid.
const EventDOMDocumentUpdated = "DOM.documentUpdated"

type DOMDocumentUpdatedEvent struct {
}

func (e *DOMDocumentUpdatedEvent) CDPEventName() string {
	return EventDOMDocumentUpdated
}

// Fired when `Element`'s inline style is modified via a CSS property modification.
const EventDOMInlineStyleInvalidated = "DOM.inlineStyleInvalidated"

type DOMInlineStyleInvalidatedEvent struct {
	// Ids of the nodes for which the inline styles have been invalidated.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

func (e *DOMInlineStyleInvalidatedEvent) CDPEventName() string {
	return EventDOMInlineStyleInvalidated
}

// Called when a pseudo element is added to an element.
const EventDOMPseudoElementAdded = "DOM.pseudoElementAdded"

type DOMPseudoElementAddedEvent struct {
	// Pseudo element's parent element id.
	ParentId DOMNodeId `json:"parentId"`
	// The added pseudo element.
	PseudoElement DOMNode `json:"pseudoElement"`
}

func (e *DOMPseudoElementAddedEvent) CDPEventName() string {
	return EventDOMPseudoElementAdded
}

// Called when top layer elements are changed.
const EventDOMTopLayerElementsUpdated = "DOM.topLayerElementsUpdated"

type DOMTopLayerElementsUpdatedEvent struct {
}

func (e *DOMTopLayerElementsUpdatedEvent) CDPEventName() string {
	return EventDOMTopLayerElementsUpdated
}

// Fired when a node's scrollability state changes.
const EventDOMScrollableFlagUpdated = "DOM.scrollableFlagUpdated"

type DOMScrollableFlagUpdatedEvent struct {
	// The id of the node.
	NodeId DOMNodeId `json:"nodeId"`
	// If the node is scrollable.
	IsScrollable bool `json:"isScrollable"`
}

func (e *DOMScrollableFlagUpdatedEvent) CDPEventName() string {
	return EventDOMScrollableFlagUpdated
}

// Fired when a node's ad related state changes.
const EventDOMAdRelatedStateUpdated = "DOM.adRelatedStateUpdated"

type DOMAdRelatedStateUpdatedEvent struct {
	// The id of the node.
	NodeId DOMNodeId `json:"nodeId"`
	// The provenance of the ad related node, if it is ad related.
	AdProvenance *NetworkAdProvenance `json:"adProvenance,omitempty"`
}

func (e *DOMAdRelatedStateUpdatedEvent) CDPEventName() string {
	return EventDOMAdRelatedStateUpdated
}

// Fired when a node's starting styles changes.
const EventDOMAffectedByStartingStylesFlagUpdated = "DOM.affectedByStartingStylesFlagUpdated"

type DOMAffectedByStartingStylesFlagUpdatedEvent struct {
	// The id of the node.
	NodeId DOMNodeId `json:"nodeId"`
	// If the node has starting styles.
	AffectedByStartingStyles bool `json:"affectedByStartingStyles"`
}

func (e *DOMAffectedByStartingStylesFlagUpdatedEvent) CDPEventName() string {
	return EventDOMAffectedByStartingStylesFlagUpdated
}

// Called when a pseudo element is removed from an element.
const EventDOMPseudoElementRemoved = "DOM.pseudoElementRemoved"

type DOMPseudoElementRemovedEvent struct {
	// Pseudo element's parent element id.
	ParentId DOMNodeId `json:"parentId"`
	// The removed pseudo element id.
	PseudoElementId DOMNodeId `json:"pseudoElementId"`
}

func (e *DOMPseudoElementRemovedEvent) CDPEventName() string {
	return EventDOMPseudoElementRemoved
}

// Fired when backend wants to provide client with the missing DOM structure. This happens upon
// most of the calls requesting node ids.
const EventDOMSetChildNodes = "DOM.setChildNodes"

type DOMSetChildNodesEvent struct {
	// Parent node id to populate with children.
	ParentId DOMNodeId `json:"parentId"`
	// Child nodes array.
	Nodes []DOMNode `json:"nodes"`
}

func (e *DOMSetChildNodesEvent) CDPEventName() string {
	return EventDOMSetChildNodes
}

// Called when shadow root is popped from the element.
const EventDOMShadowRootPopped = "DOM.shadowRootPopped"

type DOMShadowRootPoppedEvent struct {
	// Host element id.
	HostId DOMNodeId `json:"hostId"`
	// Shadow root id.
	RootId DOMNodeId `json:"rootId"`
}

func (e *DOMShadowRootPoppedEvent) CDPEventName() string {
	return EventDOMShadowRootPopped
}

// Called when shadow root is pushed into the element.
const EventDOMShadowRootPushed = "DOM.shadowRootPushed"

type DOMShadowRootPushedEvent struct {
	// Host element id.
	HostId DOMNodeId `json:"hostId"`
	// Shadow root.
	Root DOMNode `json:"root"`
}

func (e *DOMShadowRootPushedEvent) CDPEventName() string {
	return EventDOMShadowRootPushed
}
