// Code generated by cdpgen; DO NOT EDIT.

package cdp

type DOMStorageSerializedStorageKey string

// DOM Storage identifier.
type DOMStorageStorageId struct {
	// Security origin for the storage.
	SecurityOrigin *string `json:"securityOrigin,omitempty"`
	// Represents a key by which DOM Storage keys its CachedStorageAreas
	StorageKey *DOMStorageSerializedStorageKey `json:"storageKey,omitempty"`
	// Whether the storage is local storage (not session storage).
	IsLocalStorage bool `json:"isLocalStorage"`
}

// DOM Storage item.
type DOMStorageItem []string

type DOMStorageClearParams struct {
	StorageId DOMStorageStorageId `json:"storageId"`
}

func DOMStorageClear(storageId DOMStorageStorageId) *DOMStorageClearParams {
	return &DOMStorageClearParams{
		StorageId: storageId,
	}
}

func (p *DOMStorageClearParams) CDPMethodName() string {
	return "DOMStorage.clear"
}

// Disables storage tracking, prevents storage events from being sent to the client.
type DOMStorageDisableParams struct {
}

func DOMStorageDisable() *DOMStorageDisableParams {
	return &DOMStorageDisableParams{}
}

func (p *DOMStorageDisableParams) CDPMethodName() string {
	return "DOMStorage.disable"
}

// Enables storage tracking, storage events will now be delivered to the client.
type DOMStorageEnableParams struct {
}

func DOMStorageEnable() *DOMStorageEnableParams {
	return &DOMStorageEnableParams{}
}

func (p *DOMStorageEnableParams) CDPMethodName() string {
	return "DOMStorage.enable"
}

type DOMStorageGetDOMStorageItemsParams struct {
	StorageId DOMStorageStorageId `json:"storageId"`
}

type DOMStorageGetDOMStorageItemsReturns struct {
	Entries []DOMStorageItem `json:"entries"`
}

func DOMStorageGetDOMStorageItems(storageId DOMStorageStorageId) *DOMStorageGetDOMStorageItemsParams {
	return &DOMStorageGetDOMStorageItemsParams{
		StorageId: storageId,
	}
}

func (p *DOMStorageGetDOMStorageItemsParams) CDPMethodName() string {
	return "DOMStorage.getDOMStorageItems"
}

type DOMStorageRemoveDOMStorageItemParams struct {
	StorageId DOMStorageStorageId `json:"storageId"`
	Key       string              `json:"key"`
}

func DOMStorageRemoveDOMStorageItem(storageId DOMStorageStorageId, key string) *DOMStorageRemoveDOMStorageItemParams {
	return &DOMStorageRemoveDOMStorageItemParams{
		StorageId: storageId,
		Key:       key,
	}
}

func (p *DOMStorageRemoveDOMStorageItemParams) CDPMethodName() string {
	return "DOMStorage.removeDOMStorageItem"
}

type DOMStorageSetDOMStorageItemParams struct {
	StorageId DOMStorageStorageId `json:"storageId"`
	Key       string              `json:"key"`
	Value     string              `json:"value"`
}

func DOMStorageSetDOMStorageItem(storageId DOMStorageStorageId, key string, value string) *DOMStorageSetDOMStorageItemParams {
	return &DOMStorageSetDOMStorageItemParams{
		StorageId: storageId,
		Key:       key,
		Value:     value,
	}
}

func (p *DOMStorageSetDOMStorageItemParams) CDPMethodName() string {
	return "DOMStorage.setDOMStorageItem"
}

const EventDOMStorageDomStorageItemAdded = "DOMStorage.domStorageItemAdded"

type DOMStorageDomStorageItemAddedEvent struct {
	StorageId DOMStorageStorageId `json:"storageId"`
	Key       string              `json:"key"`
	NewValue  string              `json:"newValue"`
}

func (e *DOMStorageDomStorageItemAddedEvent) CDPEventName() string {
	return EventDOMStorageDomStorageItemAdded
}

const EventDOMStorageDomStorageItemRemoved = "DOMStorage.domStorageItemRemoved"

type DOMStorageDomStorageItemRemovedEvent struct {
	StorageId DOMStorageStorageId `json:"storageId"`
	Key       string              `json:"key"`
}

func (e *DOMStorageDomStorageItemRemovedEvent) CDPEventName() string {
	return EventDOMStorageDomStorageItemRemoved
}

const EventDOMStorageDomStorageItemUpdated = "DOMStorage.domStorageItemUpdated"

type DOMStorageDomStorageItemUpdatedEvent struct {
	StorageId DOMStorageStorageId `json:"storageId"`
	Key       string              `json:"key"`
	OldValue  string              `json:"oldValue"`
	NewValue  string              `json:"newValue"`
}

func (e *DOMStorageDomStorageItemUpdatedEvent) CDPEventName() string {
	return EventDOMStorageDomStorageItemUpdated
}

const EventDOMStorageDomStorageItemsCleared = "DOMStorage.domStorageItemsCleared"

type DOMStorageDomStorageItemsClearedEvent struct {
	StorageId DOMStorageStorageId `json:"storageId"`
}

func (e *DOMStorageDomStorageItemsClearedEvent) CDPEventName() string {
	return EventDOMStorageDomStorageItemsCleared
}
