// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Sets breakpoint on particular native event.
type EventBreakpointsSetInstrumentationBreakpointParams struct {
	// Instrumentation name to stop on.
	EventName string `json:"eventName"`
}

func EventBreakpointsSetInstrumentationBreakpoint(eventName string) *EventBreakpointsSetInstrumentationBreakpointParams {
	return &EventBreakpointsSetInstrumentationBreakpointParams{
		EventName: eventName,
	}
}

func (p *EventBreakpointsSetInstrumentationBreakpointParams) CDPMethodName() string {
	return "EventBreakpoints.setInstrumentationBreakpoint"
}

// Removes breakpoint on particular native event.
type EventBreakpointsRemoveInstrumentationBreakpointParams struct {
	// Instrumentation name to stop on.
	EventName string `json:"eventName"`
}

func EventBreakpointsRemoveInstrumentationBreakpoint(eventName string) *EventBreakpointsRemoveInstrumentationBreakpointParams {
	return &EventBreakpointsRemoveInstrumentationBreakpointParams{
		EventName: eventName,
	}
}

func (p *EventBreakpointsRemoveInstrumentationBreakpointParams) CDPMethodName() string {
	return "EventBreakpoints.removeInstrumentationBreakpoint"
}

// Removes all breakpoints
type EventBreakpointsDisableParams struct {
}

func EventBreakpointsDisable() *EventBreakpointsDisableParams {
	return &EventBreakpointsDisableParams{}
}

func (p *EventBreakpointsDisableParams) CDPMethodName() string {
	return "EventBreakpoints.disable"
}
