// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Unique request identifier.
// Note that this does not identify individual HTTP requests that are part of
// a network request.
type FetchRequestId string

// Stages of the request to handle. Request will intercept before the request is
// sent. Response will intercept after the response is received (but before response
// body is received).
type FetchRequestStage string

const (
	FetchRequestStageRequest  FetchRequestStage = "Request"
	FetchRequestStageResponse FetchRequestStage = "Response"
)

type FetchRequestPattern struct {
	// Wildcards (`'*'` -> zero or more, `'?'` -> exactly one) are allowed. Escape character is
	// backslash. Omitting is equivalent to `"*"`.
	UrlPattern *string `json:"urlPattern,omitempty"`
	// If set, only requests for matching resource types will be intercepted.
	ResourceType *NetworkResourceType `json:"resourceType,omitempty"`
	// Stage at which to begin intercepting requests. Default is Request.
	RequestStage *FetchRequestStage `json:"requestStage,omitempty"`
}

// Response HTTP header entry
type FetchHeaderEntry struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Authorization challenge for HTTP status code 401 or 407.
type FetchAuthChallenge struct {
	// Source of the authentication challenge.
	Source *string `json:"source,omitempty"`
	// Origin of the challenger.
	Origin string `json:"origin"`
	// The authentication scheme used, such as basic or digest
	Scheme string `json:"scheme"`
	// The realm of the challenge. May be empty.
	Realm string `json:"realm"`
}

// Response to an AuthChallenge.
type FetchAuthChallengeResponse struct {
	// The decision on what to do in response to the authorization challenge.  Default means
	// deferring to the default behavior of the net stack, which will likely either the Cancel
	// authentication or display a popup dialog box.
	Response string `json:"response"`
	// The username to provide, possibly empty. Should only be set if response is
	// ProvideCredentials.
	Username *string `json:"username,omitempty"`
	// The password to provide, possibly empty. Should only be set if response is
	// ProvideCredentials.
	Password *string `json:"password,omitempty"`
}

// Disables the fetch domain.
type FetchDisableParams struct {
}

func FetchDisable() *FetchDisableParams {
	return &FetchDisableParams{}
}

func (p *FetchDisableParams) CDPMethodName() string {
	return "Fetch.disable"
}

// Enables issuing of requestPaused events. A request will be paused until client
// calls one of failRequest, fulfillRequest or continueRequest/continueWithAuth.
type FetchEnableParams struct {
	// If specified, only requests matching any of these patterns will produce
	// fetchRequested event and will be paused until clients response. If not set,
	// all requests will be affected.
	Patterns []FetchRequestPattern `json:"patterns,omitempty"`
	// If true, authRequired events will be issued and requests will be paused
	// expecting a call to continueWithAuth.
	HandleAuthRequests *bool `json:"handleAuthRequests,omitempty"`
}

func FetchEnable() *FetchEnableParams {
	return &FetchEnableParams{}
}

func (p *FetchEnableParams) WithPatterns(v []FetchRequestPattern) *FetchEnableParams {
	p.Patterns = v
	return p
}

func (p *FetchEnableParams) WithHandleAuthRequests(v bool) *FetchEnableParams {
	p.HandleAuthRequests = &v
	return p
}

func (p *FetchEnableParams) CDPMethodName() string {
	return "Fetch.enable"
}

// Causes the request to fail with specified reason.
type FetchFailRequestParams struct {
	// An id the client received in requestPaused event.
	RequestId FetchRequestId `json:"requestId"`
	// Causes the request to fail with the given reason.
	ErrorReason NetworkErrorReason `json:"errorReason"`
}

func FetchFailRequest(requestId FetchRequestId, errorReason NetworkErrorReason) *FetchFailRequestParams {
	return &FetchFailRequestParams{
		RequestId:   requestId,
		ErrorReason: errorReason,
	}
}

func (p *FetchFailRequestParams) CDPMethodName() string {
	return "Fetch.failRequest"
}

// Provides response to the request.
type FetchFulfillRequestParams struct {
	// An id the client received in requestPaused event.
	RequestId FetchRequestId `json:"requestId"`
	// An HTTP response code.
	ResponseCode int64 `json:"responseCode"`
	// Response headers.
	ResponseHeaders []FetchHeaderEntry `json:"responseHeaders,omitempty"`
	// Alternative way of specifying response headers as a \0-separated
	// series of name: value pairs. Prefer the above method unless you
	// need to represent some non-UTF8 values that can't be transmitted
	// over the protocol as text. (Encoded as a base64 string when passed over JSON)
	BinaryResponseHeaders *string `json:"binaryResponseHeaders,omitempty"`
	// A response body. If absent, original response body will be used if
	// the request is intercepted at the response stage and empty body
	// will be used if the request is intercepted at the request stage. (Encoded as a base64 string when passed over JSON)
	Body *string `json:"body,omitempty"`
	// A textual representation of responseCode.
	// If absent, a standard phrase matching responseCode is used.
	ResponsePhrase *string `json:"responsePhrase,omitempty"`
}

func FetchFulfillRequest(requestId FetchRequestId, responseCode int64) *FetchFulfillRequestParams {
	return &FetchFulfillRequestParams{
		RequestId:    requestId,
		ResponseCode: responseCode,
	}
}

func (p *FetchFulfillRequestParams) WithResponseHeaders(v []FetchHeaderEntry) *FetchFulfillRequestParams {
	p.ResponseHeaders = v
	return p
}

func (p *FetchFulfillRequestParams) WithBinaryResponseHeaders(v string) *FetchFulfillRequestParams {
	p.BinaryResponseHeaders = &v
	return p
}

func (p *FetchFulfillRequestParams) WithBody(v string) *FetchFulfillRequestParams {
	p.Body = &v
	return p
}

func (p *FetchFulfillRequestParams) WithResponsePhrase(v string) *FetchFulfillRequestParams {
	p.ResponsePhrase = &v
	return p
}

func (p *FetchFulfillRequestParams) CDPMethodName() string {
	return "Fetch.fulfillRequest"
}

// Continues the request, optionally modifying some of its parameters.
type FetchContinueRequestParams struct {
	// An id the client received in requestPaused event.
	RequestId FetchRequestId `json:"requestId"`
	// If set, the request url will be modified in a way that's not observable by page.
	Url *string `json:"url,omitempty"`
	// If set, the request method is overridden.
	Method *string `json:"method,omitempty"`
	// If set, overrides the post data in the request. (Encoded as a base64 string when passed over JSON)
	PostData *string `json:"postData,omitempty"`
	// If set, overrides the request headers. Note that the overrides do not
	// extend to subsequent redirect hops, if a redirect happens. Another override
	// may be applied to a different request produced by a redirect.
	Headers []FetchHeaderEntry `json:"headers,omitempty"`
	// If set, overrides response interception behavior for this request.
	InterceptResponse *bool `json:"interceptResponse,omitempty"`
}

func FetchContinueRequest(requestId FetchRequestId) *FetchContinueRequestParams {
	return &FetchContinueRequestParams{
		RequestId: requestId,
	}
}

func (p *FetchContinueRequestParams) WithUrl(v string) *FetchContinueRequestParams {
	p.Url = &v
	return p
}

func (p *FetchContinueRequestParams) WithMethod(v string) *FetchContinueRequestParams {
	p.Method = &v
	return p
}

func (p *FetchContinueRequestParams) WithPostData(v string) *FetchContinueRequestParams {
	p.PostData = &v
	return p
}

func (p *FetchContinueRequestParams) WithHeaders(v []FetchHeaderEntry) *FetchContinueRequestParams {
	p.Headers = v
	return p
}

func (p *FetchContinueRequestParams) WithInterceptResponse(v bool) *FetchContinueRequestParams {
	p.InterceptResponse = &v
	return p
}

func (p *FetchContinueRequestParams) CDPMethodName() string {
	return "Fetch.continueRequest"
}

// Continues a request supplying authChallengeResponse following authRequired event.
type FetchContinueWithAuthParams struct {
	// An id the client received in authRequired event.
	RequestId FetchRequestId `json:"requestId"`
	// Response to  with an authChallenge.
	AuthChallengeResponse FetchAuthChallengeResponse `json:"authChallengeResponse"`
}

func FetchContinueWithAuth(requestId FetchRequestId, authChallengeResponse FetchAuthChallengeResponse) *FetchContinueWithAuthParams {
	return &FetchContinueWithAuthParams{
		RequestId:             requestId,
		AuthChallengeResponse: authChallengeResponse,
	}
}

func (p *FetchContinueWithAuthParams) CDPMethodName() string {
	return "Fetch.continueWithAuth"
}

// Continues loading of the paused response, optionally modifying the
// response headers. If either responseCode or headers are modified, all of them
// must be present.
type FetchContinueResponseParams struct {
	// An id the client received in requestPaused event.
	RequestId FetchRequestId `json:"requestId"`
	// An HTTP response code. If absent, original response code will be used.
	ResponseCode *int64 `json:"responseCode,omitempty"`
	// A textual representation of responseCode.
	// If absent, a standard phrase matching responseCode is used.
	ResponsePhrase *string `json:"responsePhrase,omitempty"`
	// Response headers. If absent, original response headers will be used.
	ResponseHeaders []FetchHeaderEntry `json:"responseHeaders,omitempty"`
	// Alternative way of specifying response headers as a \0-separated
	// series of name: value pairs. Prefer the above method unless you
	// need to represent some non-UTF8 values that can't be transmitted
	// over the protocol as text. (Encoded as a base64 string when passed over JSON)
	BinaryResponseHeaders *string `json:"binaryResponseHeaders,omitempty"`
}

func FetchContinueResponse(requestId FetchRequestId) *FetchContinueResponseParams {
	return &FetchContinueResponseParams{
		RequestId: requestId,
	}
}

func (p *FetchContinueResponseParams) WithResponseCode(v int64) *FetchContinueResponseParams {
	p.ResponseCode = &v
	return p
}

func (p *FetchContinueResponseParams) WithResponsePhrase(v string) *FetchContinueResponseParams {
	p.ResponsePhrase = &v
	return p
}

func (p *FetchContinueResponseParams) WithResponseHeaders(v []FetchHeaderEntry) *FetchContinueResponseParams {
	p.ResponseHeaders = v
	return p
}

func (p *FetchContinueResponseParams) WithBinaryResponseHeaders(v string) *FetchContinueResponseParams {
	p.BinaryResponseHeaders = &v
	return p
}

func (p *FetchContinueResponseParams) CDPMethodName() string {
	return "Fetch.continueResponse"
}

// Causes the body of the response to be received from the server and
// returned as a single string. May only be issued for a request that
// is paused in the Response stage and is mutually exclusive with
// takeResponseBodyForInterceptionAsStream. Calling other methods that
// affect the request or disabling fetch domain before body is received
// results in an undefined behavior.
// Note that the response body is not available for redirects. Requests
// paused in the _redirect received_ state may be differentiated by
// `responseCode` and presence of `location` response header, see
// comments to `requestPaused` for details.
type FetchGetResponseBodyParams struct {
	// Identifier for the intercepted request to get body for.
	RequestId FetchRequestId `json:"requestId"`
}

type FetchGetResponseBodyReturns struct {
	// Response body.
	Body string `json:"body"`
	// True, if content was sent as base64.
	Base64Encoded bool `json:"base64Encoded"`
}

func FetchGetResponseBody(requestId FetchRequestId) *FetchGetResponseBodyParams {
	return &FetchGetResponseBodyParams{
		RequestId: requestId,
	}
}

func (p *FetchGetResponseBodyParams) CDPMethodName() string {
	return "Fetch.getResponseBody"
}

// Returns a handle to the stream representing the response body.
// The request must be paused in the HeadersReceived stage.
// Note that after this command the request can't be continued
// as is -- client either needs to cancel it or to provide the
// response body.
// The stream only supports sequential read, IO.read will fail if the position
// is specified.
// This method is mutually exclusive with getResponseBody.
// Calling other methods that affect the request or disabling fetch
// domain before body is received results in an undefined behavior.
type FetchTakeResponseBodyAsStreamParams struct {
	RequestId FetchRequestId `json:"requestId"`
}

type FetchTakeResponseBodyAsStreamReturns struct {
	Stream IOStreamHandle `json:"stream"`
}

func FetchTakeResponseBodyAsStream(requestId FetchRequestId) *FetchTakeResponseBodyAsStreamParams {
	return &FetchTakeResponseBodyAsStreamParams{
		RequestId: requestId,
	}
}

func (p *FetchTakeResponseBodyAsStreamParams) CDPMethodName() string {
	return "Fetch.takeResponseBodyAsStream"
}

// Issued when the domain is enabled and the request URL matches the
// specified filter. The request is paused until the client responds
// with one of continueRequest, failRequest or fulfillRequest.
// The stage of the request can be determined by presence of responseErrorReason
// and responseStatusCode -- the request is at the response stage if either
// of these fields is present and in the request stage otherwise.
// Redirect responses and subsequent requests are reported similarly to regular
// responses and requests. Redirect responses may be distinguished by the value
// of `responseStatusCode` (which is one of 301, 302, 303, 307, 308) along with
// presence of the `location` header. Requests resulting from a redirect will
// have `redirectedRequestId` field set.
const EventFetchRequestPaused = "Fetch.requestPaused"

type FetchRequestPausedEvent struct {
	// Each request the page makes will have a unique id.
	RequestId FetchRequestId `json:"requestId"`
	// The details of the request.
	Request NetworkRequest `json:"request"`
	// The id of the frame that initiated the request.
	FrameId PageFrameId `json:"frameId"`
	// How the requested resource will be used.
	ResourceType NetworkResourceType `json:"resourceType"`
	// Response error if intercepted at response stage.
	ResponseErrorReason *NetworkErrorReason `json:"responseErrorReason,omitempty"`
	// Response code if intercepted at response stage.
	ResponseStatusCode *int64 `json:"responseStatusCode,omitempty"`
	// Response status text if intercepted at response stage.
	ResponseStatusText *string `json:"responseStatusText,omitempty"`
	// Response headers if intercepted at the response stage.
	ResponseHeaders []FetchHeaderEntry `json:"responseHeaders,omitempty"`
	// If the intercepted request had a corresponding Network.requestWillBeSent event fired for it,
	// then this networkId will be the same as the requestId present in the requestWillBeSent event.
	NetworkId *NetworkRequestId `json:"networkId,omitempty"`
	// If the request is due to a redirect response from the server, the id of the request that
	// has caused the redirect.
	RedirectedRequestId *FetchRequestId `json:"redirectedRequestId,omitempty"`
}

func (e *FetchRequestPausedEvent) CDPEventName() string {
	return EventFetchRequestPaused
}

// Issued when the domain is enabled with handleAuthRequests set to true.
// The request is paused until client responds with continueWithAuth.
const EventFetchAuthRequired = "Fetch.authRequired"

type FetchAuthRequiredEvent struct {
	// Each request the page makes will have a unique id.
	RequestId FetchRequestId `json:"requestId"`
	// The details of the request.
	Request NetworkRequest `json:"request"`
	// The id of the frame that initiated the request.
	FrameId PageFrameId `json:"frameId"`
	// How the requested resource will be used.
	ResourceType NetworkResourceType `json:"resourceType"`
	// Details of the Authorization Challenge encountered.
	// If this is set, client should respond with continueRequest that
	// contains AuthChallengeResponse.
	AuthChallenge FetchAuthChallenge `json:"authChallenge"`
}

func (e *FetchAuthRequiredEvent) CDPEventName() string {
	return EventFetchAuthRequired
}
