// Code generated by cdpgen; DO NOT EDIT.

package cdp

type FileSystemFile struct {
	Name string `json:"name"`
	// Timestamp
	LastModified NetworkTimeSinceEpoch `json:"lastModified"`
	// Size in bytes
	Size float64 `json:"size"`
	Type string  `json:"type"`
}

type FileSystemDirectory struct {
	Name              string   `json:"name"`
	NestedDirectories []string `json:"nestedDirectories"`
	// Files that are directly nested under this directory.
	NestedFiles []FileSystemFile `json:"nestedFiles"`
}

type FileSystemBucketFileSystemLocator struct {
	// Storage key
	StorageKey StorageSerializedStorageKey `json:"storageKey"`
	// Bucket name. Not passing a `bucketName` will retrieve the default Bucket. (https://developer.mozilla.org/en-US/docs/Web/API/Storage_API#storage_buckets)
	BucketName *string `json:"bucketName,omitempty"`
	// Path to the directory using each path component as an array item.
	PathComponents []string `json:"pathComponents"`
}

type FileSystemGetDirectoryParams struct {
	BucketFileSystemLocator FileSystemBucketFileSystemLocator `json:"bucketFileSystemLocator"`
}

type FileSystemGetDirectoryReturns struct {
	// Returns the directory object at the path.
	Directory FileSystemDirectory `json:"directory"`
}

func FileSystemGetDirectory(bucketFileSystemLocator FileSystemBucketFileSystemLocator) *FileSystemGetDirectoryParams {
	return &FileSystemGetDirectoryParams{
		BucketFileSystemLocator: bucketFileSystemLocator,
	}
}

func (p *FileSystemGetDirectoryParams) CDPMethodName() string {
	return "FileSystem.getDirectory"
}
