// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Heap snapshot object id.
type HeapProfilerHeapSnapshotObjectId string

// Sampling Heap Profile node. Holds callsite information, allocation statistics and child nodes.
type HeapProfilerSamplingHeapProfileNode struct {
	// Function location.
	CallFrame RuntimeCallFrame `json:"callFrame"`
	// Allocations size in bytes for the node excluding children.
	SelfSize float64 `json:"selfSize"`
	// Node id. Ids are unique across all profiles collected between startSampling and stopSampling.
	Id int64 `json:"id"`
	// Child nodes.
	Children []HeapProfilerSamplingHeapProfileNode `json:"children"`
}

// A single sample from a sampling profile.
type HeapProfilerSamplingHeapProfileSample struct {
	// Allocation size in bytes attributed to the sample.
	Size float64 `json:"size"`
	// Id of the corresponding profile tree node.
	NodeId int64 `json:"nodeId"`
	// Time-ordered sample ordinal number. It is unique across all profiles retrieved
	// between startSampling and stopSampling.
	Ordinal float64 `json:"ordinal"`
}

// Sampling profile.
type HeapProfilerSamplingHeapProfile struct {
	Head    HeapProfilerSamplingHeapProfileNode     `json:"head"`
	Samples []HeapProfilerSamplingHeapProfileSample `json:"samples"`
}

// Enables console to refer to the node with given id via $x (see Command Line API for more details
// $x functions).
type HeapProfilerAddInspectedHeapObjectParams struct {
	// Heap snapshot object id to be accessible by means of $x command line API.
	HeapObjectId HeapProfilerHeapSnapshotObjectId `json:"heapObjectId"`
}

func HeapProfilerAddInspectedHeapObject(heapObjectId HeapProfilerHeapSnapshotObjectId) *HeapProfilerAddInspectedHeapObjectParams {
	return &HeapProfilerAddInspectedHeapObjectParams{
		HeapObjectId: heapObjectId,
	}
}

func (p *HeapProfilerAddInspectedHeapObjectParams) CDPMethodName() string {
	return "HeapProfiler.addInspectedHeapObject"
}

type HeapProfilerCollectGarbageParams struct {
}

func HeapProfilerCollectGarbage() *HeapProfilerCollectGarbageParams {
	return &HeapProfilerCollectGarbageParams{}
}

func (p *HeapProfilerCollectGarbageParams) CDPMethodName() string {
	return "HeapProfiler.collectGarbage"
}

type HeapProfilerDisableParams struct {
}

func HeapProfilerDisable() *HeapProfilerDisableParams {
	return &HeapProfilerDisableParams{}
}

func (p *HeapProfilerDisableParams) CDPMethodName() string {
	return "HeapProfiler.disable"
}

type HeapProfilerEnableParams struct {
}

func HeapProfilerEnable() *HeapProfilerEnableParams {
	return &HeapProfilerEnableParams{}
}

func (p *HeapProfilerEnableParams) CDPMethodName() string {
	return "HeapProfiler.enable"
}

type HeapProfilerGetHeapObjectIdParams struct {
	// Identifier of the object to get heap object id for.
	ObjectId RuntimeRemoteObjectId `json:"objectId"`
}

type HeapProfilerGetHeapObjectIdReturns struct {
	// Id of the heap snapshot object corresponding to the passed remote object id.
	HeapSnapshotObjectId HeapProfilerHeapSnapshotObjectId `json:"heapSnapshotObjectId"`
}

func HeapProfilerGetHeapObjectId(objectId RuntimeRemoteObjectId) *HeapProfilerGetHeapObjectIdParams {
	return &HeapProfilerGetHeapObjectIdParams{
		ObjectId: objectId,
	}
}

func (p *HeapProfilerGetHeapObjectIdParams) CDPMethodName() string {
	return "HeapProfiler.getHeapObjectId"
}

type HeapProfilerGetObjectByHeapObjectIdParams struct {
	ObjectId HeapProfilerHeapSnapshotObjectId `json:"objectId"`
	// Symbolic group name that can be used to release multiple objects.
	ObjectGroup *string `json:"objectGroup,omitempty"`
}

type HeapProfilerGetObjectByHeapObjectIdReturns struct {
	// Evaluation result.
	Result RuntimeRemoteObject `json:"result"`
}

func HeapProfilerGetObjectByHeapObjectId(objectId HeapProfilerHeapSnapshotObjectId) *HeapProfilerGetObjectByHeapObjectIdParams {
	return &HeapProfilerGetObjectByHeapObjectIdParams{
		ObjectId: objectId,
	}
}

func (p *HeapProfilerGetObjectByHeapObjectIdParams) WithObjectGroup(v string) *HeapProfilerGetObjectByHeapObjectIdParams {
	p.ObjectGroup = &v
	return p
}

func (p *HeapProfilerGetObjectByHeapObjectIdParams) CDPMethodName() string {
	return "HeapProfiler.getObjectByHeapObjectId"
}

type HeapProfilerGetSamplingProfileParams struct {
}

type HeapProfilerGetSamplingProfileReturns struct {
	// Return the sampling profile being collected.
	Profile HeapProfilerSamplingHeapProfile `json:"profile"`
}

func HeapProfilerGetSamplingProfile() *HeapProfilerGetSamplingProfileParams {
	return &HeapProfilerGetSamplingProfileParams{}
}

func (p *HeapProfilerGetSamplingProfileParams) CDPMethodName() string {
	return "HeapProfiler.getSamplingProfile"
}

type HeapProfilerStartSamplingParams struct {
	// Average sample interval in bytes. Poisson distribution is used for the intervals. The
	// default value is 32768 bytes.
	SamplingInterval *float64 `json:"samplingInterval,omitempty"`
	// Maximum stack depth. The default value is 128.
	StackDepth *float64 `json:"stackDepth,omitempty"`
	// By default, the sampling heap profiler reports only objects which are
	// still alive when the profile is returned via getSamplingProfile or
	// stopSampling, which is useful for determining what functions contribute
	// the most to steady-state memory usage. This flag instructs the sampling
	// heap profiler to also include information about objects discarded by
	// major GC, which will show which functions cause large temporary memory
	// usage or long GC pauses.
	IncludeObjectsCollectedByMajorGC *bool `json:"includeObjectsCollectedByMajorGC,omitempty"`
	// By default, the sampling heap profiler reports only objects which are
	// still alive when the profile is returned via getSamplingProfile or
	// stopSampling, which is useful for determining what functions contribute
	// the most to steady-state memory usage. This flag instructs the sampling
	// heap profiler to also include information about objects discarded by
	// minor GC, which is useful when tuning a latency-sensitive application
	// for minimal GC activity.
	IncludeObjectsCollectedByMinorGC *bool `json:"includeObjectsCollectedByMinorGC,omitempty"`
}

func HeapProfilerStartSampling() *HeapProfilerStartSamplingParams {
	return &HeapProfilerStartSamplingParams{}
}

func (p *HeapProfilerStartSamplingParams) WithSamplingInterval(v float64) *HeapProfilerStartSamplingParams {
	p.SamplingInterval = &v
	return p
}

func (p *HeapProfilerStartSamplingParams) WithStackDepth(v float64) *HeapProfilerStartSamplingParams {
	p.StackDepth = &v
	return p
}

func (p *HeapProfilerStartSamplingParams) WithIncludeObjectsCollectedByMajorGC(v bool) *HeapProfilerStartSamplingParams {
	p.IncludeObjectsCollectedByMajorGC = &v
	return p
}

func (p *HeapProfilerStartSamplingParams) WithIncludeObjectsCollectedByMinorGC(v bool) *HeapProfilerStartSamplingParams {
	p.IncludeObjectsCollectedByMinorGC = &v
	return p
}

func (p *HeapProfilerStartSamplingParams) CDPMethodName() string {
	return "HeapProfiler.startSampling"
}

type HeapProfilerStartTrackingHeapObjectsParams struct {
	TrackAllocations *bool `json:"trackAllocations,omitempty"`
}

func HeapProfilerStartTrackingHeapObjects() *HeapProfilerStartTrackingHeapObjectsParams {
	return &HeapProfilerStartTrackingHeapObjectsParams{}
}

func (p *HeapProfilerStartTrackingHeapObjectsParams) WithTrackAllocations(v bool) *HeapProfilerStartTrackingHeapObjectsParams {
	p.TrackAllocations = &v
	return p
}

func (p *HeapProfilerStartTrackingHeapObjectsParams) CDPMethodName() string {
	return "HeapProfiler.startTrackingHeapObjects"
}

type HeapProfilerStopSamplingParams struct {
}

type HeapProfilerStopSamplingReturns struct {
	// Recorded sampling heap profile.
	Profile HeapProfilerSamplingHeapProfile `json:"profile"`
}

func HeapProfilerStopSampling() *HeapProfilerStopSamplingParams {
	return &HeapProfilerStopSamplingParams{}
}

func (p *HeapProfilerStopSamplingParams) CDPMethodName() string {
	return "HeapProfiler.stopSampling"
}

type HeapProfilerStopTrackingHeapObjectsParams struct {
	// If true 'reportHeapSnapshotProgress' events will be generated while snapshot is being taken
	// when the tracking is stopped.
	ReportProgress *bool `json:"reportProgress,omitempty"`
	// Deprecated in favor of `exposeInternals`.
	TreatGlobalObjectsAsRoots *bool `json:"treatGlobalObjectsAsRoots,omitempty"`
	// If true, numerical values are included in the snapshot
	CaptureNumericValue *bool `json:"captureNumericValue,omitempty"`
	// If true, exposes internals of the snapshot.
	ExposeInternals *bool `json:"exposeInternals,omitempty"`
}

func HeapProfilerStopTrackingHeapObjects() *HeapProfilerStopTrackingHeapObjectsParams {
	return &HeapProfilerStopTrackingHeapObjectsParams{}
}

func (p *HeapProfilerStopTrackingHeapObjectsParams) WithReportProgress(v bool) *HeapProfilerStopTrackingHeapObjectsParams {
	p.ReportProgress = &v
	return p
}

func (p *HeapProfilerStopTrackingHeapObjectsParams) WithTreatGlobalObjectsAsRoots(v bool) *HeapProfilerStopTrackingHeapObjectsParams {
	p.TreatGlobalObjectsAsRoots = &v
	return p
}

func (p *HeapProfilerStopTrackingHeapObjectsParams) WithCaptureNumericValue(v bool) *HeapProfilerStopTrackingHeapObjectsParams {
	p.CaptureNumericValue = &v
	return p
}

func (p *HeapProfilerStopTrackingHeapObjectsParams) WithExposeInternals(v bool) *HeapProfilerStopTrackingHeapObjectsParams {
	p.ExposeInternals = &v
	return p
}

func (p *HeapProfilerStopTrackingHeapObjectsParams) CDPMethodName() string {
	return "HeapProfiler.stopTrackingHeapObjects"
}

type HeapProfilerTakeHeapSnapshotParams struct {
	// If true 'reportHeapSnapshotProgress' events will be generated while snapshot is being taken.
	ReportProgress *bool `json:"reportProgress,omitempty"`
	// If true, a raw snapshot without artificial roots will be generated.
	// Deprecated in favor of `exposeInternals`.
	TreatGlobalObjectsAsRoots *bool `json:"treatGlobalObjectsAsRoots,omitempty"`
	// If true, numerical values are included in the snapshot
	CaptureNumericValue *bool `json:"captureNumericValue,omitempty"`
	// If true, exposes internals of the snapshot.
	ExposeInternals *bool `json:"exposeInternals,omitempty"`
}

func HeapProfilerTakeHeapSnapshot() *HeapProfilerTakeHeapSnapshotParams {
	return &HeapProfilerTakeHeapSnapshotParams{}
}

func (p *HeapProfilerTakeHeapSnapshotParams) WithReportProgress(v bool) *HeapProfilerTakeHeapSnapshotParams {
	p.ReportProgress = &v
	return p
}

func (p *HeapProfilerTakeHeapSnapshotParams) WithTreatGlobalObjectsAsRoots(v bool) *HeapProfilerTakeHeapSnapshotParams {
	p.TreatGlobalObjectsAsRoots = &v
	return p
}

func (p *HeapProfilerTakeHeapSnapshotParams) WithCaptureNumericValue(v bool) *HeapProfilerTakeHeapSnapshotParams {
	p.CaptureNumericValue = &v
	return p
}

func (p *HeapProfilerTakeHeapSnapshotParams) WithExposeInternals(v bool) *HeapProfilerTakeHeapSnapshotParams {
	p.ExposeInternals = &v
	return p
}

func (p *HeapProfilerTakeHeapSnapshotParams) CDPMethodName() string {
	return "HeapProfiler.takeHeapSnapshot"
}

const EventHeapProfilerAddHeapSnapshotChunk = "HeapProfiler.addHeapSnapshotChunk"

type HeapProfilerAddHeapSnapshotChunkEvent struct {
	Chunk string `json:"chunk"`
}

func (e *HeapProfilerAddHeapSnapshotChunkEvent) CDPEventName() string {
	return EventHeapProfilerAddHeapSnapshotChunk
}

// If heap objects tracking has been started then backend may send update for one or more fragments
const EventHeapProfilerHeapStatsUpdate = "HeapProfiler.heapStatsUpdate"

type HeapProfilerHeapStatsUpdateEvent struct {
	// An array of triplets. Each triplet describes a fragment. The first integer is the fragment
	// index, the second integer is a total count of objects for the fragment, the third integer is
	// a total size of the objects for the fragment.
	StatsUpdate []int64 `json:"statsUpdate"`
}

func (e *HeapProfilerHeapStatsUpdateEvent) CDPEventName() string {
	return EventHeapProfilerHeapStatsUpdate
}

// If heap objects tracking has been started then backend regularly sends a current value for last
// seen object id and corresponding timestamp. If the were changes in the heap since last event
// then one or more heapStatsUpdate events will be sent before a new lastSeenObjectId event.
const EventHeapProfilerLastSeenObjectId = "HeapProfiler.lastSeenObjectId"

type HeapProfilerLastSeenObjectIdEvent struct {
	LastSeenObjectId int64   `json:"lastSeenObjectId"`
	Timestamp        float64 `json:"timestamp"`
}

func (e *HeapProfilerLastSeenObjectIdEvent) CDPEventName() string {
	return EventHeapProfilerLastSeenObjectId
}

const EventHeapProfilerReportHeapSnapshotProgress = "HeapProfiler.reportHeapSnapshotProgress"

type HeapProfilerReportHeapSnapshotProgressEvent struct {
	Done     int64 `json:"done"`
	Total    int64 `json:"total"`
	Finished *bool `json:"finished,omitempty"`
}

func (e *HeapProfilerReportHeapSnapshotProgressEvent) CDPEventName() string {
	return EventHeapProfilerReportHeapSnapshotProgress
}

const EventHeapProfilerResetProfiles = "HeapProfiler.resetProfiles"

type HeapProfilerResetProfilesEvent struct {
}

func (e *HeapProfilerResetProfilesEvent) CDPEventName() string {
	return EventHeapProfilerResetProfiles
}
