// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Disables inspector domain notifications.
type InspectorDisableParams struct {
}

func InspectorDisable() *InspectorDisableParams {
	return &InspectorDisableParams{}
}

func (p *InspectorDisableParams) CDPMethodName() string {
	return "Inspector.disable"
}

// Enables inspector domain notifications.
type InspectorEnableParams struct {
}

func InspectorEnable() *InspectorEnableParams {
	return &InspectorEnableParams{}
}

func (p *InspectorEnableParams) CDPMethodName() string {
	return "Inspector.enable"
}

// Fired when remote debugging connection is about to be terminated. Contains detach reason.
const EventInspectorDetached = "Inspector.detached"

type InspectorDetachedEvent struct {
	// The reason why connection has been terminated.
	Reason string `json:"reason"`
}

func (e *InspectorDetachedEvent) CDPEventName() string {
	return EventInspectorDetached
}

// Fired when debugging target has crashed
const EventInspectorTargetCrashed = "Inspector.targetCrashed"

type InspectorTargetCrashedEvent struct {
}

func (e *InspectorTargetCrashedEvent) CDPEventName() string {
	return EventInspectorTargetCrashed
}

// Fired when debugging target has reloaded after crash
const EventInspectorTargetReloadedAfterCrash = "Inspector.targetReloadedAfterCrash"

type InspectorTargetReloadedAfterCrashEvent struct {
}

func (e *InspectorTargetReloadedAfterCrashEvent) CDPEventName() string {
	return EventInspectorTargetReloadedAfterCrash
}

// Fired on worker targets when main worker script and any imported scripts have been evaluated.
const EventInspectorWorkerScriptLoaded = "Inspector.workerScriptLoaded"

type InspectorWorkerScriptLoadedEvent struct {
}

func (e *InspectorWorkerScriptLoadedEvent) CDPEventName() string {
	return EventInspectorWorkerScriptLoaded
}
