// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Log entry.
type LogLogEntry struct {
	// Log entry source.
	Source string `json:"source"`
	// Log entry severity.
	Level string `json:"level"`
	// Logged text.
	Text     string  `json:"text"`
	Category *string `json:"category,omitempty"`
	// Timestamp when this entry was added.
	Timestamp RuntimeTimestamp `json:"timestamp"`
	// URL of the resource if known.
	Url *string `json:"url,omitempty"`
	// Line number in the resource.
	LineNumber *int64 `json:"lineNumber,omitempty"`
	// JavaScript stack trace.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
	// Identifier of the network request associated with this entry.
	NetworkRequestId *NetworkRequestId `json:"networkRequestId,omitempty"`
	// Identifier of the worker associated with this entry.
	WorkerId *string `json:"workerId,omitempty"`
	// Call arguments.
	Args []RuntimeRemoteObject `json:"args,omitempty"`
}

// Violation configuration setting.
type LogViolationSetting struct {
	// Violation type.
	Name string `json:"name"`
	// Time threshold to trigger upon.
	Threshold float64 `json:"threshold"`
}

// Clears the log.
type LogClearParams struct {
}

func LogClear() *LogClearParams {
	return &LogClearParams{}
}

func (p *LogClearParams) CDPMethodName() string {
	return "Log.clear"
}

// Disables log domain, prevents further log entries from being reported to the client.
type LogDisableParams struct {
}

func LogDisable() *LogDisableParams {
	return &LogDisableParams{}
}

func (p *LogDisableParams) CDPMethodName() string {
	return "Log.disable"
}

// Enables log domain, sends the entries collected so far to the client by means of the
// `entryAdded` notification.
type LogEnableParams struct {
}

func LogEnable() *LogEnableParams {
	return &LogEnableParams{}
}

func (p *LogEnableParams) CDPMethodName() string {
	return "Log.enable"
}

// start violation reporting.
type LogStartViolationsReportParams struct {
	// Configuration for violations.
	Config []LogViolationSetting `json:"config"`
}

func LogStartViolationsReport(config []LogViolationSetting) *LogStartViolationsReportParams {
	return &LogStartViolationsReportParams{
		Config: config,
	}
}

func (p *LogStartViolationsReportParams) CDPMethodName() string {
	return "Log.startViolationsReport"
}

// Stop violation reporting.
type LogStopViolationsReportParams struct {
}

func LogStopViolationsReport() *LogStopViolationsReportParams {
	return &LogStopViolationsReportParams{}
}

func (p *LogStopViolationsReportParams) CDPMethodName() string {
	return "Log.stopViolationsReport"
}

// Issued when new message was logged.
const EventLogEntryAdded = "Log.entryAdded"

type LogEntryAddedEvent struct {
	// The entry.
	Entry LogLogEntry `json:"entry"`
}

func (e *LogEntryAddedEvent) CDPEventName() string {
	return EventLogEntryAdded
}
