// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Players will get an ID that is unique within the agent context.
type MediaPlayerId string

type MediaTimestamp float64

// Have one type per entry in MediaLogRecord::Type
// Corresponds to kMessage
type MediaPlayerMessage struct {
	// Keep in sync with MediaLogMessageLevel
	// We are currently keeping the message level 'error' separate from the
	// PlayerError type because right now they represent different things,
	// this one being a DVLOG(ERROR) style log message that gets printed
	// based on what log level is selected in the UI, and the other is a
	// representation of a media::PipelineStatus object. Soon however we're
	// going to be moving away from using PipelineStatus for errors and
	// introducing a new error type which should hopefully let us integrate
	// the error log level into the PlayerError type.
	Level   string `json:"level"`
	Message string `json:"message"`
}

// Corresponds to kMediaPropertyChange
type MediaPlayerProperty struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// Corresponds to kMediaEventTriggered
type MediaPlayerEvent struct {
	Timestamp MediaTimestamp `json:"timestamp"`
	Value     string         `json:"value"`
}

// Represents logged source line numbers reported in an error.
// NOTE: file and line are from chromium c++ implementation code, not js.
type MediaPlayerErrorSourceLocation struct {
	File string `json:"file"`
	Line int64  `json:"line"`
}

// Corresponds to kMediaError
type MediaPlayerError struct {
	ErrorType string `json:"errorType"`
	// Code is the numeric enum entry for a specific set of error codes, such
	// as PipelineStatusCodes in media/base/pipeline_status.h
	Code int64 `json:"code"`
	// A trace of where this error was caused / where it passed through.
	Stack []MediaPlayerErrorSourceLocation `json:"stack"`
	// Errors potentially have a root cause error, ie, a DecoderError might be
	// caused by an WindowsError
	Cause []MediaPlayerError `json:"cause"`
	// Extra data attached to an error, such as an HRESULT, Video Codec, etc.
	Data map[string]any `json:"data"`
}

type MediaPlayer struct {
	PlayerId  MediaPlayerId     `json:"playerId"`
	DomNodeId *DOMBackendNodeId `json:"domNodeId,omitempty"`
}

// Enables the Media domain
type MediaEnableParams struct {
}

func MediaEnable() *MediaEnableParams {
	return &MediaEnableParams{}
}

func (p *MediaEnableParams) CDPMethodName() string {
	return "Media.enable"
}

// Disables the Media domain.
type MediaDisableParams struct {
}

func MediaDisable() *MediaDisableParams {
	return &MediaDisableParams{}
}

func (p *MediaDisableParams) CDPMethodName() string {
	return "Media.disable"
}

// This can be called multiple times, and can be used to set / override /
// remove player properties. A null propValue indicates removal.
const EventMediaPlayerPropertiesChanged = "Media.playerPropertiesChanged"

type MediaPlayerPropertiesChangedEvent struct {
	PlayerId   MediaPlayerId         `json:"playerId"`
	Properties []MediaPlayerProperty `json:"properties"`
}

func (e *MediaPlayerPropertiesChangedEvent) CDPEventName() string {
	return EventMediaPlayerPropertiesChanged
}

// Send events as a list, allowing them to be batched on the browser for less
// congestion. If batched, events must ALWAYS be in chronological order.
const EventMediaPlayerEventsAdded = "Media.playerEventsAdded"

type MediaPlayerEventsAddedEvent struct {
	PlayerId MediaPlayerId      `json:"playerId"`
	Events   []MediaPlayerEvent `json:"events"`
}

func (e *MediaPlayerEventsAddedEvent) CDPEventName() string {
	return EventMediaPlayerEventsAdded
}

// Send a list of any messages that need to be delivered.
const EventMediaPlayerMessagesLogged = "Media.playerMessagesLogged"

type MediaPlayerMessagesLoggedEvent struct {
	PlayerId MediaPlayerId        `json:"playerId"`
	Messages []MediaPlayerMessage `json:"messages"`
}

func (e *MediaPlayerMessagesLoggedEvent) CDPEventName() string {
	return EventMediaPlayerMessagesLogged
}

// Send a list of any errors that need to be delivered.
const EventMediaPlayerErrorsRaised = "Media.playerErrorsRaised"

type MediaPlayerErrorsRaisedEvent struct {
	PlayerId MediaPlayerId      `json:"playerId"`
	Errors   []MediaPlayerError `json:"errors"`
}

func (e *MediaPlayerErrorsRaisedEvent) CDPEventName() string {
	return EventMediaPlayerErrorsRaised
}

// Called whenever a player is created, or when a new agent joins and receives
// a list of active players. If an agent is restored, it will receive one
// event for each active player.
const EventMediaPlayerCreated = "Media.playerCreated"

type MediaPlayerCreatedEvent struct {
	Player MediaPlayer `json:"player"`
}

func (e *MediaPlayerCreatedEvent) CDPEventName() string {
	return EventMediaPlayerCreated
}
