// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Configuration data for drawing the source order of an elements children.
type OverlaySourceOrderConfig struct {
	// the color to outline the given element in.
	ParentOutlineColor DOMRGBA `json:"parentOutlineColor"`
	// the color to outline the child elements in.
	ChildOutlineColor DOMRGBA `json:"childOutlineColor"`
}

// Configuration data for the highlighting of Grid elements.
type OverlayGridHighlightConfig struct {
	// Whether the extension lines from grid cells to the rulers should be shown (default: false).
	ShowGridExtensionLines *bool `json:"showGridExtensionLines,omitempty"`
	// Show Positive line number labels (default: false).
	ShowPositiveLineNumbers *bool `json:"showPositiveLineNumbers,omitempty"`
	// Show Negative line number labels (default: false).
	ShowNegativeLineNumbers *bool `json:"showNegativeLineNumbers,omitempty"`
	// Show area name labels (default: false).
	ShowAreaNames *bool `json:"showAreaNames,omitempty"`
	// Show line name labels (default: false).
	ShowLineNames *bool `json:"showLineNames,omitempty"`
	// Show track size labels (default: false).
	ShowTrackSizes *bool `json:"showTrackSizes,omitempty"`
	// The grid container border highlight color (default: transparent).
	GridBorderColor *DOMRGBA `json:"gridBorderColor,omitempty"`
	// The cell border color (default: transparent). Deprecated, please use rowLineColor and columnLineColor instead.
	CellBorderColor *DOMRGBA `json:"cellBorderColor,omitempty"`
	// The row line color (default: transparent).
	RowLineColor *DOMRGBA `json:"rowLineColor,omitempty"`
	// The column line color (default: transparent).
	ColumnLineColor *DOMRGBA `json:"columnLineColor,omitempty"`
	// Whether the grid border is dashed (default: false).
	GridBorderDash *bool `json:"gridBorderDash,omitempty"`
	// Whether the cell border is dashed (default: false). Deprecated, please us rowLineDash and columnLineDash instead.
	CellBorderDash *bool `json:"cellBorderDash,omitempty"`
	// Whether row lines are dashed (default: false).
	RowLineDash *bool `json:"rowLineDash,omitempty"`
	// Whether column lines are dashed (default: false).
	ColumnLineDash *bool `json:"columnLineDash,omitempty"`
	// The row gap highlight fill color (default: transparent).
	RowGapColor *DOMRGBA `json:"rowGapColor,omitempty"`
	// The row gap hatching fill color (default: transparent).
	RowHatchColor *DOMRGBA `json:"rowHatchColor,omitempty"`
	// The column gap highlight fill color (default: transparent).
	ColumnGapColor *DOMRGBA `json:"columnGapColor,omitempty"`
	// The column gap hatching fill color (default: transparent).
	ColumnHatchColor *DOMRGBA `json:"columnHatchColor,omitempty"`
	// The named grid areas border color (Default: transparent).
	AreaBorderColor *DOMRGBA `json:"areaBorderColor,omitempty"`
	// The grid container background color (Default: transparent).
	GridBackgroundColor *DOMRGBA `json:"gridBackgroundColor,omitempty"`
}

// Configuration data for the highlighting of Flex container elements.
type OverlayFlexContainerHighlightConfig struct {
	// The style of the container border
	ContainerBorder *OverlayLineStyle `json:"containerBorder,omitempty"`
	// The style of the separator between lines
	LineSeparator *OverlayLineStyle `json:"lineSeparator,omitempty"`
	// The style of the separator between items
	ItemSeparator *OverlayLineStyle `json:"itemSeparator,omitempty"`
	// Style of content-distribution space on the main axis (justify-content).
	MainDistributedSpace *OverlayBoxStyle `json:"mainDistributedSpace,omitempty"`
	// Style of content-distribution space on the cross axis (align-content).
	CrossDistributedSpace *OverlayBoxStyle `json:"crossDistributedSpace,omitempty"`
	// Style of empty space caused by row gaps (gap/row-gap).
	RowGapSpace *OverlayBoxStyle `json:"rowGapSpace,omitempty"`
	// Style of empty space caused by columns gaps (gap/column-gap).
	ColumnGapSpace *OverlayBoxStyle `json:"columnGapSpace,omitempty"`
	// Style of the self-alignment line (align-items).
	CrossAlignment *OverlayLineStyle `json:"crossAlignment,omitempty"`
}

// Configuration data for the highlighting of Flex item elements.
type OverlayFlexItemHighlightConfig struct {
	// Style of the box representing the item's base size
	BaseSizeBox *OverlayBoxStyle `json:"baseSizeBox,omitempty"`
	// Style of the border around the box representing the item's base size
	BaseSizeBorder *OverlayLineStyle `json:"baseSizeBorder,omitempty"`
	// Style of the arrow representing if the item grew or shrank
	FlexibilityArrow *OverlayLineStyle `json:"flexibilityArrow,omitempty"`
}

// Style information for drawing a line.
type OverlayLineStyle struct {
	// The color of the line (default: transparent)
	Color *DOMRGBA `json:"color,omitempty"`
	// The line pattern (default: solid)
	Pattern *string `json:"pattern,omitempty"`
}

// Style information for drawing a box.
type OverlayBoxStyle struct {
	// The background color for the box (default: transparent)
	FillColor *DOMRGBA `json:"fillColor,omitempty"`
	// The hatching color for the box (default: transparent)
	HatchColor *DOMRGBA `json:"hatchColor,omitempty"`
}

type OverlayContrastAlgorithm string

const (
	OverlayContrastAlgorithmAa   OverlayContrastAlgorithm = "aa"
	OverlayContrastAlgorithmAaa  OverlayContrastAlgorithm = "aaa"
	OverlayContrastAlgorithmApca OverlayContrastAlgorithm = "apca"
)

// Configuration data for the highlighting of page elements.
type OverlayHighlightConfig struct {
	// Whether the node info tooltip should be shown (default: false).
	ShowInfo *bool `json:"showInfo,omitempty"`
	// Whether the node styles in the tooltip (default: false).
	ShowStyles *bool `json:"showStyles,omitempty"`
	// Whether the rulers should be shown (default: false).
	ShowRulers *bool `json:"showRulers,omitempty"`
	// Whether the a11y info should be shown (default: true).
	ShowAccessibilityInfo *bool `json:"showAccessibilityInfo,omitempty"`
	// Whether the extension lines from node to the rulers should be shown (default: false).
	ShowExtensionLines *bool `json:"showExtensionLines,omitempty"`
	// The content box highlight fill color (default: transparent).
	ContentColor *DOMRGBA `json:"contentColor,omitempty"`
	// The padding highlight fill color (default: transparent).
	PaddingColor *DOMRGBA `json:"paddingColor,omitempty"`
	// The border highlight fill color (default: transparent).
	BorderColor *DOMRGBA `json:"borderColor,omitempty"`
	// The margin highlight fill color (default: transparent).
	MarginColor *DOMRGBA `json:"marginColor,omitempty"`
	// The event target element highlight fill color (default: transparent).
	EventTargetColor *DOMRGBA `json:"eventTargetColor,omitempty"`
	// The shape outside fill color (default: transparent).
	ShapeColor *DOMRGBA `json:"shapeColor,omitempty"`
	// The shape margin fill color (default: transparent).
	ShapeMarginColor *DOMRGBA `json:"shapeMarginColor,omitempty"`
	// The grid layout color (default: transparent).
	CssGridColor *DOMRGBA `json:"cssGridColor,omitempty"`
	// The color format used to format color styles (default: hex).
	ColorFormat *OverlayColorFormat `json:"colorFormat,omitempty"`
	// The grid layout highlight configuration (default: all transparent).
	GridHighlightConfig *OverlayGridHighlightConfig `json:"gridHighlightConfig,omitempty"`
	// The flex container highlight configuration (default: all transparent).
	FlexContainerHighlightConfig *OverlayFlexContainerHighlightConfig `json:"flexContainerHighlightConfig,omitempty"`
	// The flex item highlight configuration (default: all transparent).
	FlexItemHighlightConfig *OverlayFlexItemHighlightConfig `json:"flexItemHighlightConfig,omitempty"`
	// The contrast algorithm to use for the contrast ratio (default: aa).
	ContrastAlgorithm *OverlayContrastAlgorithm `json:"contrastAlgorithm,omitempty"`
	// The container query container highlight configuration (default: all transparent).
	ContainerQueryContainerHighlightConfig *OverlayContainerQueryContainerHighlightConfig `json:"containerQueryContainerHighlightConfig,omitempty"`
}

type OverlayColorFormat string

const (
	OverlayColorFormatRgb OverlayColorFormat = "rgb"
	OverlayColorFormatHsl OverlayColorFormat = "hsl"
	OverlayColorFormatHwb OverlayColorFormat = "hwb"
	OverlayColorFormatHex OverlayColorFormat = "hex"
)

// Configurations for Persistent Grid Highlight
type OverlayGridNodeHighlightConfig struct {
	// A descriptor for the highlight appearance.
	GridHighlightConfig OverlayGridHighlightConfig `json:"gridHighlightConfig"`
	// Identifier of the node to highlight.
	NodeId DOMNodeId `json:"nodeId"`
}

type OverlayFlexNodeHighlightConfig struct {
	// A descriptor for the highlight appearance of flex containers.
	FlexContainerHighlightConfig OverlayFlexContainerHighlightConfig `json:"flexContainerHighlightConfig"`
	// Identifier of the node to highlight.
	NodeId DOMNodeId `json:"nodeId"`
}

type OverlayScrollSnapContainerHighlightConfig struct {
	// The style of the snapport border (default: transparent)
	SnapportBorder *OverlayLineStyle `json:"snapportBorder,omitempty"`
	// The style of the snap area border (default: transparent)
	SnapAreaBorder *OverlayLineStyle `json:"snapAreaBorder,omitempty"`
	// The margin highlight fill color (default: transparent).
	ScrollMarginColor *DOMRGBA `json:"scrollMarginColor,omitempty"`
	// The padding highlight fill color (default: transparent).
	ScrollPaddingColor *DOMRGBA `json:"scrollPaddingColor,omitempty"`
}

type OverlayScrollSnapHighlightConfig struct {
	// A descriptor for the highlight appearance of scroll snap containers.
	ScrollSnapContainerHighlightConfig OverlayScrollSnapContainerHighlightConfig `json:"scrollSnapContainerHighlightConfig"`
	// Identifier of the node to highlight.
	NodeId DOMNodeId `json:"nodeId"`
}

// Configuration for dual screen hinge
type OverlayHingeConfig struct {
	// A rectangle represent hinge
	Rect DOMRect `json:"rect"`
	// The content box highlight fill color (default: a dark color).
	ContentColor *DOMRGBA `json:"contentColor,omitempty"`
	// The content box highlight outline color (default: transparent).
	OutlineColor *DOMRGBA `json:"outlineColor,omitempty"`
}

// Configuration for Window Controls Overlay
type OverlayWindowControlsOverlayConfig struct {
	// Whether the title bar CSS should be shown when emulating the Window Controls Overlay.
	ShowCSS bool `json:"showCSS"`
	// Selected platforms to show the overlay.
	SelectedPlatform string `json:"selectedPlatform"`
	// The theme color defined in app manifest.
	ThemeColor string `json:"themeColor"`
}

type OverlayContainerQueryHighlightConfig struct {
	// A descriptor for the highlight appearance of container query containers.
	ContainerQueryContainerHighlightConfig OverlayContainerQueryContainerHighlightConfig `json:"containerQueryContainerHighlightConfig"`
	// Identifier of the container node to highlight.
	NodeId DOMNodeId `json:"nodeId"`
}

type OverlayContainerQueryContainerHighlightConfig struct {
	// The style of the container border.
	ContainerBorder *OverlayLineStyle `json:"containerBorder,omitempty"`
	// The style of the descendants' borders.
	DescendantBorder *OverlayLineStyle `json:"descendantBorder,omitempty"`
}

type OverlayIsolatedElementHighlightConfig struct {
	// A descriptor for the highlight appearance of an element in isolation mode.
	IsolationModeHighlightConfig OverlayIsolationModeHighlightConfig `json:"isolationModeHighlightConfig"`
	// Identifier of the isolated element to highlight.
	NodeId DOMNodeId `json:"nodeId"`
}

type OverlayIsolationModeHighlightConfig struct {
	// The fill color of the resizers (default: transparent).
	ResizerColor *DOMRGBA `json:"resizerColor,omitempty"`
	// The fill color for resizer handles (default: transparent).
	ResizerHandleColor *DOMRGBA `json:"resizerHandleColor,omitempty"`
	// The fill color for the mask covering non-isolated elements (default: transparent).
	MaskColor *DOMRGBA `json:"maskColor,omitempty"`
}

type OverlayInspectMode string

const (
	OverlayInspectModeSearchForNode         OverlayInspectMode = "searchForNode"
	OverlayInspectModeSearchForUAShadowDOM  OverlayInspectMode = "searchForUAShadowDOM"
	OverlayInspectModeCaptureAreaScreenshot OverlayInspectMode = "captureAreaScreenshot"
	OverlayInspectModeNone                  OverlayInspectMode = "none"
)

type OverlayInspectedElementAnchorConfig struct {
	// Identifier of the node to highlight.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node to highlight.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
}

// Disables domain notifications.
type OverlayDisableParams struct {
}

func OverlayDisable() *OverlayDisableParams {
	return &OverlayDisableParams{}
}

func (p *OverlayDisableParams) CDPMethodName() string {
	return "Overlay.disable"
}

// Enables domain notifications.
type OverlayEnableParams struct {
}

func OverlayEnable() *OverlayEnableParams {
	return &OverlayEnableParams{}
}

func (p *OverlayEnableParams) CDPMethodName() string {
	return "Overlay.enable"
}

// For testing.
type OverlayGetHighlightObjectForTestParams struct {
	// Id of the node to get highlight object for.
	NodeId DOMNodeId `json:"nodeId"`
	// Whether to include distance info.
	IncludeDistance *bool `json:"includeDistance,omitempty"`
	// Whether to include style info.
	IncludeStyle *bool `json:"includeStyle,omitempty"`
	// The color format to get config with (default: hex).
	ColorFormat *OverlayColorFormat `json:"colorFormat,omitempty"`
	// Whether to show accessibility info (default: true).
	ShowAccessibilityInfo *bool `json:"showAccessibilityInfo,omitempty"`
}

type OverlayGetHighlightObjectForTestReturns struct {
	// Highlight data for the node.
	Highlight map[string]any `json:"highlight"`
}

func OverlayGetHighlightObjectForTest(nodeId DOMNodeId) *OverlayGetHighlightObjectForTestParams {
	return &OverlayGetHighlightObjectForTestParams{
		NodeId: nodeId,
	}
}

func (p *OverlayGetHighlightObjectForTestParams) WithIncludeDistance(v bool) *OverlayGetHighlightObjectForTestParams {
	p.IncludeDistance = &v
	return p
}

func (p *OverlayGetHighlightObjectForTestParams) WithIncludeStyle(v bool) *OverlayGetHighlightObjectForTestParams {
	p.IncludeStyle = &v
	return p
}

func (p *OverlayGetHighlightObjectForTestParams) WithColorFormat(v OverlayColorFormat) *OverlayGetHighlightObjectForTestParams {
	p.ColorFormat = &v
	return p
}

func (p *OverlayGetHighlightObjectForTestParams) WithShowAccessibilityInfo(v bool) *OverlayGetHighlightObjectForTestParams {
	p.ShowAccessibilityInfo = &v
	return p
}

func (p *OverlayGetHighlightObjectForTestParams) CDPMethodName() string {
	return "Overlay.getHighlightObjectForTest"
}

// For Persistent Grid testing.
type OverlayGetGridHighlightObjectsForTestParams struct {
	// Ids of the node to get highlight object for.
	NodeIds []DOMNodeId `json:"nodeIds"`
}

type OverlayGetGridHighlightObjectsForTestReturns struct {
	// Grid Highlight data for the node ids provided.
	Highlights map[string]any `json:"highlights"`
}

func OverlayGetGridHighlightObjectsForTest(nodeIds []DOMNodeId) *OverlayGetGridHighlightObjectsForTestParams {
	return &OverlayGetGridHighlightObjectsForTestParams{
		NodeIds: nodeIds,
	}
}

func (p *OverlayGetGridHighlightObjectsForTestParams) CDPMethodName() string {
	return "Overlay.getGridHighlightObjectsForTest"
}

// For Source Order Viewer testing.
type OverlayGetSourceOrderHighlightObjectForTestParams struct {
	// Id of the node to highlight.
	NodeId DOMNodeId `json:"nodeId"`
}

type OverlayGetSourceOrderHighlightObjectForTestReturns struct {
	// Source order highlight data for the node id provided.
	Highlight map[string]any `json:"highlight"`
}

func OverlayGetSourceOrderHighlightObjectForTest(nodeId DOMNodeId) *OverlayGetSourceOrderHighlightObjectForTestParams {
	return &OverlayGetSourceOrderHighlightObjectForTestParams{
		NodeId: nodeId,
	}
}

func (p *OverlayGetSourceOrderHighlightObjectForTestParams) CDPMethodName() string {
	return "Overlay.getSourceOrderHighlightObjectForTest"
}

// Hides any highlight.
type OverlayHideHighlightParams struct {
}

func OverlayHideHighlight() *OverlayHideHighlightParams {
	return &OverlayHideHighlightParams{}
}

func (p *OverlayHideHighlightParams) CDPMethodName() string {
	return "Overlay.hideHighlight"
}

// Highlights owner element of the frame with given id.
// Deprecated: Doesn't work reliably and cannot be fixed due to process
// separation (the owner node might be in a different process). Determine
// the owner node in the client and use highlightNode.
type OverlayHighlightFrameParams struct {
	// Identifier of the frame to highlight.
	FrameId PageFrameId `json:"frameId"`
	// The content box highlight fill color (default: transparent).
	ContentColor *DOMRGBA `json:"contentColor,omitempty"`
	// The content box highlight outline color (default: transparent).
	ContentOutlineColor *DOMRGBA `json:"contentOutlineColor,omitempty"`
}

func OverlayHighlightFrame(frameId PageFrameId) *OverlayHighlightFrameParams {
	return &OverlayHighlightFrameParams{
		FrameId: frameId,
	}
}

func (p *OverlayHighlightFrameParams) WithContentColor(v DOMRGBA) *OverlayHighlightFrameParams {
	p.ContentColor = &v
	return p
}

func (p *OverlayHighlightFrameParams) WithContentOutlineColor(v DOMRGBA) *OverlayHighlightFrameParams {
	p.ContentOutlineColor = &v
	return p
}

func (p *OverlayHighlightFrameParams) CDPMethodName() string {
	return "Overlay.highlightFrame"
}

// Highlights DOM node with given id or with the given JavaScript object wrapper. Either nodeId or
// objectId must be specified.
type OverlayHighlightNodeParams struct {
	// A descriptor for the highlight appearance.
	HighlightConfig OverlayHighlightConfig `json:"highlightConfig"`
	// Identifier of the node to highlight.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node to highlight.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node to be highlighted.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// Selectors to highlight relevant nodes.
	Selector *string `json:"selector,omitempty"`
}

func OverlayHighlightNode(highlightConfig OverlayHighlightConfig) *OverlayHighlightNodeParams {
	return &OverlayHighlightNodeParams{
		HighlightConfig: highlightConfig,
	}
}

func (p *OverlayHighlightNodeParams) WithNodeId(v DOMNodeId) *OverlayHighlightNodeParams {
	p.NodeId = &v
	return p
}

func (p *OverlayHighlightNodeParams) WithBackendNodeId(v DOMBackendNodeId) *OverlayHighlightNodeParams {
	p.BackendNodeId = &v
	return p
}

func (p *OverlayHighlightNodeParams) WithObjectId(v RuntimeRemoteObjectId) *OverlayHighlightNodeParams {
	p.ObjectId = &v
	return p
}

func (p *OverlayHighlightNodeParams) WithSelector(v string) *OverlayHighlightNodeParams {
	p.Selector = &v
	return p
}

func (p *OverlayHighlightNodeParams) CDPMethodName() string {
	return "Overlay.highlightNode"
}

// Highlights given quad. Coordinates are absolute with respect to the main frame viewport.
type OverlayHighlightQuadParams struct {
	// Quad to highlight
	Quad DOMQuad `json:"quad"`
	// The highlight fill color (default: transparent).
	Color *DOMRGBA `json:"color,omitempty"`
	// The highlight outline color (default: transparent).
	OutlineColor *DOMRGBA `json:"outlineColor,omitempty"`
}

func OverlayHighlightQuad(quad DOMQuad) *OverlayHighlightQuadParams {
	return &OverlayHighlightQuadParams{
		Quad: quad,
	}
}

func (p *OverlayHighlightQuadParams) WithColor(v DOMRGBA) *OverlayHighlightQuadParams {
	p.Color = &v
	return p
}

func (p *OverlayHighlightQuadParams) WithOutlineColor(v DOMRGBA) *OverlayHighlightQuadParams {
	p.OutlineColor = &v
	return p
}

func (p *OverlayHighlightQuadParams) CDPMethodName() string {
	return "Overlay.highlightQuad"
}

// Highlights given rectangle. Coordinates are absolute with respect to the main frame viewport.
// Issue: the method does not handle device pixel ratio (DPR) correctly.
// The coordinates currently have to be adjusted by the client
// if DPR is not 1 (see crbug.com/437807128).
type OverlayHighlightRectParams struct {
	// X coordinate
	X int64 `json:"x"`
	// Y coordinate
	Y int64 `json:"y"`
	// Rectangle width
	Width int64 `json:"width"`
	// Rectangle height
	Height int64 `json:"height"`
	// The highlight fill color (default: transparent).
	Color *DOMRGBA `json:"color,omitempty"`
	// The highlight outline color (default: transparent).
	OutlineColor *DOMRGBA `json:"outlineColor,omitempty"`
}

func OverlayHighlightRect(x int64, y int64, width int64, height int64) *OverlayHighlightRectParams {
	return &OverlayHighlightRectParams{
		X:      x,
		Y:      y,
		Width:  width,
		Height: height,
	}
}

func (p *OverlayHighlightRectParams) WithColor(v DOMRGBA) *OverlayHighlightRectParams {
	p.Color = &v
	return p
}

func (p *OverlayHighlightRectParams) WithOutlineColor(v DOMRGBA) *OverlayHighlightRectParams {
	p.OutlineColor = &v
	return p
}

func (p *OverlayHighlightRectParams) CDPMethodName() string {
	return "Overlay.highlightRect"
}

// Highlights the source order of the children of the DOM node with given id or with the given
// JavaScript object wrapper. Either nodeId or objectId must be specified.
type OverlayHighlightSourceOrderParams struct {
	// A descriptor for the appearance of the overlay drawing.
	SourceOrderConfig OverlaySourceOrderConfig `json:"sourceOrderConfig"`
	// Identifier of the node to highlight.
	NodeId *DOMNodeId `json:"nodeId,omitempty"`
	// Identifier of the backend node to highlight.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// JavaScript object id of the node to be highlighted.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

func OverlayHighlightSourceOrder(sourceOrderConfig OverlaySourceOrderConfig) *OverlayHighlightSourceOrderParams {
	return &OverlayHighlightSourceOrderParams{
		SourceOrderConfig: sourceOrderConfig,
	}
}

func (p *OverlayHighlightSourceOrderParams) WithNodeId(v DOMNodeId) *OverlayHighlightSourceOrderParams {
	p.NodeId = &v
	return p
}

func (p *OverlayHighlightSourceOrderParams) WithBackendNodeId(v DOMBackendNodeId) *OverlayHighlightSourceOrderParams {
	p.BackendNodeId = &v
	return p
}

func (p *OverlayHighlightSourceOrderParams) WithObjectId(v RuntimeRemoteObjectId) *OverlayHighlightSourceOrderParams {
	p.ObjectId = &v
	return p
}

func (p *OverlayHighlightSourceOrderParams) CDPMethodName() string {
	return "Overlay.highlightSourceOrder"
}

// Enters the 'inspect' mode. In this mode, elements that user is hovering over are highlighted.
// Backend then generates 'inspectNodeRequested' event upon element selection.
type OverlaySetInspectModeParams struct {
	// Set an inspection mode.
	Mode OverlayInspectMode `json:"mode"`
	// A descriptor for the highlight appearance of hovered-over nodes. May be omitted if `enabled
	// == false`.
	HighlightConfig *OverlayHighlightConfig `json:"highlightConfig,omitempty"`
}

func OverlaySetInspectMode(mode OverlayInspectMode) *OverlaySetInspectModeParams {
	return &OverlaySetInspectModeParams{
		Mode: mode,
	}
}

func (p *OverlaySetInspectModeParams) WithHighlightConfig(v OverlayHighlightConfig) *OverlaySetInspectModeParams {
	p.HighlightConfig = &v
	return p
}

func (p *OverlaySetInspectModeParams) CDPMethodName() string {
	return "Overlay.setInspectMode"
}

// Highlights owner element of all frames detected to be ads.
type OverlaySetShowAdHighlightsParams struct {
	// True for showing ad highlights
	Show bool `json:"show"`
}

func OverlaySetShowAdHighlights(show bool) *OverlaySetShowAdHighlightsParams {
	return &OverlaySetShowAdHighlightsParams{
		Show: show,
	}
}

func (p *OverlaySetShowAdHighlightsParams) CDPMethodName() string {
	return "Overlay.setShowAdHighlights"
}

type OverlaySetPausedInDebuggerMessageParams struct {
	// The message to display, also triggers resume and step over controls.
	Message *string `json:"message,omitempty"`
}

func OverlaySetPausedInDebuggerMessage() *OverlaySetPausedInDebuggerMessageParams {
	return &OverlaySetPausedInDebuggerMessageParams{}
}

func (p *OverlaySetPausedInDebuggerMessageParams) WithMessage(v string) *OverlaySetPausedInDebuggerMessageParams {
	p.Message = &v
	return p
}

func (p *OverlaySetPausedInDebuggerMessageParams) CDPMethodName() string {
	return "Overlay.setPausedInDebuggerMessage"
}

// Requests that backend shows debug borders on layers
type OverlaySetShowDebugBordersParams struct {
	// True for showing debug borders
	Show bool `json:"show"`
}

func OverlaySetShowDebugBorders(show bool) *OverlaySetShowDebugBordersParams {
	return &OverlaySetShowDebugBordersParams{
		Show: show,
	}
}

func (p *OverlaySetShowDebugBordersParams) CDPMethodName() string {
	return "Overlay.setShowDebugBorders"
}

// Requests that backend shows the FPS counter
type OverlaySetShowFPSCounterParams struct {
	// True for showing the FPS counter
	Show bool `json:"show"`
}

func OverlaySetShowFPSCounter(show bool) *OverlaySetShowFPSCounterParams {
	return &OverlaySetShowFPSCounterParams{
		Show: show,
	}
}

func (p *OverlaySetShowFPSCounterParams) CDPMethodName() string {
	return "Overlay.setShowFPSCounter"
}

// Highlight multiple elements with the CSS Grid overlay.
type OverlaySetShowGridOverlaysParams struct {
	// An array of node identifiers and descriptors for the highlight appearance.
	GridNodeHighlightConfigs []OverlayGridNodeHighlightConfig `json:"gridNodeHighlightConfigs"`
}

func OverlaySetShowGridOverlays(gridNodeHighlightConfigs []OverlayGridNodeHighlightConfig) *OverlaySetShowGridOverlaysParams {
	return &OverlaySetShowGridOverlaysParams{
		GridNodeHighlightConfigs: gridNodeHighlightConfigs,
	}
}

func (p *OverlaySetShowGridOverlaysParams) CDPMethodName() string {
	return "Overlay.setShowGridOverlays"
}

type OverlaySetShowFlexOverlaysParams struct {
	// An array of node identifiers and descriptors for the highlight appearance.
	FlexNodeHighlightConfigs []OverlayFlexNodeHighlightConfig `json:"flexNodeHighlightConfigs"`
}

func OverlaySetShowFlexOverlays(flexNodeHighlightConfigs []OverlayFlexNodeHighlightConfig) *OverlaySetShowFlexOverlaysParams {
	return &OverlaySetShowFlexOverlaysParams{
		FlexNodeHighlightConfigs: flexNodeHighlightConfigs,
	}
}

func (p *OverlaySetShowFlexOverlaysParams) CDPMethodName() string {
	return "Overlay.setShowFlexOverlays"
}

type OverlaySetShowScrollSnapOverlaysParams struct {
	// An array of node identifiers and descriptors for the highlight appearance.
	ScrollSnapHighlightConfigs []OverlayScrollSnapHighlightConfig `json:"scrollSnapHighlightConfigs"`
}

func OverlaySetShowScrollSnapOverlays(scrollSnapHighlightConfigs []OverlayScrollSnapHighlightConfig) *OverlaySetShowScrollSnapOverlaysParams {
	return &OverlaySetShowScrollSnapOverlaysParams{
		ScrollSnapHighlightConfigs: scrollSnapHighlightConfigs,
	}
}

func (p *OverlaySetShowScrollSnapOverlaysParams) CDPMethodName() string {
	return "Overlay.setShowScrollSnapOverlays"
}

type OverlaySetShowContainerQueryOverlaysParams struct {
	// An array of node identifiers and descriptors for the highlight appearance.
	ContainerQueryHighlightConfigs []OverlayContainerQueryHighlightConfig `json:"containerQueryHighlightConfigs"`
}

func OverlaySetShowContainerQueryOverlays(containerQueryHighlightConfigs []OverlayContainerQueryHighlightConfig) *OverlaySetShowContainerQueryOverlaysParams {
	return &OverlaySetShowContainerQueryOverlaysParams{
		ContainerQueryHighlightConfigs: containerQueryHighlightConfigs,
	}
}

func (p *OverlaySetShowContainerQueryOverlaysParams) CDPMethodName() string {
	return "Overlay.setShowContainerQueryOverlays"
}

type OverlaySetShowInspectedElementAnchorParams struct {
	// Node identifier for which to show an anchor for.
	InspectedElementAnchorConfig OverlayInspectedElementAnchorConfig `json:"inspectedElementAnchorConfig"`
}

func OverlaySetShowInspectedElementAnchor(inspectedElementAnchorConfig OverlayInspectedElementAnchorConfig) *OverlaySetShowInspectedElementAnchorParams {
	return &OverlaySetShowInspectedElementAnchorParams{
		InspectedElementAnchorConfig: inspectedElementAnchorConfig,
	}
}

func (p *OverlaySetShowInspectedElementAnchorParams) CDPMethodName() string {
	return "Overlay.setShowInspectedElementAnchor"
}

// Requests that backend shows paint rectangles
type OverlaySetShowPaintRectsParams struct {
	// True for showing paint rectangles
	Result bool `json:"result"`
}

func OverlaySetShowPaintRects(result bool) *OverlaySetShowPaintRectsParams {
	return &OverlaySetShowPaintRectsParams{
		Result: result,
	}
}

func (p *OverlaySetShowPaintRectsParams) CDPMethodName() string {
	return "Overlay.setShowPaintRects"
}

// Requests that backend shows layout shift regions
type OverlaySetShowLayoutShiftRegionsParams struct {
	// True for showing layout shift regions
	Result bool `json:"result"`
}

func OverlaySetShowLayoutShiftRegions(result bool) *OverlaySetShowLayoutShiftRegionsParams {
	return &OverlaySetShowLayoutShiftRegionsParams{
		Result: result,
	}
}

func (p *OverlaySetShowLayoutShiftRegionsParams) CDPMethodName() string {
	return "Overlay.setShowLayoutShiftRegions"
}

// Requests that backend shows scroll bottleneck rects
type OverlaySetShowScrollBottleneckRectsParams struct {
	// True for showing scroll bottleneck rects
	Show bool `json:"show"`
}

func OverlaySetShowScrollBottleneckRects(show bool) *OverlaySetShowScrollBottleneckRectsParams {
	return &OverlaySetShowScrollBottleneckRectsParams{
		Show: show,
	}
}

func (p *OverlaySetShowScrollBottleneckRectsParams) CDPMethodName() string {
	return "Overlay.setShowScrollBottleneckRects"
}

// Deprecated, no longer has any effect.
type OverlaySetShowHitTestBordersParams struct {
	// True for showing hit-test borders
	Show bool `json:"show"`
}

func OverlaySetShowHitTestBorders(show bool) *OverlaySetShowHitTestBordersParams {
	return &OverlaySetShowHitTestBordersParams{
		Show: show,
	}
}

func (p *OverlaySetShowHitTestBordersParams) CDPMethodName() string {
	return "Overlay.setShowHitTestBorders"
}

// Deprecated, no longer has any effect.
type OverlaySetShowWebVitalsParams struct {
	Show bool `json:"show"`
}

func OverlaySetShowWebVitals(show bool) *OverlaySetShowWebVitalsParams {
	return &OverlaySetShowWebVitalsParams{
		Show: show,
	}
}

func (p *OverlaySetShowWebVitalsParams) CDPMethodName() string {
	return "Overlay.setShowWebVitals"
}

// Paints viewport size upon main frame resize.
type OverlaySetShowViewportSizeOnResizeParams struct {
	// Whether to paint size or not.
	Show bool `json:"show"`
}

func OverlaySetShowViewportSizeOnResize(show bool) *OverlaySetShowViewportSizeOnResizeParams {
	return &OverlaySetShowViewportSizeOnResizeParams{
		Show: show,
	}
}

func (p *OverlaySetShowViewportSizeOnResizeParams) CDPMethodName() string {
	return "Overlay.setShowViewportSizeOnResize"
}

// Add a dual screen device hinge
type OverlaySetShowHingeParams struct {
	// hinge data, null means hideHinge
	HingeConfig *OverlayHingeConfig `json:"hingeConfig,omitempty"`
}

func OverlaySetShowHinge() *OverlaySetShowHingeParams {
	return &OverlaySetShowHingeParams{}
}

func (p *OverlaySetShowHingeParams) WithHingeConfig(v OverlayHingeConfig) *OverlaySetShowHingeParams {
	p.HingeConfig = &v
	return p
}

func (p *OverlaySetShowHingeParams) CDPMethodName() string {
	return "Overlay.setShowHinge"
}

// Show elements in isolation mode with overlays.
type OverlaySetShowIsolatedElementsParams struct {
	// An array of node identifiers and descriptors for the highlight appearance.
	IsolatedElementHighlightConfigs []OverlayIsolatedElementHighlightConfig `json:"isolatedElementHighlightConfigs"`
}

func OverlaySetShowIsolatedElements(isolatedElementHighlightConfigs []OverlayIsolatedElementHighlightConfig) *OverlaySetShowIsolatedElementsParams {
	return &OverlaySetShowIsolatedElementsParams{
		IsolatedElementHighlightConfigs: isolatedElementHighlightConfigs,
	}
}

func (p *OverlaySetShowIsolatedElementsParams) CDPMethodName() string {
	return "Overlay.setShowIsolatedElements"
}

// Show Window Controls Overlay for PWA
type OverlaySetShowWindowControlsOverlayParams struct {
	// Window Controls Overlay data, null means hide Window Controls Overlay
	WindowControlsOverlayConfig *OverlayWindowControlsOverlayConfig `json:"windowControlsOverlayConfig,omitempty"`
}

func OverlaySetShowWindowControlsOverlay() *OverlaySetShowWindowControlsOverlayParams {
	return &OverlaySetShowWindowControlsOverlayParams{}
}

func (p *OverlaySetShowWindowControlsOverlayParams) WithWindowControlsOverlayConfig(v OverlayWindowControlsOverlayConfig) *OverlaySetShowWindowControlsOverlayParams {
	p.WindowControlsOverlayConfig = &v
	return p
}

func (p *OverlaySetShowWindowControlsOverlayParams) CDPMethodName() string {
	return "Overlay.setShowWindowControlsOverlay"
}

// Fired when the node should be inspected. This happens after call to `setInspectMode` or when
// user manually inspects an element.
const EventOverlayInspectNodeRequested = "Overlay.inspectNodeRequested"

type OverlayInspectNodeRequestedEvent struct {
	// Id of the node to inspect.
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
}

func (e *OverlayInspectNodeRequestedEvent) CDPEventName() string {
	return EventOverlayInspectNodeRequested
}

// Fired when the node should be highlighted. This happens after call to `setInspectMode`.
const EventOverlayNodeHighlightRequested = "Overlay.nodeHighlightRequested"

type OverlayNodeHighlightRequestedEvent struct {
	NodeId DOMNodeId `json:"nodeId"`
}

func (e *OverlayNodeHighlightRequestedEvent) CDPEventName() string {
	return EventOverlayNodeHighlightRequested
}

// Fired when user asks to capture screenshot of some area on the page.
const EventOverlayScreenshotRequested = "Overlay.screenshotRequested"

type OverlayScreenshotRequestedEvent struct {
	// Viewport to capture, in device independent pixels (dip).
	Viewport PageViewport `json:"viewport"`
}

func (e *OverlayScreenshotRequestedEvent) CDPEventName() string {
	return EventOverlayScreenshotRequested
}

// Fired when user asks to show the Inspect panel.
const EventOverlayInspectPanelShowRequested = "Overlay.inspectPanelShowRequested"

type OverlayInspectPanelShowRequestedEvent struct {
	// Id of the node to show in the panel.
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
}

func (e *OverlayInspectPanelShowRequestedEvent) CDPEventName() string {
	return EventOverlayInspectPanelShowRequested
}

// Fired when user asks to restore the Inspected Element floating window.
const EventOverlayInspectedElementWindowRestored = "Overlay.inspectedElementWindowRestored"

type OverlayInspectedElementWindowRestoredEvent struct {
	// Id of the node to restore the floating window for.
	BackendNodeId DOMBackendNodeId `json:"backendNodeId"`
}

func (e *OverlayInspectedElementWindowRestoredEvent) CDPEventName() string {
	return EventOverlayInspectedElementWindowRestored
}

// Fired when user cancels the inspect mode.
const EventOverlayInspectModeCanceled = "Overlay.inspectModeCanceled"

type OverlayInspectModeCanceledEvent struct {
}

func (e *OverlayInspectModeCanceledEvent) CDPEventName() string {
	return EventOverlayInspectModeCanceled
}
