// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Run-time execution metric.
type PerformanceMetric struct {
	// Metric name.
	Name string `json:"name"`
	// Metric value.
	Value float64 `json:"value"`
}

// Disable collecting and reporting metrics.
type PerformanceDisableParams struct {
}

func PerformanceDisable() *PerformanceDisableParams {
	return &PerformanceDisableParams{}
}

func (p *PerformanceDisableParams) CDPMethodName() string {
	return "Performance.disable"
}

// Enable collecting and reporting metrics.
type PerformanceEnableParams struct {
	// Time domain to use for collecting and reporting duration metrics.
	TimeDomain *string `json:"timeDomain,omitempty"`
}

func PerformanceEnable() *PerformanceEnableParams {
	return &PerformanceEnableParams{}
}

func (p *PerformanceEnableParams) WithTimeDomain(v string) *PerformanceEnableParams {
	p.TimeDomain = &v
	return p
}

func (p *PerformanceEnableParams) CDPMethodName() string {
	return "Performance.enable"
}

// Sets time domain to use for collecting and reporting duration metrics.
// Note that this must be called before enabling metrics collection. Calling
// this method while metrics collection is enabled returns an error.
type PerformanceSetTimeDomainParams struct {
	// Time domain
	TimeDomain string `json:"timeDomain"`
}

func PerformanceSetTimeDomain(timeDomain string) *PerformanceSetTimeDomainParams {
	return &PerformanceSetTimeDomainParams{
		TimeDomain: timeDomain,
	}
}

func (p *PerformanceSetTimeDomainParams) CDPMethodName() string {
	return "Performance.setTimeDomain"
}

// Retrieve current values of run-time metrics.
type PerformanceGetMetricsParams struct {
}

type PerformanceGetMetricsReturns struct {
	// Current values for run-time metrics.
	Metrics []PerformanceMetric `json:"metrics"`
}

func PerformanceGetMetrics() *PerformanceGetMetricsParams {
	return &PerformanceGetMetricsParams{}
}

func (p *PerformanceGetMetricsParams) CDPMethodName() string {
	return "Performance.getMetrics"
}

// Current values of the metrics.
const EventPerformanceMetrics = "Performance.metrics"

type PerformanceMetricsEvent struct {
	// Current values of the metrics.
	Metrics []PerformanceMetric `json:"metrics"`
	// Timestamp title.
	Title string `json:"title"`
}

func (e *PerformanceMetricsEvent) CDPEventName() string {
	return EventPerformanceMetrics
}
