// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Profile node. Holds callsite information, execution statistics and child nodes.
type ProfilerProfileNode struct {
	// Unique id of the node.
	Id int64 `json:"id"`
	// Function location.
	CallFrame RuntimeCallFrame `json:"callFrame"`
	// Number of samples where this node was on top of the call stack.
	HitCount *int64 `json:"hitCount,omitempty"`
	// Child node ids.
	Children []int64 `json:"children,omitempty"`
	// The reason of being not optimized. The function may be deoptimized or marked as don't
	// optimize.
	DeoptReason *string `json:"deoptReason,omitempty"`
	// An array of source position ticks.
	PositionTicks []ProfilerPositionTickInfo `json:"positionTicks,omitempty"`
}

// Profile.
type ProfilerProfile struct {
	// The list of profile nodes. First item is the root node.
	Nodes []ProfilerProfileNode `json:"nodes"`
	// Profiling start timestamp in microseconds.
	StartTime float64 `json:"startTime"`
	// Profiling end timestamp in microseconds.
	EndTime float64 `json:"endTime"`
	// Ids of samples top nodes.
	Samples []int64 `json:"samples,omitempty"`
	// Time intervals between adjacent samples in microseconds. The first delta is relative to the
	// profile startTime.
	TimeDeltas []int64 `json:"timeDeltas,omitempty"`
}

// Specifies a number of samples attributed to a certain source position.
type ProfilerPositionTickInfo struct {
	// Source line number (1-based).
	Line int64 `json:"line"`
	// Number of samples attributed to the source line.
	Ticks int64 `json:"ticks"`
}

// Coverage data for a source range.
type ProfilerCoverageRange struct {
	// JavaScript script source offset for the range start.
	StartOffset int64 `json:"startOffset"`
	// JavaScript script source offset for the range end.
	EndOffset int64 `json:"endOffset"`
	// Collected execution count of the source range.
	Count int64 `json:"count"`
}

// Coverage data for a JavaScript function.
type ProfilerFunctionCoverage struct {
	// JavaScript function name.
	FunctionName string `json:"functionName"`
	// Source ranges inside the function with coverage data.
	Ranges []ProfilerCoverageRange `json:"ranges"`
	// Whether coverage data for this function has block granularity.
	IsBlockCoverage bool `json:"isBlockCoverage"`
}

// Coverage data for a JavaScript script.
type ProfilerScriptCoverage struct {
	// JavaScript script id.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// JavaScript script name or url.
	Url string `json:"url"`
	// Functions contained in the script that has coverage data.
	Functions []ProfilerFunctionCoverage `json:"functions"`
}

type ProfilerDisableParams struct {
}

func ProfilerDisable() *ProfilerDisableParams {
	return &ProfilerDisableParams{}
}

func (p *ProfilerDisableParams) CDPMethodName() string {
	return "Profiler.disable"
}

type ProfilerEnableParams struct {
}

func ProfilerEnable() *ProfilerEnableParams {
	return &ProfilerEnableParams{}
}

func (p *ProfilerEnableParams) CDPMethodName() string {
	return "Profiler.enable"
}

// Collect coverage data for the current isolate. The coverage data may be incomplete due to
// garbage collection.
type ProfilerGetBestEffortCoverageParams struct {
}

type ProfilerGetBestEffortCoverageReturns struct {
	// Coverage data for the current isolate.
	Result []ProfilerScriptCoverage `json:"result"`
}

func ProfilerGetBestEffortCoverage() *ProfilerGetBestEffortCoverageParams {
	return &ProfilerGetBestEffortCoverageParams{}
}

func (p *ProfilerGetBestEffortCoverageParams) CDPMethodName() string {
	return "Profiler.getBestEffortCoverage"
}

// Changes CPU profiler sampling interval. Must be called before CPU profiles recording started.
type ProfilerSetSamplingIntervalParams struct {
	// New sampling interval in microseconds.
	Interval int64 `json:"interval"`
}

func ProfilerSetSamplingInterval(interval int64) *ProfilerSetSamplingIntervalParams {
	return &ProfilerSetSamplingIntervalParams{
		Interval: interval,
	}
}

func (p *ProfilerSetSamplingIntervalParams) CDPMethodName() string {
	return "Profiler.setSamplingInterval"
}

type ProfilerStartParams struct {
}

func ProfilerStart() *ProfilerStartParams {
	return &ProfilerStartParams{}
}

func (p *ProfilerStartParams) CDPMethodName() string {
	return "Profiler.start"
}

// Enable precise code coverage. Coverage data for JavaScript executed before enabling precise code
// coverage may be incomplete. Enabling prevents running optimized code and resets execution
// counters.
type ProfilerStartPreciseCoverageParams struct {
	// Collect accurate call counts beyond simple 'covered' or 'not covered'.
	CallCount *bool `json:"callCount,omitempty"`
	// Collect block-based coverage.
	Detailed *bool `json:"detailed,omitempty"`
	// Allow the backend to send updates on its own initiative
	AllowTriggeredUpdates *bool `json:"allowTriggeredUpdates,omitempty"`
}

type ProfilerStartPreciseCoverageReturns struct {
	// Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
	Timestamp float64 `json:"timestamp"`
}

func ProfilerStartPreciseCoverage() *ProfilerStartPreciseCoverageParams {
	return &ProfilerStartPreciseCoverageParams{}
}

func (p *ProfilerStartPreciseCoverageParams) WithCallCount(v bool) *ProfilerStartPreciseCoverageParams {
	p.CallCount = &v
	return p
}

func (p *ProfilerStartPreciseCoverageParams) WithDetailed(v bool) *ProfilerStartPreciseCoverageParams {
	p.Detailed = &v
	return p
}

func (p *ProfilerStartPreciseCoverageParams) WithAllowTriggeredUpdates(v bool) *ProfilerStartPreciseCoverageParams {
	p.AllowTriggeredUpdates = &v
	return p
}

func (p *ProfilerStartPreciseCoverageParams) CDPMethodName() string {
	return "Profiler.startPreciseCoverage"
}

type ProfilerStopParams struct {
}

type ProfilerStopReturns struct {
	// Recorded profile.
	Profile ProfilerProfile `json:"profile"`
}

func ProfilerStop() *ProfilerStopParams {
	return &ProfilerStopParams{}
}

func (p *ProfilerStopParams) CDPMethodName() string {
	return "Profiler.stop"
}

// Disable precise code coverage. Disabling releases unnecessary execution count records and allows
// executing optimized code.
type ProfilerStopPreciseCoverageParams struct {
}

func ProfilerStopPreciseCoverage() *ProfilerStopPreciseCoverageParams {
	return &ProfilerStopPreciseCoverageParams{}
}

func (p *ProfilerStopPreciseCoverageParams) CDPMethodName() string {
	return "Profiler.stopPreciseCoverage"
}

// Collect coverage data for the current isolate, and resets execution counters. Precise code
// coverage needs to have started.
type ProfilerTakePreciseCoverageParams struct {
}

type ProfilerTakePreciseCoverageReturns struct {
	// Coverage data for the current isolate.
	Result []ProfilerScriptCoverage `json:"result"`
	// Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
	Timestamp float64 `json:"timestamp"`
}

func ProfilerTakePreciseCoverage() *ProfilerTakePreciseCoverageParams {
	return &ProfilerTakePreciseCoverageParams{}
}

func (p *ProfilerTakePreciseCoverageParams) CDPMethodName() string {
	return "Profiler.takePreciseCoverage"
}

const EventProfilerConsoleProfileFinished = "Profiler.consoleProfileFinished"

type ProfilerConsoleProfileFinishedEvent struct {
	Id string `json:"id"`
	// Location of console.profileEnd().
	Location DebuggerLocation `json:"location"`
	Profile  ProfilerProfile  `json:"profile"`
	// Profile title passed as an argument to console.profile().
	Title *string `json:"title,omitempty"`
}

func (e *ProfilerConsoleProfileFinishedEvent) CDPEventName() string {
	return EventProfilerConsoleProfileFinished
}

// Sent when new profile recording is started using console.profile() call.
const EventProfilerConsoleProfileStarted = "Profiler.consoleProfileStarted"

type ProfilerConsoleProfileStartedEvent struct {
	Id string `json:"id"`
	// Location of console.profile().
	Location DebuggerLocation `json:"location"`
	// Profile title passed as an argument to console.profile().
	Title *string `json:"title,omitempty"`
}

func (e *ProfilerConsoleProfileStartedEvent) CDPEventName() string {
	return EventProfilerConsoleProfileStarted
}

// Reports coverage delta since the last poll (either from an event like this, or from
// `takePreciseCoverage` for the current isolate. May only be sent if precise code
// coverage has been started. This event can be trigged by the embedder to, for example,
// trigger collection of coverage data immediately at a certain point in time.
const EventProfilerPreciseCoverageDeltaUpdate = "Profiler.preciseCoverageDeltaUpdate"

type ProfilerPreciseCoverageDeltaUpdateEvent struct {
	// Monotonically increasing time (in seconds) when the coverage update was taken in the backend.
	Timestamp float64 `json:"timestamp"`
	// Identifier for distinguishing coverage events.
	Occasion string `json:"occasion"`
	// Coverage data for the current isolate.
	Result []ProfilerScriptCoverage `json:"result"`
}

func (e *ProfilerPreciseCoverageDeltaUpdateEvent) CDPEventName() string {
	return EventProfilerPreciseCoverageDeltaUpdate
}
