// Code generated by cdpgen; DO NOT EDIT.

package cdp

// The following types are the replica of
// https://crsrc.org/c/chrome/browser/web_applications/proto/web_app_os_integration_state.proto;drc=9910d3be894c8f142c977ba1023f30a656bc13fc;l=67
type PWAFileHandlerAccept struct {
	// New name of the mimetype according to
	// https://www.iana.org/assignments/media-types/media-types.xhtml
	MediaType      string   `json:"mediaType"`
	FileExtensions []string `json:"fileExtensions"`
}

type PWAFileHandler struct {
	Action      string                 `json:"action"`
	Accepts     []PWAFileHandlerAccept `json:"accepts"`
	DisplayName string                 `json:"displayName"`
}

// If user prefers opening the app in browser or an app window.
type PWADisplayMode string

const (
	PWADisplayModeStandalone PWADisplayMode = "standalone"
	PWADisplayModeBrowser    PWADisplayMode = "browser"
)

// Returns the following OS state for the given manifest id.
type PWAGetOsAppStateParams struct {
	// The id from the webapp's manifest file, commonly it's the url of the
	// site installing the webapp. See
	// https://web.dev/learn/pwa/web-app-manifest.
	ManifestId string `json:"manifestId"`
}

type PWAGetOsAppStateReturns struct {
	BadgeCount   int64            `json:"badgeCount"`
	FileHandlers []PWAFileHandler `json:"fileHandlers"`
}

func PWAGetOsAppState(manifestId string) *PWAGetOsAppStateParams {
	return &PWAGetOsAppStateParams{
		ManifestId: manifestId,
	}
}

func (p *PWAGetOsAppStateParams) CDPMethodName() string {
	return "PWA.getOsAppState"
}

// Installs the given manifest identity, optionally using the given installUrlOrBundleUrl
//
// IWA-specific install description:
// manifestId corresponds to isolated-app:// + web_package::SignedWebBundleId
//
// File installation mode:
// The installUrlOrBundleUrl can be either file:// or http(s):// pointing
// to a signed web bundle (.swbn). In this case SignedWebBundleId must correspond to
// The .swbn file's signing key.
//
// Dev proxy installation mode:
// installUrlOrBundleUrl must be http(s):// that serves dev mode IWA.
// web_package::SignedWebBundleId must be of type dev proxy.
//
// The advantage of dev proxy mode is that all changes to IWA
// automatically will be reflected in the running app without
// reinstallation.
//
// To generate bundle id for proxy mode:
//  1. Generate 32 random bytes.
//  2. Add a specific suffix at the end following the documentation
//     https://github.com/WICG/isolated-web-apps/blob/main/Scheme.md#suffix
//  3. Encode the entire sequence using Base32 without padding.
//
// If Chrome is not in IWA dev
// mode, the installation will fail, regardless of the state of the allowlist.
type PWAInstallParams struct {
	ManifestId string `json:"manifestId"`
	// The location of the app or bundle overriding the one derived from the
	// manifestId.
	InstallUrlOrBundleUrl *string `json:"installUrlOrBundleUrl,omitempty"`
}

func PWAInstall(manifestId string) *PWAInstallParams {
	return &PWAInstallParams{
		ManifestId: manifestId,
	}
}

func (p *PWAInstallParams) WithInstallUrlOrBundleUrl(v string) *PWAInstallParams {
	p.InstallUrlOrBundleUrl = &v
	return p
}

func (p *PWAInstallParams) CDPMethodName() string {
	return "PWA.install"
}

// Uninstalls the given manifest_id and closes any opened app windows.
type PWAUninstallParams struct {
	ManifestId string `json:"manifestId"`
}

func PWAUninstall(manifestId string) *PWAUninstallParams {
	return &PWAUninstallParams{
		ManifestId: manifestId,
	}
}

func (p *PWAUninstallParams) CDPMethodName() string {
	return "PWA.uninstall"
}

// Launches the installed web app, or an url in the same web app instead of the
// default start url if it is provided. Returns a page Target.TargetID which
// can be used to attach to via Target.attachToTarget or similar APIs.
type PWALaunchParams struct {
	ManifestId string  `json:"manifestId"`
	Url        *string `json:"url,omitempty"`
}

type PWALaunchReturns struct {
	// ID of the tab target created as a result.
	TargetId TargetTargetID `json:"targetId"`
}

func PWALaunch(manifestId string) *PWALaunchParams {
	return &PWALaunchParams{
		ManifestId: manifestId,
	}
}

func (p *PWALaunchParams) WithUrl(v string) *PWALaunchParams {
	p.Url = &v
	return p
}

func (p *PWALaunchParams) CDPMethodName() string {
	return "PWA.launch"
}

// Opens one or more local files from an installed web app identified by its
// manifestId. The web app needs to have file handlers registered to process
// the files. The API returns one or more page Target.TargetIDs which can be
// used to attach to via Target.attachToTarget or similar APIs.
// If some files in the parameters cannot be handled by the web app, they will
// be ignored. If none of the files can be handled, this API returns an error.
// If no files are provided as the parameter, this API also returns an error.
//
// According to the definition of the file handlers in the manifest file, one
// Target.TargetID may represent a page handling one or more files. The order
// of the returned Target.TargetIDs is not guaranteed.
//
// TODO(crbug.com/339454034): Check the existences of the input files.
type PWALaunchFilesInAppParams struct {
	ManifestId string   `json:"manifestId"`
	Files      []string `json:"files"`
}

type PWALaunchFilesInAppReturns struct {
	// IDs of the tab targets created as the result.
	TargetIds []TargetTargetID `json:"targetIds"`
}

func PWALaunchFilesInApp(manifestId string, files []string) *PWALaunchFilesInAppParams {
	return &PWALaunchFilesInAppParams{
		ManifestId: manifestId,
		Files:      files,
	}
}

func (p *PWALaunchFilesInAppParams) CDPMethodName() string {
	return "PWA.launchFilesInApp"
}

// Opens the current page in its web app identified by the manifest id, needs
// to be called on a page target. This function returns immediately without
// waiting for the app to finish loading.
type PWAOpenCurrentPageInAppParams struct {
	ManifestId string `json:"manifestId"`
}

func PWAOpenCurrentPageInApp(manifestId string) *PWAOpenCurrentPageInAppParams {
	return &PWAOpenCurrentPageInAppParams{
		ManifestId: manifestId,
	}
}

func (p *PWAOpenCurrentPageInAppParams) CDPMethodName() string {
	return "PWA.openCurrentPageInApp"
}

// Changes user settings of the web app identified by its manifestId. If the
// app was not installed, this command returns an error. Unset parameters will
// be ignored; unrecognized values will cause an error.
//
// Unlike the ones defined in the manifest files of the web apps, these
// settings are provided by the browser and controlled by the users, they
// impact the way the browser handling the web apps.
//
// See the comment of each parameter.
type PWAChangeAppUserSettingsParams struct {
	ManifestId string `json:"manifestId"`
	// If user allows the links clicked on by the user in the app's scope, or
	// extended scope if the manifest has scope extensions and the flags
	// `DesktopPWAsLinkCapturingWithScopeExtensions` and
	// `WebAppEnableScopeExtensions` are enabled.
	//
	// Note, the API does not support resetting the linkCapturing to the
	// initial value, uninstalling and installing the web app again will reset
	// it.
	//
	// TODO(crbug.com/339453269): Setting this value on ChromeOS is not
	// supported yet.
	LinkCapturing *bool           `json:"linkCapturing,omitempty"`
	DisplayMode   *PWADisplayMode `json:"displayMode,omitempty"`
}

func PWAChangeAppUserSettings(manifestId string) *PWAChangeAppUserSettingsParams {
	return &PWAChangeAppUserSettingsParams{
		ManifestId: manifestId,
	}
}

func (p *PWAChangeAppUserSettingsParams) WithLinkCapturing(v bool) *PWAChangeAppUserSettingsParams {
	p.LinkCapturing = &v
	return p
}

func (p *PWAChangeAppUserSettingsParams) WithDisplayMode(v PWADisplayMode) *PWAChangeAppUserSettingsParams {
	p.DisplayMode = &v
	return p
}

func (p *PWAChangeAppUserSettingsParams) CDPMethodName() string {
	return "PWA.changeAppUserSettings"
}
