// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Unique script identifier.
type RuntimeScriptId string

// Represents options for serialization. Overrides `generatePreview` and `returnByValue`.
type RuntimeSerializationOptions struct {
	Serialization string `json:"serialization"`
	// Deep serialization depth. Default is full depth. Respected only in `deep` serialization mode.
	MaxDepth *int64 `json:"maxDepth,omitempty"`
	// Embedder-specific parameters. For example if connected to V8 in Chrome these control DOM
	// serialization via `maxNodeDepth: integer` and `includeShadowTree: "none" | "open" | "all"`.
	// Values can be only of type string or integer.
	AdditionalParameters map[string]any `json:"additionalParameters,omitempty"`
}

// Represents deep serialized value.
type RuntimeDeepSerializedValue struct {
	Type     string  `json:"type"`
	Value    any     `json:"value,omitempty"`
	ObjectId *string `json:"objectId,omitempty"`
	// Set if value reference met more then once during serialization. In such
	// case, value is provided only to one of the serialized values. Unique
	// per value in the scope of one CDP call.
	WeakLocalObjectReference *int64 `json:"weakLocalObjectReference,omitempty"`
}

// Unique object identifier.
type RuntimeRemoteObjectId string

// Primitive value which cannot be JSON-stringified. Includes values `-0`, `NaN`, `Infinity`,
// `-Infinity`, and bigint literals.
type RuntimeUnserializableValue string

// Mirror object referencing original JavaScript object.
type RuntimeRemoteObject struct {
	// Object type.
	Type string `json:"type"`
	// Object subtype hint. Specified for `object` type values only.
	// NOTE: If you change anything here, make sure to also update
	// `subtype` in `ObjectPreview` and `PropertyPreview` below.
	Subtype *string `json:"subtype,omitempty"`
	// Object class (constructor) name. Specified for `object` type values only.
	ClassName *string `json:"className,omitempty"`
	// Remote object value in case of primitive values or JSON values (if it was requested).
	Value any `json:"value,omitempty"`
	// Primitive value which can not be JSON-stringified does not have `value`, but gets this
	// property.
	UnserializableValue *RuntimeUnserializableValue `json:"unserializableValue,omitempty"`
	// String representation of the object.
	Description *string `json:"description,omitempty"`
	// Deep serialized value.
	DeepSerializedValue *RuntimeDeepSerializedValue `json:"deepSerializedValue,omitempty"`
	// Unique object identifier (for non-primitive values).
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// Preview containing abbreviated property values. Specified for `object` type values only.
	Preview       *RuntimeObjectPreview `json:"preview,omitempty"`
	CustomPreview *RuntimeCustomPreview `json:"customPreview,omitempty"`
}

type RuntimeCustomPreview struct {
	// The JSON-stringified result of formatter.header(object, config) call.
	// It contains json ML array that represents RemoteObject.
	Header string `json:"header"`
	// If formatter returns true as a result of formatter.hasBody call then bodyGetterId will
	// contain RemoteObjectId for the function that returns result of formatter.body(object, config) call.
	// The result value is json ML array.
	BodyGetterId *RuntimeRemoteObjectId `json:"bodyGetterId,omitempty"`
}

// Object containing abbreviated remote object value.
type RuntimeObjectPreview struct {
	// Object type.
	Type string `json:"type"`
	// Object subtype hint. Specified for `object` type values only.
	Subtype *string `json:"subtype,omitempty"`
	// String representation of the object.
	Description *string `json:"description,omitempty"`
	// True iff some of the properties or entries of the original object did not fit.
	Overflow bool `json:"overflow"`
	// List of the properties.
	Properties []RuntimePropertyPreview `json:"properties"`
	// List of the entries. Specified for `map` and `set` subtype values only.
	Entries []RuntimeEntryPreview `json:"entries,omitempty"`
}

type RuntimePropertyPreview struct {
	// Property name.
	Name string `json:"name"`
	// Object type. Accessor means that the property itself is an accessor property.
	Type string `json:"type"`
	// User-friendly property value string.
	Value *string `json:"value,omitempty"`
	// Nested value preview.
	ValuePreview *RuntimeObjectPreview `json:"valuePreview,omitempty"`
	// Object subtype hint. Specified for `object` type values only.
	Subtype *string `json:"subtype,omitempty"`
}

type RuntimeEntryPreview struct {
	// Preview of the key. Specified for map-like collection entries.
	Key *RuntimeObjectPreview `json:"key,omitempty"`
	// Preview of the value.
	Value RuntimeObjectPreview `json:"value"`
}

// Object property descriptor.
type RuntimePropertyDescriptor struct {
	// Property name or symbol description.
	Name string `json:"name"`
	// The value associated with the property.
	Value *RuntimeRemoteObject `json:"value,omitempty"`
	// True if the value associated with the property may be changed (data descriptors only).
	Writable *bool `json:"writable,omitempty"`
	// A function which serves as a getter for the property, or `undefined` if there is no getter
	// (accessor descriptors only).
	Get *RuntimeRemoteObject `json:"get,omitempty"`
	// A function which serves as a setter for the property, or `undefined` if there is no setter
	// (accessor descriptors only).
	Set *RuntimeRemoteObject `json:"set,omitempty"`
	// True if the type of this property descriptor may be changed and if the property may be
	// deleted from the corresponding object.
	Configurable bool `json:"configurable"`
	// True if this property shows up during enumeration of the properties on the corresponding
	// object.
	Enumerable bool `json:"enumerable"`
	// True if the result was thrown during the evaluation.
	WasThrown *bool `json:"wasThrown,omitempty"`
	// True if the property is owned for the object.
	IsOwn *bool `json:"isOwn,omitempty"`
	// Property symbol object, if the property is of the `symbol` type.
	Symbol *RuntimeRemoteObject `json:"symbol,omitempty"`
}

// Object internal property descriptor. This property isn't normally visible in JavaScript code.
type RuntimeInternalPropertyDescriptor struct {
	// Conventional property name.
	Name string `json:"name"`
	// The value associated with the property.
	Value *RuntimeRemoteObject `json:"value,omitempty"`
}

// Object private field descriptor.
type RuntimePrivatePropertyDescriptor struct {
	// Private property name.
	Name string `json:"name"`
	// The value associated with the private property.
	Value *RuntimeRemoteObject `json:"value,omitempty"`
	// A function which serves as a getter for the private property,
	// or `undefined` if there is no getter (accessor descriptors only).
	Get *RuntimeRemoteObject `json:"get,omitempty"`
	// A function which serves as a setter for the private property,
	// or `undefined` if there is no setter (accessor descriptors only).
	Set *RuntimeRemoteObject `json:"set,omitempty"`
}

// Represents function call argument. Either remote object id `objectId`, primitive `value`,
// unserializable primitive value or neither of (for undefined) them should be specified.
type RuntimeCallArgument struct {
	// Primitive value or serializable javascript object.
	Value any `json:"value,omitempty"`
	// Primitive value which can not be JSON-stringified.
	UnserializableValue *RuntimeUnserializableValue `json:"unserializableValue,omitempty"`
	// Remote object handle.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
}

// Id of an execution context.
type RuntimeExecutionContextId int64

// Description of an isolated world.
type RuntimeExecutionContextDescription struct {
	// Unique id of the execution context. It can be used to specify in which execution context
	// script evaluation should be performed.
	Id RuntimeExecutionContextId `json:"id"`
	// Execution context origin.
	Origin string `json:"origin"`
	// Human readable name describing given context.
	Name string `json:"name"`
	// A system-unique execution context identifier. Unlike the id, this is unique across
	// multiple processes, so can be reliably used to identify specific context while backend
	// performs a cross-process navigation.
	UniqueId string `json:"uniqueId"`
	// Embedder-specific auxiliary data likely matching {isDefault: boolean, type: 'default'|'isolated'|'worker', frameId: string}
	AuxData map[string]any `json:"auxData,omitempty"`
}

// Detailed information about exception (or error) that was thrown during script compilation or
// execution.
type RuntimeExceptionDetails struct {
	// Exception id.
	ExceptionId int64 `json:"exceptionId"`
	// Exception text, which should be used together with exception object when available.
	Text string `json:"text"`
	// Line number of the exception location (0-based).
	LineNumber int64 `json:"lineNumber"`
	// Column number of the exception location (0-based).
	ColumnNumber int64 `json:"columnNumber"`
	// Script ID of the exception location.
	ScriptId *RuntimeScriptId `json:"scriptId,omitempty"`
	// URL of the exception location, to be used when the script was not reported.
	Url *string `json:"url,omitempty"`
	// JavaScript stack trace if available.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
	// Exception object if available.
	Exception *RuntimeRemoteObject `json:"exception,omitempty"`
	// Identifier of the context where exception happened.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
	// Dictionary with entries of meta data that the client associated
	// with this exception, such as information about associated network
	// requests, etc.
	ExceptionMetaData map[string]any `json:"exceptionMetaData,omitempty"`
}

// Number of milliseconds since epoch.
type RuntimeTimestamp float64

// Number of milliseconds.
type RuntimeTimeDelta float64

// Stack entry for runtime errors and assertions.
type RuntimeCallFrame struct {
	// JavaScript function name.
	FunctionName string `json:"functionName"`
	// JavaScript script id.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// JavaScript script name or url.
	Url string `json:"url"`
	// JavaScript script line number (0-based).
	LineNumber int64 `json:"lineNumber"`
	// JavaScript script column number (0-based).
	ColumnNumber int64 `json:"columnNumber"`
}

// Call frames for assertions or error messages.
type RuntimeStackTrace struct {
	// String label of this stack trace. For async traces this may be a name of the function that
	// initiated the async call.
	Description *string `json:"description,omitempty"`
	// JavaScript function name.
	CallFrames []RuntimeCallFrame `json:"callFrames"`
	// Asynchronous JavaScript stack trace that preceded this stack, if available.
	Parent *RuntimeStackTrace `json:"parent,omitempty"`
	// Asynchronous JavaScript stack trace that preceded this stack, if available.
	ParentId *RuntimeStackTraceId `json:"parentId,omitempty"`
}

// Unique identifier of current debugger.
type RuntimeUniqueDebuggerId string

// If `debuggerId` is set stack trace comes from another debugger and can be resolved there. This
// allows to track cross-debugger calls. See `Runtime.StackTrace` and `Debugger.paused` for usages.
type RuntimeStackTraceId struct {
	Id         string                   `json:"id"`
	DebuggerId *RuntimeUniqueDebuggerId `json:"debuggerId,omitempty"`
}

// Add handler to promise with given promise object id.
type RuntimeAwaitPromiseParams struct {
	// Identifier of the promise.
	PromiseObjectId RuntimeRemoteObjectId `json:"promiseObjectId"`
	// Whether the result is expected to be a JSON object that should be sent by value.
	ReturnByValue *bool `json:"returnByValue,omitempty"`
	// Whether preview should be generated for the result.
	GeneratePreview *bool `json:"generatePreview,omitempty"`
}

type RuntimeAwaitPromiseReturns struct {
	// Promise result. Will contain rejected value if promise was rejected.
	Result RuntimeRemoteObject `json:"result"`
	// Exception details if stack strace is available.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeAwaitPromise(promiseObjectId RuntimeRemoteObjectId) *RuntimeAwaitPromiseParams {
	return &RuntimeAwaitPromiseParams{
		PromiseObjectId: promiseObjectId,
	}
}

func (p *RuntimeAwaitPromiseParams) WithReturnByValue(v bool) *RuntimeAwaitPromiseParams {
	p.ReturnByValue = &v
	return p
}

func (p *RuntimeAwaitPromiseParams) WithGeneratePreview(v bool) *RuntimeAwaitPromiseParams {
	p.GeneratePreview = &v
	return p
}

func (p *RuntimeAwaitPromiseParams) CDPMethodName() string {
	return "Runtime.awaitPromise"
}

// Calls function with given declaration on the given object. Object group of the result is
// inherited from the target object.
type RuntimeCallFunctionOnParams struct {
	// Declaration of the function to call.
	FunctionDeclaration string `json:"functionDeclaration"`
	// Identifier of the object to call function on. Either objectId or executionContextId should
	// be specified.
	ObjectId *RuntimeRemoteObjectId `json:"objectId,omitempty"`
	// Call arguments. All call arguments must belong to the same JavaScript world as the target
	// object.
	Arguments []RuntimeCallArgument `json:"arguments,omitempty"`
	// In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent *bool `json:"silent,omitempty"`
	// Whether the result is expected to be a JSON object which should be sent by value.
	// Can be overriden by `serializationOptions`.
	ReturnByValue *bool `json:"returnByValue,omitempty"`
	// Whether preview should be generated for the result.
	GeneratePreview *bool `json:"generatePreview,omitempty"`
	// Whether execution should be treated as initiated by user in the UI.
	UserGesture *bool `json:"userGesture,omitempty"`
	// Whether execution should `await` for resulting value and return once awaited promise is
	// resolved.
	AwaitPromise *bool `json:"awaitPromise,omitempty"`
	// Specifies execution context which global object will be used to call function on. Either
	// executionContextId or objectId should be specified.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
	// Symbolic group name that can be used to release multiple objects. If objectGroup is not
	// specified and objectId is, objectGroup will be inherited from object.
	ObjectGroup *string `json:"objectGroup,omitempty"`
	// Whether to throw an exception if side effect cannot be ruled out during evaluation.
	ThrowOnSideEffect *bool `json:"throwOnSideEffect,omitempty"`
	// An alternative way to specify the execution context to call function on.
	// Compared to contextId that may be reused across processes, this is guaranteed to be
	// system-unique, so it can be used to prevent accidental function call
	// in context different than intended (e.g. as a result of navigation across process
	// boundaries).
	// This is mutually exclusive with `executionContextId`.
	UniqueContextId *string `json:"uniqueContextId,omitempty"`
	// Specifies the result serialization. If provided, overrides
	// `generatePreview` and `returnByValue`.
	SerializationOptions *RuntimeSerializationOptions `json:"serializationOptions,omitempty"`
}

type RuntimeCallFunctionOnReturns struct {
	// Call result.
	Result RuntimeRemoteObject `json:"result"`
	// Exception details.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeCallFunctionOn(functionDeclaration string) *RuntimeCallFunctionOnParams {
	return &RuntimeCallFunctionOnParams{
		FunctionDeclaration: functionDeclaration,
	}
}

func (p *RuntimeCallFunctionOnParams) WithObjectId(v RuntimeRemoteObjectId) *RuntimeCallFunctionOnParams {
	p.ObjectId = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithArguments(v []RuntimeCallArgument) *RuntimeCallFunctionOnParams {
	p.Arguments = v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithSilent(v bool) *RuntimeCallFunctionOnParams {
	p.Silent = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithReturnByValue(v bool) *RuntimeCallFunctionOnParams {
	p.ReturnByValue = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithGeneratePreview(v bool) *RuntimeCallFunctionOnParams {
	p.GeneratePreview = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithUserGesture(v bool) *RuntimeCallFunctionOnParams {
	p.UserGesture = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithAwaitPromise(v bool) *RuntimeCallFunctionOnParams {
	p.AwaitPromise = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithExecutionContextId(v RuntimeExecutionContextId) *RuntimeCallFunctionOnParams {
	p.ExecutionContextId = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithObjectGroup(v string) *RuntimeCallFunctionOnParams {
	p.ObjectGroup = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithThrowOnSideEffect(v bool) *RuntimeCallFunctionOnParams {
	p.ThrowOnSideEffect = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithUniqueContextId(v string) *RuntimeCallFunctionOnParams {
	p.UniqueContextId = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) WithSerializationOptions(v RuntimeSerializationOptions) *RuntimeCallFunctionOnParams {
	p.SerializationOptions = &v
	return p
}

func (p *RuntimeCallFunctionOnParams) CDPMethodName() string {
	return "Runtime.callFunctionOn"
}

// Compiles expression.
type RuntimeCompileScriptParams struct {
	// Expression to compile.
	Expression string `json:"expression"`
	// Source url to be set for the script.
	SourceURL string `json:"sourceURL"`
	// Specifies whether the compiled script should be persisted.
	PersistScript bool `json:"persistScript"`
	// Specifies in which execution context to perform script run. If the parameter is omitted the
	// evaluation will be performed in the context of the inspected page.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
}

type RuntimeCompileScriptReturns struct {
	// Id of the script.
	ScriptId *RuntimeScriptId `json:"scriptId,omitempty"`
	// Exception details.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeCompileScript(expression string, sourceURL string, persistScript bool) *RuntimeCompileScriptParams {
	return &RuntimeCompileScriptParams{
		Expression:    expression,
		SourceURL:     sourceURL,
		PersistScript: persistScript,
	}
}

func (p *RuntimeCompileScriptParams) WithExecutionContextId(v RuntimeExecutionContextId) *RuntimeCompileScriptParams {
	p.ExecutionContextId = &v
	return p
}

func (p *RuntimeCompileScriptParams) CDPMethodName() string {
	return "Runtime.compileScript"
}

// Disables reporting of execution contexts creation.
type RuntimeDisableParams struct {
}

func RuntimeDisable() *RuntimeDisableParams {
	return &RuntimeDisableParams{}
}

func (p *RuntimeDisableParams) CDPMethodName() string {
	return "Runtime.disable"
}

// Discards collected exceptions and console API calls.
type RuntimeDiscardConsoleEntriesParams struct {
}

func RuntimeDiscardConsoleEntries() *RuntimeDiscardConsoleEntriesParams {
	return &RuntimeDiscardConsoleEntriesParams{}
}

func (p *RuntimeDiscardConsoleEntriesParams) CDPMethodName() string {
	return "Runtime.discardConsoleEntries"
}

// Enables reporting of execution contexts creation by means of `executionContextCreated` event.
// When the reporting gets enabled the event will be sent immediately for each existing execution
// context.
type RuntimeEnableParams struct {
}

func RuntimeEnable() *RuntimeEnableParams {
	return &RuntimeEnableParams{}
}

func (p *RuntimeEnableParams) CDPMethodName() string {
	return "Runtime.enable"
}

// Evaluates expression on global object.
type RuntimeEvaluateParams struct {
	// Expression to evaluate.
	Expression string `json:"expression"`
	// Symbolic group name that can be used to release multiple objects.
	ObjectGroup *string `json:"objectGroup,omitempty"`
	// Determines whether Command Line API should be available during the evaluation.
	IncludeCommandLineAPI *bool `json:"includeCommandLineAPI,omitempty"`
	// In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent *bool `json:"silent,omitempty"`
	// Specifies in which execution context to perform evaluation. If the parameter is omitted the
	// evaluation will be performed in the context of the inspected page.
	// This is mutually exclusive with `uniqueContextId`, which offers an
	// alternative way to identify the execution context that is more reliable
	// in a multi-process environment.
	ContextId *RuntimeExecutionContextId `json:"contextId,omitempty"`
	// Whether the result is expected to be a JSON object that should be sent by value.
	ReturnByValue *bool `json:"returnByValue,omitempty"`
	// Whether preview should be generated for the result.
	GeneratePreview *bool `json:"generatePreview,omitempty"`
	// Whether execution should be treated as initiated by user in the UI.
	UserGesture *bool `json:"userGesture,omitempty"`
	// Whether execution should `await` for resulting value and return once awaited promise is
	// resolved.
	AwaitPromise *bool `json:"awaitPromise,omitempty"`
	// Whether to throw an exception if side effect cannot be ruled out during evaluation.
	// This implies `disableBreaks` below.
	ThrowOnSideEffect *bool `json:"throwOnSideEffect,omitempty"`
	// Terminate execution after timing out (number of milliseconds).
	Timeout *RuntimeTimeDelta `json:"timeout,omitempty"`
	// Disable breakpoints during execution.
	DisableBreaks *bool `json:"disableBreaks,omitempty"`
	// Setting this flag to true enables `let` re-declaration and top-level `await`.
	// Note that `let` variables can only be re-declared if they originate from
	// `replMode` themselves.
	ReplMode *bool `json:"replMode,omitempty"`
	// The Content Security Policy (CSP) for the target might block 'unsafe-eval'
	// which includes eval(), Function(), setTimeout() and setInterval()
	// when called with non-callable arguments. This flag bypasses CSP for this
	// evaluation and allows unsafe-eval. Defaults to true.
	AllowUnsafeEvalBlockedByCSP *bool `json:"allowUnsafeEvalBlockedByCSP,omitempty"`
	// An alternative way to specify the execution context to evaluate in.
	// Compared to contextId that may be reused across processes, this is guaranteed to be
	// system-unique, so it can be used to prevent accidental evaluation of the expression
	// in context different than intended (e.g. as a result of navigation across process
	// boundaries).
	// This is mutually exclusive with `contextId`.
	UniqueContextId *string `json:"uniqueContextId,omitempty"`
	// Specifies the result serialization. If provided, overrides
	// `generatePreview` and `returnByValue`.
	SerializationOptions *RuntimeSerializationOptions `json:"serializationOptions,omitempty"`
}

type RuntimeEvaluateReturns struct {
	// Evaluation result.
	Result RuntimeRemoteObject `json:"result"`
	// Exception details.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeEvaluate(expression string) *RuntimeEvaluateParams {
	return &RuntimeEvaluateParams{
		Expression: expression,
	}
}

func (p *RuntimeEvaluateParams) WithObjectGroup(v string) *RuntimeEvaluateParams {
	p.ObjectGroup = &v
	return p
}

func (p *RuntimeEvaluateParams) WithIncludeCommandLineAPI(v bool) *RuntimeEvaluateParams {
	p.IncludeCommandLineAPI = &v
	return p
}

func (p *RuntimeEvaluateParams) WithSilent(v bool) *RuntimeEvaluateParams {
	p.Silent = &v
	return p
}

func (p *RuntimeEvaluateParams) WithContextId(v RuntimeExecutionContextId) *RuntimeEvaluateParams {
	p.ContextId = &v
	return p
}

func (p *RuntimeEvaluateParams) WithReturnByValue(v bool) *RuntimeEvaluateParams {
	p.ReturnByValue = &v
	return p
}

func (p *RuntimeEvaluateParams) WithGeneratePreview(v bool) *RuntimeEvaluateParams {
	p.GeneratePreview = &v
	return p
}

func (p *RuntimeEvaluateParams) WithUserGesture(v bool) *RuntimeEvaluateParams {
	p.UserGesture = &v
	return p
}

func (p *RuntimeEvaluateParams) WithAwaitPromise(v bool) *RuntimeEvaluateParams {
	p.AwaitPromise = &v
	return p
}

func (p *RuntimeEvaluateParams) WithThrowOnSideEffect(v bool) *RuntimeEvaluateParams {
	p.ThrowOnSideEffect = &v
	return p
}

func (p *RuntimeEvaluateParams) WithTimeout(v RuntimeTimeDelta) *RuntimeEvaluateParams {
	p.Timeout = &v
	return p
}

func (p *RuntimeEvaluateParams) WithDisableBreaks(v bool) *RuntimeEvaluateParams {
	p.DisableBreaks = &v
	return p
}

func (p *RuntimeEvaluateParams) WithReplMode(v bool) *RuntimeEvaluateParams {
	p.ReplMode = &v
	return p
}

func (p *RuntimeEvaluateParams) WithAllowUnsafeEvalBlockedByCSP(v bool) *RuntimeEvaluateParams {
	p.AllowUnsafeEvalBlockedByCSP = &v
	return p
}

func (p *RuntimeEvaluateParams) WithUniqueContextId(v string) *RuntimeEvaluateParams {
	p.UniqueContextId = &v
	return p
}

func (p *RuntimeEvaluateParams) WithSerializationOptions(v RuntimeSerializationOptions) *RuntimeEvaluateParams {
	p.SerializationOptions = &v
	return p
}

func (p *RuntimeEvaluateParams) CDPMethodName() string {
	return "Runtime.evaluate"
}

// Returns the isolate id.
type RuntimeGetIsolateIdParams struct {
}

type RuntimeGetIsolateIdReturns struct {
	// The isolate id.
	Id string `json:"id"`
}

func RuntimeGetIsolateId() *RuntimeGetIsolateIdParams {
	return &RuntimeGetIsolateIdParams{}
}

func (p *RuntimeGetIsolateIdParams) CDPMethodName() string {
	return "Runtime.getIsolateId"
}

// Returns the JavaScript heap usage.
// It is the total usage of the corresponding isolate not scoped to a particular Runtime.
type RuntimeGetHeapUsageParams struct {
}

type RuntimeGetHeapUsageReturns struct {
	// Used JavaScript heap size in bytes.
	UsedSize float64 `json:"usedSize"`
	// Allocated JavaScript heap size in bytes.
	TotalSize float64 `json:"totalSize"`
	// Used size in bytes in the embedder's garbage-collected heap.
	EmbedderHeapUsedSize float64 `json:"embedderHeapUsedSize"`
	// Size in bytes of backing storage for array buffers and external strings.
	BackingStorageSize float64 `json:"backingStorageSize"`
}

func RuntimeGetHeapUsage() *RuntimeGetHeapUsageParams {
	return &RuntimeGetHeapUsageParams{}
}

func (p *RuntimeGetHeapUsageParams) CDPMethodName() string {
	return "Runtime.getHeapUsage"
}

// Returns properties of a given object. Object group of the result is inherited from the target
// object.
type RuntimeGetPropertiesParams struct {
	// Identifier of the object to return properties for.
	ObjectId RuntimeRemoteObjectId `json:"objectId"`
	// If true, returns properties belonging only to the element itself, not to its prototype
	// chain.
	OwnProperties *bool `json:"ownProperties,omitempty"`
	// If true, returns accessor properties (with getter/setter) only; internal properties are not
	// returned either.
	AccessorPropertiesOnly *bool `json:"accessorPropertiesOnly,omitempty"`
	// Whether preview should be generated for the results.
	GeneratePreview *bool `json:"generatePreview,omitempty"`
	// If true, returns non-indexed properties only.
	NonIndexedPropertiesOnly *bool `json:"nonIndexedPropertiesOnly,omitempty"`
}

type RuntimeGetPropertiesReturns struct {
	// Object properties.
	Result []RuntimePropertyDescriptor `json:"result"`
	// Internal object properties (only of the element itself).
	InternalProperties []RuntimeInternalPropertyDescriptor `json:"internalProperties,omitempty"`
	// Object private properties.
	PrivateProperties []RuntimePrivatePropertyDescriptor `json:"privateProperties,omitempty"`
	// Exception details.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeGetProperties(objectId RuntimeRemoteObjectId) *RuntimeGetPropertiesParams {
	return &RuntimeGetPropertiesParams{
		ObjectId: objectId,
	}
}

func (p *RuntimeGetPropertiesParams) WithOwnProperties(v bool) *RuntimeGetPropertiesParams {
	p.OwnProperties = &v
	return p
}

func (p *RuntimeGetPropertiesParams) WithAccessorPropertiesOnly(v bool) *RuntimeGetPropertiesParams {
	p.AccessorPropertiesOnly = &v
	return p
}

func (p *RuntimeGetPropertiesParams) WithGeneratePreview(v bool) *RuntimeGetPropertiesParams {
	p.GeneratePreview = &v
	return p
}

func (p *RuntimeGetPropertiesParams) WithNonIndexedPropertiesOnly(v bool) *RuntimeGetPropertiesParams {
	p.NonIndexedPropertiesOnly = &v
	return p
}

func (p *RuntimeGetPropertiesParams) CDPMethodName() string {
	return "Runtime.getProperties"
}

// Returns all let, const and class variables from global scope.
type RuntimeGlobalLexicalScopeNamesParams struct {
	// Specifies in which execution context to lookup global scope variables.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
}

type RuntimeGlobalLexicalScopeNamesReturns struct {
	Names []string `json:"names"`
}

func RuntimeGlobalLexicalScopeNames() *RuntimeGlobalLexicalScopeNamesParams {
	return &RuntimeGlobalLexicalScopeNamesParams{}
}

func (p *RuntimeGlobalLexicalScopeNamesParams) WithExecutionContextId(v RuntimeExecutionContextId) *RuntimeGlobalLexicalScopeNamesParams {
	p.ExecutionContextId = &v
	return p
}

func (p *RuntimeGlobalLexicalScopeNamesParams) CDPMethodName() string {
	return "Runtime.globalLexicalScopeNames"
}

type RuntimeQueryObjectsParams struct {
	// Identifier of the prototype to return objects for.
	PrototypeObjectId RuntimeRemoteObjectId `json:"prototypeObjectId"`
	// Symbolic group name that can be used to release the results.
	ObjectGroup *string `json:"objectGroup,omitempty"`
}

type RuntimeQueryObjectsReturns struct {
	// Array with objects.
	Objects RuntimeRemoteObject `json:"objects"`
}

func RuntimeQueryObjects(prototypeObjectId RuntimeRemoteObjectId) *RuntimeQueryObjectsParams {
	return &RuntimeQueryObjectsParams{
		PrototypeObjectId: prototypeObjectId,
	}
}

func (p *RuntimeQueryObjectsParams) WithObjectGroup(v string) *RuntimeQueryObjectsParams {
	p.ObjectGroup = &v
	return p
}

func (p *RuntimeQueryObjectsParams) CDPMethodName() string {
	return "Runtime.queryObjects"
}

// Releases remote object with given id.
type RuntimeReleaseObjectParams struct {
	// Identifier of the object to release.
	ObjectId RuntimeRemoteObjectId `json:"objectId"`
}

func RuntimeReleaseObject(objectId RuntimeRemoteObjectId) *RuntimeReleaseObjectParams {
	return &RuntimeReleaseObjectParams{
		ObjectId: objectId,
	}
}

func (p *RuntimeReleaseObjectParams) CDPMethodName() string {
	return "Runtime.releaseObject"
}

// Releases all remote objects that belong to a given group.
type RuntimeReleaseObjectGroupParams struct {
	// Symbolic object group name.
	ObjectGroup string `json:"objectGroup"`
}

func RuntimeReleaseObjectGroup(objectGroup string) *RuntimeReleaseObjectGroupParams {
	return &RuntimeReleaseObjectGroupParams{
		ObjectGroup: objectGroup,
	}
}

func (p *RuntimeReleaseObjectGroupParams) CDPMethodName() string {
	return "Runtime.releaseObjectGroup"
}

// Tells inspected instance to run if it was waiting for debugger to attach.
type RuntimeRunIfWaitingForDebuggerParams struct {
}

func RuntimeRunIfWaitingForDebugger() *RuntimeRunIfWaitingForDebuggerParams {
	return &RuntimeRunIfWaitingForDebuggerParams{}
}

func (p *RuntimeRunIfWaitingForDebuggerParams) CDPMethodName() string {
	return "Runtime.runIfWaitingForDebugger"
}

// Runs script with given id in a given context.
type RuntimeRunScriptParams struct {
	// Id of the script to run.
	ScriptId RuntimeScriptId `json:"scriptId"`
	// Specifies in which execution context to perform script run. If the parameter is omitted the
	// evaluation will be performed in the context of the inspected page.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
	// Symbolic group name that can be used to release multiple objects.
	ObjectGroup *string `json:"objectGroup,omitempty"`
	// In silent mode exceptions thrown during evaluation are not reported and do not pause
	// execution. Overrides `setPauseOnException` state.
	Silent *bool `json:"silent,omitempty"`
	// Determines whether Command Line API should be available during the evaluation.
	IncludeCommandLineAPI *bool `json:"includeCommandLineAPI,omitempty"`
	// Whether the result is expected to be a JSON object which should be sent by value.
	ReturnByValue *bool `json:"returnByValue,omitempty"`
	// Whether preview should be generated for the result.
	GeneratePreview *bool `json:"generatePreview,omitempty"`
	// Whether execution should `await` for resulting value and return once awaited promise is
	// resolved.
	AwaitPromise *bool `json:"awaitPromise,omitempty"`
}

type RuntimeRunScriptReturns struct {
	// Run result.
	Result RuntimeRemoteObject `json:"result"`
	// Exception details.
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeRunScript(scriptId RuntimeScriptId) *RuntimeRunScriptParams {
	return &RuntimeRunScriptParams{
		ScriptId: scriptId,
	}
}

func (p *RuntimeRunScriptParams) WithExecutionContextId(v RuntimeExecutionContextId) *RuntimeRunScriptParams {
	p.ExecutionContextId = &v
	return p
}

func (p *RuntimeRunScriptParams) WithObjectGroup(v string) *RuntimeRunScriptParams {
	p.ObjectGroup = &v
	return p
}

func (p *RuntimeRunScriptParams) WithSilent(v bool) *RuntimeRunScriptParams {
	p.Silent = &v
	return p
}

func (p *RuntimeRunScriptParams) WithIncludeCommandLineAPI(v bool) *RuntimeRunScriptParams {
	p.IncludeCommandLineAPI = &v
	return p
}

func (p *RuntimeRunScriptParams) WithReturnByValue(v bool) *RuntimeRunScriptParams {
	p.ReturnByValue = &v
	return p
}

func (p *RuntimeRunScriptParams) WithGeneratePreview(v bool) *RuntimeRunScriptParams {
	p.GeneratePreview = &v
	return p
}

func (p *RuntimeRunScriptParams) WithAwaitPromise(v bool) *RuntimeRunScriptParams {
	p.AwaitPromise = &v
	return p
}

func (p *RuntimeRunScriptParams) CDPMethodName() string {
	return "Runtime.runScript"
}

// Enables or disables async call stacks tracking.
type RuntimeSetAsyncCallStackDepthParams struct {
	// Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async
	// call stacks (default).
	MaxDepth int64 `json:"maxDepth"`
}

func RuntimeSetAsyncCallStackDepth(maxDepth int64) *RuntimeSetAsyncCallStackDepthParams {
	return &RuntimeSetAsyncCallStackDepthParams{
		MaxDepth: maxDepth,
	}
}

func (p *RuntimeSetAsyncCallStackDepthParams) CDPMethodName() string {
	return "Runtime.setAsyncCallStackDepth"
}

type RuntimeSetCustomObjectFormatterEnabledParams struct {
	Enabled bool `json:"enabled"`
}

func RuntimeSetCustomObjectFormatterEnabled(enabled bool) *RuntimeSetCustomObjectFormatterEnabledParams {
	return &RuntimeSetCustomObjectFormatterEnabledParams{
		Enabled: enabled,
	}
}

func (p *RuntimeSetCustomObjectFormatterEnabledParams) CDPMethodName() string {
	return "Runtime.setCustomObjectFormatterEnabled"
}

type RuntimeSetMaxCallStackSizeToCaptureParams struct {
	Size int64 `json:"size"`
}

func RuntimeSetMaxCallStackSizeToCapture(size int64) *RuntimeSetMaxCallStackSizeToCaptureParams {
	return &RuntimeSetMaxCallStackSizeToCaptureParams{
		Size: size,
	}
}

func (p *RuntimeSetMaxCallStackSizeToCaptureParams) CDPMethodName() string {
	return "Runtime.setMaxCallStackSizeToCapture"
}

// Terminate current or next JavaScript execution.
// Will cancel the termination when the outer-most script execution ends.
type RuntimeTerminateExecutionParams struct {
}

func RuntimeTerminateExecution() *RuntimeTerminateExecutionParams {
	return &RuntimeTerminateExecutionParams{}
}

func (p *RuntimeTerminateExecutionParams) CDPMethodName() string {
	return "Runtime.terminateExecution"
}

// If executionContextId is empty, adds binding with the given name on the
// global objects of all inspected contexts, including those created later,
// bindings survive reloads.
// Binding function takes exactly one argument, this argument should be string,
// in case of any other input, function throws an exception.
// Each binding function call produces Runtime.bindingCalled notification.
type RuntimeAddBindingParams struct {
	Name string `json:"name"`
	// If specified, the binding would only be exposed to the specified
	// execution context. If omitted and `executionContextName` is not set,
	// the binding is exposed to all execution contexts of the target.
	// This parameter is mutually exclusive with `executionContextName`.
	// Deprecated in favor of `executionContextName` due to an unclear use case
	// and bugs in implementation (crbug.com/1169639). `executionContextId` will be
	// removed in the future.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
	// If specified, the binding is exposed to the executionContext with
	// matching name, even for contexts created after the binding is added.
	// See also `ExecutionContext.name` and `worldName` parameter to
	// `Page.addScriptToEvaluateOnNewDocument`.
	// This parameter is mutually exclusive with `executionContextId`.
	ExecutionContextName *string `json:"executionContextName,omitempty"`
}

func RuntimeAddBinding(name string) *RuntimeAddBindingParams {
	return &RuntimeAddBindingParams{
		Name: name,
	}
}

func (p *RuntimeAddBindingParams) WithExecutionContextId(v RuntimeExecutionContextId) *RuntimeAddBindingParams {
	p.ExecutionContextId = &v
	return p
}

func (p *RuntimeAddBindingParams) WithExecutionContextName(v string) *RuntimeAddBindingParams {
	p.ExecutionContextName = &v
	return p
}

func (p *RuntimeAddBindingParams) CDPMethodName() string {
	return "Runtime.addBinding"
}

// This method does not remove binding function from global object but
// unsubscribes current runtime agent from Runtime.bindingCalled notifications.
type RuntimeRemoveBindingParams struct {
	Name string `json:"name"`
}

func RuntimeRemoveBinding(name string) *RuntimeRemoveBindingParams {
	return &RuntimeRemoveBindingParams{
		Name: name,
	}
}

func (p *RuntimeRemoveBindingParams) CDPMethodName() string {
	return "Runtime.removeBinding"
}

// This method tries to lookup and populate exception details for a
// JavaScript Error object.
// Note that the stackTrace portion of the resulting exceptionDetails will
// only be populated if the Runtime domain was enabled at the time when the
// Error was thrown.
type RuntimeGetExceptionDetailsParams struct {
	// The error object for which to resolve the exception details.
	ErrorObjectId RuntimeRemoteObjectId `json:"errorObjectId"`
}

type RuntimeGetExceptionDetailsReturns struct {
	ExceptionDetails *RuntimeExceptionDetails `json:"exceptionDetails,omitempty"`
}

func RuntimeGetExceptionDetails(errorObjectId RuntimeRemoteObjectId) *RuntimeGetExceptionDetailsParams {
	return &RuntimeGetExceptionDetailsParams{
		ErrorObjectId: errorObjectId,
	}
}

func (p *RuntimeGetExceptionDetailsParams) CDPMethodName() string {
	return "Runtime.getExceptionDetails"
}

// Notification is issued every time when binding is called.
const EventRuntimeBindingCalled = "Runtime.bindingCalled"

type RuntimeBindingCalledEvent struct {
	Name    string `json:"name"`
	Payload string `json:"payload"`
	// Identifier of the context where the call was made.
	ExecutionContextId RuntimeExecutionContextId `json:"executionContextId"`
}

func (e *RuntimeBindingCalledEvent) CDPEventName() string {
	return EventRuntimeBindingCalled
}

// Issued when console API was called.
const EventRuntimeConsoleAPICalled = "Runtime.consoleAPICalled"

type RuntimeConsoleAPICalledEvent struct {
	// Type of the call.
	Type string `json:"type"`
	// Call arguments.
	Args []RuntimeRemoteObject `json:"args"`
	// Identifier of the context where the call was made.
	ExecutionContextId RuntimeExecutionContextId `json:"executionContextId"`
	// Call timestamp.
	Timestamp RuntimeTimestamp `json:"timestamp"`
	// Stack trace captured when the call was made. The async stack chain is automatically reported for
	// the following call types: `assert`, `error`, `trace`, `warning`. For other types the async call
	// chain can be retrieved using `Debugger.getStackTrace` and `stackTrace.parentId` field.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
	// Console context descriptor for calls on non-default console context (not console.*):
	// 'anonymous#unique-logger-id' for call on unnamed context, 'name#unique-logger-id' for call
	// on named context.
	Context *string `json:"context,omitempty"`
}

func (e *RuntimeConsoleAPICalledEvent) CDPEventName() string {
	return EventRuntimeConsoleAPICalled
}

// Issued when unhandled exception was revoked.
const EventRuntimeExceptionRevoked = "Runtime.exceptionRevoked"

type RuntimeExceptionRevokedEvent struct {
	// Reason describing why exception was revoked.
	Reason string `json:"reason"`
	// The id of revoked exception, as reported in `exceptionThrown`.
	ExceptionId int64 `json:"exceptionId"`
}

func (e *RuntimeExceptionRevokedEvent) CDPEventName() string {
	return EventRuntimeExceptionRevoked
}

// Issued when exception was thrown and unhandled.
const EventRuntimeExceptionThrown = "Runtime.exceptionThrown"

type RuntimeExceptionThrownEvent struct {
	// Timestamp of the exception.
	Timestamp        RuntimeTimestamp        `json:"timestamp"`
	ExceptionDetails RuntimeExceptionDetails `json:"exceptionDetails"`
}

func (e *RuntimeExceptionThrownEvent) CDPEventName() string {
	return EventRuntimeExceptionThrown
}

// Issued when new execution context is created.
const EventRuntimeExecutionContextCreated = "Runtime.executionContextCreated"

type RuntimeExecutionContextCreatedEvent struct {
	// A newly created execution context.
	Context RuntimeExecutionContextDescription `json:"context"`
}

func (e *RuntimeExecutionContextCreatedEvent) CDPEventName() string {
	return EventRuntimeExecutionContextCreated
}

// Issued when execution context is destroyed.
const EventRuntimeExecutionContextDestroyed = "Runtime.executionContextDestroyed"

type RuntimeExecutionContextDestroyedEvent struct {
	// Id of the destroyed context
	ExecutionContextId RuntimeExecutionContextId `json:"executionContextId"`
	// Unique Id of the destroyed context
	ExecutionContextUniqueId string `json:"executionContextUniqueId"`
}

func (e *RuntimeExecutionContextDestroyedEvent) CDPEventName() string {
	return EventRuntimeExecutionContextDestroyed
}

// Issued when all executionContexts were cleared in browser
const EventRuntimeExecutionContextsCleared = "Runtime.executionContextsCleared"

type RuntimeExecutionContextsClearedEvent struct {
}

func (e *RuntimeExecutionContextsClearedEvent) CDPEventName() string {
	return EventRuntimeExecutionContextsCleared
}

// Issued when object should be inspected (for example, as a result of inspect() command line API
// call).
const EventRuntimeInspectRequested = "Runtime.inspectRequested"

type RuntimeInspectRequestedEvent struct {
	Object RuntimeRemoteObject `json:"object"`
	Hints  map[string]any      `json:"hints"`
	// Identifier of the context where the call was made.
	ExecutionContextId *RuntimeExecutionContextId `json:"executionContextId,omitempty"`
}

func (e *RuntimeInspectRequestedEvent) CDPEventName() string {
	return EventRuntimeInspectRequested
}
