// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Description of the protocol domain.
type SchemaDomain struct {
	// Domain name.
	Name string `json:"name"`
	// Domain version.
	Version string `json:"version"`
}

// Returns supported domains.
type SchemaGetDomainsParams struct {
}

type SchemaGetDomainsReturns struct {
	// List of supported domains.
	Domains []SchemaDomain `json:"domains"`
}

func SchemaGetDomains() *SchemaGetDomainsParams {
	return &SchemaGetDomainsParams{}
}

func (p *SchemaGetDomainsParams) CDPMethodName() string {
	return "Schema.getDomains"
}
