// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Indicates the PC/SC error code.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__ErrorCodes.html
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/secauthn/authentication-return-values
type SmartCardEmulationResultCode string

const (
	SmartCardEmulationResultCodeSuccess            SmartCardEmulationResultCode = "success"
	SmartCardEmulationResultCodeRemovedCard        SmartCardEmulationResultCode = "removed-card"
	SmartCardEmulationResultCodeResetCard          SmartCardEmulationResultCode = "reset-card"
	SmartCardEmulationResultCodeUnpoweredCard      SmartCardEmulationResultCode = "unpowered-card"
	SmartCardEmulationResultCodeUnresponsiveCard   SmartCardEmulationResultCode = "unresponsive-card"
	SmartCardEmulationResultCodeUnsupportedCard    SmartCardEmulationResultCode = "unsupported-card"
	SmartCardEmulationResultCodeReaderUnavailable  SmartCardEmulationResultCode = "reader-unavailable"
	SmartCardEmulationResultCodeSharingViolation   SmartCardEmulationResultCode = "sharing-violation"
	SmartCardEmulationResultCodeNotTransacted      SmartCardEmulationResultCode = "not-transacted"
	SmartCardEmulationResultCodeNoSmartcard        SmartCardEmulationResultCode = "no-smartcard"
	SmartCardEmulationResultCodeProtoMismatch      SmartCardEmulationResultCode = "proto-mismatch"
	SmartCardEmulationResultCodeSystemCancelled    SmartCardEmulationResultCode = "system-cancelled"
	SmartCardEmulationResultCodeNotReady           SmartCardEmulationResultCode = "not-ready"
	SmartCardEmulationResultCodeCancelled          SmartCardEmulationResultCode = "cancelled"
	SmartCardEmulationResultCodeInsufficientBuffer SmartCardEmulationResultCode = "insufficient-buffer"
	SmartCardEmulationResultCodeInvalidHandle      SmartCardEmulationResultCode = "invalid-handle"
	SmartCardEmulationResultCodeInvalidParameter   SmartCardEmulationResultCode = "invalid-parameter"
	SmartCardEmulationResultCodeInvalidValue       SmartCardEmulationResultCode = "invalid-value"
	SmartCardEmulationResultCodeNoMemory           SmartCardEmulationResultCode = "no-memory"
	SmartCardEmulationResultCodeTimeout            SmartCardEmulationResultCode = "timeout"
	SmartCardEmulationResultCodeUnknownReader      SmartCardEmulationResultCode = "unknown-reader"
	SmartCardEmulationResultCodeUnsupportedFeature SmartCardEmulationResultCode = "unsupported-feature"
	SmartCardEmulationResultCodeNoReadersAvailable SmartCardEmulationResultCode = "no-readers-available"
	SmartCardEmulationResultCodeServiceStopped     SmartCardEmulationResultCode = "service-stopped"
	SmartCardEmulationResultCodeNoService          SmartCardEmulationResultCode = "no-service"
	SmartCardEmulationResultCodeCommError          SmartCardEmulationResultCode = "comm-error"
	SmartCardEmulationResultCodeInternalError      SmartCardEmulationResultCode = "internal-error"
	SmartCardEmulationResultCodeServerTooBusy      SmartCardEmulationResultCode = "server-too-busy"
	SmartCardEmulationResultCodeUnexpected         SmartCardEmulationResultCode = "unexpected"
	SmartCardEmulationResultCodeShutdown           SmartCardEmulationResultCode = "shutdown"
	SmartCardEmulationResultCodeUnknownCard        SmartCardEmulationResultCode = "unknown-card"
	SmartCardEmulationResultCodeUnknown            SmartCardEmulationResultCode = "unknown"
)

// Maps to the |SCARD_SHARE_*| values.
type SmartCardEmulationShareMode string

const (
	SmartCardEmulationShareModeShared    SmartCardEmulationShareMode = "shared"
	SmartCardEmulationShareModeExclusive SmartCardEmulationShareMode = "exclusive"
	SmartCardEmulationShareModeDirect    SmartCardEmulationShareMode = "direct"
)

// Indicates what the reader should do with the card.
type SmartCardEmulationDisposition string

const (
	SmartCardEmulationDispositionLeaveCard   SmartCardEmulationDisposition = "leave-card"
	SmartCardEmulationDispositionResetCard   SmartCardEmulationDisposition = "reset-card"
	SmartCardEmulationDispositionUnpowerCard SmartCardEmulationDisposition = "unpower-card"
	SmartCardEmulationDispositionEjectCard   SmartCardEmulationDisposition = "eject-card"
)

// Maps to |SCARD_*| connection state values.
type SmartCardEmulationConnectionState string

const (
	SmartCardEmulationConnectionStateAbsent     SmartCardEmulationConnectionState = "absent"
	SmartCardEmulationConnectionStatePresent    SmartCardEmulationConnectionState = "present"
	SmartCardEmulationConnectionStateSwallowed  SmartCardEmulationConnectionState = "swallowed"
	SmartCardEmulationConnectionStatePowered    SmartCardEmulationConnectionState = "powered"
	SmartCardEmulationConnectionStateNegotiable SmartCardEmulationConnectionState = "negotiable"
	SmartCardEmulationConnectionStateSpecific   SmartCardEmulationConnectionState = "specific"
)

// Maps to the |SCARD_STATE_*| flags.
type SmartCardEmulationReaderStateFlags struct {
	Unaware     *bool `json:"unaware,omitempty"`
	Ignore      *bool `json:"ignore,omitempty"`
	Changed     *bool `json:"changed,omitempty"`
	Unknown     *bool `json:"unknown,omitempty"`
	Unavailable *bool `json:"unavailable,omitempty"`
	Empty       *bool `json:"empty,omitempty"`
	Present     *bool `json:"present,omitempty"`
	Exclusive   *bool `json:"exclusive,omitempty"`
	Inuse       *bool `json:"inuse,omitempty"`
	Mute        *bool `json:"mute,omitempty"`
	Unpowered   *bool `json:"unpowered,omitempty"`
}

// Maps to the |SCARD_PROTOCOL_*| flags.
type SmartCardEmulationProtocolSet struct {
	T0  *bool `json:"t0,omitempty"`
	T1  *bool `json:"t1,omitempty"`
	Raw *bool `json:"raw,omitempty"`
}

// Maps to the |SCARD_PROTOCOL_*| values.
type SmartCardEmulationProtocol string

const (
	SmartCardEmulationProtocolT0  SmartCardEmulationProtocol = "t0"
	SmartCardEmulationProtocolT1  SmartCardEmulationProtocol = "t1"
	SmartCardEmulationProtocolRaw SmartCardEmulationProtocol = "raw"
)

type SmartCardEmulationReaderStateIn struct {
	Reader                string                             `json:"reader"`
	CurrentState          SmartCardEmulationReaderStateFlags `json:"currentState"`
	CurrentInsertionCount int64                              `json:"currentInsertionCount"`
}

type SmartCardEmulationReaderStateOut struct {
	Reader     string                             `json:"reader"`
	EventState SmartCardEmulationReaderStateFlags `json:"eventState"`
	EventCount int64                              `json:"eventCount"`
	Atr        string                             `json:"atr"`
}

// Enables the |SmartCardEmulation| domain.
type SmartCardEmulationEnableParams struct {
}

func SmartCardEmulationEnable() *SmartCardEmulationEnableParams {
	return &SmartCardEmulationEnableParams{}
}

func (p *SmartCardEmulationEnableParams) CDPMethodName() string {
	return "SmartCardEmulation.enable"
}

// Disables the |SmartCardEmulation| domain.
type SmartCardEmulationDisableParams struct {
}

func SmartCardEmulationDisable() *SmartCardEmulationDisableParams {
	return &SmartCardEmulationDisableParams{}
}

func (p *SmartCardEmulationDisableParams) CDPMethodName() string {
	return "SmartCardEmulation.disable"
}

// Reports the successful result of a |SCardEstablishContext| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext
type SmartCardEmulationReportEstablishContextResultParams struct {
	RequestId string `json:"requestId"`
	ContextId int64  `json:"contextId"`
}

func SmartCardEmulationReportEstablishContextResult(requestId string, contextId int64) *SmartCardEmulationReportEstablishContextResultParams {
	return &SmartCardEmulationReportEstablishContextResultParams{
		RequestId: requestId,
		ContextId: contextId,
	}
}

func (p *SmartCardEmulationReportEstablishContextResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportEstablishContextResult"
}

// Reports the successful result of a |SCardReleaseContext| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext
type SmartCardEmulationReportReleaseContextResultParams struct {
	RequestId string `json:"requestId"`
}

func SmartCardEmulationReportReleaseContextResult(requestId string) *SmartCardEmulationReportReleaseContextResultParams {
	return &SmartCardEmulationReportReleaseContextResultParams{
		RequestId: requestId,
	}
}

func (p *SmartCardEmulationReportReleaseContextResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportReleaseContextResult"
}

// Reports the successful result of a |SCardListReaders| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa
type SmartCardEmulationReportListReadersResultParams struct {
	RequestId string   `json:"requestId"`
	Readers   []string `json:"readers"`
}

func SmartCardEmulationReportListReadersResult(requestId string, readers []string) *SmartCardEmulationReportListReadersResultParams {
	return &SmartCardEmulationReportListReadersResultParams{
		RequestId: requestId,
		Readers:   readers,
	}
}

func (p *SmartCardEmulationReportListReadersResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportListReadersResult"
}

// Reports the successful result of a |SCardGetStatusChange| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea
type SmartCardEmulationReportGetStatusChangeResultParams struct {
	RequestId    string                             `json:"requestId"`
	ReaderStates []SmartCardEmulationReaderStateOut `json:"readerStates"`
}

func SmartCardEmulationReportGetStatusChangeResult(requestId string, readerStates []SmartCardEmulationReaderStateOut) *SmartCardEmulationReportGetStatusChangeResultParams {
	return &SmartCardEmulationReportGetStatusChangeResultParams{
		RequestId:    requestId,
		ReaderStates: readerStates,
	}
}

func (p *SmartCardEmulationReportGetStatusChangeResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportGetStatusChangeResult"
}

// Reports the result of a |SCardBeginTransaction| call.
// On success, this creates a new transaction object.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction
type SmartCardEmulationReportBeginTransactionResultParams struct {
	RequestId string `json:"requestId"`
	Handle    int64  `json:"handle"`
}

func SmartCardEmulationReportBeginTransactionResult(requestId string, handle int64) *SmartCardEmulationReportBeginTransactionResultParams {
	return &SmartCardEmulationReportBeginTransactionResultParams{
		RequestId: requestId,
		Handle:    handle,
	}
}

func (p *SmartCardEmulationReportBeginTransactionResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportBeginTransactionResult"
}

// Reports the successful result of a call that returns only a result code.
// Used for: |SCardCancel|, |SCardDisconnect|, |SCardSetAttrib|, |SCardEndTransaction|.
//
// This maps to:
//  1. SCardCancel
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel
//
//  2. SCardDisconnect
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect
//
//  3. SCardSetAttrib
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib
//
//  4. SCardEndTransaction
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction
type SmartCardEmulationReportPlainResultParams struct {
	RequestId string `json:"requestId"`
}

func SmartCardEmulationReportPlainResult(requestId string) *SmartCardEmulationReportPlainResultParams {
	return &SmartCardEmulationReportPlainResultParams{
		RequestId: requestId,
	}
}

func (p *SmartCardEmulationReportPlainResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportPlainResult"
}

// Reports the successful result of a |SCardConnect| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta
type SmartCardEmulationReportConnectResultParams struct {
	RequestId      string                      `json:"requestId"`
	Handle         int64                       `json:"handle"`
	ActiveProtocol *SmartCardEmulationProtocol `json:"activeProtocol,omitempty"`
}

func SmartCardEmulationReportConnectResult(requestId string, handle int64) *SmartCardEmulationReportConnectResultParams {
	return &SmartCardEmulationReportConnectResultParams{
		RequestId: requestId,
		Handle:    handle,
	}
}

func (p *SmartCardEmulationReportConnectResultParams) WithActiveProtocol(v SmartCardEmulationProtocol) *SmartCardEmulationReportConnectResultParams {
	p.ActiveProtocol = &v
	return p
}

func (p *SmartCardEmulationReportConnectResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportConnectResult"
}

// Reports the successful result of a call that sends back data on success.
// Used for |SCardTransmit|, |SCardControl|, and |SCardGetAttrib|.
//
// This maps to:
//  1. SCardTransmit
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit
//
//  2. SCardControl
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol
//
//  3. SCardGetAttrib
//     PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
//     Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib
type SmartCardEmulationReportDataResultParams struct {
	RequestId string `json:"requestId"`
	Data      string `json:"data"`
}

func SmartCardEmulationReportDataResult(requestId string, data string) *SmartCardEmulationReportDataResultParams {
	return &SmartCardEmulationReportDataResultParams{
		RequestId: requestId,
		Data:      data,
	}
}

func (p *SmartCardEmulationReportDataResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportDataResult"
}

// Reports the successful result of a |SCardStatus| call.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa
type SmartCardEmulationReportStatusResultParams struct {
	RequestId  string                            `json:"requestId"`
	ReaderName string                            `json:"readerName"`
	State      SmartCardEmulationConnectionState `json:"state"`
	Atr        string                            `json:"atr"`
	Protocol   *SmartCardEmulationProtocol       `json:"protocol,omitempty"`
}

func SmartCardEmulationReportStatusResult(requestId string, readerName string, state SmartCardEmulationConnectionState, atr string) *SmartCardEmulationReportStatusResultParams {
	return &SmartCardEmulationReportStatusResultParams{
		RequestId:  requestId,
		ReaderName: readerName,
		State:      state,
		Atr:        atr,
	}
}

func (p *SmartCardEmulationReportStatusResultParams) WithProtocol(v SmartCardEmulationProtocol) *SmartCardEmulationReportStatusResultParams {
	p.Protocol = &v
	return p
}

func (p *SmartCardEmulationReportStatusResultParams) CDPMethodName() string {
	return "SmartCardEmulation.reportStatusResult"
}

// Reports an error result for the given request.
type SmartCardEmulationReportErrorParams struct {
	RequestId  string                       `json:"requestId"`
	ResultCode SmartCardEmulationResultCode `json:"resultCode"`
}

func SmartCardEmulationReportError(requestId string, resultCode SmartCardEmulationResultCode) *SmartCardEmulationReportErrorParams {
	return &SmartCardEmulationReportErrorParams{
		RequestId:  requestId,
		ResultCode: resultCode,
	}
}

func (p *SmartCardEmulationReportErrorParams) CDPMethodName() string {
	return "SmartCardEmulation.reportError"
}

// Fired when |SCardEstablishContext| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaa1b8970169fd4883a6dc4a8f43f19b67
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardestablishcontext
const EventSmartCardEmulationEstablishContextRequested = "SmartCardEmulation.establishContextRequested"

type SmartCardEmulationEstablishContextRequestedEvent struct {
	RequestId string `json:"requestId"`
}

func (e *SmartCardEmulationEstablishContextRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationEstablishContextRequested
}

// Fired when |SCardReleaseContext| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga6aabcba7744c5c9419fdd6404f73a934
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardreleasecontext
const EventSmartCardEmulationReleaseContextRequested = "SmartCardEmulation.releaseContextRequested"

type SmartCardEmulationReleaseContextRequestedEvent struct {
	RequestId string `json:"requestId"`
	ContextId int64  `json:"contextId"`
}

func (e *SmartCardEmulationReleaseContextRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationReleaseContextRequested
}

// Fired when |SCardListReaders| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga93b07815789b3cf2629d439ecf20f0d9
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersa
const EventSmartCardEmulationListReadersRequested = "SmartCardEmulation.listReadersRequested"

type SmartCardEmulationListReadersRequestedEvent struct {
	RequestId string `json:"requestId"`
	ContextId int64  `json:"contextId"`
}

func (e *SmartCardEmulationListReadersRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationListReadersRequested
}

// Fired when |SCardGetStatusChange| is called. Timeout is specified in milliseconds.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga33247d5d1257d59e55647c3bb717db24
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetstatuschangea
const EventSmartCardEmulationGetStatusChangeRequested = "SmartCardEmulation.getStatusChangeRequested"

type SmartCardEmulationGetStatusChangeRequestedEvent struct {
	RequestId    string                            `json:"requestId"`
	ContextId    int64                             `json:"contextId"`
	ReaderStates []SmartCardEmulationReaderStateIn `json:"readerStates"`
	// in milliseconds, if absent, it means "infinite"
	Timeout *int64 `json:"timeout,omitempty"`
}

func (e *SmartCardEmulationGetStatusChangeRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationGetStatusChangeRequested
}

// Fired when |SCardCancel| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacbbc0c6d6c0cbbeb4f4debf6fbeeee6
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcancel
const EventSmartCardEmulationCancelRequested = "SmartCardEmulation.cancelRequested"

type SmartCardEmulationCancelRequestedEvent struct {
	RequestId string `json:"requestId"`
	ContextId int64  `json:"contextId"`
}

func (e *SmartCardEmulationCancelRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationCancelRequested
}

// Fired when |SCardConnect| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4e515829752e0a8dbc4d630696a8d6a5
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardconnecta
const EventSmartCardEmulationConnectRequested = "SmartCardEmulation.connectRequested"

type SmartCardEmulationConnectRequestedEvent struct {
	RequestId          string                        `json:"requestId"`
	ContextId          int64                         `json:"contextId"`
	Reader             string                        `json:"reader"`
	ShareMode          SmartCardEmulationShareMode   `json:"shareMode"`
	PreferredProtocols SmartCardEmulationProtocolSet `json:"preferredProtocols"`
}

func (e *SmartCardEmulationConnectRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationConnectRequested
}

// Fired when |SCardDisconnect| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga4be198045c73ec0deb79e66c0ca1738a
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scarddisconnect
const EventSmartCardEmulationDisconnectRequested = "SmartCardEmulation.disconnectRequested"

type SmartCardEmulationDisconnectRequestedEvent struct {
	RequestId   string                        `json:"requestId"`
	Handle      int64                         `json:"handle"`
	Disposition SmartCardEmulationDisposition `json:"disposition"`
}

func (e *SmartCardEmulationDisconnectRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationDisconnectRequested
}

// Fired when |SCardTransmit| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga9a2d77242a271310269065e64633ab99
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardtransmit
const EventSmartCardEmulationTransmitRequested = "SmartCardEmulation.transmitRequested"

type SmartCardEmulationTransmitRequestedEvent struct {
	RequestId string                      `json:"requestId"`
	Handle    int64                       `json:"handle"`
	Data      string                      `json:"data"`
	Protocol  *SmartCardEmulationProtocol `json:"protocol,omitempty"`
}

func (e *SmartCardEmulationTransmitRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationTransmitRequested
}

// Fired when |SCardControl| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gac3454d4657110fd7f753b2d3d8f4e32f
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardcontrol
const EventSmartCardEmulationControlRequested = "SmartCardEmulation.controlRequested"

type SmartCardEmulationControlRequestedEvent struct {
	RequestId   string `json:"requestId"`
	Handle      int64  `json:"handle"`
	ControlCode int64  `json:"controlCode"`
	Data        string `json:"data"`
}

func (e *SmartCardEmulationControlRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationControlRequested
}

// Fired when |SCardGetAttrib| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaacfec51917255b7a25b94c5104961602
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardgetattrib
const EventSmartCardEmulationGetAttribRequested = "SmartCardEmulation.getAttribRequested"

type SmartCardEmulationGetAttribRequestedEvent struct {
	RequestId string `json:"requestId"`
	Handle    int64  `json:"handle"`
	AttribId  int64  `json:"attribId"`
}

func (e *SmartCardEmulationGetAttribRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationGetAttribRequested
}

// Fired when |SCardSetAttrib| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#ga060f0038a4ddfd5dd2b8fadf3c3a2e4f
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardsetattrib
const EventSmartCardEmulationSetAttribRequested = "SmartCardEmulation.setAttribRequested"

type SmartCardEmulationSetAttribRequestedEvent struct {
	RequestId string `json:"requestId"`
	Handle    int64  `json:"handle"`
	AttribId  int64  `json:"attribId"`
	Data      string `json:"data"`
}

func (e *SmartCardEmulationSetAttribRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationSetAttribRequested
}

// Fired when |SCardStatus| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae49c3c894ad7ac12a5b896bde70d0382
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardstatusa
const EventSmartCardEmulationStatusRequested = "SmartCardEmulation.statusRequested"

type SmartCardEmulationStatusRequestedEvent struct {
	RequestId string `json:"requestId"`
	Handle    int64  `json:"handle"`
}

func (e *SmartCardEmulationStatusRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationStatusRequested
}

// Fired when |SCardBeginTransaction| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gaddb835dce01a0da1d6ca02d33ee7d861
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardbegintransaction
const EventSmartCardEmulationBeginTransactionRequested = "SmartCardEmulation.beginTransactionRequested"

type SmartCardEmulationBeginTransactionRequestedEvent struct {
	RequestId string `json:"requestId"`
	Handle    int64  `json:"handle"`
}

func (e *SmartCardEmulationBeginTransactionRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationBeginTransactionRequested
}

// Fired when |SCardEndTransaction| is called.
//
// This maps to:
// PC/SC Lite: https://pcsclite.apdu.fr/api/group__API.html#gae8742473b404363e5c587f570d7e2f3b
// Microsoft: https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardendtransaction
const EventSmartCardEmulationEndTransactionRequested = "SmartCardEmulation.endTransactionRequested"

type SmartCardEmulationEndTransactionRequestedEvent struct {
	RequestId   string                        `json:"requestId"`
	Handle      int64                         `json:"handle"`
	Disposition SmartCardEmulationDisposition `json:"disposition"`
}

func (e *SmartCardEmulationEndTransactionRequestedEvent) CDPEventName() string {
	return EventSmartCardEmulationEndTransactionRequested
}
