// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Configuration for memory dump. Used only when "memory-infra" category is enabled.
type TracingMemoryDumpConfig map[string]any

type TracingTraceConfig struct {
	// Controls how the trace buffer stores data. The default is `recordUntilFull`.
	RecordMode *string `json:"recordMode,omitempty"`
	// Size of the trace buffer in kilobytes. If not specified or zero is passed, a default value
	// of 200 MB would be used.
	TraceBufferSizeInKb *float64 `json:"traceBufferSizeInKb,omitempty"`
	// Turns on JavaScript stack sampling.
	EnableSampling *bool `json:"enableSampling,omitempty"`
	// Turns on system tracing.
	EnableSystrace *bool `json:"enableSystrace,omitempty"`
	// Turns on argument filter.
	EnableArgumentFilter *bool `json:"enableArgumentFilter,omitempty"`
	// Included category filters.
	IncludedCategories []string `json:"includedCategories,omitempty"`
	// Excluded category filters.
	ExcludedCategories []string `json:"excludedCategories,omitempty"`
	// Configuration to synthesize the delays in tracing.
	SyntheticDelays []string `json:"syntheticDelays,omitempty"`
	// Configuration for memory dump triggers. Used only when "memory-infra" category is enabled.
	MemoryDumpConfig *TracingMemoryDumpConfig `json:"memoryDumpConfig,omitempty"`
}

// Data format of a trace. Can be either the legacy JSON format or the
// protocol buffer format. Note that the JSON format will be deprecated soon.
type TracingStreamFormat string

const (
	TracingStreamFormatJson  TracingStreamFormat = "json"
	TracingStreamFormatProto TracingStreamFormat = "proto"
)

// Compression type to use for traces returned via streams.
type TracingStreamCompression string

const (
	TracingStreamCompressionNone TracingStreamCompression = "none"
	TracingStreamCompressionGzip TracingStreamCompression = "gzip"
)

// Details exposed when memory request explicitly declared.
// Keep consistent with memory_dump_request_args.h and
// memory_instrumentation.mojom
type TracingMemoryDumpLevelOfDetail string

const (
	TracingMemoryDumpLevelOfDetailBackground TracingMemoryDumpLevelOfDetail = "background"
	TracingMemoryDumpLevelOfDetailLight      TracingMemoryDumpLevelOfDetail = "light"
	TracingMemoryDumpLevelOfDetailDetailed   TracingMemoryDumpLevelOfDetail = "detailed"
)

// Backend type to use for tracing. `chrome` uses the Chrome-integrated
// tracing service and is supported on all platforms. `system` is only
// supported on Chrome OS and uses the Perfetto system tracing service.
// `auto` chooses `system` when the perfettoConfig provided to Tracing.start
// specifies at least one non-Chrome data source; otherwise uses `chrome`.
type TracingTracingBackend string

const (
	TracingTracingBackendAuto   TracingTracingBackend = "auto"
	TracingTracingBackendChrome TracingTracingBackend = "chrome"
	TracingTracingBackendSystem TracingTracingBackend = "system"
)

// Stop trace events collection.
type TracingEndParams struct {
}

func TracingEnd() *TracingEndParams {
	return &TracingEndParams{}
}

func (p *TracingEndParams) CDPMethodName() string {
	return "Tracing.end"
}

// Gets supported tracing categories.
type TracingGetCategoriesParams struct {
}

type TracingGetCategoriesReturns struct {
	// A list of supported tracing categories.
	Categories []string `json:"categories"`
}

func TracingGetCategories() *TracingGetCategoriesParams {
	return &TracingGetCategoriesParams{}
}

func (p *TracingGetCategoriesParams) CDPMethodName() string {
	return "Tracing.getCategories"
}

// Return a descriptor for all available tracing categories.
type TracingGetTrackEventDescriptorParams struct {
}

type TracingGetTrackEventDescriptorReturns struct {
	// Base64-encoded serialized perfetto.protos.TrackEventDescriptor protobuf message. (Encoded as a base64 string when passed over JSON)
	Descriptor string `json:"descriptor"`
}

func TracingGetTrackEventDescriptor() *TracingGetTrackEventDescriptorParams {
	return &TracingGetTrackEventDescriptorParams{}
}

func (p *TracingGetTrackEventDescriptorParams) CDPMethodName() string {
	return "Tracing.getTrackEventDescriptor"
}

// Record a clock sync marker in the trace.
type TracingRecordClockSyncMarkerParams struct {
	// The ID of this clock sync marker
	SyncId string `json:"syncId"`
}

func TracingRecordClockSyncMarker(syncId string) *TracingRecordClockSyncMarkerParams {
	return &TracingRecordClockSyncMarkerParams{
		SyncId: syncId,
	}
}

func (p *TracingRecordClockSyncMarkerParams) CDPMethodName() string {
	return "Tracing.recordClockSyncMarker"
}

// Request a global memory dump.
type TracingRequestMemoryDumpParams struct {
	// Enables more deterministic results by forcing garbage collection
	Deterministic *bool `json:"deterministic,omitempty"`
	// Specifies level of details in memory dump. Defaults to "detailed".
	LevelOfDetail *TracingMemoryDumpLevelOfDetail `json:"levelOfDetail,omitempty"`
}

type TracingRequestMemoryDumpReturns struct {
	// GUID of the resulting global memory dump.
	DumpGuid string `json:"dumpGuid"`
	// True iff the global memory dump succeeded.
	Success bool `json:"success"`
}

func TracingRequestMemoryDump() *TracingRequestMemoryDumpParams {
	return &TracingRequestMemoryDumpParams{}
}

func (p *TracingRequestMemoryDumpParams) WithDeterministic(v bool) *TracingRequestMemoryDumpParams {
	p.Deterministic = &v
	return p
}

func (p *TracingRequestMemoryDumpParams) WithLevelOfDetail(v TracingMemoryDumpLevelOfDetail) *TracingRequestMemoryDumpParams {
	p.LevelOfDetail = &v
	return p
}

func (p *TracingRequestMemoryDumpParams) CDPMethodName() string {
	return "Tracing.requestMemoryDump"
}

// Start trace events collection.
type TracingStartParams struct {
	// Category/tag filter
	Categories *string `json:"categories,omitempty"`
	// Tracing options
	Options *string `json:"options,omitempty"`
	// If set, the agent will issue bufferUsage events at this interval, specified in milliseconds
	BufferUsageReportingInterval *float64 `json:"bufferUsageReportingInterval,omitempty"`
	// Whether to report trace events as series of dataCollected events or to save trace to a
	// stream (defaults to `ReportEvents`).
	TransferMode *string `json:"transferMode,omitempty"`
	// Trace data format to use. This only applies when using `ReturnAsStream`
	// transfer mode (defaults to `json`).
	StreamFormat *TracingStreamFormat `json:"streamFormat,omitempty"`
	// Compression format to use. This only applies when using `ReturnAsStream`
	// transfer mode (defaults to `none`)
	StreamCompression *TracingStreamCompression `json:"streamCompression,omitempty"`
	TraceConfig       *TracingTraceConfig       `json:"traceConfig,omitempty"`
	// Base64-encoded serialized perfetto.protos.TraceConfig protobuf message
	// When specified, the parameters `categories`, `options`, `traceConfig`
	// are ignored. (Encoded as a base64 string when passed over JSON)
	PerfettoConfig *string `json:"perfettoConfig,omitempty"`
	// Backend type (defaults to `auto`)
	TracingBackend *TracingTracingBackend `json:"tracingBackend,omitempty"`
}

func TracingStart() *TracingStartParams {
	return &TracingStartParams{}
}

func (p *TracingStartParams) WithCategories(v string) *TracingStartParams {
	p.Categories = &v
	return p
}

func (p *TracingStartParams) WithOptions(v string) *TracingStartParams {
	p.Options = &v
	return p
}

func (p *TracingStartParams) WithBufferUsageReportingInterval(v float64) *TracingStartParams {
	p.BufferUsageReportingInterval = &v
	return p
}

func (p *TracingStartParams) WithTransferMode(v string) *TracingStartParams {
	p.TransferMode = &v
	return p
}

func (p *TracingStartParams) WithStreamFormat(v TracingStreamFormat) *TracingStartParams {
	p.StreamFormat = &v
	return p
}

func (p *TracingStartParams) WithStreamCompression(v TracingStreamCompression) *TracingStartParams {
	p.StreamCompression = &v
	return p
}

func (p *TracingStartParams) WithTraceConfig(v TracingTraceConfig) *TracingStartParams {
	p.TraceConfig = &v
	return p
}

func (p *TracingStartParams) WithPerfettoConfig(v string) *TracingStartParams {
	p.PerfettoConfig = &v
	return p
}

func (p *TracingStartParams) WithTracingBackend(v TracingTracingBackend) *TracingStartParams {
	p.TracingBackend = &v
	return p
}

func (p *TracingStartParams) CDPMethodName() string {
	return "Tracing.start"
}

const EventTracingBufferUsage = "Tracing.bufferUsage"

type TracingBufferUsageEvent struct {
	// A number in range [0..1] that indicates the used size of event buffer as a fraction of its
	// total size.
	PercentFull *float64 `json:"percentFull,omitempty"`
	// An approximate number of events in the trace log.
	EventCount *float64 `json:"eventCount,omitempty"`
	// A number in range [0..1] that indicates the used size of event buffer as a fraction of its
	// total size.
	Value *float64 `json:"value,omitempty"`
}

func (e *TracingBufferUsageEvent) CDPEventName() string {
	return EventTracingBufferUsage
}

// Contains a bucket of collected trace events. When tracing is stopped collected events will be
// sent as a sequence of dataCollected events followed by tracingComplete event.
const EventTracingDataCollected = "Tracing.dataCollected"

type TracingDataCollectedEvent struct {
	Value []map[string]any `json:"value"`
}

func (e *TracingDataCollectedEvent) CDPEventName() string {
	return EventTracingDataCollected
}

// Signals that tracing is stopped and there is no trace buffers pending flush, all data were
// delivered via dataCollected events.
const EventTracingTracingComplete = "Tracing.tracingComplete"

type TracingTracingCompleteEvent struct {
	// Indicates whether some trace data is known to have been lost, e.g. because the trace ring
	// buffer wrapped around.
	DataLossOccurred bool `json:"dataLossOccurred"`
	// A handle of the stream that holds resulting trace data.
	Stream *IOStreamHandle `json:"stream,omitempty"`
	// Trace data format of returned stream.
	TraceFormat *TracingStreamFormat `json:"traceFormat,omitempty"`
	// Compression format of returned stream.
	StreamCompression *TracingStreamCompression `json:"streamCompression,omitempty"`
}

func (e *TracingTracingCompleteEvent) CDPEventName() string {
	return EventTracingTracingComplete
}
