// Code generated by cdpgen; DO NOT EDIT.

package cdp

// An unique ID for a graph object (AudioContext, AudioNode, AudioParam) in Web Audio API
type WebAudioGraphObjectId string

// Enum of BaseAudioContext types
type WebAudioContextType string

const (
	WebAudioContextTypeRealtime WebAudioContextType = "realtime"
	WebAudioContextTypeOffline  WebAudioContextType = "offline"
)

// Enum of AudioContextState from the spec
type WebAudioContextState string

const (
	WebAudioContextStateSuspended   WebAudioContextState = "suspended"
	WebAudioContextStateRunning     WebAudioContextState = "running"
	WebAudioContextStateClosed      WebAudioContextState = "closed"
	WebAudioContextStateInterrupted WebAudioContextState = "interrupted"
)

// Enum of AudioNode types
type WebAudioNodeType string

// Enum of AudioNode::ChannelCountMode from the spec
type WebAudioChannelCountMode string

const (
	WebAudioChannelCountModeClampedMax WebAudioChannelCountMode = "clamped-max"
	WebAudioChannelCountModeExplicit   WebAudioChannelCountMode = "explicit"
	WebAudioChannelCountModeMax        WebAudioChannelCountMode = "max"
)

// Enum of AudioNode::ChannelInterpretation from the spec
type WebAudioChannelInterpretation string

const (
	WebAudioChannelInterpretationDiscrete WebAudioChannelInterpretation = "discrete"
	WebAudioChannelInterpretationSpeakers WebAudioChannelInterpretation = "speakers"
)

// Enum of AudioParam types
type WebAudioParamType string

// Enum of AudioParam::AutomationRate from the spec
type WebAudioAutomationRate string

const (
	WebAudioAutomationRateARate WebAudioAutomationRate = "a-rate"
	WebAudioAutomationRateKRate WebAudioAutomationRate = "k-rate"
)

// Fields in AudioContext that change in real-time.
type WebAudioContextRealtimeData struct {
	// The current context time in second in BaseAudioContext.
	CurrentTime float64 `json:"currentTime"`
	// The time spent on rendering graph divided by render quantum duration,
	// and multiplied by 100. 100 means the audio renderer reached the full
	// capacity and glitch may occur.
	RenderCapacity float64 `json:"renderCapacity"`
	// A running mean of callback interval.
	CallbackIntervalMean float64 `json:"callbackIntervalMean"`
	// A running variance of callback interval.
	CallbackIntervalVariance float64 `json:"callbackIntervalVariance"`
}

// Protocol object for BaseAudioContext
type WebAudioBaseAudioContext struct {
	ContextId    WebAudioGraphObjectId        `json:"contextId"`
	ContextType  WebAudioContextType          `json:"contextType"`
	ContextState WebAudioContextState         `json:"contextState"`
	RealtimeData *WebAudioContextRealtimeData `json:"realtimeData,omitempty"`
	// Platform-dependent callback buffer size.
	CallbackBufferSize float64 `json:"callbackBufferSize"`
	// Number of output channels supported by audio hardware in use.
	MaxOutputChannelCount float64 `json:"maxOutputChannelCount"`
	// Context sample rate.
	SampleRate float64 `json:"sampleRate"`
}

// Protocol object for AudioListener
type WebAudioAudioListener struct {
	ListenerId WebAudioGraphObjectId `json:"listenerId"`
	ContextId  WebAudioGraphObjectId `json:"contextId"`
}

// Protocol object for AudioNode
type WebAudioAudioNode struct {
	NodeId                WebAudioGraphObjectId         `json:"nodeId"`
	ContextId             WebAudioGraphObjectId         `json:"contextId"`
	NodeType              WebAudioNodeType              `json:"nodeType"`
	NumberOfInputs        float64                       `json:"numberOfInputs"`
	NumberOfOutputs       float64                       `json:"numberOfOutputs"`
	ChannelCount          float64                       `json:"channelCount"`
	ChannelCountMode      WebAudioChannelCountMode      `json:"channelCountMode"`
	ChannelInterpretation WebAudioChannelInterpretation `json:"channelInterpretation"`
}

// Protocol object for AudioParam
type WebAudioAudioParam struct {
	ParamId      WebAudioGraphObjectId  `json:"paramId"`
	NodeId       WebAudioGraphObjectId  `json:"nodeId"`
	ContextId    WebAudioGraphObjectId  `json:"contextId"`
	ParamType    WebAudioParamType      `json:"paramType"`
	Rate         WebAudioAutomationRate `json:"rate"`
	DefaultValue float64                `json:"defaultValue"`
	MinValue     float64                `json:"minValue"`
	MaxValue     float64                `json:"maxValue"`
}

// Enables the WebAudio domain and starts sending context lifetime events.
type WebAudioEnableParams struct {
}

func WebAudioEnable() *WebAudioEnableParams {
	return &WebAudioEnableParams{}
}

func (p *WebAudioEnableParams) CDPMethodName() string {
	return "WebAudio.enable"
}

// Disables the WebAudio domain.
type WebAudioDisableParams struct {
}

func WebAudioDisable() *WebAudioDisableParams {
	return &WebAudioDisableParams{}
}

func (p *WebAudioDisableParams) CDPMethodName() string {
	return "WebAudio.disable"
}

// Fetch the realtime data from the registered contexts.
type WebAudioGetRealtimeDataParams struct {
	ContextId WebAudioGraphObjectId `json:"contextId"`
}

type WebAudioGetRealtimeDataReturns struct {
	RealtimeData WebAudioContextRealtimeData `json:"realtimeData"`
}

func WebAudioGetRealtimeData(contextId WebAudioGraphObjectId) *WebAudioGetRealtimeDataParams {
	return &WebAudioGetRealtimeDataParams{
		ContextId: contextId,
	}
}

func (p *WebAudioGetRealtimeDataParams) CDPMethodName() string {
	return "WebAudio.getRealtimeData"
}

// Notifies that a new BaseAudioContext has been created.
const EventWebAudioContextCreated = "WebAudio.contextCreated"

type WebAudioContextCreatedEvent struct {
	Context WebAudioBaseAudioContext `json:"context"`
}

func (e *WebAudioContextCreatedEvent) CDPEventName() string {
	return EventWebAudioContextCreated
}

// Notifies that an existing BaseAudioContext will be destroyed.
const EventWebAudioContextWillBeDestroyed = "WebAudio.contextWillBeDestroyed"

type WebAudioContextWillBeDestroyedEvent struct {
	ContextId WebAudioGraphObjectId `json:"contextId"`
}

func (e *WebAudioContextWillBeDestroyedEvent) CDPEventName() string {
	return EventWebAudioContextWillBeDestroyed
}

// Notifies that existing BaseAudioContext has changed some properties (id stays the same)..
const EventWebAudioContextChanged = "WebAudio.contextChanged"

type WebAudioContextChangedEvent struct {
	Context WebAudioBaseAudioContext `json:"context"`
}

func (e *WebAudioContextChangedEvent) CDPEventName() string {
	return EventWebAudioContextChanged
}

// Notifies that the construction of an AudioListener has finished.
const EventWebAudioAudioListenerCreated = "WebAudio.audioListenerCreated"

type WebAudioAudioListenerCreatedEvent struct {
	Listener WebAudioAudioListener `json:"listener"`
}

func (e *WebAudioAudioListenerCreatedEvent) CDPEventName() string {
	return EventWebAudioAudioListenerCreated
}

// Notifies that a new AudioListener has been created.
const EventWebAudioAudioListenerWillBeDestroyed = "WebAudio.audioListenerWillBeDestroyed"

type WebAudioAudioListenerWillBeDestroyedEvent struct {
	ContextId  WebAudioGraphObjectId `json:"contextId"`
	ListenerId WebAudioGraphObjectId `json:"listenerId"`
}

func (e *WebAudioAudioListenerWillBeDestroyedEvent) CDPEventName() string {
	return EventWebAudioAudioListenerWillBeDestroyed
}

// Notifies that a new AudioNode has been created.
const EventWebAudioAudioNodeCreated = "WebAudio.audioNodeCreated"

type WebAudioAudioNodeCreatedEvent struct {
	Node WebAudioAudioNode `json:"node"`
}

func (e *WebAudioAudioNodeCreatedEvent) CDPEventName() string {
	return EventWebAudioAudioNodeCreated
}

// Notifies that an existing AudioNode has been destroyed.
const EventWebAudioAudioNodeWillBeDestroyed = "WebAudio.audioNodeWillBeDestroyed"

type WebAudioAudioNodeWillBeDestroyedEvent struct {
	ContextId WebAudioGraphObjectId `json:"contextId"`
	NodeId    WebAudioGraphObjectId `json:"nodeId"`
}

func (e *WebAudioAudioNodeWillBeDestroyedEvent) CDPEventName() string {
	return EventWebAudioAudioNodeWillBeDestroyed
}

// Notifies that a new AudioParam has been created.
const EventWebAudioAudioParamCreated = "WebAudio.audioParamCreated"

type WebAudioAudioParamCreatedEvent struct {
	Param WebAudioAudioParam `json:"param"`
}

func (e *WebAudioAudioParamCreatedEvent) CDPEventName() string {
	return EventWebAudioAudioParamCreated
}

// Notifies that an existing AudioParam has been destroyed.
const EventWebAudioAudioParamWillBeDestroyed = "WebAudio.audioParamWillBeDestroyed"

type WebAudioAudioParamWillBeDestroyedEvent struct {
	ContextId WebAudioGraphObjectId `json:"contextId"`
	NodeId    WebAudioGraphObjectId `json:"nodeId"`
	ParamId   WebAudioGraphObjectId `json:"paramId"`
}

func (e *WebAudioAudioParamWillBeDestroyedEvent) CDPEventName() string {
	return EventWebAudioAudioParamWillBeDestroyed
}

// Notifies that two AudioNodes are connected.
const EventWebAudioNodesConnected = "WebAudio.nodesConnected"

type WebAudioNodesConnectedEvent struct {
	ContextId             WebAudioGraphObjectId `json:"contextId"`
	SourceId              WebAudioGraphObjectId `json:"sourceId"`
	DestinationId         WebAudioGraphObjectId `json:"destinationId"`
	SourceOutputIndex     *float64              `json:"sourceOutputIndex,omitempty"`
	DestinationInputIndex *float64              `json:"destinationInputIndex,omitempty"`
}

func (e *WebAudioNodesConnectedEvent) CDPEventName() string {
	return EventWebAudioNodesConnected
}

// Notifies that AudioNodes are disconnected. The destination can be null, and it means all the outgoing connections from the source are disconnected.
const EventWebAudioNodesDisconnected = "WebAudio.nodesDisconnected"

type WebAudioNodesDisconnectedEvent struct {
	ContextId             WebAudioGraphObjectId `json:"contextId"`
	SourceId              WebAudioGraphObjectId `json:"sourceId"`
	DestinationId         WebAudioGraphObjectId `json:"destinationId"`
	SourceOutputIndex     *float64              `json:"sourceOutputIndex,omitempty"`
	DestinationInputIndex *float64              `json:"destinationInputIndex,omitempty"`
}

func (e *WebAudioNodesDisconnectedEvent) CDPEventName() string {
	return EventWebAudioNodesDisconnected
}

// Notifies that an AudioNode is connected to an AudioParam.
const EventWebAudioNodeParamConnected = "WebAudio.nodeParamConnected"

type WebAudioNodeParamConnectedEvent struct {
	ContextId         WebAudioGraphObjectId `json:"contextId"`
	SourceId          WebAudioGraphObjectId `json:"sourceId"`
	DestinationId     WebAudioGraphObjectId `json:"destinationId"`
	SourceOutputIndex *float64              `json:"sourceOutputIndex,omitempty"`
}

func (e *WebAudioNodeParamConnectedEvent) CDPEventName() string {
	return EventWebAudioNodeParamConnected
}

// Notifies that an AudioNode is disconnected to an AudioParam.
const EventWebAudioNodeParamDisconnected = "WebAudio.nodeParamDisconnected"

type WebAudioNodeParamDisconnectedEvent struct {
	ContextId         WebAudioGraphObjectId `json:"contextId"`
	SourceId          WebAudioGraphObjectId `json:"sourceId"`
	DestinationId     WebAudioGraphObjectId `json:"destinationId"`
	SourceOutputIndex *float64              `json:"sourceOutputIndex,omitempty"`
}

func (e *WebAudioNodeParamDisconnectedEvent) CDPEventName() string {
	return EventWebAudioNodeParamDisconnected
}
