// Code generated by cdpgen; DO NOT EDIT.

package cdp

// Tool annotations
type WebMCPAnnotation struct {
	// A hint indicating that the tool does not modify any state.
	ReadOnly *bool `json:"readOnly,omitempty"`
	// If the declarative tool was declared with the autosubmit attribute.
	Autosubmit *bool `json:"autosubmit,omitempty"`
}

// Definition of a tool that can be invoked.
type WebMCPTool struct {
	// Tool name.
	Name string `json:"name"`
	// Tool description.
	Description string `json:"description"`
	// Schema for the tool's input parameters.
	InputSchema map[string]any `json:"inputSchema,omitempty"`
	// Optional annotations for the tool.
	Annotations *WebMCPAnnotation `json:"annotations,omitempty"`
	// Frame identifier associated with the tool registration.
	FrameId PageFrameId `json:"frameId"`
	// Optional node ID for declarative tools.
	BackendNodeId *DOMBackendNodeId `json:"backendNodeId,omitempty"`
	// The stack trace at the time of the registration.
	StackTrace *RuntimeStackTrace `json:"stackTrace,omitempty"`
}

// Enables the WebMCP domain, allowing events to be sent. Enabling the domain will trigger a toolsAdded event for
// all currently registered tools.
type WebMCPEnableParams struct {
}

func WebMCPEnable() *WebMCPEnableParams {
	return &WebMCPEnableParams{}
}

func (p *WebMCPEnableParams) CDPMethodName() string {
	return "WebMCP.enable"
}

// Event fired when new tools are added.
const EventWebMCPToolsAdded = "WebMCP.toolsAdded"

type WebMCPToolsAddedEvent struct {
	// Array of tools that were added.
	Tools []WebMCPTool `json:"tools"`
}

func (e *WebMCPToolsAddedEvent) CDPEventName() string {
	return EventWebMCPToolsAdded
}

// Event fired when tools are removed.
const EventWebMCPToolsRemoved = "WebMCP.toolsRemoved"

type WebMCPToolsRemovedEvent struct {
	// Array of tools that were removed.
	Tools []WebMCPTool `json:"tools"`
}

func (e *WebMCPToolsRemovedEvent) CDPEventName() string {
	return EventWebMCPToolsRemoved
}
